{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelMetaDataValueAlphabetical"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistorder\/channelmetadatavaluealphabetical"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistorder\/channelmetadatavaluealphabetical"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/channelMetaDataValueAlphabetical","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Alphabetical value order of a selected key in meta data for group channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelMetaDataValueAlphabetical"}],"title":"GroupChannelListOrder.channelMetaDataValueAlphabetical","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListOrder@SBDGroupChannelListOrderChannelMetaDataValueAlphabetical","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelListOrderChannelMetaDataValueAlphabetical"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListOrder":{"role":"symbol","title":"GroupChannelListOrder","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListOrder"}],"abstract":[{"type":"text","text":"The order type for "},{"type":"codeVoice","code":"GroupChannelListQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListOrder"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistorder"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListOrder/channelMetaDataValueAlphabetical":{"role":"symbol","title":"GroupChannelListOrder.channelMetaDataValueAlphabetical","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelMetaDataValueAlphabetical"}],"abstract":[{"type":"text","text":"Alphabetical value order of a selected key in meta data for group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/channelMetaDataValueAlphabetical","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelListOrderChannelMetaDataValueAlphabetical"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistorder\/channelmetadatavaluealphabetical"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelListOrderChannelMetaDataValueAlphabetical"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListOrderChannelMetaDataValueAlphabetical"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDGroupChannelListOrderChannelMetaDataValueAlphabetical"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder\/title","value":"SBDGroupChannelListOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder~1channelMetaDataValueAlphabetical\/title","value":"SBDGroupChannelListOrderChannelMetaDataValueAlphabetical"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder~1channelMetaDataValueAlphabetical\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListOrderChannelMetaDataValueAlphabetical"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}