{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/publicgroupchannelmembershipfilter\/all"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/publicgroupchannelmembershipfilter\/all"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelMembershipFilter\/all","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Without filter."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"title":"PublicGroupChannelMembershipFilter.all","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDPublicGroupChannelMembershipFilter@SBDPublicGroupChannelMembershipFilterAll","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDPublicGroupChannelMembershipFilterAll"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelMembershipFilter"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelMembershipFilter":{"role":"symbol","title":"PublicGroupChannelMembershipFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicGroupChannelMembershipFilter"}],"abstract":[{"type":"text","text":"Filter my channels or all ones in public group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelMembershipFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PublicGroupChannelMembershipFilter"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannelmembershipfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelMembershipFilter/all":{"role":"symbol","title":"PublicGroupChannelMembershipFilter.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[{"type":"text","text":"Without filter."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelMembershipFilter\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPublicGroupChannelMembershipFilterAll"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannelmembershipfilter\/all"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDPublicGroupChannelMembershipFilterAll"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelMembershipFilterAll"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDPublicGroupChannelMembershipFilterAll"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelMembershipFilter\/title","value":"SBDPublicGroupChannelMembershipFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelMembershipFilter\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelMembershipFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelMembershipFilter~1all\/title","value":"SBDPublicGroupChannelMembershipFilterAll"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelMembershipFilter~1all\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelMembershipFilterAll"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}