{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joined"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/publicgroupchannelmembershipfilter\/joined"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/publicgroupchannelmembershipfilter\/joined"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelMembershipFilter\/joined","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Filter public group channel the current user joined in."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joined"}],"title":"PublicGroupChannelMembershipFilter.joined","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDPublicGroupChannelMembershipFilter@SBDPublicGroupChannelMembershipFilterJoined","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDPublicGroupChannelMembershipFilterJoined"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelMembershipFilter"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelMembershipFilter":{"role":"symbol","title":"PublicGroupChannelMembershipFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicGroupChannelMembershipFilter"}],"abstract":[{"type":"text","text":"Filter my channels or all ones in public group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelMembershipFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PublicGroupChannelMembershipFilter"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannelmembershipfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelMembershipFilter/joined":{"role":"symbol","title":"PublicGroupChannelMembershipFilter.joined","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joined"}],"abstract":[{"type":"text","text":"Filter public group channel the current user joined in."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelMembershipFilter\/joined","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPublicGroupChannelMembershipFilterJoined"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannelmembershipfilter\/joined"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDPublicGroupChannelMembershipFilterJoined"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelMembershipFilterJoined"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDPublicGroupChannelMembershipFilterJoined"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelMembershipFilter\/title","value":"SBDPublicGroupChannelMembershipFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelMembershipFilter\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelMembershipFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelMembershipFilter~1joined\/title","value":"SBDPublicGroupChannelMembershipFilterJoined"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelMembershipFilter~1joined\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelMembershipFilterJoined"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}