{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"delete"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/reactioneventaction\/delete"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/reactioneventaction\/delete"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEventAction\/delete","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"delete"}],"title":"ReactionEventAction.delete","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDReactionEventAction@SBDReactionEventActionDelete","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDReactionEventActionDelete"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEventAction"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReactionEventAction":{"role":"symbol","title":"ReactionEventAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReactionEventAction"}],"abstract":[{"type":"text","text":"The ReactionEvent action state."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEventAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReactionEventAction"}],"url":"\/documentation\/sendbirdchatsdk\/reactioneventaction"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReactionEventAction/delete":{"role":"symbol","title":"ReactionEventAction.delete","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"delete"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEventAction\/delete","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDReactionEventActionDelete"}],"url":"\/documentation\/sendbirdchatsdk\/reactioneventaction\/delete"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDReactionEventActionDelete"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDReactionEventActionDelete"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDReactionEventActionDelete"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEventAction\/title","value":"SBDReactionEventAction"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEventAction\/fragments","value":[{"kind":"identifier","text":"SBDReactionEventAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEventAction~1delete\/title","value":"SBDReactionEventActionDelete"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEventAction~1delete\/fragments","value":[{"kind":"identifier","text":"SBDReactionEventActionDelete"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}