{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollData","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollData","text":"PollData"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/polldetails\/data"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/polldetails\/data"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/data","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An additional text to accompany the poll."},{"type":"text","text":" "},{"type":"text","text":"Can be used to provide explanations for incorrect quiz answers"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollData","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollData"},{"kind":"text","text":"?"}],"title":"data","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDPollDetails(py)data","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"data"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/data":{"role":"symbol","title":"data","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollData","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollData"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"An additional text to accompany the poll."},{"type":"text","text":" "},{"type":"text","text":"Can be used to provide explanations for incorrect quiz answers"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/data","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"data"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails\/data"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollData":{"role":"symbol","title":"PollData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollData"}],"abstract":[{"type":"text","text":"Represents a poll data"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PollData"}],"url":"\/documentation\/sendbirdchatsdk\/polldata"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails":{"role":"symbol","title":"PollDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollDetails"}],"abstract":[{"type":"text","text":"Represents a poll details information"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PollDetails"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"data"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"data"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollData","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollData","text":"SBDPollData"},{"kind":"text","text":" *"},{"kind":"identifier","text":"data"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1data\/title","value":"data"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1data\/fragments","value":[{"kind":"identifier","text":"data"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollData\/title","value":"SBDPollData"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollData\/fragments","value":[{"kind":"identifier","text":"SBDPollData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails\/title","value":"SBDPollDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails\/fragments","value":[{"kind":"identifier","text":"SBDPollDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}