{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createParticipantListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramsBuilder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQueryParams","text":"ParticipantListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQuery","text":"ParticipantListQuery"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"UserListQuery"},{"type":"text","text":" instance for the participant list of the channel instance."}]}]},{"kind":"parameters","parameters":[{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The params object to change query condition."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/openchannel\/createparticipantlistquery(paramsbuilder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/openchannel\/createparticipantlistquery(paramsbuilder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(paramsBuilder:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a participant list query for this channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createParticipantListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramsBuilder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ParticipantListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ParticipantListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQuery"},{"kind":"text","text":"?"}],"title":"createParticipantListQuery(paramsBuilder:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDOpenChannel(im)createParticipantListQueryWithParamsBuilder:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"createParticipantListQueryWithParamsBuilder:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ParticipantListQuery":{"role":"symbol","title":"ParticipantListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ParticipantListQuery"},{"type":"text","text":" class is a query class for getting the list of participants in"},{"type":"text","text":" "},{"type":"text","text":"an open channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ParticipantListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/participantlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ParticipantListQueryParams":{"role":"symbol","title":"ParticipantListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ParticipantListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/participantlistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel":{"role":"symbol","title":"OpenChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" class represents a open channel which is a public chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannel"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/createParticipantListQuery(paramsBuilder:)":{"role":"symbol","title":"createParticipantListQuery(paramsBuilder:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createParticipantListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramsBuilder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ParticipantListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ParticipantListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQuery"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Creates a participant list query for this channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(paramsBuilder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createParticipantListQueryWithParamsBuilder:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/createparticipantlistquery(paramsbuilder:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createParticipantListQueryWithParamsBuilder:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createParticipantListQueryWithParamsBuilder:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQuery","text":"SBDParticipantListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createParticipantListQueryWithParamsBuilder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDParticipantListQueryParams *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDParticipantListQueryParams)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"paramsBuilder"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQuery\/title","value":"SBDParticipantListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQuery\/fragments","value":[{"kind":"identifier","text":"SBDParticipantListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQueryParams\/title","value":"SBDParticipantListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDParticipantListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel\/title","value":"SBDOpenChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createParticipantListQuery(paramsBuilder:)\/title","value":"createParticipantListQueryWithParamsBuilder:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createParticipantListQuery(paramsBuilder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createParticipantListQueryWithParamsBuilder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}