{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(createChannelWithCompletionHandler:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK18OpenChannelHandlera","text":"OpenChannelHandler"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to execute."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name and cover URL of the channel are generated in Sendbird server."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/openchannel\/createchannel(completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/openchannel\/createchannel(completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createChannel(completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates an open channel."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"createChannelWithCompletionHandler:"}],"role":"symbol","title":"createChannel(completionHandler:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK18OpenChannelHandlera"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDOpenChannel(cm)createChannelWithCompletionHandler:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelHandler":{"role":"symbol","title":"OpenChannelHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelHandler"}],"abstract":[{"type":"text","text":"Group channel handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannelHandler"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelhandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel":{"role":"symbol","title":"OpenChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" class represents a open channel which is a public chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannel"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/createChannel(completionHandler:)":{"role":"symbol","title":"createChannel(completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK18OpenChannelHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates an open channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createChannel(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createChannelWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/createchannel(completionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createChannelWithCompletionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createChannelWithCompletionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"createChannelWithCompletionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDOpenChannel *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDOpenChannel#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel\/title","value":"SBDOpenChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createChannel(completionHandler:)\/title","value":"createChannelWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createChannel(completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createChannelWithCompletionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}