{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(createChannelWithParams:progressHandler:completionHandler:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelCreateParams","text":"OpenChannelCreateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progressHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ProgressHandler","preciseIdentifier":"s:15SendbirdChatSDK15ProgressHandlera","text":"ProgressHandler"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK18OpenChannelHandlera","text":"OpenChannelHandler"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The parameter instance of "},{"type":"codeVoice","code":"OpenChannelCreateParams"},{"type":"text","text":" what has properties to create open channel."}]}]},{"name":"progressHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to monitor progression. "},{"type":"codeVoice","code":"bytesSent"},{"type":"text","text":" is the number of bytes sent since"},{"type":"text","text":" "},{"type":"text","text":"the last time this method was called. "},{"type":"codeVoice","code":"totalBytesSent"},{"type":"text","text":" is the total number of bytes sent so far. "},{"type":"codeVoice","code":"totalBytesExpectedToSend"},{"type":"text","text":" "},{"type":"text","text":"is the expected length of the body "},{"type":"strong","inlineContent":[{"type":"text","text":"data"}]},{"type":"text","text":". These parameters are the same to the declaration of "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsessiontaskdelegate\/1408299-urlsession"},{"type":"text","text":"."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to execute. "},{"type":"codeVoice","code":"channel"},{"type":"text","text":" is the open channel instance."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.206"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/openchannel\/createchannel(params:progresshandler:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/openchannel\/createchannel(params:progresshandler:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createChannel(params:progressHandler:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a open channel with "},{"type":"codeVoice","code":"OpenChannelCreateParams"},{"type":"text","text":" class."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"createChannelWithParams:progressHandler:completionHandler:"}],"role":"symbol","title":"createChannel(params:progressHandler:completionHandler:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelCreateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progressHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProgressHandler","preciseIdentifier":"s:15SendbirdChatSDK15ProgressHandlera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK18OpenChannelHandlera"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDOpenChannel(cm)createChannelWithParams:progressHandler:completionHandler:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ProgressHandler":{"role":"symbol","title":"ProgressHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressHandler"}],"abstract":[{"type":"text","text":"Binary progress handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ProgressHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProgressHandler"}],"url":"\/documentation\/sendbirdchatsdk\/progresshandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelCreateParams":{"role":"symbol","title":"OpenChannelCreateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelCreateParams"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OpenChannelCreateParams"},{"type":"text","text":" class contain parameters for "},{"type":"codeVoice","code":"open channel"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelCreateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannelCreateParams"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelcreateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel":{"role":"symbol","title":"OpenChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" class represents a open channel which is a public chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannel"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelHandler":{"role":"symbol","title":"OpenChannelHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelHandler"}],"abstract":[{"type":"text","text":"Group channel handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannelHandler"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelhandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/createChannel(params:progressHandler:completionHandler:)":{"role":"symbol","title":"createChannel(params:progressHandler:completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelCreateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progressHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProgressHandler","preciseIdentifier":"s:15SendbirdChatSDK15ProgressHandlera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK18OpenChannelHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a open channel with "},{"type":"codeVoice","code":"OpenChannelCreateParams"},{"type":"text","text":" class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createChannel(params:progressHandler:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createChannelWithParams:progressHandler:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/createchannel(params:progresshandler:completionhandler:)"},"https://developer.apple.com/documentation/foundation/urlsessiontaskdelegate/1408299-urlsession":{"title":"urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)","titleInlineContent":[{"type":"codeVoice","code":"urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsessiontaskdelegate\/1408299-urlsession","url":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsessiontaskdelegate\/1408299-urlsession"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createChannelWithParams:progressHandler:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createChannelWithParams:progressHandler:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"createChannelWithParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelCreateParams","text":"SBDOpenChannelCreateParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(long long, long long, long long)","preciseIdentifier":"c:BFv(#K#K#K)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"progressHandler"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDOpenChannel *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDOpenChannel#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelCreateParams\/title","value":"SBDOpenChannelCreateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelCreateParams\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannelCreateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel\/title","value":"SBDOpenChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createChannel(params:progressHandler:completionHandler:)\/title","value":"createChannelWithParams:progressHandler:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createChannel(params:progressHandler:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createChannelWithParams:progressHandler:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}