{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(enterChannelWithCompletionHandler:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera","text":"SBErrorHandler"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to execute."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/openchannel\/enter(completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/openchannel\/enter(completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/enter(completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enters this channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"title":"enter(completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDOpenChannel(im)enterChannelWithCompletionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"enterChannelWithCompletionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel":{"role":"symbol","title":"OpenChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" class represents a open channel which is a public chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannel"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/enter(completionHandler:)":{"role":"symbol","title":"enter(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Enters this channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/enter(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enterChannelWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/enter(completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBErrorHandler":{"role":"symbol","title":"SBErrorHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBErrorHandler"}],"abstract":[{"type":"text","text":"Error handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBErrorHandler"}],"url":"\/documentation\/sendbirdchatsdk\/sberrorhandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enterChannelWithCompletionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enterChannelWithCompletionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"enterChannelWithCompletionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel\/title","value":"SBDOpenChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1enter(completionHandler:)\/title","value":"enterChannelWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1enter(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enterChannelWithCompletionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}