{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromSerializedData"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?) -> `Self`"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"EmojiContainer"},{"type":"text","text":" if parameter is valid, otherwise "},{"type":"codeVoice","code":"nil"}]}]},{"kind":"parameters","parameters":[{"name":"data","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Data"},{"type":"text","text":" instance"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/emojicontainer\/build(fromserializeddata:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/emojicontainer\/build(fromserializeddata:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiContainer\/build(fromSerializedData:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Deserializes and reconstructs the object"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromSerializedData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?) -> `Self`"},{"kind":"text","text":"?"}],"title":"build(fromSerializedData:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDEmojiContainer(cm)buildFromSerializedData:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"buildFromSerializedData:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiContainer","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiContainer\/Serializable-Implementations"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/EmojiContainer/build(fromSerializedData:)":{"role":"symbol","title":"build(fromSerializedData:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromSerializedData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?) -> `Self`"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Deserializes and reconstructs the object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiContainer\/build(fromSerializedData:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildFromSerializedData:"}],"url":"\/documentation\/sendbirdchatsdk\/emojicontainer\/build(fromserializeddata:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/EmojiContainer":{"role":"symbol","title":"EmojiContainer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmojiContainer"}],"abstract":[{"type":"text","text":"An object contains list of "},{"type":"codeVoice","code":"EmojiCategory"},{"type":"text","text":" and hash"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmojiContainer"}],"url":"\/documentation\/sendbirdchatsdk\/emojicontainer"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/EmojiContainer/Serializable-Implementations":{"role":"collectionGroup","title":"Serializable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiContainer\/Serializable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/emojicontainer\/serializable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"buildFromSerializedData:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildFromSerializedData:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"buildFromSerializedData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"data"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiContainer~1build(fromSerializedData:)\/title","value":"buildFromSerializedData:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiContainer~1build(fromSerializedData:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildFromSerializedData:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiContainer\/title","value":"SBDEmojiContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiContainer\/fragments","value":[{"kind":"identifier","text":"SBDEmojiContainer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}