{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categories"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiCategory","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDEmojiCategory","text":"EmojiCategory"},{"kind":"text","text":"] { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/emojicontainer\/categories"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/emojicontainer\/categories"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiContainer\/categories","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Emoji category list"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categories"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"EmojiCategory","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDEmojiCategory"},{"kind":"text","text":"]"}],"title":"categories","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDEmojiContainer(py)categories","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"categories"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiContainer"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/EmojiContainer/categories":{"role":"symbol","title":"categories","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categories"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"EmojiCategory","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDEmojiCategory"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Emoji category list"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiContainer\/categories","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"categories"}],"url":"\/documentation\/sendbirdchatsdk\/emojicontainer\/categories"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/EmojiCategory":{"role":"symbol","title":"EmojiCategory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmojiCategory"}],"abstract":[{"type":"text","text":"Class to represent emoji cateogry"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmojiCategory"}],"url":"\/documentation\/sendbirdchatsdk\/emojicategory"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/EmojiContainer":{"role":"symbol","title":"EmojiContainer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmojiContainer"}],"abstract":[{"type":"text","text":"An object contains list of "},{"type":"codeVoice","code":"EmojiCategory"},{"type":"text","text":" and hash"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmojiContainer"}],"url":"\/documentation\/sendbirdchatsdk\/emojicontainer"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"categories"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"categories"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBDEmojiCategory *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *"},{"kind":"identifier","text":"categories"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiContainer~1categories\/title","value":"categories"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiContainer~1categories\/fragments","value":[{"kind":"identifier","text":"categories"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiCategory\/title","value":"SBDEmojiCategory"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiCategory\/fragments","value":[{"kind":"identifier","text":"SBDEmojiCategory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiContainer\/title","value":"SBDEmojiContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiContainer\/fragments","value":[{"kind":"identifier","text":"SBDEmojiContainer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}