{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asSBError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError","text":"SBError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/coreerror\/assberror(message:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/asSBError(message:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Converts error code to "},{"type":"codeVoice","code":"SBError"},{"type":"text","text":" instance with message"}],"kind":"symbol","metadata":{"role":"symbol","title":"asSBError(message:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asSBError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError"}],"symbolKind":"method","externalID":"s:15SendbirdChatSDK11SBErrorCodePAAE02asD07messageAA0D0CSSSg_tF::SYNTHESIZED::c:@M@SendbirdChatSDK@E@SBCoreError","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/SBErrorCode-Implementations"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/SBErrorCode-Implementations":{"role":"collectionGroup","title":"SBErrorCode Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/SBErrorCode-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/coreerror\/sberrorcode-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBError":{"role":"symbol","title":"SBError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBError"}],"abstract":[{"type":"text","text":"Sendbird error class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBError"}],"url":"\/documentation\/sendbirdchatsdk\/sberror"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError":{"role":"symbol","title":"CoreError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreError"}],"abstract":[{"type":"text","text":"Core error code"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CoreError"}],"url":"\/documentation\/sendbirdchatsdk\/coreerror"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/asSBError(message:)":{"role":"symbol","title":"asSBError(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asSBError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError"}],"abstract":[{"type":"text","text":"Converts error code to "},{"type":"codeVoice","code":"SBError"},{"type":"text","text":" instance with message"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/asSBError(message:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/coreerror\/assberror(message:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SBError\/title","value":"SBError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SBError\/fragments","value":[{"kind":"identifier","text":"SBError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError\/title","value":"SBCoreError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError\/fragments","value":[{"kind":"identifier","text":"SBCoreError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}