{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileSizeLimitExceeded"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/coreerror\/filesizelimitexceeded"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/coreerror\/filesizelimitexceeded"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/fileSizeLimitExceeded","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileSizeLimitExceeded"}],"title":"CoreError.fileSizeLimitExceeded","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBCoreError@SBCoreErrorFileSizeLimitExceeded","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBCoreErrorFileSizeLimitExceeded"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError":{"role":"symbol","title":"CoreError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreError"}],"abstract":[{"type":"text","text":"Core error code"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CoreError"}],"url":"\/documentation\/sendbirdchatsdk\/coreerror"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/fileSizeLimitExceeded":{"role":"symbol","title":"CoreError.fileSizeLimitExceeded","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileSizeLimitExceeded"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/fileSizeLimitExceeded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBCoreErrorFileSizeLimitExceeded"}],"url":"\/documentation\/sendbirdchatsdk\/coreerror\/filesizelimitexceeded"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBCoreErrorFileSizeLimitExceeded"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBCoreErrorFileSizeLimitExceeded"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBCoreErrorFileSizeLimitExceeded"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError\/title","value":"SBCoreError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError\/fragments","value":[{"kind":"identifier","text":"SBCoreError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1fileSizeLimitExceeded\/title","value":"SBCoreErrorFileSizeLimitExceeded"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1fileSizeLimitExceeded\/fragments","value":[{"kind":"identifier","text":"SBCoreErrorFileSizeLimitExceeded"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}