{"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelcollection\/basechanneldelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelcollection\/basechanneldelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/BaseChannelDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:createdMetaCounters:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:createdMetaData:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:deletedMetaCountersKeys:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:deletedMetaDataKeys:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:didReceive:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:didReceiveMention:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:updatedMetaCounters:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:updatedMetaData:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:userWasBanned:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:userWasMuted:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:userWasUnbanned:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:userWasUnmuted:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelDidUpdateOperators(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelWasChanged(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelWasDeleted(_:channelType:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelWasFrozen(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelWasUnfrozen(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"SendbirdChatSDK"}],"role":"collectionGroup","title":"BaseChannelDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channel(_:updatedMetaData:)":{"role":"symbol","title":"channel(_:updatedMetaData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"updatedMetaData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"A callback when meta data was updated in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:updatedMetaData:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:updatedMetaData:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channel(_:updatedmetadata:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channelWasFrozen(_:)":{"role":"symbol","title":"channelWasFrozen(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelWasFrozen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when an channel was frozen."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelWasFrozen(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelWasFrozen:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channelwasfrozen(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channel(_:userWasUnbanned:)":{"role":"symbol","title":"channel(_:userWasUnbanned:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userWasUnbanned"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a user was unbanned in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:userWasUnbanned:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:userWasUnbanned:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channel(_:userwasunbanned:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channelDidUpdateOperators(_:)":{"role":"symbol","title":"channelDidUpdateOperators(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidUpdateOperators"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when operators were updated in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelDidUpdateOperators(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelDidUpdateOperators:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channeldidupdateoperators(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channelWasDeleted(_:channelType:)":{"role":"symbol","title":"channelWasDeleted(_:channelType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelWasDeleted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when an open channel was deleted."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelWasDeleted(_:channelType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelWasDeleted:channelType:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channelwasdeleted(_:channeltype:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channel(_:deletedMetaDataKeys:)":{"role":"symbol","title":"channel(_:deletedMetaDataKeys:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedMetaDataKeys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"A callback when meta data was deleted in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:deletedMetaDataKeys:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:deletedMetaDataKeys:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channel(_:deletedmetadatakeys:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channel(_:didReceive:)":{"role":"symbol","title":"channel(_:didReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a message is received."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:didReceive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:didReceiveMessage:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channel(_:didreceive:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channel(_:userWasMuted:)":{"role":"symbol","title":"channel(_:userWasMuted:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userWasMuted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a user was muted in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:userWasMuted:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:userWasMuted:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channel(_:userwasmuted:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channel(_:userWasUnmuted:)":{"role":"symbol","title":"channel(_:userWasUnmuted:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userWasUnmuted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a user was unmuted in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:userWasUnmuted:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:userWasUnmuted:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channel(_:userwasunmuted:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channel(_:createdMetaCounters:)":{"role":"symbol","title":"channel(_:createdMetaCounters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"createdMetaCounters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"A callback when meta counters were created in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:createdMetaCounters:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:createdMetaCounters:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channel(_:createdmetacounters:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channel(_:updatedMetaCounters:)":{"role":"symbol","title":"channel(_:updatedMetaCounters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"updatedMetaCounters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"A callback when meta counters were updated in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:updatedMetaCounters:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:updatedMetaCounters:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channel(_:updatedmetacounters:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channel(_:createdMetaData:)":{"role":"symbol","title":"channel(_:createdMetaData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"createdMetaData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"A callback when meta data was created in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:createdMetaData:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:createdMetaData:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channel(_:createdmetadata:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channelWasUnfrozen(_:)":{"role":"symbol","title":"channelWasUnfrozen(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelWasUnfrozen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when an channel was unfrozen."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelWasUnfrozen(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelWasUnfrozen:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channelwasunfrozen(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection":{"role":"symbol","title":"GroupChannelCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelCollection"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channelWasChanged(_:)":{"role":"symbol","title":"channelWasChanged(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelWasChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when an open channel was changed."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelWasChanged(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelWasChanged:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channelwaschanged(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channel(_:didReceiveMention:)":{"role":"symbol","title":"channel(_:didReceiveMention:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveMention"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A delegate is called when someone mentioned the user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:didReceiveMention:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:didReceiveMention:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channel(_:didreceivemention:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channel(_:deletedMetaCountersKeys:)":{"role":"symbol","title":"channel(_:deletedMetaCountersKeys:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedMetaCountersKeys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"A callback when meta counters were deleted in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:deletedMetaCountersKeys:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:deletedMetaCountersKeys:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channel(_:deletedmetacounterskeys:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channel(_:userWasBanned:)":{"role":"symbol","title":"channel(_:userWasBanned:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userWasBanned"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a user was banned in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:userWasBanned:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:userWasBanned:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channel(_:userwasbanned:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:createdMetaCounters:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:createdMetaData:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:deletedMetaCountersKeys:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:deletedMetaDataKeys:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:didReceive:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:didReceiveMention:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:updatedMetaCounters:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:updatedMetaData:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:userWasBanned:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:userWasMuted:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:userWasUnbanned:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channel(_:userWasUnmuted:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelDidUpdateOperators(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelWasChanged(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelWasDeleted(_:channelType:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelWasFrozen(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelWasUnfrozen(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:updatedMetaData:)\/title","value":"channel:updatedMetaData:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:updatedMetaData:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:updatedMetaData:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channelWasFrozen(_:)\/title","value":"channelWasFrozen:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channelWasFrozen(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelWasFrozen:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:userWasUnbanned:)\/title","value":"channel:userWasUnbanned:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:userWasUnbanned:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userWasUnbanned:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channelDidUpdateOperators(_:)\/title","value":"channelDidUpdateOperators:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channelDidUpdateOperators(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidUpdateOperators:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channelWasDeleted(_:channelType:)\/title","value":"channelWasDeleted:channelType:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channelWasDeleted(_:channelType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelWasDeleted:channelType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:deletedMetaDataKeys:)\/title","value":"channel:deletedMetaDataKeys:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:deletedMetaDataKeys:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:deletedMetaDataKeys:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:didReceive:)\/title","value":"channel:didReceiveMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:didReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didReceiveMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:userWasMuted:)\/title","value":"channel:userWasMuted:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:userWasMuted:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userWasMuted:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:userWasUnmuted:)\/title","value":"channel:userWasUnmuted:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:userWasUnmuted:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userWasUnmuted:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:createdMetaCounters:)\/title","value":"channel:createdMetaCounters:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:createdMetaCounters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:createdMetaCounters:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:updatedMetaCounters:)\/title","value":"channel:updatedMetaCounters:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:updatedMetaCounters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:updatedMetaCounters:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:createdMetaData:)\/title","value":"channel:createdMetaData:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:createdMetaData:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:createdMetaData:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channelWasUnfrozen(_:)\/title","value":"channelWasUnfrozen:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channelWasUnfrozen(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelWasUnfrozen:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection\/title","value":"SBDGroupChannelCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channelWasChanged(_:)\/title","value":"channelWasChanged:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channelWasChanged(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelWasChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:didReceiveMention:)\/title","value":"channel:didReceiveMention:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:didReceiveMention:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didReceiveMention:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:deletedMetaCountersKeys:)\/title","value":"channel:deletedMetaCountersKeys:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:deletedMetaCountersKeys:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:deletedMetaCountersKeys:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:userWasBanned:)\/title","value":"channel:userWasBanned:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channel(_:userWasBanned:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userWasBanned:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}