{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery","text":"GroupChannelListQuery"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelcollection\/query"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelcollection\/query"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/query","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Group channel list query"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery"}],"title":"query","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection(py)query","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"query"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection":{"role":"symbol","title":"GroupChannelCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelCollection"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/query":{"role":"symbol","title":"query","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery"}],"abstract":[{"type":"text","text":"Group channel list query"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/query","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"query"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/query"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuery":{"role":"symbol","title":"GroupChannelListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannelListQuery"},{"type":"text","text":" class is a query class for getting the list of group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquery"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"query"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"query"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery","text":"SBDGroupChannelListQuery"},{"kind":"text","text":" *"},{"kind":"identifier","text":"query"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection\/title","value":"SBDGroupChannelCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1query\/title","value":"query"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1query\/fragments","value":[{"kind":"identifier","text":"query"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery\/title","value":"SBDGroupChannelListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}