{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"muted"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/restrictiontype\/muted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/restrictiontype\/muted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/muted","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"muted"}],"title":"RestrictionType.muted","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDRestrictionType@SBDRestrictionTypeMuted","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDRestrictionTypeMuted"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionType/muted":{"role":"symbol","title":"RestrictionType.muted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"muted"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/muted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDRestrictionTypeMuted"}],"url":"\/documentation\/sendbirdchatsdk\/restrictiontype\/muted"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionType":{"role":"symbol","title":"RestrictionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictionType"}],"abstract":[{"type":"text","text":"Restriction type for restrictedUser"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RestrictionType"}],"url":"\/documentation\/sendbirdchatsdk\/restrictiontype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDRestrictionTypeMuted"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDRestrictionTypeMuted"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDRestrictionTypeMuted"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionType~1muted\/title","value":"SBDRestrictionTypeMuted"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionType~1muted\/fragments","value":[{"kind":"identifier","text":"SBDRestrictionTypeMuted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionType\/title","value":"SBDRestrictionType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionType\/fragments","value":[{"kind":"identifier","text":"SBDRestrictionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}