{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"applicationID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isLocalCachingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDLogLevel","text":"LogLevel"},{"kind":"text","text":" = .none, "},{"kind":"externalParam","text":"appVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"applicationID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Sendbird Application ID"}]}]},{"name":"isLocalCachingEnabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" if using local caching"}]}]},{"name":"logLevel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"log level"}]}]},{"name":"appVersion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"host app version"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/initparams\/init(applicationid:islocalcachingenabled:loglevel:appversion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/initparams\/init(applicationid:islocalcachingenabled:loglevel:appversion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/InitParams\/init(applicationID:isLocalCachingEnabled:logLevel:appVersion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Parameter constructor"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"applicationID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isLocalCachingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDLogLevel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"appVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(applicationID:isLocalCachingEnabled:logLevel:appVersion:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDInitParams(im)initWithApplicationID:isLocalCachingEnabled:logLevel:appVersion:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithApplicationID:isLocalCachingEnabled:logLevel:appVersion:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/InitParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/InitParams/init(applicationID:isLocalCachingEnabled:logLevel:appVersion:)":{"role":"symbol","title":"init(applicationID:isLocalCachingEnabled:logLevel:appVersion:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"applicationID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isLocalCachingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDLogLevel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"appVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Parameter constructor"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/InitParams\/init(applicationID:isLocalCachingEnabled:logLevel:appVersion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithApplicationID:isLocalCachingEnabled:logLevel:appVersion:"}],"url":"\/documentation\/sendbirdchatsdk\/initparams\/init(applicationid:islocalcachingenabled:loglevel:appversion:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel":{"role":"symbol","title":"LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/sendbirdchatsdk\/loglevel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/InitParams":{"role":"symbol","title":"InitParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InitParams"}],"abstract":[{"type":"text","text":"An object to initialize SendbirdChat"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/InitParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InitParams"}],"url":"\/documentation\/sendbirdchatsdk\/initparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithApplicationID:isLocalCachingEnabled:logLevel:appVersion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithApplicationID:isLocalCachingEnabled:logLevel:appVersion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithApplicationID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"applicationID"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLocalCachingEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isLocalCachingEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDLogLevel","text":"SBDLogLevel"},{"kind":"text","text":")"},{"kind":"internalParam","text":"logLevel"},{"kind":"text","text":" "},{"kind":"identifier","text":"appVersion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"appVersion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1InitParams~1init(applicationID:isLocalCachingEnabled:logLevel:appVersion:)\/title","value":"initWithApplicationID:isLocalCachingEnabled:logLevel:appVersion:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1InitParams~1init(applicationID:isLocalCachingEnabled:logLevel:appVersion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithApplicationID:isLocalCachingEnabled:logLevel:appVersion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel\/title","value":"SBDLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel\/fragments","value":[{"kind":"identifier","text":"SBDLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1InitParams\/title","value":"SBDInitParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1InitParams\/fragments","value":[{"kind":"identifier","text":"SBDInitParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}