{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionOnly"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/pushtriggeroption\/mentiononly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/pushtriggeroption\/mentiononly"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTriggerOption\/mentionOnly","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Receive only mentioned messages’s notification."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionOnly"}],"title":"PushTriggerOption.mentionOnly","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDPushTriggerOption@SBDPushTriggerOptionMentionOnly","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDPushTriggerOptionMentionOnly"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTriggerOption"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTriggerOption":{"role":"symbol","title":"PushTriggerOption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushTriggerOption"}],"abstract":[{"type":"text","text":"The options to choose which push notification for the current user to receive."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTriggerOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushTriggerOption"}],"url":"\/documentation\/sendbirdchatsdk\/pushtriggeroption"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTriggerOption/mentionOnly":{"role":"symbol","title":"PushTriggerOption.mentionOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionOnly"}],"abstract":[{"type":"text","text":"Receive only mentioned messages’s notification."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTriggerOption\/mentionOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushTriggerOptionMentionOnly"}],"url":"\/documentation\/sendbirdchatsdk\/pushtriggeroption\/mentiononly"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDPushTriggerOptionMentionOnly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPushTriggerOptionMentionOnly"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDPushTriggerOptionMentionOnly"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTriggerOption\/title","value":"SBDPushTriggerOption"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTriggerOption\/fragments","value":[{"kind":"identifier","text":"SBDPushTriggerOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTriggerOption~1mentionOnly\/title","value":"SBDPushTriggerOptionMentionOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTriggerOption~1mentionOnly\/fragments","value":[{"kind":"identifier","text":"SBDPushTriggerOptionMentionOnly"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}