{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/pushtriggeroption\/off"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/pushtriggeroption\/off"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTriggerOption\/off","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Do NOT receive any remote push notification."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"title":"PushTriggerOption.off","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDPushTriggerOption@SBDPushTriggerOptionOff","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDPushTriggerOptionOff"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTriggerOption"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTriggerOption":{"role":"symbol","title":"PushTriggerOption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushTriggerOption"}],"abstract":[{"type":"text","text":"The options to choose which push notification for the current user to receive."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTriggerOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushTriggerOption"}],"url":"\/documentation\/sendbirdchatsdk\/pushtriggeroption"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTriggerOption/off":{"role":"symbol","title":"PushTriggerOption.off","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"abstract":[{"type":"text","text":"Do NOT receive any remote push notification."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTriggerOption\/off","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushTriggerOptionOff"}],"url":"\/documentation\/sendbirdchatsdk\/pushtriggeroption\/off"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDPushTriggerOptionOff"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPushTriggerOptionOff"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDPushTriggerOptionOff"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTriggerOption\/title","value":"SBDPushTriggerOption"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTriggerOption\/fragments","value":[{"kind":"identifier","text":"SBDPushTriggerOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTriggerOption~1off\/title","value":"SBDPushTriggerOptionOff"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTriggerOption~1off\/fragments","value":[{"kind":"identifier","text":"SBDPushTriggerOptionOff"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}