{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDetectHugeGap"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection","text":"MessageCollection"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"collection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Message collection object."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagecollectiondelegate\/diddetecthugegap(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagecollectiondelegate\/diddetecthugegap(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/didDetectHugeGap(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Invoked when the huge gap has been detected."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didDetectHugeGap:"}],"role":"symbol","title":"didDetectHugeGap(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDetectHugeGap"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDMessageCollectionDelegate(im)didDetectHugeGap:","required":true,"modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionDelegate":{"role":"symbol","title":"MessageCollectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollectionDelegate"}],"abstract":[{"type":"text","text":"Methods that are invoked when the event of the message collection occurs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollectionDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollectiondelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection":{"role":"symbol","title":"MessageCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollection"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionDelegate/didDetectHugeGap(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didDetectHugeGap:"}],"role":"symbol","title":"didDetectHugeGap(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDetectHugeGap"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Invoked when the huge gap has been detected."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/didDetectHugeGap(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagecollectiondelegate\/diddetecthugegap(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didDetectHugeGap:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didDetectHugeGap:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didDetectHugeGap:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection","text":"SBDMessageCollection"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"collection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate\/title","value":"SBDMessageCollectionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollectionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/title","value":"SBDMessageCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1didDetectHugeGap(_:)\/title","value":"didDetectHugeGap:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1didDetectHugeGap(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didDetectHugeGap:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}