{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCollection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection","text":"MessageCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext","text":"MessageContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedChannel"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"collection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Message collection object."}]}]},{"name":"context","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The reason why the channel are deleted."}]}]},{"name":"channelURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Channel URL that has been deleted."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagecollectiondelegate\/messagecollection(_:context:deletedchannel:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagecollectiondelegate\/messagecollection(_:context:deletedchannel:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:deletedChannel:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Invoked when the channel that has the message collection is deleted."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"messageCollection:context:deletedChannel:"}],"role":"symbol","title":"messageCollection(_:context:deletedChannel:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDMessageCollectionDelegate(im)messageCollection:context:deletedChannel:","required":true,"modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection":{"role":"symbol","title":"MessageCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollection"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionDelegate":{"role":"symbol","title":"MessageCollectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollectionDelegate"}],"abstract":[{"type":"text","text":"Methods that are invoked when the event of the message collection occurs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollectionDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollectiondelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionDelegate/messageCollection(_:context:deletedChannel:)":{"navigatorTitle":[{"kind":"identifier","text":"messageCollection:context:deletedChannel:"}],"role":"symbol","title":"messageCollection(_:context:deletedChannel:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Invoked when the channel that has the message collection is deleted."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:deletedChannel:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagecollectiondelegate\/messagecollection(_:context:deletedchannel:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageContext":{"role":"symbol","title":"MessageContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageContext"}],"abstract":[{"type":"text","text":"Represents what happened to the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageContext"}],"url":"\/documentation\/sendbirdchatsdk\/messagecontext"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"messageCollection:context:deletedChannel:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageCollection:context:deletedChannel:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"messageCollection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection","text":"SBDMessageCollection"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"collection"},{"kind":"text","text":" "},{"kind":"identifier","text":"context:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext","text":"SBDMessageContext"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"context"},{"kind":"text","text":" "},{"kind":"identifier","text":"deletedChannel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelURL"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/title","value":"SBDMessageCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate\/title","value":"SBDMessageCollectionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollectionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1messageCollection(_:context:deletedChannel:)\/title","value":"messageCollection:context:deletedChannel:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1messageCollection(_:context:deletedChannel:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageCollection:context:deletedChannel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageContext\/title","value":"SBDMessageContext"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageContext\/fragments","value":[{"kind":"identifier","text":"SBDMessageContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}