{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCollection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection","text":"MessageCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext","text":"MessageContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel","text":"GroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedMessages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage","text":"BaseMessage"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"collection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Message collection object."}]}]},{"name":"context","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The reason why the messages are deleted."}]}]},{"name":"channel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The channel that has the messages."}]}]},{"name":"deletedMessages","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Messages to be deleted."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagecollectiondelegate\/messagecollection(_:context:channel:deletedmessages:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagecollectiondelegate\/messagecollection(_:context:channel:deletedmessages:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:channel:deletedMessages:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Invoked when the message are deleted."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"messageCollection:context:channel:deletedMessages:"}],"role":"symbol","title":"messageCollection(_:context:channel:deletedMessages:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedMessages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDMessageCollectionDelegate(im)messageCollection:context:channel:deletedMessages:","required":true,"modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageContext":{"role":"symbol","title":"MessageContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageContext"}],"abstract":[{"type":"text","text":"Represents what happened to the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageContext"}],"url":"\/documentation\/sendbirdchatsdk\/messagecontext"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionDelegate":{"role":"symbol","title":"MessageCollectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollectionDelegate"}],"abstract":[{"type":"text","text":"Methods that are invoked when the event of the message collection occurs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollectionDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollectiondelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage":{"role":"symbol","title":"BaseMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessage"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":" class represents the base message which is generated by a user or an admin."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":", the "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"AdminMessage"},{"type":"text","text":" are derived from this class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessage"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel":{"role":"symbol","title":"GroupChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" class represents a group channel which is a private chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection":{"role":"symbol","title":"MessageCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollection"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionDelegate/messageCollection(_:context:channel:deletedMessages:)":{"navigatorTitle":[{"kind":"identifier","text":"messageCollection:context:channel:deletedMessages:"}],"role":"symbol","title":"messageCollection(_:context:channel:deletedMessages:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedMessages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Invoked when the message are deleted."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:channel:deletedMessages:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagecollectiondelegate\/messagecollection(_:context:channel:deletedmessages:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"messageCollection:context:channel:deletedMessages:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageCollection:context:channel:deletedMessages:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"messageCollection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection","text":"SBDMessageCollection"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"collection"},{"kind":"text","text":" "},{"kind":"identifier","text":"context:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext","text":"SBDMessageContext"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"context"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel","text":"SBDGroupChannel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channel"},{"kind":"text","text":" "},{"kind":"identifier","text":"deletedMessages:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBDBaseMessage *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"deletedMessages"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageContext\/title","value":"SBDMessageContext"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageContext\/fragments","value":[{"kind":"identifier","text":"SBDMessageContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate\/title","value":"SBDMessageCollectionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollectionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/title","value":"SBDBaseMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/title","value":"SBDGroupChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/title","value":"SBDMessageCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1messageCollection(_:context:channel:deletedMessages:)\/title","value":"messageCollection:context:channel:deletedMessages:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1messageCollection(_:context:channel:deletedMessages:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageCollection:context:channel:deletedMessages:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}