{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(createWithMessageListParams:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams","text":"MessageListParams"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams","text":"MessageChangeLogsParams"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A created instance of "},{"type":"codeVoice","code":"MessageChangeLogsParams"}]}]},{"kind":"parameters","parameters":[{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"previous message list query"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.185"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/create(with:)-6gu6z"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/create(with:)-6gu6z"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/create(with:)-6gu6z","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"MessageChangeLogParams"},{"type":"text","text":" from a given "},{"type":"codeVoice","code":"MessageListParams"},{"type":"text","text":" instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"MessageChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams"}],"title":"create(with:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams(cm)createWithMessageListParams:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"createWithMessageListParams:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams":{"role":"symbol","title":"MessageChangeLogsParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageChangeLogsParams"}],"abstract":[{"type":"text","text":"An object contains set of options for message change logs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageChangeLogsParams"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams":{"role":"symbol","title":"MessageListParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListParams"}],"abstract":[{"type":"text","text":"An object contains set of options for get message methods"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageListParams"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams/create(with:)-6gu6z":{"role":"symbol","title":"create(with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"MessageChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams"}],"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"MessageChangeLogParams"},{"type":"text","text":" from a given "},{"type":"codeVoice","code":"MessageListParams"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/create(with:)-6gu6z","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithMessageListParams:"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/create(with:)-6gu6z"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithMessageListParams:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithMessageListParams:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams","text":"SBDMessageChangeLogsParams"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createWithMessageListParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams","text":"SBDMessageListParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams\/title","value":"SBDMessageChangeLogsParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams\/fragments","value":[{"kind":"identifier","text":"SBDMessageChangeLogsParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams\/title","value":"SBDMessageListParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams\/fragments","value":[{"kind":"identifier","text":"SBDMessageListParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1create(with:)-6gu6z\/title","value":"createWithMessageListParams:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1create(with:)-6gu6z\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithMessageListParams:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}