{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(createWithPreviousMessageListQuery:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PreviousMessageListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPreviousMessageListQuery","text":"PreviousMessageListQuery"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams","text":"MessageChangeLogsParams"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A created instance of "},{"type":"codeVoice","code":"MessageChangeLogsParams"}]}]},{"kind":"parameters","parameters":[{"name":"query","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"previous message list query"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.185"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/create(with:)-3gsev"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/create(with:)-3gsev"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/create(with:)-3gsev","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"PreviousMessageListQuery"},{"type":"text","text":" from a given "},{"type":"codeVoice","code":"PreviousMessageListQuery"},{"type":"text","text":" instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PreviousMessageListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPreviousMessageListQuery"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"MessageChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams"}],"title":"create(with:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams(cm)createWithPreviousMessageListQuery:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"createWithPreviousMessageListQuery:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams/create(with:)-3gsev":{"role":"symbol","title":"create(with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PreviousMessageListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPreviousMessageListQuery"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"MessageChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams"}],"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"PreviousMessageListQuery"},{"type":"text","text":" from a given "},{"type":"codeVoice","code":"PreviousMessageListQuery"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/create(with:)-3gsev","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithPreviousMessageListQuery:"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/create(with:)-3gsev"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams":{"role":"symbol","title":"MessageChangeLogsParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageChangeLogsParams"}],"abstract":[{"type":"text","text":"An object contains set of options for message change logs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageChangeLogsParams"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PreviousMessageListQuery":{"role":"symbol","title":"PreviousMessageListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviousMessageListQuery"}],"abstract":[{"type":"text","text":"An object which retrieves messages from the given channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PreviousMessageListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreviousMessageListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/previousmessagelistquery"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithPreviousMessageListQuery:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithPreviousMessageListQuery:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams","text":"SBDMessageChangeLogsParams"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createWithPreviousMessageListQuery:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PreviousMessageListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPreviousMessageListQuery","text":"SBDPreviousMessageListQuery"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"query"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1create(with:)-3gsev\/title","value":"createWithPreviousMessageListQuery:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1create(with:)-3gsev\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithPreviousMessageListQuery:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams\/title","value":"SBDMessageChangeLogsParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams\/fragments","value":[{"kind":"identifier","text":"SBDMessageChangeLogsParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PreviousMessageListQuery\/title","value":"SBDPreviousMessageListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PreviousMessageListQuery\/fragments","value":[{"kind":"identifier","text":"SBDPreviousMessageListQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}