{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"includeMetaArray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"includeReactions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"includeThreadInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"includePollDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"includeParentMessageInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"replyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReplyType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReplyType","text":"ReplyType"},{"kind":"text","text":" = .none)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/init(includemetaarray:includereactions:includethreadinfo:includepolldetails:includeparentmessageinfo:replytype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/init(includemetaarray:includereactions:includethreadinfo:includepolldetails:includeparentmessageinfo:replytype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/init(includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Default parameter constructor"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"includeMetaArray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeReactions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeThreadInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includePollDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeParentMessageInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReplyType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReplyType"},{"kind":"text","text":")"}],"title":"init(includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams(im)initWithIncludeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithIncludeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReplyType":{"role":"symbol","title":"ReplyType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReplyType"}],"abstract":[{"type":"text","text":"Reply type filter"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReplyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReplyType"}],"url":"\/documentation\/sendbirdchatsdk\/replytype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams":{"role":"symbol","title":"MessageChangeLogsParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageChangeLogsParams"}],"abstract":[{"type":"text","text":"An object contains set of options for message change logs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageChangeLogsParams"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams/init(includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:)":{"role":"symbol","title":"init(includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"includeMetaArray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeReactions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeThreadInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includePollDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeParentMessageInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReplyType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReplyType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Default parameter constructor"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/init(includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithIncludeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/init(includemetaarray:includereactions:includethreadinfo:includepolldetails:includeparentmessageinfo:replytype:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithIncludeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithIncludeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithIncludeMetaArray:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"includeMetaArray"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeReactions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"includeReactions"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeThreadInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"includeThreadInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"includePollDetails:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"includePollDetails"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeParentMessageInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"includeParentMessageInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"replyType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReplyType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReplyType","text":"SBDReplyType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"replyType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReplyType\/title","value":"SBDReplyType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReplyType\/fragments","value":[{"kind":"identifier","text":"SBDReplyType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams\/title","value":"SBDMessageChangeLogsParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams\/fragments","value":[{"kind":"identifier","text":"SBDMessageChangeLogsParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1init(includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:)\/title","value":"initWithIncludeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1init(includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithIncludeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}