{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"replyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReplyType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReplyType","text":"ReplyType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/replytype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/replytype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/replyType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Determines which reply types to include in the results. Default is "},{"type":"codeVoice","code":".none"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"replyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReplyType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReplyType"}],"title":"replyType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams(py)replyType","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"replyType"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReplyType":{"role":"symbol","title":"ReplyType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReplyType"}],"abstract":[{"type":"text","text":"Reply type filter"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReplyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReplyType"}],"url":"\/documentation\/sendbirdchatsdk\/replytype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams/replyType":{"role":"symbol","title":"replyType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"replyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReplyType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReplyType"}],"abstract":[{"type":"text","text":"Determines which reply types to include in the results. Default is "},{"type":"codeVoice","code":".none"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/replyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"replyType"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/replytype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams":{"role":"symbol","title":"MessageChangeLogsParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageChangeLogsParams"}],"abstract":[{"type":"text","text":"An object contains set of options for message change logs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageChangeLogsParams"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"replyType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"replyType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReplyType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReplyType","text":"SBDReplyType"},{"kind":"identifier","text":"replyType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReplyType\/title","value":"SBDReplyType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReplyType\/fragments","value":[{"kind":"identifier","text":"SBDReplyType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1replyType\/title","value":"replyType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1replyType\/fragments","value":[{"kind":"identifier","text":"replyType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams\/title","value":"SBDMessageChangeLogsParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams\/fragments","value":[{"kind":"identifier","text":"SBDMessageChangeLogsParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}