{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagesendingstatus\/failed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagesendingstatus\/failed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/failed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates the status of the message that failed to send the message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"title":"MessageSendingStatus.failed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDMessageSendingStatus@SBDMessageSendingStatusFailed","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDMessageSendingStatusFailed"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus/failed":{"role":"symbol","title":"MessageSendingStatus.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"Indicates the status of the message that failed to send the message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageSendingStatusFailed"}],"url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus\/failed"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus":{"role":"symbol","title":"MessageSendingStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSendingStatus"}],"abstract":[{"type":"text","text":"Constants of type to describe message’s sending status."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageSendingStatus"}],"url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageSendingStatusFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatusFailed"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDMessageSendingStatusFailed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1failed\/title","value":"SBDMessageSendingStatusFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1failed\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatusFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus\/title","value":"SBDMessageSendingStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}