{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagesendingstatus\/pending"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagesendingstatus\/pending"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/pending","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates the status of the message returned when trying to send a message."},{"type":"text","text":" "},{"type":"text","text":"The message with the pending status means that is not dispatched completely to the Sendbird"},{"type":"text","text":" "},{"type":"text","text":"server. The pending message should be replaced with a message (failed or succeeded)"},{"type":"text","text":" "},{"type":"text","text":"from the callback."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"title":"MessageSendingStatus.pending","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDMessageSendingStatus@SBDMessageSendingStatusPending","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDMessageSendingStatusPending"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus":{"role":"symbol","title":"MessageSendingStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSendingStatus"}],"abstract":[{"type":"text","text":"Constants of type to describe message’s sending status."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageSendingStatus"}],"url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus/pending":{"role":"symbol","title":"MessageSendingStatus.pending","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"abstract":[{"type":"text","text":"Indicates the status of the message returned when trying to send a message."},{"type":"text","text":" "},{"type":"text","text":"The message with the pending status means that is not dispatched completely to the Sendbird"},{"type":"text","text":" "},{"type":"text","text":"server. The pending message should be replaced with a message (failed or succeeded)"},{"type":"text","text":" "},{"type":"text","text":"from the callback."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/pending","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageSendingStatusPending"}],"url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus\/pending"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageSendingStatusPending"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatusPending"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDMessageSendingStatusPending"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus\/title","value":"SBDMessageSendingStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1pending\/title","value":"SBDMessageSendingStatusPending"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1pending\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatusPending"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}