{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"succeeded"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagesendingstatus\/succeeded"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagesendingstatus\/succeeded"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/succeeded","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates the status of the message that success to send the message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"succeeded"}],"title":"MessageSendingStatus.succeeded","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDMessageSendingStatus@SBDMessageSendingStatusSucceeded","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDMessageSendingStatusSucceeded"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus":{"role":"symbol","title":"MessageSendingStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSendingStatus"}],"abstract":[{"type":"text","text":"Constants of type to describe message’s sending status."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageSendingStatus"}],"url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus/succeeded":{"role":"symbol","title":"MessageSendingStatus.succeeded","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"succeeded"}],"abstract":[{"type":"text","text":"Indicates the status of the message that success to send the message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/succeeded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageSendingStatusSucceeded"}],"url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus\/succeeded"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageSendingStatusSucceeded"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatusSucceeded"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDMessageSendingStatusSucceeded"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus\/title","value":"SBDMessageSendingStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1succeeded\/title","value":"SBDMessageSendingStatusSucceeded"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1succeeded\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatusSucceeded"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}