{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionWasClosed"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"App should force a user to a login page to connect again."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.205"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sessiondelegate\/sessionwasclosed()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/sessiondelegate\/sessionwasclosed()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionWasClosed()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the SDK can’t refresh the session."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"sessionWasClosed"}],"role":"symbol","title":"sessionWasClosed()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionWasClosed"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDSessionDelegate(im)sessionWasClosed","required":true,"modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SessionDelegate/sessionWasClosed()":{"navigatorTitle":[{"kind":"identifier","text":"sessionWasClosed"}],"role":"symbol","title":"sessionWasClosed()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionWasClosed"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the SDK can’t refresh the session."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionWasClosed()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/sessiondelegate\/sessionwasclosed()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SessionDelegate":{"role":"symbol","title":"SessionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionDelegate"}],"abstract":[{"type":"text","text":"Represents a delegate to receive session relates events"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/sessiondelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sessionWasClosed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionWasClosed"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"sessionWasClosed"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate~1sessionWasClosed()\/title","value":"sessionWasClosed"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate~1sessionWasClosed()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionWasClosed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate\/title","value":"SBDSessionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate\/fragments","value":[{"kind":"identifier","text":"SBDSessionDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}