{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionTokenDidRequire"},{"kind":"text","text":"("},{"kind":"externalParam","text":"successCompletion"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failCompletion"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fail"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"success","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this block method after retrieving a new token. In case when"},{"type":"text","text":" "},{"type":"text","text":"app decides not to refresh the session for this user, they should call this with "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]},{"name":"fail","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this block method when failed to retrieve a new token."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Pass on the new (retrieved) token to SDK via "},{"type":"codeVoice","code":"success(NEW_TOKEN)"},{"type":"text","text":" or "},{"type":"codeVoice","code":"fail()"},{"type":"text","text":" if fetch failed."},{"type":"text","text":" "},{"type":"text","text":"In case when app decides not to refresh the session for this user, they should call "},{"type":"codeVoice","code":"success(nil)"},{"type":"text","text":"."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.205"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sessiondelegate\/sessiontokendidrequire(successcompletion:failcompletion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/sessiondelegate\/sessiontokendidrequire(successcompletion:failcompletion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionTokenDidRequire(successCompletion:failCompletion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"App needs to fetch a new token."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"sessionTokenDidRequireWithSuccessCompletion:failCompletion:"}],"role":"symbol","title":"sessionTokenDidRequire(successCompletion:failCompletion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionTokenDidRequire"},{"kind":"text","text":"("},{"kind":"externalParam","text":"successCompletion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failCompletion"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDSessionDelegate(im)sessionTokenDidRequireWithSuccessCompletion:failCompletion:","required":true,"modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SessionDelegate":{"role":"symbol","title":"SessionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionDelegate"}],"abstract":[{"type":"text","text":"Represents a delegate to receive session relates events"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/sessiondelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SessionDelegate/sessionTokenDidRequire(successCompletion:failCompletion:)":{"navigatorTitle":[{"kind":"identifier","text":"sessionTokenDidRequireWithSuccessCompletion:failCompletion:"}],"role":"symbol","title":"sessionTokenDidRequire(successCompletion:failCompletion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionTokenDidRequire"},{"kind":"text","text":"("},{"kind":"externalParam","text":"successCompletion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failCompletion"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"App needs to fetch a new token."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionTokenDidRequire(successCompletion:failCompletion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/sessiondelegate\/sessiontokendidrequire(successcompletion:failcompletion:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sessionTokenDidRequireWithSuccessCompletion:failCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionTokenDidRequireWithSuccessCompletion:failCompletion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"sessionTokenDidRequireWithSuccessCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSString *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSString)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"success"},{"kind":"text","text":" "},{"kind":"identifier","text":"failCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":")"},{"kind":"internalParam","text":"fail"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate\/title","value":"SBDSessionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate\/fragments","value":[{"kind":"identifier","text":"SBDSessionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate~1sessionTokenDidRequire(successCompletion:failCompletion:)\/title","value":"sessionTokenDidRequireWithSuccessCompletion:failCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate~1sessionTokenDidRequire(successCompletion:failCompletion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionTokenDidRequireWithSuccessCompletion:failCompletion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}