{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionDidHaveError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError","text":"SBError"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error object"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.205"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sessiondelegate\/sessiondidhaveerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/sessiondelegate\/sessiondidhaveerror(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionDidHaveError(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the SDK run into an error while refreshing the session key."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"sessionDidHaveError:"}],"role":"symbol","title":"sessionDidHaveError(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionDidHaveError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDSessionDelegate(im)sessionDidHaveError:","required":true,"modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBError":{"role":"symbol","title":"SBError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBError"}],"abstract":[{"type":"text","text":"Sendbird error class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBError"}],"url":"\/documentation\/sendbirdchatsdk\/sberror"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SessionDelegate":{"role":"symbol","title":"SessionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionDelegate"}],"abstract":[{"type":"text","text":"Represents a delegate to receive session relates events"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/sessiondelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SessionDelegate/sessionDidHaveError(_:)":{"navigatorTitle":[{"kind":"identifier","text":"sessionDidHaveError:"}],"role":"symbol","title":"sessionDidHaveError(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionDidHaveError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the SDK run into an error while refreshing the session key."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionDidHaveError(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/sessiondelegate\/sessiondidhaveerror(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sessionDidHaveError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionDidHaveError:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"sessionDidHaveError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError","text":"SBError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SBError\/title","value":"SBError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SBError\/fragments","value":[{"kind":"identifier","text":"SBError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate\/title","value":"SBDSessionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate\/fragments","value":[{"kind":"identifier","text":"SBDSessionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate~1sessionDidHaveError(_:)\/title","value":"sessionDidHaveError:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate~1sessionDidHaveError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionDidHaveError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}