{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailSizes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize","text":"ThumbnailSize"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/scheduledfilemessageupdateparams\/thumbnailsizes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/scheduledfilemessageupdateparams\/thumbnailsizes"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledFileMessageUpdateParams\/thumbnailSizes","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The thumbnail sizes. This parameter is the array of "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" instance and works for image file only."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailSizes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize"},{"kind":"text","text":"]?"}],"title":"thumbnailSizes","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledFileMessageUpdateParams(py)thumbnailSizes","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"thumbnailSizes"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledFileMessageUpdateParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledFileMessageUpdateParams":{"role":"symbol","title":"ScheduledFileMessageUpdateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledFileMessageUpdateParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledFileMessageUpdateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledFileMessageUpdateParams"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledfilemessageupdateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledFileMessageUpdateParams/thumbnailSizes":{"role":"symbol","title":"thumbnailSizes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailSizes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The thumbnail sizes. This parameter is the array of "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" instance and works for image file only."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledFileMessageUpdateParams\/thumbnailSizes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnailSizes"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledfilemessageupdateparams\/thumbnailsizes"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThumbnailSize":{"role":"symbol","title":"ThumbnailSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailSize"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" class represents the thumbnail size of thumbnail."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThumbnailSize"}],"url":"\/documentation\/sendbirdchatsdk\/thumbnailsize"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"thumbnailSizes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"thumbnailSizes"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBDThumbnailSize *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *"},{"kind":"identifier","text":"thumbnailSizes"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledFileMessageUpdateParams\/title","value":"SBDScheduledFileMessageUpdateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledFileMessageUpdateParams\/fragments","value":[{"kind":"identifier","text":"SBDScheduledFileMessageUpdateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledFileMessageUpdateParams~1thumbnailSizes\/title","value":"thumbnailSizes"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledFileMessageUpdateParams~1thumbnailSizes\/fragments","value":[{"kind":"identifier","text":"thumbnailSizes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize\/title","value":"SBDThumbnailSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize\/fragments","value":[{"kind":"identifier","text":"SBDThumbnailSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}