{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"harassing"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/reportcategory\/harassing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/reportcategory\/harassing"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/harassing","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Report harassing content."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"harassing"}],"title":"ReportCategory.harassing","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDReportCategory@SBDReportCategoryHarassing","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDReportCategoryHarassing"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReportCategory":{"role":"symbol","title":"ReportCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportCategory"}],"abstract":[{"type":"text","text":"Categories of reporting reasons"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReportCategory"}],"url":"\/documentation\/sendbirdchatsdk\/reportcategory"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReportCategory/harassing":{"role":"symbol","title":"ReportCategory.harassing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"harassing"}],"abstract":[{"type":"text","text":"Report harassing content."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/harassing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDReportCategoryHarassing"}],"url":"\/documentation\/sendbirdchatsdk\/reportcategory\/harassing"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDReportCategoryHarassing"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDReportCategoryHarassing"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDReportCategoryHarassing"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory\/title","value":"SBDReportCategory"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory\/fragments","value":[{"kind":"identifier","text":"SBDReportCategory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory~1harassing\/title","value":"SBDReportCategoryHarassing"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory~1harassing\/fragments","value":[{"kind":"identifier","text":"SBDReportCategoryHarassing"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}