{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suspicious"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/reportcategory\/suspicious"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/reportcategory\/suspicious"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/suspicious","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Report suspicious content"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suspicious"}],"title":"ReportCategory.suspicious","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDReportCategory@SBDReportCategorySuspicious","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDReportCategorySuspicious"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReportCategory":{"role":"symbol","title":"ReportCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportCategory"}],"abstract":[{"type":"text","text":"Categories of reporting reasons"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReportCategory"}],"url":"\/documentation\/sendbirdchatsdk\/reportcategory"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReportCategory/suspicious":{"role":"symbol","title":"ReportCategory.suspicious","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suspicious"}],"abstract":[{"type":"text","text":"Report suspicious content"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/suspicious","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDReportCategorySuspicious"}],"url":"\/documentation\/sendbirdchatsdk\/reportcategory\/suspicious"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDReportCategorySuspicious"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDReportCategorySuspicious"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDReportCategorySuspicious"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory\/title","value":"SBDReportCategory"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory\/fragments","value":[{"kind":"identifier","text":"SBDReportCategory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory~1suspicious\/title","value":"SBDReportCategorySuspicious"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory~1suspicious\/fragments","value":[{"kind":"identifier","text":"SBDReportCategorySuspicious"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}