{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQuery","text":"SBDMemberListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createMemberListQueryWithChannelURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"params:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQueryParams","text":"SBDMemberListQueryParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"\\param params The params object to change query condition."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"returns:"},{"type":"text","text":" "},{"type":"text","text":"The instance to query the members in group channel."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sbdgroupchannel\/creatememberlistquerywithchannelurl:params:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBDGroupChannel\/createMemberListQueryWithChannelURL:params:","interfaceLanguage":"occ"},"abstract":[{"type":"text","text":"Creates a query for members in group channel."},{"type":"text","text":" "},{"type":"text","text":"\\param channelURL channel url"}],"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createMemberListQueryWithChannelURL:params:"}],"title":"createMemberListQueryWithChannelURL:params:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDGroupChannel(cm)createMemberListQueryWithChannelURL:params:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"createMemberListQueryWithChannelURL:params:"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQueryParams":{"role":"symbol","title":"MemberListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBDGroupChannel/createMemberListQueryWithChannelURL:params:":{"role":"symbol","title":"createMemberListQueryWithChannelURL:params:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createMemberListQueryWithChannelURL:params:"}],"abstract":[{"type":"text","text":"Creates a query for members in group channel."},{"type":"text","text":" "},{"type":"text","text":"\\param channelURL channel url"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBDGroupChannel\/createMemberListQueryWithChannelURL:params:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createMemberListQueryWithChannelURL:params:"}],"url":"\/documentation\/sendbirdchatsdk\/sbdgroupchannel\/creatememberlistquerywithchannelurl:params:"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery":{"role":"symbol","title":"MemberListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MemberListQuery"},{"type":"text","text":" class is a query class for getting the list member in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams\/title","value":"SBDMemberListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDMemberListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery\/title","value":"SBDMemberListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery\/fragments","value":[{"kind":"identifier","text":"SBDMemberListQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}