{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invitedByNonFriend"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/memberstatefilter\/invitedbynonfriend"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/memberstatefilter\/invitedbynonfriend"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/invitedByNonFriend","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Filter of invited by non-friend state only."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invitedByNonFriend"}],"title":"MemberStateFilter.invitedByNonFriend","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDMemberStateFilter@SBDMemberStateFilterInvitedByNonFriend","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDMemberStateFilterInvitedByNonFriend"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberStateFilter":{"role":"symbol","title":"MemberStateFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberStateFilter"}],"abstract":[{"type":"text","text":"Member state filter for group channel list query and group channel count"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberStateFilter"}],"url":"\/documentation\/sendbirdchatsdk\/memberstatefilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberStateFilter/invitedByNonFriend":{"role":"symbol","title":"MemberStateFilter.invitedByNonFriend","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invitedByNonFriend"}],"abstract":[{"type":"text","text":"Filter of invited by non-friend state only."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/invitedByNonFriend","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMemberStateFilterInvitedByNonFriend"}],"url":"\/documentation\/sendbirdchatsdk\/memberstatefilter\/invitedbynonfriend"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDMemberStateFilterInvitedByNonFriend"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMemberStateFilterInvitedByNonFriend"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDMemberStateFilterInvitedByNonFriend"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter\/title","value":"SBDMemberStateFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter\/fragments","value":[{"kind":"identifier","text":"SBDMemberStateFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter~1invitedByNonFriend\/title","value":"SBDMemberStateFilterInvitedByNonFriend"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter~1invitedByNonFriend\/fragments","value":[{"kind":"identifier","text":"SBDMemberStateFilterInvitedByNonFriend"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}