{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinedOnly"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/memberstatefilter\/joinedonly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/memberstatefilter\/joinedonly"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/joinedOnly","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Filter of joined state only."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinedOnly"}],"title":"MemberStateFilter.joinedOnly","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDMemberStateFilter@SBDMemberStateFilterJoinedOnly","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDMemberStateFilterJoinedOnly"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberStateFilter/joinedOnly":{"role":"symbol","title":"MemberStateFilter.joinedOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinedOnly"}],"abstract":[{"type":"text","text":"Filter of joined state only."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/joinedOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMemberStateFilterJoinedOnly"}],"url":"\/documentation\/sendbirdchatsdk\/memberstatefilter\/joinedonly"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberStateFilter":{"role":"symbol","title":"MemberStateFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberStateFilter"}],"abstract":[{"type":"text","text":"Member state filter for group channel list query and group channel count"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberStateFilter"}],"url":"\/documentation\/sendbirdchatsdk\/memberstatefilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDMemberStateFilterJoinedOnly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMemberStateFilterJoinedOnly"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDMemberStateFilterJoinedOnly"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter~1joinedOnly\/title","value":"SBDMemberStateFilterJoinedOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter~1joinedOnly\/fragments","value":[{"kind":"identifier","text":"SBDMemberStateFilterJoinedOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter\/title","value":"SBDMemberStateFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter\/fragments","value":[{"kind":"identifier","text":"SBDMemberStateFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}