{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadMessageCountOnly"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/countpreference\/unreadmessagecountonly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/countpreference\/unreadmessagecountonly"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/unreadMessageCountOnly","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The channel of this preference has only unread message count."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadMessageCountOnly"}],"title":"CountPreference.unreadMessageCountOnly","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDCountPreference@SBDCountPreferenceUnreadMessageCountOnly","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDCountPreferenceUnreadMessageCountOnly"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CountPreference/unreadMessageCountOnly":{"role":"symbol","title":"CountPreference.unreadMessageCountOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadMessageCountOnly"}],"abstract":[{"type":"text","text":"The channel of this preference has only unread message count."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/unreadMessageCountOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCountPreferenceUnreadMessageCountOnly"}],"url":"\/documentation\/sendbirdchatsdk\/countpreference\/unreadmessagecountonly"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CountPreference":{"role":"symbol","title":"CountPreference","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CountPreference"}],"abstract":[{"type":"text","text":"The enum type to represent various kinds of counts."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CountPreference"}],"url":"\/documentation\/sendbirdchatsdk\/countpreference"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDCountPreferenceUnreadMessageCountOnly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDCountPreferenceUnreadMessageCountOnly"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDCountPreferenceUnreadMessageCountOnly"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CountPreference~1unreadMessageCountOnly\/title","value":"SBDCountPreferenceUnreadMessageCountOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CountPreference~1unreadMessageCountOnly\/fragments","value":[{"kind":"identifier","text":"SBDCountPreferenceUnreadMessageCountOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CountPreference\/title","value":"SBDCountPreference"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CountPreference\/fragments","value":[{"kind":"identifier","text":"SBDCountPreference"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}