{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatedVoteCounts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UpdatedVoteCount","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUpdatedVoteCount","text":"UpdatedVoteCount"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/pollvoteevent\/updatedvotecounts"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/pollvoteevent\/updatedvotecounts"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollVoteEvent\/updatedVoteCounts","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Updated poll options"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatedVoteCounts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UpdatedVoteCount","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUpdatedVoteCount"},{"kind":"text","text":"]"}],"title":"updatedVoteCounts","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDPollVoteEvent(py)updatedVoteCounts","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"updatedVoteCounts"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollVoteEvent"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollVoteEvent":{"role":"symbol","title":"PollVoteEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollVoteEvent"}],"abstract":[{"type":"text","text":"Represents a vote event on a poll"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollVoteEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PollVoteEvent"}],"url":"\/documentation\/sendbirdchatsdk\/pollvoteevent"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UpdatedVoteCount":{"role":"symbol","title":"UpdatedVoteCount","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpdatedVoteCount"}],"abstract":[{"type":"text","text":"An object contains information about updated vote count"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UpdatedVoteCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UpdatedVoteCount"}],"url":"\/documentation\/sendbirdchatsdk\/updatedvotecount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollVoteEvent/updatedVoteCounts":{"role":"symbol","title":"updatedVoteCounts","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatedVoteCounts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UpdatedVoteCount","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUpdatedVoteCount"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Updated poll options"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollVoteEvent\/updatedVoteCounts","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updatedVoteCounts"}],"url":"\/documentation\/sendbirdchatsdk\/pollvoteevent\/updatedvotecounts"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"updatedVoteCounts"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"updatedVoteCounts"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBDUpdatedVoteCount *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *"},{"kind":"identifier","text":"updatedVoteCounts"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollVoteEvent\/title","value":"SBDPollVoteEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollVoteEvent\/fragments","value":[{"kind":"identifier","text":"SBDPollVoteEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UpdatedVoteCount\/title","value":"SBDUpdatedVoteCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UpdatedVoteCount\/fragments","value":[{"kind":"identifier","text":"SBDUpdatedVoteCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollVoteEvent~1updatedVoteCounts\/title","value":"updatedVoteCounts"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollVoteEvent~1updatedVoteCounts\/fragments","value":[{"kind":"identifier","text":"updatedVoteCounts"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}