{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelChangelog"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/collectioneventsource\/channelchangelog"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/collectioneventsource\/channelchangelog"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/channelChangelog","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Channel change log"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelChangelog"}],"title":"CollectionEventSource.channelChangelog","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDCollectionEventSource@SBDCollectionEventSourceChannelChangelog","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceChannelChangelog"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/channelChangelog":{"role":"symbol","title":"CollectionEventSource.channelChangelog","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelChangelog"}],"abstract":[{"type":"text","text":"Channel change log"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/channelChangelog","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceChannelChangelog"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/channelchangelog"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource":{"role":"symbol","title":"CollectionEventSource","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionEventSource"}],"abstract":[{"type":"text","text":"Channel sources that represents where the channel object comes from."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CollectionEventSource"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDCollectionEventSourceChannelChangelog"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceChannelChangelog"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDCollectionEventSourceChannelChangelog"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1channelChangelog\/title","value":"SBDCollectionEventSourceChannelChangelog"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1channelChangelog\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceChannelChangelog"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource\/title","value":"SBDCollectionEventSource"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}