{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventChannelDeleted"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventchanneldeleted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventchanneldeleted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelDeleted","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Channel has been deleted"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventChannelDeleted"}],"title":"CollectionEventSource.eventChannelDeleted","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDCollectionEventSource@SBDCollectionEventSourceEventChannelDeleted","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelDeleted"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource":{"role":"symbol","title":"CollectionEventSource","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionEventSource"}],"abstract":[{"type":"text","text":"Channel sources that represents where the channel object comes from."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CollectionEventSource"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventChannelDeleted":{"role":"symbol","title":"CollectionEventSource.eventChannelDeleted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventChannelDeleted"}],"abstract":[{"type":"text","text":"Channel has been deleted"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelDeleted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelDeleted"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventchanneldeleted"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDCollectionEventSourceEventChannelDeleted"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelDeleted"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelDeleted"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource\/title","value":"SBDCollectionEventSource"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSource"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelDeleted\/title","value":"SBDCollectionEventSourceEventChannelDeleted"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelDeleted\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelDeleted"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}