{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventChannelUnfrozen"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventchannelunfrozen"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventchannelunfrozen"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelUnfrozen","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Channel has been unfrozen"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventChannelUnfrozen"}],"title":"CollectionEventSource.eventChannelUnfrozen","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDCollectionEventSource@SBDCollectionEventSourceEventChannelUnfrozen","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelUnfrozen"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventChannelUnfrozen":{"role":"symbol","title":"CollectionEventSource.eventChannelUnfrozen","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventChannelUnfrozen"}],"abstract":[{"type":"text","text":"Channel has been unfrozen"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelUnfrozen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelUnfrozen"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventchannelunfrozen"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource":{"role":"symbol","title":"CollectionEventSource","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionEventSource"}],"abstract":[{"type":"text","text":"Channel sources that represents where the channel object comes from."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CollectionEventSource"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDCollectionEventSourceEventChannelUnfrozen"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelUnfrozen"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelUnfrozen"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelUnfrozen\/title","value":"SBDCollectionEventSourceEventChannelUnfrozen"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelUnfrozen\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelUnfrozen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource\/title","value":"SBDCollectionEventSource"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}