{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localMessageCanceled"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/collectioneventsource\/localmessagecanceled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/collectioneventsource\/localmessagecanceled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/localMessageCanceled","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Message has been canceled"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localMessageCanceled"}],"title":"CollectionEventSource.localMessageCanceled","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDCollectionEventSource@SBDCollectionEventSourceLocalMessageCanceled","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceLocalMessageCanceled"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/localMessageCanceled":{"role":"symbol","title":"CollectionEventSource.localMessageCanceled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localMessageCanceled"}],"abstract":[{"type":"text","text":"Message has been canceled"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/localMessageCanceled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceLocalMessageCanceled"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/localmessagecanceled"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource":{"role":"symbol","title":"CollectionEventSource","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionEventSource"}],"abstract":[{"type":"text","text":"Channel sources that represents where the channel object comes from."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CollectionEventSource"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDCollectionEventSourceLocalMessageCanceled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceLocalMessageCanceled"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDCollectionEventSourceLocalMessageCanceled"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1localMessageCanceled\/title","value":"SBDCollectionEventSourceLocalMessageCanceled"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1localMessageCanceled\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceLocalMessageCanceled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource\/title","value":"SBDCollectionEventSource"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}