{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asSBError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError","text":"SBError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/chaterror\/assberror(message:)-7qwcr"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChatError\/asSBError(message:)-7qwcr","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SBErrorCode.asSBError(message:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asSBError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError"}],"title":"asSBError(message:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:15SendbirdChatSDK0B5ErrorO9asSBError7messageAA0F0CSSSg_tF","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChatError"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBError":{"role":"symbol","title":"SBError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBError"}],"abstract":[{"type":"text","text":"Sendbird error class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBError"}],"url":"\/documentation\/sendbirdchatsdk\/sberror"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChatError/asSBError(message:)-7qwcr":{"role":"symbol","title":"asSBError(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asSBError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChatError\/asSBError(message:)-7qwcr","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/chaterror\/assberror(message:)-7qwcr"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChatError":{"role":"symbol","title":"ChatError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatError"}],"url":"\/documentation\/sendbirdchatsdk\/chaterror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SBError\/title","value":"SBError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SBError\/fragments","value":[{"kind":"identifier","text":"SBError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChatError\/title","value":"SBChatError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChatError\/fragments","value":[{"kind":"identifier","text":"SBChatError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}