{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidParameterValueBoolean"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/chaterror\/invalidparametervalueboolean"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/chaterror\/invalidparametervalueboolean"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChatError\/invalidParameterValueBoolean","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidParameterValueBoolean"}],"title":"ChatError.invalidParameterValueBoolean","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBChatError@SBChatErrorInvalidParameterValueBoolean","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBChatErrorInvalidParameterValueBoolean"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChatError"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChatError":{"role":"symbol","title":"ChatError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatError"}],"url":"\/documentation\/sendbirdchatsdk\/chaterror"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChatError/invalidParameterValueBoolean":{"role":"symbol","title":"ChatError.invalidParameterValueBoolean","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidParameterValueBoolean"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChatError\/invalidParameterValueBoolean","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBChatErrorInvalidParameterValueBoolean"}],"url":"\/documentation\/sendbirdchatsdk\/chaterror\/invalidparametervalueboolean"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBChatErrorInvalidParameterValueBoolean"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBChatErrorInvalidParameterValueBoolean"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBChatErrorInvalidParameterValueBoolean"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChatError\/title","value":"SBChatError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChatError\/fragments","value":[{"kind":"identifier","text":"SBChatError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChatError~1invalidParameterValueBoolean\/title","value":"SBChatErrorInvalidParameterValueBoolean"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChatError~1invalidParameterValueBoolean\/fragments","value":[{"kind":"identifier","text":"SBChatErrorInvalidParameterValueBoolean"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}