{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notFoundInDatabase"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/chaterror\/notfoundindatabase"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/chaterror\/notfoundindatabase"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChatError\/notFoundInDatabase","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notFoundInDatabase"}],"title":"ChatError.notFoundInDatabase","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBChatError@SBChatErrorNotFoundInDatabase","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBChatErrorNotFoundInDatabase"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChatError"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChatError/notFoundInDatabase":{"role":"symbol","title":"ChatError.notFoundInDatabase","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notFoundInDatabase"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChatError\/notFoundInDatabase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBChatErrorNotFoundInDatabase"}],"url":"\/documentation\/sendbirdchatsdk\/chaterror\/notfoundindatabase"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChatError":{"role":"symbol","title":"ChatError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatError"}],"url":"\/documentation\/sendbirdchatsdk\/chaterror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBChatErrorNotFoundInDatabase"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBChatErrorNotFoundInDatabase"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBChatErrorNotFoundInDatabase"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChatError~1notFoundInDatabase\/title","value":"SBChatErrorNotFoundInDatabase"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChatError~1notFoundInDatabase\/fragments","value":[{"kind":"identifier","text":"SBChatErrorNotFoundInDatabase"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChatError\/title","value":"SBChatError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChatError\/fragments","value":[{"kind":"identifier","text":"SBChatError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}