{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheAndReplaceByApi"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagecollectioninitpolicy\/cacheandreplacebyapi"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagecollectioninitpolicy\/cacheandreplacebyapi"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionInitPolicy\/cacheAndReplaceByApi","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Caches will be replaced by api result"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheAndReplaceByApi"}],"title":"MessageCollectionInitPolicy.cacheAndReplaceByApi","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDMessageCollectionInitPolicy@SBDMessageCollectionInitPolicyCacheAndReplaceByApi","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDMessageCollectionInitPolicyCacheAndReplaceByApi"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionInitPolicy"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionInitPolicy":{"role":"symbol","title":"MessageCollectionInitPolicy","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollectionInitPolicy"}],"abstract":[{"type":"text","text":"The policy for the message collection initialization."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionInitPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollectionInitPolicy"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollectioninitpolicy"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionInitPolicy/cacheAndReplaceByApi":{"role":"symbol","title":"MessageCollectionInitPolicy.cacheAndReplaceByApi","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheAndReplaceByApi"}],"abstract":[{"type":"text","text":"Caches will be replaced by api result"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionInitPolicy\/cacheAndReplaceByApi","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageCollectionInitPolicyCacheAndReplaceByApi"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollectioninitpolicy\/cacheandreplacebyapi"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageCollectionInitPolicyCacheAndReplaceByApi"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollectionInitPolicyCacheAndReplaceByApi"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDMessageCollectionInitPolicyCacheAndReplaceByApi"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionInitPolicy\/title","value":"SBDMessageCollectionInitPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionInitPolicy\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollectionInitPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionInitPolicy~1cacheAndReplaceByApi\/title","value":"SBDMessageCollectionInitPolicyCacheAndReplaceByApi"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionInitPolicy~1cacheAndReplaceByApi\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollectionInitPolicyCacheAndReplaceByApi"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}