{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption\/default"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption\/default"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/default","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The push notification will be delivered by the opposite user’s setting."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"title":"PushNotificationDeliveryOption.default","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDPushNotificationDeliveryOption@SBDPushNotificationDeliveryOptionDefault","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOptionDefault"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushNotificationDeliveryOption":{"role":"symbol","title":"PushNotificationDeliveryOption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationDeliveryOption"}],"abstract":[{"type":"text","text":"The push option that determines how to deliver the push notification when sending a user or a file message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationDeliveryOption"}],"url":"\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushNotificationDeliveryOption/default":{"role":"symbol","title":"PushNotificationDeliveryOption.default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"abstract":[{"type":"text","text":"The push notification will be delivered by the opposite user’s setting."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOptionDefault"}],"url":"\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption\/default"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDPushNotificationDeliveryOptionDefault"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOptionDefault"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOptionDefault"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption\/title","value":"SBDPushNotificationDeliveryOption"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption\/fragments","value":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption~1default\/title","value":"SBDPushNotificationDeliveryOptionDefault"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption~1default\/fragments","value":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOptionDefault"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}