{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suppress"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption\/suppress"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption\/suppress"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/suppress","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The push notification will never be delivered."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suppress"}],"title":"PushNotificationDeliveryOption.suppress","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDPushNotificationDeliveryOption@SBDPushNotificationDeliveryOptionSuppress","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOptionSuppress"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushNotificationDeliveryOption/suppress":{"role":"symbol","title":"PushNotificationDeliveryOption.suppress","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suppress"}],"abstract":[{"type":"text","text":"The push notification will never be delivered."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/suppress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOptionSuppress"}],"url":"\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption\/suppress"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushNotificationDeliveryOption":{"role":"symbol","title":"PushNotificationDeliveryOption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationDeliveryOption"}],"abstract":[{"type":"text","text":"The push option that determines how to deliver the push notification when sending a user or a file message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationDeliveryOption"}],"url":"\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDPushNotificationDeliveryOptionSuppress"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOptionSuppress"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOptionSuppress"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption~1suppress\/title","value":"SBDPushNotificationDeliveryOptionSuppress"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption~1suppress\/fragments","value":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOptionSuppress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption\/title","value":"SBDPushNotificationDeliveryOption"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption\/fragments","value":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}