{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didVotePoll"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollVoteEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollVoteEvent","text":"PollVoteEvent"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"event","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"event object that contains voting information."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.232"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechanneldelegate\/didvotepoll(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechanneldelegate\/didvotepoll(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/didVotePoll(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A callback when vote has been occurred."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didVotePoll:"}],"role":"symbol","title":"didVotePoll(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didVotePoll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PollVoteEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollVoteEvent"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDBaseChannelDelegate(im)didVotePoll:","required":true,"modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/didVotePoll(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didVotePoll:"}],"role":"symbol","title":"didVotePoll(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didVotePoll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PollVoteEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollVoteEvent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when vote has been occurred."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/didVotePoll(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/didvotepoll(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate":{"role":"symbol","title":"BaseChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events"},{"type":"text","text":" "},{"type":"text","text":"in the channel. Delegate methods in "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" are common for the "},{"type":"codeVoice","code":"BaseChannel"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Exclusive delegate methods for "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" can be found in"},{"type":"text","text":" "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":". You must use "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":" instead of using "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" by using "},{"type":"codeVoice","code":"add(_:identifier:)"},{"type":"text","text":" in "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollVoteEvent":{"role":"symbol","title":"PollVoteEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollVoteEvent"}],"abstract":[{"type":"text","text":"Represents a vote event on a poll"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollVoteEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PollVoteEvent"}],"url":"\/documentation\/sendbirdchatsdk\/pollvoteevent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didVotePoll:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didVotePoll:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didVotePoll:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollVoteEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollVoteEvent","text":"SBDPollVoteEvent"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"event"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1didVotePoll(_:)\/title","value":"didVotePoll:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1didVotePoll(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didVotePoll:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate\/title","value":"SBDBaseChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannelDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollVoteEvent\/title","value":"SBDPollVoteEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollVoteEvent\/fragments","value":[{"kind":"identifier","text":"SBDPollVoteEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}