{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"file"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/filemessagecreateparams\/file"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/filemessagecreateparams\/file"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageCreateParams\/file","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Binary file data. "},{"type":"codeVoice","code":"file"},{"type":"text","text":" and "},{"type":"codeVoice","code":"fileURL"},{"type":"text","text":" cannot be set together."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"file"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"title":"file","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessageCreateParams(py)file","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"file"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageCreateParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessageCreateParams":{"role":"symbol","title":"FileMessageCreateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessageCreateParams"}],"abstract":[{"type":"text","text":"An object contains set of options to create "},{"type":"codeVoice","code":"FileMessage"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageCreateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessageCreateParams"}],"url":"\/documentation\/sendbirdchatsdk\/filemessagecreateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessageCreateParams/file":{"role":"symbol","title":"file","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"file"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Binary file data. "},{"type":"codeVoice","code":"file"},{"type":"text","text":" and "},{"type":"codeVoice","code":"fileURL"},{"type":"text","text":" cannot be set together."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageCreateParams\/file","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"file"}],"url":"\/documentation\/sendbirdchatsdk\/filemessagecreateparams\/file"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"file"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"file"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *"},{"kind":"identifier","text":"file"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessageCreateParams\/title","value":"SBDFileMessageCreateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessageCreateParams\/fragments","value":[{"kind":"identifier","text":"SBDFileMessageCreateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessageCreateParams~1file\/title","value":"file"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessageCreateParams~1file\/fragments","value":[{"kind":"identifier","text":"file"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}