{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailSizes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize","text":"ThumbnailSize"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/filemessagecreateparams\/thumbnailsizes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/filemessagecreateparams\/thumbnailsizes"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageCreateParams\/thumbnailSizes","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Thumbnail sizes. This parameter is the array of "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" instance and works for image file only."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailSizes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize"},{"kind":"text","text":"]?"}],"title":"thumbnailSizes","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessageCreateParams(py)thumbnailSizes","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"thumbnailSizes"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageCreateParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessageCreateParams":{"role":"symbol","title":"FileMessageCreateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessageCreateParams"}],"abstract":[{"type":"text","text":"An object contains set of options to create "},{"type":"codeVoice","code":"FileMessage"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageCreateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessageCreateParams"}],"url":"\/documentation\/sendbirdchatsdk\/filemessagecreateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessageCreateParams/thumbnailSizes":{"role":"symbol","title":"thumbnailSizes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailSizes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Thumbnail sizes. This parameter is the array of "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" instance and works for image file only."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageCreateParams\/thumbnailSizes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnailSizes"}],"url":"\/documentation\/sendbirdchatsdk\/filemessagecreateparams\/thumbnailsizes"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThumbnailSize":{"role":"symbol","title":"ThumbnailSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailSize"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" class represents the thumbnail size of thumbnail."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThumbnailSize"}],"url":"\/documentation\/sendbirdchatsdk\/thumbnailsize"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"thumbnailSizes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"thumbnailSizes"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBDThumbnailSize *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *"},{"kind":"identifier","text":"thumbnailSizes"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessageCreateParams\/title","value":"SBDFileMessageCreateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessageCreateParams\/fragments","value":[{"kind":"identifier","text":"SBDFileMessageCreateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessageCreateParams~1thumbnailSizes\/title","value":"thumbnailSizes"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessageCreateParams~1thumbnailSizes\/fragments","value":[{"kind":"identifier","text":"thumbnailSizes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize\/title","value":"SBDThumbnailSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize\/fragments","value":[{"kind":"identifier","text":"SBDThumbnailSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}