{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateTotalUnreadMessageCount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"totalCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalCountByCustomType"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"totalCount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"New total unread count"}]}]},{"name":"totalCountByCustomType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Dictionary with key of custom tyeps and value of unread count"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.154"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/usereventdelegate\/didupdatetotalunreadmessagecount(_:totalcountbycustomtype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/usereventdelegate\/didupdatetotalunreadmessagecount(_:totalcountbycustomtype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserEventDelegate\/didUpdateTotalUnreadMessageCount(_:totalCountByCustomType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Invoked when total unread message count has been updated"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didUpdateTotalUnreadMessageCount:totalCountByCustomType:"}],"role":"symbol","title":"didUpdateTotalUnreadMessageCount(_:totalCountByCustomType:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateTotalUnreadMessageCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalCountByCustomType"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]?)"}],"symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDUserEventDelegate(im)didUpdateTotalUnreadMessageCount:totalCountByCustomType:","required":true,"modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserEventDelegate"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserEventDelegate/didUpdateTotalUnreadMessageCount(_:totalCountByCustomType:)":{"navigatorTitle":[{"kind":"identifier","text":"didUpdateTotalUnreadMessageCount:totalCountByCustomType:"}],"role":"symbol","title":"didUpdateTotalUnreadMessageCount(_:totalCountByCustomType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateTotalUnreadMessageCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalCountByCustomType"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Invoked when total unread message count has been updated"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserEventDelegate\/didUpdateTotalUnreadMessageCount(_:totalCountByCustomType:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/usereventdelegate\/didupdatetotalunreadmessagecount(_:totalcountbycustomtype:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserEventDelegate":{"role":"symbol","title":"UserEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserEventDelegate"}],"abstract":[{"type":"text","text":"Represents a delegate to receive user relates events"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserEventDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserEventDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/usereventdelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didUpdateTotalUnreadMessageCount:totalCountByCustomType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateTotalUnreadMessageCount:totalCountByCustomType:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didUpdateTotalUnreadMessageCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int32_t","preciseIdentifier":"c:@T@int32_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"totalCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalCountByCustomType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"totalCountByCustomType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserEventDelegate~1didUpdateTotalUnreadMessageCount(_:totalCountByCustomType:)\/title","value":"didUpdateTotalUnreadMessageCount:totalCountByCustomType:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserEventDelegate~1didUpdateTotalUnreadMessageCount(_:totalCountByCustomType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateTotalUnreadMessageCount:totalCountByCustomType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserEventDelegate\/title","value":"SBDUserEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserEventDelegate\/fragments","value":[{"kind":"identifier","text":"SBDUserEventDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}