{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQueryParams","text":"MutedUserListQueryParams"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/muteduserlistquery\/params"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/muteduserlistquery\/params"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQuery\/params","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutedUserListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQueryParams"}],"title":"params","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQuery(py)params","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"params"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQuery"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MutedUserListQuery/params":{"role":"symbol","title":"params","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutedUserListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQuery\/params","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"params"}],"url":"\/documentation\/sendbirdchatsdk\/muteduserlistquery\/params"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MutedUserListQuery":{"role":"symbol","title":"MutedUserListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MutedUserListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MutedUserListQuery"},{"type":"text","text":" class is a query class for getting the list of muted users in"},{"type":"text","text":" "},{"type":"text","text":"a specific channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MutedUserListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/muteduserlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MutedUserListQueryParams":{"role":"symbol","title":"MutedUserListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MutedUserListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MutedUserListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/muteduserlistqueryparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"params"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"params"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQueryParams","text":"SBDMutedUserListQueryParams"},{"kind":"text","text":" *"},{"kind":"identifier","text":"params"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MutedUserListQuery~1params\/title","value":"params"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MutedUserListQuery~1params\/fragments","value":[{"kind":"identifier","text":"params"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MutedUserListQuery\/title","value":"SBDMutedUserListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MutedUserListQuery\/fragments","value":[{"kind":"identifier","text":"SBDMutedUserListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MutedUserListQueryParams\/title","value":"SBDMutedUserListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MutedUserListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDMutedUserListQueryParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}