{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(applyThreadInfoUpdateEvent:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apply"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"threadInfoUpdateEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadInfoUpdateEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadInfoUpdateEvent","text":"ThreadInfoUpdateEvent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" if "},{"type":"codeVoice","code":"threadInfoUpdateEvent"},{"type":"text","text":"was applied successfully otherwise "},{"type":"codeVoice","code":"false"}]}]},{"kind":"parameters","parameters":[{"name":"threadInfoUpdateEvent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The event object that is applied to."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.181"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basemessage\/apply(_:)-640ud"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basemessage\/apply(_:)-640ud"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/apply(_:)-640ud","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Applies the update of the thread information to the message object."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"applyThreadInfoUpdateEvent:"}],"role":"symbol","title":"apply(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apply"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ThreadInfoUpdateEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadInfoUpdateEvent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseMessage(im)applyThreadInfoUpdateEvent:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage":{"role":"symbol","title":"BaseMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessage"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":" class represents the base message which is generated by a user or an admin."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":", the "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"AdminMessage"},{"type":"text","text":" are derived from this class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessage"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/apply(_:)-640ud":{"role":"symbol","title":"apply(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apply"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ThreadInfoUpdateEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadInfoUpdateEvent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Applies the update of the thread information to the message object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/apply(_:)-640ud","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applyThreadInfoUpdateEvent:"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/apply(_:)-640ud"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadInfoUpdateEvent":{"role":"symbol","title":"ThreadInfoUpdateEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThreadInfoUpdateEvent"}],"abstract":[{"type":"text","text":"An object that is returned through the event handler when a threaded reply is added or deleted."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadInfoUpdateEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThreadInfoUpdateEvent"}],"url":"\/documentation\/sendbirdchatsdk\/threadinfoupdateevent"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"applyThreadInfoUpdateEvent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyThreadInfoUpdateEvent:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"applyThreadInfoUpdateEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadInfoUpdateEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadInfoUpdateEvent","text":"SBDThreadInfoUpdateEvent"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"threadInfoUpdateEvent"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/title","value":"SBDBaseMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1apply(_:)-640ud\/title","value":"applyThreadInfoUpdateEvent:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1apply(_:)-640ud\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyThreadInfoUpdateEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadInfoUpdateEvent\/title","value":"SBDThreadInfoUpdateEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadInfoUpdateEvent\/fragments","value":[{"kind":"identifier","text":"SBDThreadInfoUpdateEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}