{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(getScheduledMessageWithParams:completionHandler:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getScheduledMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledMessageRetrievalParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledMessageRetrievalParams","text":"ScheduledMessageRetrievalParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18BaseMessageHandlera","text":"BaseMessageHandler"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The instance of "},{"type":"codeVoice","code":"ScheduledMessageRetrievalParams"},{"type":"text","text":" that can has parameters"},{"type":"text","text":" "},{"type":"text","text":"related with scheduled message."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to be executed after the message is registered in the schedule."},{"type":"text","text":" "},{"type":"text","text":"This block has no return value and takes two argument, one is a user message is registered in the schedule and other is an"},{"type":"text","text":" "},{"type":"text","text":"error made when there is something wrong to message."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If a user leaves before sending scheduled messages, the scheduled messages will be removed."}]}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basemessage\/getscheduledmessage(params:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basemessage\/getscheduledmessage(params:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/getScheduledMessage(params:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get a message to be sent at the specified time."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getScheduledMessageWithParams:completionHandler:"}],"role":"symbol","title":"getScheduledMessage(params:completionHandler:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getScheduledMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledMessageRetrievalParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledMessageRetrievalParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18BaseMessageHandlera"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseMessage(cm)getScheduledMessageWithParams:completionHandler:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledMessageRetrievalParams":{"role":"symbol","title":"ScheduledMessageRetrievalParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledMessageRetrievalParams"}],"abstract":[{"type":"text","text":"An object that contains a set of options to retrieve scheduled messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledMessageRetrievalParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledMessageRetrievalParams"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledmessageretrievalparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessageHandler":{"role":"symbol","title":"BaseMessageHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessageHandler"}],"abstract":[{"type":"text","text":"Message handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessageHandler"}],"url":"\/documentation\/sendbirdchatsdk\/basemessagehandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/getScheduledMessage(params:completionHandler:)":{"role":"symbol","title":"getScheduledMessage(params:completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getScheduledMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledMessageRetrievalParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledMessageRetrievalParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18BaseMessageHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get a message to be sent at the specified time."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/getScheduledMessage(params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getScheduledMessageWithParams:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/getscheduledmessage(params:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage":{"role":"symbol","title":"BaseMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessage"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":" class represents the base message which is generated by a user or an admin."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":", the "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"AdminMessage"},{"type":"text","text":" are derived from this class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessage"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getScheduledMessageWithParams:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getScheduledMessageWithParams:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getScheduledMessageWithParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledMessageRetrievalParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledMessageRetrievalParams","text":"SBDScheduledMessageRetrievalParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDBaseMessage *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDBaseMessage#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledMessageRetrievalParams\/title","value":"SBDScheduledMessageRetrievalParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledMessageRetrievalParams\/fragments","value":[{"kind":"identifier","text":"SBDScheduledMessageRetrievalParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1getScheduledMessage(params:completionHandler:)\/title","value":"getScheduledMessageWithParams:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1getScheduledMessage(params:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getScheduledMessageWithParams:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/title","value":"SBDBaseMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}