{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(getThreadedMessagesWithTimestamp:params:completionHandler:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getThreadedMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadedMessageListParams","text":"ThreadedMessageListParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListHandler","preciseIdentifier":"s:15SendbirdChatSDK26ThreadedMessageListHandlera","text":"ThreadedMessageListHandler"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"timestamp","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Specifies the timestamp to be the reference point of the retrieval, in Unix milliseconds format."}]}]},{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Contains a set of parameters you can set regarding the messages in the results."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to be executed. The "},{"type":"codeVoice","code":"parentMessage"},{"type":"text","text":" retrieves"},{"type":"text","text":" "},{"type":"text","text":"the parent message of the thread. The "},{"type":"codeVoice","code":"threadedReplies"},{"type":"text","text":" retrieves the threaded replies in the thread."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"error"},{"type":"text","text":" indicates whether there is an error. If there is no error, the value is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.181"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basemessage\/getthreadedmessages(timestamp:params:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basemessage\/getthreadedmessages(timestamp:params:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/getThreadedMessages(timestamp:params:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Retrieves the threaded replies of the current message depending on the timestamp. If the current message doesn’t have replies, the result is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getThreadedMessagesWithTimestamp:params:completionHandler:"}],"role":"symbol","title":"getThreadedMessages(timestamp:params:completionHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getThreadedMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThreadedMessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadedMessageListParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThreadedMessageListHandler","preciseIdentifier":"s:15SendbirdChatSDK26ThreadedMessageListHandlera"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseMessage(im)getThreadedMessagesWithTimestamp:params:completionHandler:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams":{"role":"symbol","title":"ThreadedMessageListParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThreadedMessageListParams"}],"abstract":[{"type":"text","text":"An object contains set of options to retrieve threaded messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThreadedMessageListParams"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage":{"role":"symbol","title":"BaseMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessage"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":" class represents the base message which is generated by a user or an admin."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":", the "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"AdminMessage"},{"type":"text","text":" are derived from this class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessage"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListHandler":{"role":"symbol","title":"ThreadedMessageListHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThreadedMessageListHandler"}],"abstract":[{"type":"text","text":"Threaded handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThreadedMessageListHandler"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelisthandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/getThreadedMessages(timestamp:params:completionHandler:)":{"role":"symbol","title":"getThreadedMessages(timestamp:params:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getThreadedMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThreadedMessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadedMessageListParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThreadedMessageListHandler","preciseIdentifier":"s:15SendbirdChatSDK26ThreadedMessageListHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Retrieves the threaded replies of the current message depending on the timestamp. If the current message doesn’t have replies, the result is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/getThreadedMessages(timestamp:params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getThreadedMessagesWithTimestamp:params:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/getthreadedmessages(timestamp:params:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getThreadedMessagesWithTimestamp:params:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getThreadedMessagesWithTimestamp:params:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getThreadedMessagesWithTimestamp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"timestamp"},{"kind":"text","text":" "},{"kind":"identifier","text":"params:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadedMessageListParams","text":"SBDThreadedMessageListParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDBaseMessage *, NSArray<SBDBaseMessage *> *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDBaseMessage#*Q$objc(cs)NSArray#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams\/title","value":"SBDThreadedMessageListParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams\/fragments","value":[{"kind":"identifier","text":"SBDThreadedMessageListParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/title","value":"SBDBaseMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1getThreadedMessages(timestamp:params:completionHandler:)\/title","value":"getThreadedMessagesWithTimestamp:params:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1getThreadedMessages(timestamp:params:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getThreadedMessagesWithTimestamp:params:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}