{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessageCreateParams","text":"BaseMessageCreateParams"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Since 3.1.0"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basemessage\/messageparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basemessage\/messageparams"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/messageParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object that was used to resend this message. This property is valid when the sendingStatus is "},{"type":"codeVoice","code":"MessageSendingStatus.pending"},{"type":"text","text":" or "},{"type":"codeVoice","code":"MessageSendingStatus.failed"},{"type":"text","text":". When this message is trying to be resent, this property will be used as well. If the message object is "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":" class, then the "},{"type":"codeVoice","code":"messageParams"},{"type":"text","text":" has to be casted to "},{"type":"codeVoice","code":"UserMessageCreateParams"},{"type":"text","text":" class. If the message object is "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" class, then the "},{"type":"codeVoice","code":"messageParams"},{"type":"text","text":" has to be casted to "},{"type":"codeVoice","code":"FileMessageCreateParams"},{"type":"text","text":" class."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessageCreateParams"},{"kind":"text","text":"?"}],"title":"messageParams","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage(py)messageParams","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"messageParams"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage":{"role":"symbol","title":"BaseMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessage"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":" class represents the base message which is generated by a user or an admin."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":", the "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"AdminMessage"},{"type":"text","text":" are derived from this class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessage"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessageCreateParams":{"role":"symbol","title":"BaseMessageCreateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessageCreateParams"}],"abstract":[{"type":"text","text":"Represents the base class which has parameters to create a channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageCreateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessageCreateParams"}],"url":"\/documentation\/sendbirdchatsdk\/basemessagecreateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/messageParams":{"role":"symbol","title":"messageParams","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessageCreateParams"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"An object that was used to resend this message. This property is valid when the sendingStatus is "},{"type":"codeVoice","code":"MessageSendingStatus.pending"},{"type":"text","text":" or "},{"type":"codeVoice","code":"MessageSendingStatus.failed"},{"type":"text","text":". When this message is trying to be resent, this property will be used as well. If the message object is "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":" class, then the "},{"type":"codeVoice","code":"messageParams"},{"type":"text","text":" has to be casted to "},{"type":"codeVoice","code":"UserMessageCreateParams"},{"type":"text","text":" class. If the message object is "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" class, then the "},{"type":"codeVoice","code":"messageParams"},{"type":"text","text":" has to be casted to "},{"type":"codeVoice","code":"FileMessageCreateParams"},{"type":"text","text":" class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/messageParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageParams"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/messageparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"messageParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"messageParams"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessageCreateParams","text":"SBDBaseMessageCreateParams"},{"kind":"text","text":" *"},{"kind":"identifier","text":"messageParams"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/title","value":"SBDBaseMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessageCreateParams\/title","value":"SBDBaseMessageCreateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessageCreateParams\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessageCreateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1messageParams\/title","value":"messageParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1messageParams\/fragments","value":[{"kind":"identifier","text":"messageParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}