{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage","text":"BaseMessage"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When "},{"type":"codeVoice","code":"parentMessage"},{"type":"text","text":" is "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":" it only has 3 properties: "},{"type":"codeVoice","code":"message"},{"type":"text","text":", "},{"type":"codeVoice","code":"sender"},{"type":"text","text":" and "},{"type":"codeVoice","code":"createdAt"},{"type":"text","text":" "},{"type":"text","text":"When "},{"type":"codeVoice","code":"parentMessage"},{"type":"text","text":" is "},{"type":"codeVoice","code":"AdminMessage"},{"type":"text","text":" it only has 3 properties: "},{"type":"codeVoice","code":"message"},{"type":"text","text":", "},{"type":"codeVoice","code":"sender"},{"type":"text","text":" and "},{"type":"codeVoice","code":"createdAt"},{"type":"text","text":" "},{"type":"text","text":"When "},{"type":"codeVoice","code":"parentMessage"},{"type":"text","text":" is "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" it only has 6 properties: "},{"type":"codeVoice","code":"message"},{"type":"text","text":", "},{"type":"codeVoice","code":"sender"},{"type":"text","text":", "},{"type":"codeVoice","code":"createdAt"},{"type":"text","text":", "},{"type":"codeVoice","code":"name"},{"type":"text","text":", "},{"type":"codeVoice","code":"url"},{"type":"text","text":", "},{"type":"codeVoice","code":"type"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Since 3.0.236"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basemessage\/parentmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basemessage\/parentmessage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/parentMessage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Current message’s parent message object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"?"}],"title":"parentMessage","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage(py)parentMessage","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"parentMessage"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/parentMessage":{"role":"symbol","title":"parentMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Current message’s parent message object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/parentMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parentMessage"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/parentmessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage":{"role":"symbol","title":"BaseMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessage"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":" class represents the base message which is generated by a user or an admin."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":", the "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"AdminMessage"},{"type":"text","text":" are derived from this class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessage"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"parentMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"parentMessage"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage","text":"SBDBaseMessage"},{"kind":"text","text":" *"},{"kind":"identifier","text":"parentMessage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1parentMessage\/title","value":"parentMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1parentMessage\/fragments","value":[{"kind":"identifier","text":"parentMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/title","value":"SBDBaseMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}