{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"APNSVoIP"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/pushtokentype\/apnsvoip"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/pushtokentype\/apnsvoip"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/APNSVoIP","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Token used for VoIP from iOS device."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"APNSVoIP"}],"title":"PushTokenType.APNSVoIP","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDPushTokenType@SBDPushTokenTypeAPNSVoIP","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDPushTokenTypeAPNSVoIP"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType/APNSVoIP":{"role":"symbol","title":"PushTokenType.APNSVoIP","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"APNSVoIP"}],"abstract":[{"type":"text","text":"Token used for VoIP from iOS device."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/APNSVoIP","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushTokenTypeAPNSVoIP"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokentype\/apnsvoip"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType":{"role":"symbol","title":"PushTokenType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushTokenType"}],"abstract":[{"type":"text","text":"Constants of type for device push token."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushTokenType"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokentype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDPushTokenTypeAPNSVoIP"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenTypeAPNSVoIP"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDPushTokenTypeAPNSVoIP"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType~1APNSVoIP\/title","value":"SBDPushTokenTypeAPNSVoIP"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType~1APNSVoIP\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenTypeAPNSVoIP"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType\/title","value":"SBDPushTokenType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}