{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"APNS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/pushtokentype\/apns"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/pushtokentype\/apns"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/APNS","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Normal Token from iOS device."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"APNS"}],"title":"PushTokenType.APNS","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDPushTokenType@SBDPushTokenTypeAPNS","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDPushTokenTypeAPNS"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType/APNS":{"role":"symbol","title":"PushTokenType.APNS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"APNS"}],"abstract":[{"type":"text","text":"Normal Token from iOS device."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/APNS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushTokenTypeAPNS"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokentype\/apns"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType":{"role":"symbol","title":"PushTokenType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushTokenType"}],"abstract":[{"type":"text","text":"Constants of type for device push token."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushTokenType"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokentype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDPushTokenTypeAPNS"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenTypeAPNS"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDPushTokenTypeAPNS"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType~1APNS\/title","value":"SBDPushTokenTypeAPNS"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType~1APNS\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenTypeAPNS"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType\/title","value":"SBDPushTokenType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}