{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCM"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/pushtokentype\/gcm"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/pushtokentype\/gcm"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/GCM","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Token from Android device."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCM"}],"title":"PushTokenType.GCM","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDPushTokenType@SBDPushTokenTypeGCM","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDPushTokenTypeGCM"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType/GCM":{"role":"symbol","title":"PushTokenType.GCM","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCM"}],"abstract":[{"type":"text","text":"Token from Android device."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/GCM","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushTokenTypeGCM"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokentype\/gcm"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType":{"role":"symbol","title":"PushTokenType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushTokenType"}],"abstract":[{"type":"text","text":"Constants of type for device push token."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushTokenType"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokentype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDPushTokenTypeGCM"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenTypeGCM"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDPushTokenTypeGCM"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType~1GCM\/title","value":"SBDPushTokenTypeGCM"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType~1GCM\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenTypeGCM"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType\/title","value":"SBDPushTokenType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}