{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelUnreadMentionCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When you requested with "},{"type":"codeVoice","code":"UnreadItemKey.groupChannelUnreadMentionCount"},{"type":"text","text":", then you"},{"type":"text","text":" "},{"type":"text","text":"can get unsigned integer count. If you DID NOT REQUEST "},{"type":"codeVoice","code":"UnreadItemKey.groupChannelUnreadMentionCount"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"this property will be "},{"type":"codeVoice","code":"NSNotFound"},{"type":"text","text":"."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.103"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemcount\/groupchannelunreadmentioncount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemcount\/groupchannelunreadmentioncount"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/groupChannelUnreadMentionCount","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The count of unread mention in all of group channels."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelUnreadMentionCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"groupChannelUnreadMentionCount","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemCount(py)groupChannelUnreadMentionCount","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"groupChannelUnreadMentionCount"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount":{"role":"symbol","title":"UnreadItemCount","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadItemCount"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UnreadItemCount"},{"type":"text","text":" class represents counts of messages. The instance of this class is returned"},{"type":"text","text":" "},{"type":"text","text":"from completion handler in "},{"type":"codeVoice","code":"getUnreadItemCountWithKey:completionHandler:]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnreadItemCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/groupChannelUnreadMentionCount":{"role":"symbol","title":"groupChannelUnreadMentionCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelUnreadMentionCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The count of unread mention in all of group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/groupChannelUnreadMentionCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelUnreadMentionCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/groupchannelunreadmentioncount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"groupChannelUnreadMentionCount"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"groupChannelUnreadMentionCount"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"identifier","text":"groupChannelUnreadMentionCount"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount\/title","value":"SBDUnreadItemCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount\/fragments","value":[{"kind":"identifier","text":"SBDUnreadItemCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1groupChannelUnreadMentionCount\/title","value":"groupChannelUnreadMentionCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1groupChannelUnreadMentionCount\/fragments","value":[{"kind":"identifier","text":"groupChannelUnreadMentionCount"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}