{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"has"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey","text":"UnreadItemKey"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" if counts for key is present in the instance, otherwise "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}]}]},{"kind":"parameters","parameters":[{"name":"key","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An key to look for a count in the instance."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.101"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemcount\/has(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemcount\/has(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/has(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether a count of a given key is present, not NSNotFound."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"has"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"has(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemCount(im)has:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"has:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/has(_:)":{"role":"symbol","title":"has(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"has"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether a count of a given key is present, not NSNotFound."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/has(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"has:"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/has(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount":{"role":"symbol","title":"UnreadItemCount","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadItemCount"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UnreadItemCount"},{"type":"text","text":" class represents counts of messages. The instance of this class is returned"},{"type":"text","text":" "},{"type":"text","text":"from completion handler in "},{"type":"codeVoice","code":"getUnreadItemCountWithKey:completionHandler:]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnreadItemCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey":{"role":"symbol","title":"UnreadItemKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadItemKey"}],"abstract":[{"type":"text","text":"The bitmask keys of count about unread messages or invitation."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnreadItemKey"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"has:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"has:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"has:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey","text":"SBDUnreadItemKey"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"key"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1has(_:)\/title","value":"has:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1has(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"has:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount\/title","value":"SBDUnreadItemCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount\/fragments","value":[{"kind":"identifier","text":"SBDUnreadItemCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey\/title","value":"SBDUnreadItemKey"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey\/fragments","value":[{"kind":"identifier","text":"SBDUnreadItemKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}