{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initWithDictionary"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"json"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> `Self`"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemcount\/initwithdictionary(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemcount\/initwithdictionary(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/initWithDictionary(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialize with json dictionary"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}],"role":"symbol","title":"initWithDictionary(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initWithDictionary"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> `Self`"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDUnreadItemCount(im)initWithDictionary:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/Mappable-Implementations"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/Mappable-Implementations":{"role":"collectionGroup","title":"Mappable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/Mappable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/mappable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount":{"role":"symbol","title":"UnreadItemCount","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadItemCount"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UnreadItemCount"},{"type":"text","text":" class represents counts of messages. The instance of this class is returned"},{"type":"text","text":" "},{"type":"text","text":"from completion handler in "},{"type":"codeVoice","code":"getUnreadItemCountWithKey:completionHandler:]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnreadItemCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/initWithDictionary(_:)":{"role":"symbol","title":"initWithDictionary(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initWithDictionary"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> `Self`"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Initialize with json dictionary"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/initWithDictionary(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/initwithdictionary(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDictionary:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDictionary:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDictionary:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount\/title","value":"SBDUnreadItemCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount\/fragments","value":[{"kind":"identifier","text":"SBDUnreadItemCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1initWithDictionary(_:)\/title","value":"initWithDictionary:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1initWithDictionary(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDictionary:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}