{"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemcount\/mappable-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemcount\/mappable-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/Mappable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/initWithDictionary(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"SendbirdChatSDK"}],"role":"collectionGroup","title":"Mappable Implementations"},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/initWithDictionary(_:)":{"role":"symbol","title":"initWithDictionary(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initWithDictionary"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> `Self`"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Initialize with json dictionary"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/initWithDictionary(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/initwithdictionary(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount":{"role":"symbol","title":"UnreadItemCount","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadItemCount"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UnreadItemCount"},{"type":"text","text":" class represents counts of messages. The instance of this class is returned"},{"type":"text","text":" "},{"type":"text","text":"from completion handler in "},{"type":"codeVoice","code":"getUnreadItemCountWithKey:completionHandler:]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnreadItemCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/initWithDictionary(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1initWithDictionary(_:)\/title","value":"initWithDictionary:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1initWithDictionary(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDictionary:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount\/title","value":"SBDUnreadItemCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount\/fragments","value":[{"kind":"identifier","text":"SBDUnreadItemCount"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}