{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *"},{"kind":"identifier","text":"preferredLanguages"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/userupdateparams\/preferredlanguages"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserUpdateParams\/preferredLanguages","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Preferred langauges for this user"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"preferredLanguages"}],"title":"preferredLanguages","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDUserUpdateParams(py)preferredLanguages","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"preferredLanguages"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserUpdateParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserUpdateParams/preferredLanguages":{"role":"symbol","title":"preferredLanguages","fragments":[{"kind":"identifier","text":"preferredLanguages"}],"abstract":[{"type":"text","text":"Preferred langauges for this user"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserUpdateParams\/preferredLanguages","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/userupdateparams\/preferredlanguages"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserUpdateParams":{"role":"symbol","title":"UserUpdateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserUpdateParams"}],"abstract":[{"type":"text","text":"An object to update user information"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserUpdateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserUpdateParams"}],"url":"\/documentation\/sendbirdchatsdk\/userupdateparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserUpdateParams\/title","value":"SBDUserUpdateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserUpdateParams\/fragments","value":[{"kind":"identifier","text":"SBDUserUpdateParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}