{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/pushtokenregistrationstatus\/pending"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/pushtokenregistrationstatus\/pending"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/pending","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Registration is pending."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"title":"PushTokenRegistrationStatus.pending","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDPushTokenRegistrationStatus@SBDPushTokenRegistrationStatusPending","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDPushTokenRegistrationStatusPending"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenRegistrationStatus/pending":{"role":"symbol","title":"PushTokenRegistrationStatus.pending","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"abstract":[{"type":"text","text":"Registration is pending."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/pending","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushTokenRegistrationStatusPending"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokenregistrationstatus\/pending"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenRegistrationStatus":{"role":"symbol","title":"PushTokenRegistrationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushTokenRegistrationStatus"}],"abstract":[{"type":"text","text":"Push token registration statuses"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushTokenRegistrationStatus"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokenregistrationstatus"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDPushTokenRegistrationStatusPending"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenRegistrationStatusPending"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDPushTokenRegistrationStatusPending"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenRegistrationStatus~1pending\/title","value":"SBDPushTokenRegistrationStatusPending"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenRegistrationStatus~1pending\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenRegistrationStatusPending"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenRegistrationStatus\/title","value":"SBDPushTokenRegistrationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenRegistrationStatus\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenRegistrationStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}