{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"score"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagesearchqueryorder\/score"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagesearchqueryorder\/score"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/score","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Score type Returns the result as by their matching score."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"score"}],"title":"MessageSearchQueryOrder.score","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDMessageSearchQueryOrder@SBDMessageSearchQueryOrderScore","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDMessageSearchQueryOrderScore"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQueryOrder/score":{"role":"symbol","title":"MessageSearchQueryOrder.score","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"score"}],"abstract":[{"type":"text","text":"Score type Returns the result as by their matching score."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/score","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageSearchQueryOrderScore"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchqueryorder\/score"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQueryOrder":{"role":"symbol","title":"MessageSearchQueryOrder","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSearchQueryOrder"}],"abstract":[{"type":"text","text":"The order type for "},{"type":"codeVoice","code":"MessageSearchQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageSearchQueryOrder"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchqueryorder"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageSearchQueryOrderScore"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageSearchQueryOrderScore"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDMessageSearchQueryOrderScore"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryOrder~1score\/title","value":"SBDMessageSearchQueryOrderScore"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryOrder~1score\/fragments","value":[{"kind":"identifier","text":"SBDMessageSearchQueryOrderScore"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryOrder\/title","value":"SBDMessageSearchQueryOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryOrder\/fragments","value":[{"kind":"identifier","text":"SBDMessageSearchQueryOrder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}