{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeStamp"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagesearchqueryorder\/timestamp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagesearchqueryorder\/timestamp"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/timeStamp","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Timestamp type Returns the result as by "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":"’s timestamp."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeStamp"}],"title":"MessageSearchQueryOrder.timeStamp","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDMessageSearchQueryOrder@SBDMessageSearchQueryOrderTimeStamp","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDMessageSearchQueryOrderTimeStamp"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQueryOrder/timeStamp":{"role":"symbol","title":"MessageSearchQueryOrder.timeStamp","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeStamp"}],"abstract":[{"type":"text","text":"Timestamp type Returns the result as by "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":"’s timestamp."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/timeStamp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageSearchQueryOrderTimeStamp"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchqueryorder\/timestamp"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQueryOrder":{"role":"symbol","title":"MessageSearchQueryOrder","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSearchQueryOrder"}],"abstract":[{"type":"text","text":"The order type for "},{"type":"codeVoice","code":"MessageSearchQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageSearchQueryOrder"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchqueryorder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageSearchQueryOrderTimeStamp"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageSearchQueryOrderTimeStamp"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDMessageSearchQueryOrderTimeStamp"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryOrder~1timeStamp\/title","value":"SBDMessageSearchQueryOrderTimeStamp"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryOrder~1timeStamp\/fragments","value":[{"kind":"identifier","text":"SBDMessageSearchQueryOrderTimeStamp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryOrder\/title","value":"SBDMessageSearchQueryOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryOrder\/fragments","value":[{"kind":"identifier","text":"SBDMessageSearchQueryOrder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}