{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decrease"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/decrease"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/decrease"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/decrease","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decrease"}],"title":"ChannelMetaCountersUpdateMode.decrease","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDChannelMetaCountersUpdateMode@SBDChannelMetaCountersUpdateModeDecrease","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeDecrease"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelMetaCountersUpdateMode/decrease":{"role":"symbol","title":"ChannelMetaCountersUpdateMode.decrease","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decrease"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/decrease","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeDecrease"}],"url":"\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/decrease"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelMetaCountersUpdateMode":{"role":"symbol","title":"ChannelMetaCountersUpdateMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelMetaCountersUpdateMode"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelMetaCountersUpdateMode"}],"url":"\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDChannelMetaCountersUpdateModeDecrease"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeDecrease"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeDecrease"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode~1decrease\/title","value":"SBDChannelMetaCountersUpdateModeDecrease"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode~1decrease\/fragments","value":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeDecrease"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode\/title","value":"SBDChannelMetaCountersUpdateMode"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode\/fragments","value":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}