{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"increase"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/increase"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/increase"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/increase","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"increase"}],"title":"ChannelMetaCountersUpdateMode.increase","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDChannelMetaCountersUpdateMode@SBDChannelMetaCountersUpdateModeIncrease","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeIncrease"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelMetaCountersUpdateMode":{"role":"symbol","title":"ChannelMetaCountersUpdateMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelMetaCountersUpdateMode"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelMetaCountersUpdateMode"}],"url":"\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelMetaCountersUpdateMode/increase":{"role":"symbol","title":"ChannelMetaCountersUpdateMode.increase","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"increase"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/increase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeIncrease"}],"url":"\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/increase"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDChannelMetaCountersUpdateModeIncrease"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeIncrease"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeIncrease"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode\/title","value":"SBDChannelMetaCountersUpdateMode"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode\/fragments","value":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode~1increase\/title","value":"SBDChannelMetaCountersUpdateModeIncrease"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode~1increase\/fragments","value":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeIncrease"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}