{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/set"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/set"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/set","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"}],"title":"ChannelMetaCountersUpdateMode.set","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDChannelMetaCountersUpdateMode@SBDChannelMetaCountersUpdateModeSet","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeSet"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelMetaCountersUpdateMode/set":{"role":"symbol","title":"ChannelMetaCountersUpdateMode.set","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/set","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeSet"}],"url":"\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/set"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelMetaCountersUpdateMode":{"role":"symbol","title":"ChannelMetaCountersUpdateMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelMetaCountersUpdateMode"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelMetaCountersUpdateMode"}],"url":"\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDChannelMetaCountersUpdateModeSet"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeSet"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeSet"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode~1set\/title","value":"SBDChannelMetaCountersUpdateModeSet"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode~1set\/fragments","value":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeSet"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode\/title","value":"SBDChannelMetaCountersUpdateMode"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode\/fragments","value":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}