{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption\/default"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption\/default"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/default","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Follow the push trigger of current user. See "},{"type":"codeVoice","code":"PushTriggerOption"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"title":"GroupChannelPushTriggerOption.default","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPushTriggerOption@SBDGroupChannelPushTriggerOptionDefault","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionDefault"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelPushTriggerOption/default":{"role":"symbol","title":"GroupChannelPushTriggerOption.default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"abstract":[{"type":"text","text":"Follow the push trigger of current user. See "},{"type":"codeVoice","code":"PushTriggerOption"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionDefault"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption\/default"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelPushTriggerOption":{"role":"symbol","title":"GroupChannelPushTriggerOption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelPushTriggerOption"}],"abstract":[{"type":"text","text":"The options to choose which push notification for the current user to receive in a group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelPushTriggerOption"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelPushTriggerOptionDefault"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionDefault"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionDefault"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption~1default\/title","value":"SBDGroupChannelPushTriggerOptionDefault"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption~1default\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionDefault"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption\/title","value":"SBDGroupChannelPushTriggerOption"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}