{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption\/off"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption\/off"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/off","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Do NOT receive any remote push notification."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"title":"GroupChannelPushTriggerOption.off","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPushTriggerOption@SBDGroupChannelPushTriggerOptionOff","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionOff"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelPushTriggerOption":{"role":"symbol","title":"GroupChannelPushTriggerOption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelPushTriggerOption"}],"abstract":[{"type":"text","text":"The options to choose which push notification for the current user to receive in a group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelPushTriggerOption"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelPushTriggerOption/off":{"role":"symbol","title":"GroupChannelPushTriggerOption.off","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"abstract":[{"type":"text","text":"Do NOT receive any remote push notification."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/off","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionOff"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption\/off"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelPushTriggerOptionOff"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionOff"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionOff"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption\/title","value":"SBDGroupChannelPushTriggerOption"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption~1off\/title","value":"SBDGroupChannelPushTriggerOptionOff"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption~1off\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionOff"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}