{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnails"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Thumbnail","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnail","text":"Thumbnail"},{"kind":"text","text":"]? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/filemessage\/thumbnails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/filemessage\/thumbnails"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/thumbnails","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Image thumbnails."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnails"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Thumbnail","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnail"},{"kind":"text","text":"]?"}],"title":"thumbnails","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage(py)thumbnails","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"thumbnails"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage":{"role":"symbol","title":"FileMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessage"}],"abstract":[{"type":"text","text":"Represents a mesage object that contains a file. Derived from "},{"type":"codeVoice","code":"BaseMessage"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessage"}],"url":"\/documentation\/sendbirdchatsdk\/filemessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage/thumbnails":{"role":"symbol","title":"thumbnails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnails"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Thumbnail","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnail"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Image thumbnails."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/thumbnails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnails"}],"url":"\/documentation\/sendbirdchatsdk\/filemessage\/thumbnails"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Thumbnail":{"role":"symbol","title":"Thumbnail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Thumbnail"}],"abstract":[{"type":"text","text":"Represents a thumbnail information"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Thumbnail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Thumbnail"}],"url":"\/documentation\/sendbirdchatsdk\/thumbnail"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"thumbnails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"thumbnails"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBDThumbnail *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *"},{"kind":"identifier","text":"thumbnails"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage\/title","value":"SBDFileMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage\/fragments","value":[{"kind":"identifier","text":"SBDFileMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1thumbnails\/title","value":"thumbnails"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1thumbnails\/fragments","value":[{"kind":"identifier","text":"thumbnails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Thumbnail\/title","value":"SBDThumbnail"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Thumbnail\/fragments","value":[{"kind":"identifier","text":"SBDThumbnail"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}