{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"superChannelFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelSuperChannelFilter","text":"GroupChannelSuperChannelFilter"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchanneltotalunreadchannelcountparams\/superchannelfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchanneltotalunreadchannelcountparams\/superchannelfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelTotalUnreadChannelCountParams\/superChannelFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The enumerator filter of super channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"superChannelFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelSuperChannelFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelSuperChannelFilter"}],"title":"superChannelFilter","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelTotalUnreadChannelCountParams(py)superChannelFilter","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"superChannelFilter"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelTotalUnreadChannelCountParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelTotalUnreadChannelCountParams/superChannelFilter":{"role":"symbol","title":"superChannelFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"superChannelFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelSuperChannelFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelSuperChannelFilter"}],"abstract":[{"type":"text","text":"The enumerator filter of super channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelTotalUnreadChannelCountParams\/superChannelFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"superChannelFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchanneltotalunreadchannelcountparams\/superchannelfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelSuperChannelFilter":{"role":"symbol","title":"GroupChannelSuperChannelFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelSuperChannelFilter"}],"abstract":[{"type":"text","text":"Channel filter for super mode in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelSuperChannelFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelTotalUnreadChannelCountParams":{"role":"symbol","title":"GroupChannelTotalUnreadChannelCountParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelTotalUnreadChannelCountParams"}],"abstract":[{"type":"text","text":"An object contains set of options to retrieve total unread channel count"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelTotalUnreadChannelCountParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelTotalUnreadChannelCountParams"}],"url":"\/documentation\/sendbirdchatsdk\/groupchanneltotalunreadchannelcountparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"superChannelFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"superChannelFilter"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelSuperChannelFilter","text":"SBDGroupChannelSuperChannelFilter"},{"kind":"identifier","text":"superChannelFilter"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelTotalUnreadChannelCountParams~1superChannelFilter\/title","value":"superChannelFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelTotalUnreadChannelCountParams~1superChannelFilter\/fragments","value":[{"kind":"identifier","text":"superChannelFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter\/title","value":"SBDGroupChannelSuperChannelFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelTotalUnreadChannelCountParams\/title","value":"SBDGroupChannelTotalUnreadChannelCountParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelTotalUnreadChannelCountParams\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelTotalUnreadChannelCountParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}