{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"volume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.221"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/applecriticalalertoptions\/volume"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/applecriticalalertoptions\/volume"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppleCriticalAlertOptions\/volume","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The volume for the critical alert’s sound."},{"type":"text","text":" "},{"type":"text","text":"Set this to a value between 0.0 (silent) and 1.0 (full volume)."},{"type":"text","text":" "},{"type":"text","text":"The default value is "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"volume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"title":"volume","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDAppleCriticalAlertOptions(py)volume","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"volume"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppleCriticalAlertOptions"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppleCriticalAlertOptions/volume":{"role":"symbol","title":"volume","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"volume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"The volume for the critical alert’s sound."},{"type":"text","text":" "},{"type":"text","text":"Set this to a value between 0.0 (silent) and 1.0 (full volume)."},{"type":"text","text":" "},{"type":"text","text":"The default value is "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppleCriticalAlertOptions\/volume","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"volume"}],"url":"\/documentation\/sendbirdchatsdk\/applecriticalalertoptions\/volume"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppleCriticalAlertOptions":{"role":"symbol","title":"AppleCriticalAlertOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleCriticalAlertOptions"}],"abstract":[{"type":"text","text":"Represents the options for the Apple Critical Alert."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppleCriticalAlertOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppleCriticalAlertOptions"}],"url":"\/documentation\/sendbirdchatsdk\/applecriticalalertoptions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"volume"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"volume"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"identifier","text":"volume"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppleCriticalAlertOptions~1volume\/title","value":"volume"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppleCriticalAlertOptions~1volume\/fragments","value":[{"kind":"identifier","text":"volume"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppleCriticalAlertOptions\/title","value":"SBDAppleCriticalAlertOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppleCriticalAlertOptions\/fragments","value":[{"kind":"identifier","text":"SBDAppleCriticalAlertOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}