{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelmutedmemberfilter\/all"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelmutedmemberfilter\/all"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter\/all","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Without filter."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"title":"GroupChannelMutedMemberFilter.all","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDGroupChannelMutedMemberFilter@SBDGroupChannelMutedMemberFilterAll","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilterAll"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelMutedMemberFilter/all":{"role":"symbol","title":"GroupChannelMutedMemberFilter.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[{"type":"text","text":"Without filter."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilterAll"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelmutedmemberfilter\/all"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelMutedMemberFilter":{"role":"symbol","title":"GroupChannelMutedMemberFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelMutedMemberFilter"}],"abstract":[{"type":"text","text":"Filter operators in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelMutedMemberFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelmutedmemberfilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelMutedMemberFilterAll"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilterAll"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilterAll"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter~1all\/title","value":"SBDGroupChannelMutedMemberFilterAll"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter~1all\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilterAll"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter\/title","value":"SBDGroupChannelMutedMemberFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}