{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"muted"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelmutedmemberfilter\/muted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelmutedmemberfilter\/muted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter\/muted","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Filter muted members."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"muted"}],"title":"GroupChannelMutedMemberFilter.muted","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDGroupChannelMutedMemberFilter@SBDGroupChannelMutedMemberFilterMuted","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilterMuted"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelMutedMemberFilter":{"role":"symbol","title":"GroupChannelMutedMemberFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelMutedMemberFilter"}],"abstract":[{"type":"text","text":"Filter operators in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelMutedMemberFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelmutedmemberfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelMutedMemberFilter/muted":{"role":"symbol","title":"GroupChannelMutedMemberFilter.muted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"muted"}],"abstract":[{"type":"text","text":"Filter muted members."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter\/muted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilterMuted"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelmutedmemberfilter\/muted"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelMutedMemberFilterMuted"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilterMuted"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilterMuted"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter\/title","value":"SBDGroupChannelMutedMemberFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter~1muted\/title","value":"SBDGroupChannelMutedMemberFilterMuted"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter~1muted\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilterMuted"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}