{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmuted"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelmutedmemberfilter\/unmuted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelmutedmemberfilter\/unmuted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter\/unmuted","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Filter members not muted."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmuted"}],"title":"GroupChannelMutedMemberFilter.unmuted","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDGroupChannelMutedMemberFilter@SBDGroupChannelMutedMemberFilterUnmuted","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilterUnmuted"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelMutedMemberFilter/unmuted":{"role":"symbol","title":"GroupChannelMutedMemberFilter.unmuted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmuted"}],"abstract":[{"type":"text","text":"Filter members not muted."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter\/unmuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilterUnmuted"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelmutedmemberfilter\/unmuted"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelMutedMemberFilter":{"role":"symbol","title":"GroupChannelMutedMemberFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelMutedMemberFilter"}],"abstract":[{"type":"text","text":"Filter operators in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelMutedMemberFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelmutedmemberfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelMutedMemberFilterUnmuted"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilterUnmuted"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilterUnmuted"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter~1unmuted\/title","value":"SBDGroupChannelMutedMemberFilterUnmuted"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter~1unmuted\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilterUnmuted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter\/title","value":"SBDGroupChannelMutedMemberFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}