{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(createWithGroupChannelListQuery:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery","text":"GroupChannelListQuery"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelChangeLogsParams","text":"GroupChannelChangeLogsParams"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A created instance of "},{"type":"codeVoice","code":"GroupChannelChangeLogsParams"}]}]},{"kind":"parameters","parameters":[{"name":"query","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"group channel list query"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.185"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams\/create(query:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams\/create(query:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/create(query:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"GroupChannelChangeLogsParams"},{"type":"text","text":" from a given GroupChannelListQuery instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GroupChannelChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelChangeLogsParams"}],"title":"create(query:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelChangeLogsParams(cm)createWithGroupChannelListQuery:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"createWithGroupChannelListQuery:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelChangeLogsParams/create(query:)":{"role":"symbol","title":"create(query:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GroupChannelChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelChangeLogsParams"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"GroupChannelChangeLogsParams"},{"type":"text","text":" from a given GroupChannelListQuery instance."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/create(query:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithGroupChannelListQuery:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams\/create(query:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelChangeLogsParams":{"role":"symbol","title":"GroupChannelChangeLogsParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelChangeLogsParams"}],"abstract":[{"type":"text","text":"An object that represents the parameters for the The method returns channels according to the properties in this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelChangeLogsParams"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuery":{"role":"symbol","title":"GroupChannelListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannelListQuery"},{"type":"text","text":" class is a query class for getting the list of group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquery"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithGroupChannelListQuery:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithGroupChannelListQuery:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelChangeLogsParams","text":"SBDGroupChannelChangeLogsParams"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createWithGroupChannelListQuery:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery","text":"SBDGroupChannelListQuery"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"query"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams~1create(query:)\/title","value":"createWithGroupChannelListQuery:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams~1create(query:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithGroupChannelListQuery:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams\/title","value":"SBDGroupChannelChangeLogsParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelChangeLogsParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery\/title","value":"SBDGroupChannelListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}