{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/init","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelChangeLogsParams(im)init","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelChangeLogsParams":{"role":"symbol","title":"GroupChannelChangeLogsParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelChangeLogsParams"}],"abstract":[{"type":"text","text":"An object that represents the parameters for the The method returns channels according to the properties in this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelChangeLogsParams"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelChangeLogsParams/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams\/init"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams\/title","value":"SBDGroupChannelChangeLogsParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelChangeLogsParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}