{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.90"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basemessagecreateparams\/customtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basemessagecreateparams\/customtype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageCreateParams\/customType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Customize message’s type to filter. The default value is nil."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"customType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessageCreateParams(py)customType","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"customType"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageCreateParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessageCreateParams":{"role":"symbol","title":"BaseMessageCreateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessageCreateParams"}],"abstract":[{"type":"text","text":"Represents the base class which has parameters to create a channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageCreateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessageCreateParams"}],"url":"\/documentation\/sendbirdchatsdk\/basemessagecreateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessageCreateParams/customType":{"role":"symbol","title":"customType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Customize message’s type to filter. The default value is nil."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageCreateParams\/customType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customType"}],"url":"\/documentation\/sendbirdchatsdk\/basemessagecreateparams\/customtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"customType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"customType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *"},{"kind":"identifier","text":"customType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessageCreateParams\/title","value":"SBDBaseMessageCreateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessageCreateParams\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessageCreateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessageCreateParams~1customType\/title","value":"customType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessageCreateParams~1customType\/fragments","value":[{"kind":"identifier","text":"customType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}