{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionedUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser","text":"User"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basemessagecreateparams\/mentionedusers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basemessagecreateparams\/mentionedusers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageCreateParams\/mentionedUsers","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Mention to specific users with user objects."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionedUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":"]?"}],"title":"mentionedUsers","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessageCreateParams(py)mentionedUsers","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"mentionedUsers"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageCreateParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User":{"role":"symbol","title":"User","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"User"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"User"},{"type":"text","text":" class represents a user. The user is identified by the "},{"type":"codeVoice","code":"userID"},{"type":"text","text":", so the "},{"type":"codeVoice","code":"userID"},{"type":"text","text":" has"},{"type":"text","text":" "},{"type":"text","text":"to be unique. The "},{"type":"codeVoice","code":"userID"},{"type":"text","text":", "},{"type":"codeVoice","code":"nickname"},{"type":"text","text":" and "},{"type":"codeVoice","code":"profileURL"},{"type":"text","text":" are valid in every "},{"type":"codeVoice","code":"User"},{"type":"text","text":" "},{"type":"text","text":"instance, however the "},{"type":"codeVoice","code":"connectionStatus"},{"type":"text","text":" and "},{"type":"codeVoice","code":"lastSeenAt"},{"type":"text","text":" is valid in "},{"type":"codeVoice","code":"User"},{"type":"text","text":" instance"},{"type":"text","text":" "},{"type":"text","text":"from "},{"type":"codeVoice","code":"UserListQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"User"}],"url":"\/documentation\/sendbirdchatsdk\/user"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessageCreateParams/mentionedUsers":{"role":"symbol","title":"mentionedUsers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionedUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Mention to specific users with user objects."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageCreateParams\/mentionedUsers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mentionedUsers"}],"url":"\/documentation\/sendbirdchatsdk\/basemessagecreateparams\/mentionedusers"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessageCreateParams":{"role":"symbol","title":"BaseMessageCreateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessageCreateParams"}],"abstract":[{"type":"text","text":"Represents the base class which has parameters to create a channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageCreateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessageCreateParams"}],"url":"\/documentation\/sendbirdchatsdk\/basemessagecreateparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mentionedUsers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mentionedUsers"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBDUser *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *"},{"kind":"identifier","text":"mentionedUsers"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User\/title","value":"SBDUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User\/fragments","value":[{"kind":"identifier","text":"SBDUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessageCreateParams~1mentionedUsers\/title","value":"mentionedUsers"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessageCreateParams~1mentionedUsers\/fragments","value":[{"kind":"identifier","text":"mentionedUsers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessageCreateParams\/title","value":"SBDBaseMessageCreateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessageCreateParams\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessageCreateParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}