{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/totalscheduledmessagecountparams\/channelurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/totalscheduledmessagecountparams\/channelurl"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/channelURL","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Channel URL which has this message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"channelURL","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDTotalScheduledMessageCountParams(py)channelURL","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"channelURL"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/TotalScheduledMessageCountParams/channelURL":{"role":"symbol","title":"channelURL","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Channel URL which has this message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/channelURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelURL"}],"url":"\/documentation\/sendbirdchatsdk\/totalscheduledmessagecountparams\/channelurl"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/TotalScheduledMessageCountParams":{"role":"symbol","title":"TotalScheduledMessageCountParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TotalScheduledMessageCountParams"}],"abstract":[{"type":"text","text":"An object that contains a set of options to get scheduled messages count."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TotalScheduledMessageCountParams"}],"url":"\/documentation\/sendbirdchatsdk\/totalscheduledmessagecountparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"channelURL"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"channelURL"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *"},{"kind":"identifier","text":"channelURL"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams~1channelURL\/title","value":"channelURL"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams~1channelURL\/fragments","value":[{"kind":"identifier","text":"channelURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams\/title","value":"SBDTotalScheduledMessageCountParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams\/fragments","value":[{"kind":"identifier","text":"SBDTotalScheduledMessageCountParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}