{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduledStatusOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions","text":"ScheduledStatusOptions"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/totalscheduledmessagecountparams\/scheduledstatusoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/totalscheduledmessagecountparams\/scheduledstatusoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/scheduledStatusOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Restricts the search scope only to retrieve the messages with the specified message status. If not specified, all messages are retrieved."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduledStatusOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledStatusOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions"}],"title":"scheduledStatusOptions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDTotalScheduledMessageCountParams(py)scheduledStatusOptions","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"scheduledStatusOptions"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/TotalScheduledMessageCountParams/scheduledStatusOptions":{"role":"symbol","title":"scheduledStatusOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduledStatusOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledStatusOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions"}],"abstract":[{"type":"text","text":"Restricts the search scope only to retrieve the messages with the specified message status. If not specified, all messages are retrieved."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/scheduledStatusOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scheduledStatusOptions"}],"url":"\/documentation\/sendbirdchatsdk\/totalscheduledmessagecountparams\/scheduledstatusoptions"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/TotalScheduledMessageCountParams":{"role":"symbol","title":"TotalScheduledMessageCountParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TotalScheduledMessageCountParams"}],"abstract":[{"type":"text","text":"An object that contains a set of options to get scheduled messages count."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TotalScheduledMessageCountParams"}],"url":"\/documentation\/sendbirdchatsdk\/totalscheduledmessagecountparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions":{"role":"symbol","title":"ScheduledStatusOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledStatusOptions"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledStatusOptions"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"scheduledStatusOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"scheduledStatusOptions"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions","text":"SBDScheduledStatusOptions"},{"kind":"text","text":" *"},{"kind":"identifier","text":"scheduledStatusOptions"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams~1scheduledStatusOptions\/title","value":"scheduledStatusOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams~1scheduledStatusOptions\/fragments","value":[{"kind":"identifier","text":"scheduledStatusOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams\/title","value":"SBDTotalScheduledMessageCountParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams\/fragments","value":[{"kind":"identifier","text":"SBDTotalScheduledMessageCountParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions\/title","value":"SBDScheduledStatusOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions\/fragments","value":[{"kind":"identifier","text":"SBDScheduledStatusOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}