{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"details"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollDetails","text":"PollDetails"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"this property will be nil if "},{"type":"codeVoice","code":"includePollDetails"},{"type":"text","text":" option is NO when fetching message list"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/poll\/details"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/poll\/details"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/details","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Detail information of this poll"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"details"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollDetails","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollDetails"},{"kind":"text","text":"?"}],"title":"details","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDPoll(py)details","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"details"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll":{"role":"symbol","title":"Poll","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Poll"}],"abstract":[{"type":"text","text":"Represents a poll that users can vote"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Poll"}],"url":"\/documentation\/sendbirdchatsdk\/poll"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/details":{"role":"symbol","title":"details","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"details"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollDetails","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollDetails"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Detail information of this poll"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/details","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"details"}],"url":"\/documentation\/sendbirdchatsdk\/poll\/details"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails":{"role":"symbol","title":"PollDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollDetails"}],"abstract":[{"type":"text","text":"Represents a poll details information"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PollDetails"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"details"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"details"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollDetails","text":"SBDPollDetails"},{"kind":"text","text":" *"},{"kind":"identifier","text":"details"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll\/title","value":"SBDPoll"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll\/fragments","value":[{"kind":"identifier","text":"SBDPoll"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1details\/title","value":"details"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1details\/fragments","value":[{"kind":"identifier","text":"details"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails\/title","value":"SBDPollDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails\/fragments","value":[{"kind":"identifier","text":"SBDPollDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}