{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollUpdateParams","text":"PollUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollHandler","preciseIdentifier":"s:15SendbirdChatSDK11PollHandlera","text":"PollHandler"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"PollUpdateParams"},{"type":"text","text":" instance."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Completion block."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/poll\/update(params:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/poll\/update(params:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/update(params:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Updates this poll with params."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollHandler","preciseIdentifier":"s:15SendbirdChatSDK11PollHandlera"},{"kind":"text","text":")"}],"title":"update(params:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDPoll(im)updateWithParams:completionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"updateWithParams:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollUpdateParams":{"role":"symbol","title":"PollUpdateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollUpdateParams"}],"abstract":[{"type":"text","text":"An object contains set of options to update "},{"type":"codeVoice","code":"Poll"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollUpdateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PollUpdateParams"}],"url":"\/documentation\/sendbirdchatsdk\/pollupdateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll":{"role":"symbol","title":"Poll","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Poll"}],"abstract":[{"type":"text","text":"Represents a poll that users can vote"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Poll"}],"url":"\/documentation\/sendbirdchatsdk\/poll"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollHandler":{"role":"symbol","title":"PollHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollHandler"}],"abstract":[{"type":"text","text":"Poll handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PollHandler"}],"url":"\/documentation\/sendbirdchatsdk\/pollhandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/update(params:completionHandler:)":{"role":"symbol","title":"update(params:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollHandler","preciseIdentifier":"s:15SendbirdChatSDK11PollHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Updates this poll with params."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/update(params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateWithParams:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/poll\/update(params:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateWithParams:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateWithParams:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateWithParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollUpdateParams","text":"SBDPollUpdateParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDPoll *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDPoll#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollUpdateParams\/title","value":"SBDPollUpdateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollUpdateParams\/fragments","value":[{"kind":"identifier","text":"SBDPollUpdateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll\/title","value":"SBDPoll"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll\/fragments","value":[{"kind":"identifier","text":"SBDPoll"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1update(params:completionHandler:)\/title","value":"updateWithParams:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1update(params:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateWithParams:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}