{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenPreventAutoUnhide"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter\/hiddenpreventautounhide"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter\/hiddenpreventautounhide"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/hiddenPreventAutoUnhide","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Shows the channels will not be unhidden automatically."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenPreventAutoUnhide"}],"title":"ChannelHiddenStateFilter.hiddenPreventAutoUnhide","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDChannelHiddenStateFilter@SBDChannelHiddenStateFilterHiddenPreventAutoUnhide","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDChannelHiddenStateFilterHiddenPreventAutoUnhide"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelHiddenStateFilter/hiddenPreventAutoUnhide":{"role":"symbol","title":"ChannelHiddenStateFilter.hiddenPreventAutoUnhide","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenPreventAutoUnhide"}],"abstract":[{"type":"text","text":"Shows the channels will not be unhidden automatically."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/hiddenPreventAutoUnhide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDChannelHiddenStateFilterHiddenPreventAutoUnhide"}],"url":"\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter\/hiddenpreventautounhide"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelHiddenStateFilter":{"role":"symbol","title":"ChannelHiddenStateFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelHiddenStateFilter"}],"abstract":[{"type":"text","text":"The enum type to filter my group channels with the hidden state."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelHiddenStateFilter"}],"url":"\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDChannelHiddenStateFilterHiddenPreventAutoUnhide"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDChannelHiddenStateFilterHiddenPreventAutoUnhide"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDChannelHiddenStateFilterHiddenPreventAutoUnhide"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter~1hiddenPreventAutoUnhide\/title","value":"SBDChannelHiddenStateFilterHiddenPreventAutoUnhide"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter~1hiddenPreventAutoUnhide\/fragments","value":[{"kind":"identifier","text":"SBDChannelHiddenStateFilterHiddenPreventAutoUnhide"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter\/title","value":"SBDChannelHiddenStateFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter\/fragments","value":[{"kind":"identifier","text":"SBDChannelHiddenStateFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}