{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(applyPollUpdateEvent:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apply"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pollUpdateEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollUpdateEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollUpdateEvent","text":"PollUpdateEvent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" if event is successfuly applied"}]}]},{"kind":"parameters","parameters":[{"name":"pollUpdateEvent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"PollUpdateEvent"},{"type":"text","text":" instance"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is designed to be called when "},{"type":"codeVoice","code":"didUpdatePoll(:_)"},{"type":"text","text":" event passes the poll object"}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.232"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/usermessage\/apply(_:)-6ymzm"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/usermessage\/apply(_:)-6ymzm"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage\/apply(_:)-6ymzm","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Applies updated poll data to this message object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apply"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PollUpdateEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollUpdateEvent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"apply(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage(im)applyPollUpdateEvent:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"applyPollUpdateEvent:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessage/apply(_:)-6ymzm":{"role":"symbol","title":"apply(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apply"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PollUpdateEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollUpdateEvent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Applies updated poll data to this message object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage\/apply(_:)-6ymzm","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applyPollUpdateEvent:"}],"url":"\/documentation\/sendbirdchatsdk\/usermessage\/apply(_:)-6ymzm"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollUpdateEvent":{"role":"symbol","title":"PollUpdateEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollUpdateEvent"}],"abstract":[{"type":"text","text":"Represents an poll update event"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollUpdateEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PollUpdateEvent"}],"url":"\/documentation\/sendbirdchatsdk\/pollupdateevent"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessage":{"role":"symbol","title":"UserMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMessage"}],"abstract":[{"type":"text","text":"Represents a mesage object that contains a text message. Derived from "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserMessage"}],"url":"\/documentation\/sendbirdchatsdk\/usermessage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"applyPollUpdateEvent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyPollUpdateEvent:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"applyPollUpdateEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollUpdateEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollUpdateEvent","text":"SBDPollUpdateEvent"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"pollUpdateEvent"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessage~1apply(_:)-6ymzm\/title","value":"applyPollUpdateEvent:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessage~1apply(_:)-6ymzm\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyPollUpdateEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollUpdateEvent\/title","value":"SBDPollUpdateEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollUpdateEvent\/fragments","value":[{"kind":"identifier","text":"SBDPollUpdateEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessage\/title","value":"SBDUserMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessage\/fragments","value":[{"kind":"identifier","text":"SBDUserMessage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}