{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restrictionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDRestrictionType","text":"RestrictionType"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/restrictioninfo\/restrictiontype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/restrictioninfo\/restrictiontype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionInfo\/restrictionType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Restriction type"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restrictionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RestrictionType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDRestrictionType"}],"title":"restrictionType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDRestrictionInfo(py)restrictionType","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"restrictionType"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionInfo"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionInfo/restrictionType":{"role":"symbol","title":"restrictionType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restrictionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RestrictionType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDRestrictionType"}],"abstract":[{"type":"text","text":"Restriction type"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionInfo\/restrictionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"restrictionType"}],"url":"\/documentation\/sendbirdchatsdk\/restrictioninfo\/restrictiontype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionInfo":{"role":"symbol","title":"RestrictionInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictionInfo"}],"abstract":[{"type":"text","text":"An object contains information about restriction"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RestrictionInfo"}],"url":"\/documentation\/sendbirdchatsdk\/restrictioninfo"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionType":{"role":"symbol","title":"RestrictionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictionType"}],"abstract":[{"type":"text","text":"Restriction type for restrictedUser"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RestrictionType"}],"url":"\/documentation\/sendbirdchatsdk\/restrictiontype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"restrictionType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"restrictionType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDRestrictionType","text":"SBDRestrictionType"},{"kind":"identifier","text":"restrictionType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionInfo~1restrictionType\/title","value":"restrictionType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionInfo~1restrictionType\/fragments","value":[{"kind":"identifier","text":"restrictionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionInfo\/title","value":"SBDRestrictionInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionInfo\/fragments","value":[{"kind":"identifier","text":"SBDRestrictionInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionType\/title","value":"SBDRestrictionType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionType\/fragments","value":[{"kind":"identifier","text":"SBDRestrictionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}