{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQueryParams","text":"ParticipantListQueryParams"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/participantlistquery\/params"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/participantlistquery\/params"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQuery\/params","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A params object to set query condition."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ParticipantListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQueryParams"}],"title":"params","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQuery(py)params","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"params"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQuery"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ParticipantListQuery/params":{"role":"symbol","title":"params","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ParticipantListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQueryParams"}],"abstract":[{"type":"text","text":"A params object to set query condition."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQuery\/params","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"params"}],"url":"\/documentation\/sendbirdchatsdk\/participantlistquery\/params"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ParticipantListQueryParams":{"role":"symbol","title":"ParticipantListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ParticipantListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/participantlistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ParticipantListQuery":{"role":"symbol","title":"ParticipantListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ParticipantListQuery"},{"type":"text","text":" class is a query class for getting the list of participants in"},{"type":"text","text":" "},{"type":"text","text":"an open channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ParticipantListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/participantlistquery"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"params"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"params"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQueryParams","text":"SBDParticipantListQueryParams"},{"kind":"text","text":" *"},{"kind":"identifier","text":"params"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQuery~1params\/title","value":"params"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQuery~1params\/fragments","value":[{"kind":"identifier","text":"params"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQueryParams\/title","value":"SBDParticipantListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDParticipantListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQuery\/title","value":"SBDParticipantListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQuery\/fragments","value":[{"kind":"identifier","text":"SBDParticipantListQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}