{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage","text":"SBDUserMessage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"sendUserMessageWithParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessageCreateParams","text":"SBDUserMessageCreateParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"requestID"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDUserMessage *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDUserMessage#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sbdbasechannel\/sendusermessagewithparams:requestid:completionhandler:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBDBaseChannel\/sendUserMessageWithParams:requestID:completionHandler:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendUserMessageWithParams:requestID:completionHandler:"}],"title":"sendUserMessageWithParams:requestID:completionHandler:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)sendUserMessageWithParams:requestID:completionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"sendUserMessageWithParams:requestID:completionHandler:"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBDBaseChannel/sendUserMessageWithParams:requestID:completionHandler:":{"role":"symbol","title":"sendUserMessageWithParams:requestID:completionHandler:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendUserMessageWithParams:requestID:completionHandler:"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBDBaseChannel\/sendUserMessageWithParams:requestID:completionHandler:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendUserMessageWithParams:requestID:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/sbdbasechannel\/sendusermessagewithparams:requestid:completionhandler:"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessage":{"role":"symbol","title":"UserMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMessage"}],"abstract":[{"type":"text","text":"Represents a mesage object that contains a text message. Derived from "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserMessage"}],"url":"\/documentation\/sendbirdchatsdk\/usermessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageCreateParams":{"role":"symbol","title":"UserMessageCreateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMessageCreateParams"}],"abstract":[{"type":"text","text":"An object contains a set of options to create "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserMessageCreateParams"}],"url":"\/documentation\/sendbirdchatsdk\/usermessagecreateparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessage\/title","value":"SBDUserMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessage\/fragments","value":[{"kind":"identifier","text":"SBDUserMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams\/title","value":"SBDUserMessageCreateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams\/fragments","value":[{"kind":"identifier","text":"SBDUserMessageCreateParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}