{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage","text":"SBDFileMessage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"sendFileMessageWithParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessageCreateParams","text":"SBDFileMessageCreateParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"requestID"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage","text":"SBDFileMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"originalMessage"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSString *, long long, long long, long long)","preciseIdentifier":"c:BFv(#*$objc(cs)NSString#K#K#K)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"progressHandler"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDFileMessage *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDFileMessage#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sbdbasechannel\/sendfilemessagewithparams:requestid:originalmessage:progresshandler:completionhandler:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBDBaseChannel\/sendFileMessageWithParams:requestID:originalMessage:progressHandler:completionHandler:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendFileMessageWithParams:requestID:originalMessage:progressHandler:completionHandler:"}],"title":"sendFileMessageWithParams:requestID:originalMessage:progressHandler:completionHandler:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)sendFileMessageWithParams:requestID:originalMessage:progressHandler:completionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"sendFileMessageWithParams:requestID:originalMessage:progressHandler:completionHandler:"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBDBaseChannel/sendFileMessageWithParams:requestID:originalMessage:progressHandler:completionHandler:":{"role":"symbol","title":"sendFileMessageWithParams:requestID:originalMessage:progressHandler:completionHandler:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendFileMessageWithParams:requestID:originalMessage:progressHandler:completionHandler:"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBDBaseChannel\/sendFileMessageWithParams:requestID:originalMessage:progressHandler:completionHandler:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendFileMessageWithParams:requestID:originalMessage:progressHandler:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/sbdbasechannel\/sendfilemessagewithparams:requestid:originalmessage:progresshandler:completionhandler:"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage":{"role":"symbol","title":"FileMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessage"}],"abstract":[{"type":"text","text":"Represents a mesage object that contains a file. Derived from "},{"type":"codeVoice","code":"BaseMessage"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessage"}],"url":"\/documentation\/sendbirdchatsdk\/filemessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessageCreateParams":{"role":"symbol","title":"FileMessageCreateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessageCreateParams"}],"abstract":[{"type":"text","text":"An object contains set of options to create "},{"type":"codeVoice","code":"FileMessage"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageCreateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessageCreateParams"}],"url":"\/documentation\/sendbirdchatsdk\/filemessagecreateparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage\/title","value":"SBDFileMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage\/fragments","value":[{"kind":"identifier","text":"SBDFileMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessageCreateParams\/title","value":"SBDFileMessageCreateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessageCreateParams\/fragments","value":[{"kind":"identifier","text":"SBDFileMessageCreateParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}