{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageTypeFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageTypeFilter","text":"MessageTypeFilter"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.106"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/previousmessagelistqueryparams\/messagetypefilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/previousmessagelistqueryparams\/messagetypefilter"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PreviousMessageListQueryParams\/messageTypeFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the message type to filter messages. The default value is "},{"type":"codeVoice","code":".all"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageTypeFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageTypeFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageTypeFilter"}],"title":"messageTypeFilter","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDPreviousMessageListQueryParams(py)messageTypeFilter","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"messageTypeFilter"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PreviousMessageListQueryParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PreviousMessageListQueryParams/messageTypeFilter":{"role":"symbol","title":"messageTypeFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageTypeFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageTypeFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageTypeFilter"}],"abstract":[{"type":"text","text":"Sets the message type to filter messages. The default value is "},{"type":"codeVoice","code":".all"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PreviousMessageListQueryParams\/messageTypeFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageTypeFilter"}],"url":"\/documentation\/sendbirdchatsdk\/previousmessagelistqueryparams\/messagetypefilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageTypeFilter":{"role":"symbol","title":"MessageTypeFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageTypeFilter"}],"abstract":[{"type":"text","text":"Message type for filtering"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageTypeFilter"}],"url":"\/documentation\/sendbirdchatsdk\/messagetypefilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PreviousMessageListQueryParams":{"role":"symbol","title":"PreviousMessageListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviousMessageListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PreviousMessageListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreviousMessageListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/previousmessagelistqueryparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"messageTypeFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"messageTypeFilter"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageTypeFilter","text":"SBDMessageTypeFilter"},{"kind":"identifier","text":"messageTypeFilter"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PreviousMessageListQueryParams~1messageTypeFilter\/title","value":"messageTypeFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PreviousMessageListQueryParams~1messageTypeFilter\/fragments","value":[{"kind":"identifier","text":"messageTypeFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter\/title","value":"SBDMessageTypeFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter\/fragments","value":[{"kind":"identifier","text":"SBDMessageTypeFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PreviousMessageListQueryParams\/title","value":"SBDPreviousMessageListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PreviousMessageListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDPreviousMessageListQueryParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}