{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelNameAlphabetical"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/publicgroupchannellistorder\/channelnamealphabetical"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/publicgroupchannellistorder\/channelnamealphabetical"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/channelNameAlphabetical","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Alphabetical name order for public group channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelNameAlphabetical"}],"title":"PublicGroupChannelListOrder.channelNameAlphabetical","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDPublicGroupChannelListOrder@SBDPublicGroupChannelListOrderChannelNameAlphabetical","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDPublicGroupChannelListOrderChannelNameAlphabetical"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListOrder":{"role":"symbol","title":"PublicGroupChannelListOrder","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicGroupChannelListOrder"}],"abstract":[{"type":"text","text":"The order type for "},{"type":"codeVoice","code":"PublicGroupChannelListQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PublicGroupChannelListOrder"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistorder"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListOrder/channelNameAlphabetical":{"role":"symbol","title":"PublicGroupChannelListOrder.channelNameAlphabetical","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelNameAlphabetical"}],"abstract":[{"type":"text","text":"Alphabetical name order for public group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/channelNameAlphabetical","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPublicGroupChannelListOrderChannelNameAlphabetical"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistorder\/channelnamealphabetical"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDPublicGroupChannelListOrderChannelNameAlphabetical"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelListOrderChannelNameAlphabetical"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDPublicGroupChannelListOrderChannelNameAlphabetical"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListOrder\/title","value":"SBDPublicGroupChannelListOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListOrder\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelListOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListOrder~1channelNameAlphabetical\/title","value":"SBDPublicGroupChannelListOrderChannelNameAlphabetical"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListOrder~1channelNameAlphabetical\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelListOrderChannelNameAlphabetical"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}