{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"comparator"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBObjectComparator","preciseIdentifier":"s:15SendbirdChatSDK18SBObjectComparatora","text":"SBObjectComparator"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBObjectComparator"},{"type":"text","text":" object"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistquery\/comparator()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistquery\/comparator()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery\/comparator()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets comparator"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"comparator"}],"role":"symbol","title":"comparator()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"comparator"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBObjectComparator","preciseIdentifier":"s:15SendbirdChatSDK18SBObjectComparatora"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery(im)comparator","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery\/SBComparator-Implementations"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuery/comparator()":{"role":"symbol","title":"comparator()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"comparator"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBObjectComparator","preciseIdentifier":"s:15SendbirdChatSDK18SBObjectComparatora"}],"abstract":[{"type":"text","text":"Gets comparator"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery\/comparator()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"comparator"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquery\/comparator()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuery":{"role":"symbol","title":"GroupChannelListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannelListQuery"},{"type":"text","text":" class is a query class for getting the list of group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuery/SBComparator-Implementations":{"role":"collectionGroup","title":"SBComparator Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery\/SBComparator-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannellistquery\/sbcomparator-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBObjectComparator":{"role":"symbol","title":"SBObjectComparator","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBObjectComparator"}],"abstract":[{"type":"text","text":"Sendbird objc comparator"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBObjectComparator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBObjectComparator"}],"url":"\/documentation\/sendbirdchatsdk\/sbobjectcomparator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"comparator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"comparator"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"enum NSComparisonResult (^)(id, id)","preciseIdentifier":"c:BF$@E@NSComparisonResult(#*Qo#S3_)"},{"kind":"text","text":") "},{"kind":"identifier","text":"comparator"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery~1comparator()\/title","value":"comparator"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery~1comparator()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"comparator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery\/title","value":"SBDGroupChannelListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}