{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListOrder","text":"GroupChannelListOrder"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistquery\/order"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistquery\/order"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery\/order","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the order of the list. The order is defined in "},{"type":"codeVoice","code":"GroupChannelListOrder"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListOrder","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListOrder"}],"title":"order","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery(py)order","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"order"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuery":{"role":"symbol","title":"GroupChannelListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannelListQuery"},{"type":"text","text":" class is a query class for getting the list of group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListOrder":{"role":"symbol","title":"GroupChannelListOrder","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListOrder"}],"abstract":[{"type":"text","text":"The order type for "},{"type":"codeVoice","code":"GroupChannelListQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListOrder"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistorder"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuery/order":{"role":"symbol","title":"order","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListOrder","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListOrder"}],"abstract":[{"type":"text","text":"Sets the order of the list. The order is defined in "},{"type":"codeVoice","code":"GroupChannelListOrder"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery\/order","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"order"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquery\/order"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"order"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"order"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListOrder","text":"SBDGroupChannelListOrder"},{"kind":"identifier","text":"order"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery\/title","value":"SBDGroupChannelListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder\/title","value":"SBDGroupChannelListOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery~1order\/title","value":"order"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery~1order\/fragments","value":[{"kind":"identifier","text":"order"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}