{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQueryParams","text":"GroupChannelListQueryParams"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistquery\/params"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistquery\/params"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery\/params","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A params object to set query condition."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQueryParams"}],"title":"params","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery(py)params","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"params"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuery":{"role":"symbol","title":"GroupChannelListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannelListQuery"},{"type":"text","text":" class is a query class for getting the list of group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams":{"role":"symbol","title":"GroupChannelListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuery/params":{"role":"symbol","title":"params","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQueryParams"}],"abstract":[{"type":"text","text":"A params object to set query condition."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuery\/params","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"params"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquery\/params"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"params"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"params"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQueryParams","text":"SBDGroupChannelListQueryParams"},{"kind":"text","text":" *"},{"kind":"identifier","text":"params"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery\/title","value":"SBDGroupChannelListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams\/title","value":"SBDGroupChannelListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery~1params\/title","value":"params"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuery~1params\/fragments","value":[{"kind":"identifier","text":"params"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}