{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDCollectionEventSource","text":"CollectionEventSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sendingStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageSendingStatus","text":"MessageSendingStatus"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"source","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Message source."}]}]},{"name":"sendingStatus","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Message sending status."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns CollectionEventSource object."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagecontext\/init(source:sendingstatus:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageContext\/init(source:sendingStatus:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes with the message source."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CollectionEventSource","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDCollectionEventSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sendingStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageSendingStatus","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageSendingStatus"},{"kind":"text","text":")"}],"title":"init(source:sendingStatus:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:15SendbirdChatSDK14MessageContextC6source13sendingStatusAcA21CollectionEventSourceO_AA0d7SendingH0Otcfc","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageContext"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource":{"role":"symbol","title":"CollectionEventSource","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionEventSource"}],"abstract":[{"type":"text","text":"Channel sources that represents where the channel object comes from."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CollectionEventSource"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus":{"role":"symbol","title":"MessageSendingStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSendingStatus"}],"abstract":[{"type":"text","text":"Constants of type to describe message’s sending status."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageSendingStatus"}],"url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageContext":{"role":"symbol","title":"MessageContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageContext"}],"abstract":[{"type":"text","text":"Represents what happened to the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageContext"}],"url":"\/documentation\/sendbirdchatsdk\/messagecontext"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageContext/init(source:sendingStatus:)":{"role":"symbol","title":"init(source:sendingStatus:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CollectionEventSource","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDCollectionEventSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sendingStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageSendingStatus","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageSendingStatus"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes with the message source."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageContext\/init(source:sendingStatus:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagecontext\/init(source:sendingstatus:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource\/title","value":"SBDCollectionEventSource"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSource"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus\/title","value":"SBDMessageSendingStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageContext\/title","value":"SBDMessageContext"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageContext\/fragments","value":[{"kind":"identifier","text":"SBDMessageContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}