{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendingStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageSendingStatus","text":"MessageSendingStatus"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagecontext\/sendingstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagecontext\/sendingstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageContext\/sendingStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Message sending status"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendingStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageSendingStatus","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageSendingStatus"}],"title":"sendingStatus","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext(py)sendingStatus","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"sendingStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageContext"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus":{"role":"symbol","title":"MessageSendingStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSendingStatus"}],"abstract":[{"type":"text","text":"Constants of type to describe message’s sending status."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageSendingStatus"}],"url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageContext":{"role":"symbol","title":"MessageContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageContext"}],"abstract":[{"type":"text","text":"Represents what happened to the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageContext"}],"url":"\/documentation\/sendbirdchatsdk\/messagecontext"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageContext/sendingStatus":{"role":"symbol","title":"sendingStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendingStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageSendingStatus","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageSendingStatus"}],"abstract":[{"type":"text","text":"Message sending status"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageContext\/sendingStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendingStatus"}],"url":"\/documentation\/sendbirdchatsdk\/messagecontext\/sendingstatus"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"sendingStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sendingStatus"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageSendingStatus","text":"SBDMessageSendingStatus"},{"kind":"identifier","text":"sendingStatus"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus\/title","value":"SBDMessageSendingStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageContext\/title","value":"SBDMessageContext"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageContext\/fragments","value":[{"kind":"identifier","text":"SBDMessageContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageContext~1sendingStatus\/title","value":"sendingStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageContext~1sendingStatus\/fragments","value":[{"kind":"identifier","text":"sendingStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}