{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"broadcastOnly"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter\/broadcastonly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter\/broadcastonly"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/broadcastOnly","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"broadcastOnly"}],"title":"GroupChannelSuperChannelFilter.broadcastOnly","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDGroupChannelSuperChannelFilter@SBDGroupChannelSuperChannelFilterBroadcastOnly","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilterBroadcastOnly"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelSuperChannelFilter/broadcastOnly":{"role":"symbol","title":"GroupChannelSuperChannelFilter.broadcastOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"broadcastOnly"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/broadcastOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilterBroadcastOnly"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter\/broadcastonly"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelSuperChannelFilter":{"role":"symbol","title":"GroupChannelSuperChannelFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelSuperChannelFilter"}],"abstract":[{"type":"text","text":"Channel filter for super mode in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelSuperChannelFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelSuperChannelFilterBroadcastOnly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilterBroadcastOnly"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilterBroadcastOnly"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter~1broadcastOnly\/title","value":"SBDGroupChannelSuperChannelFilterBroadcastOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter~1broadcastOnly\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilterBroadcastOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter\/title","value":"SBDGroupChannelSuperChannelFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}