{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(addChannelDelegate:identifier:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(pl)SBDBaseChannelDelegate","text":"BaseChannelDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" delegate."}]}]},{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier for delegate."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/add(_:identifier:)-4t0fl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/add(_:identifier:)-4t0fl"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/add(_:identifier:)-4t0fl","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Adds the "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannelDelegate","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(pl)SBDBaseChannelDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"add(_:identifier:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SendbirdChat(cm)addChannelDelegate:identifier:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"addChannelDelegate:identifier:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat":{"role":"symbol","title":"SendbirdChat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendbirdChat"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":" is the core class for Sendbird. This class is singletone instance which is initialized by Application ID."},{"type":"text","text":" "},{"type":"text","text":"This class provides the methods for overall operations. The methods include "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" registration for receiving events"},{"type":"text","text":" "},{"type":"text","text":"that are related to channels, "},{"type":"codeVoice","code":"ConnectionDelegate"},{"type":"text","text":" for managing the connection status, updating the current user’s information,"},{"type":"text","text":" "},{"type":"text","text":"registration for APNS push notification and blocking other users."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendbirdChat"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat/add(_:identifier:)-4t0fl":{"role":"symbol","title":"add(_:identifier:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannelDelegate","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(pl)SBDBaseChannelDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Adds the "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/add(_:identifier:)-4t0fl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addChannelDelegate:identifier:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat\/add(_:identifier:)-4t0fl"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate":{"role":"symbol","title":"BaseChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events"},{"type":"text","text":" "},{"type":"text","text":"in the channel. Delegate methods in "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" are common for the "},{"type":"codeVoice","code":"BaseChannel"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Exclusive delegate methods for "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" can be found in"},{"type":"text","text":" "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":". You must use "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":" instead of using "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" by using "},{"type":"codeVoice","code":"add(_:identifier:)"},{"type":"text","text":" in "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"addChannelDelegate:identifier:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addChannelDelegate:identifier:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addChannelDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SBDBaseChannelDelegate>","preciseIdentifier":"c:Qo@M@SendbirdChatSDK@objc(pl)SBDBaseChannelDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/title","value":"SendbirdChat"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/fragments","value":[{"kind":"identifier","text":"SendbirdChat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1add(_:identifier:)-4t0fl\/title","value":"addChannelDelegate:identifier:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1add(_:identifier:)-4t0fl\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addChannelDelegate:identifier:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate\/title","value":"SBDBaseChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannelDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}