{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBlockedUserListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramsBuilder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BlockedUserListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBlockedUserListQueryParams","text":"BlockedUserListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BlockedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBlockedUserListQuery","text":"BlockedUserListQuery"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"BlockedUserListQuery"},{"type":"text","text":" instance."}]}]},{"kind":"parameters","parameters":[{"name":"paramsBuilder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The builder closure for setting "},{"type":"codeVoice","code":"BlockedUserListQueryParams"},{"type":"text","text":"."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/createblockeduserlistquery(paramsbuilder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/createblockeduserlistquery(paramsbuilder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/createBlockedUserListQuery(paramsBuilder:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"BlockedUserListQuery"},{"type":"text","text":" instance for getting a list of blocked users by the current user."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBlockedUserListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramsBuilder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"BlockedUserListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBlockedUserListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"BlockedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBlockedUserListQuery"}],"title":"createBlockedUserListQuery(paramsBuilder:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SendbirdChat(cm)createBlockedUserListQueryWithParamsBuilder:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"createBlockedUserListQueryWithParamsBuilder:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat/createBlockedUserListQuery(paramsBuilder:)":{"role":"symbol","title":"createBlockedUserListQuery(paramsBuilder:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBlockedUserListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramsBuilder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"BlockedUserListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBlockedUserListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"BlockedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBlockedUserListQuery"}],"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"BlockedUserListQuery"},{"type":"text","text":" instance for getting a list of blocked users by the current user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/createBlockedUserListQuery(paramsBuilder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createBlockedUserListQueryWithParamsBuilder:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat\/createblockeduserlistquery(paramsbuilder:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BlockedUserListQueryParams":{"role":"symbol","title":"BlockedUserListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockedUserListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BlockedUserListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BlockedUserListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/blockeduserlistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BlockedUserListQuery":{"role":"symbol","title":"BlockedUserListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockedUserListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BlockedUserListQuery"},{"type":"text","text":" class is a query class for getting the list of blocked users"},{"type":"text","text":" "},{"type":"text","text":"by the current user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BlockedUserListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BlockedUserListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/blockeduserlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat":{"role":"symbol","title":"SendbirdChat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendbirdChat"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":" is the core class for Sendbird. This class is singletone instance which is initialized by Application ID."},{"type":"text","text":" "},{"type":"text","text":"This class provides the methods for overall operations. The methods include "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" registration for receiving events"},{"type":"text","text":" "},{"type":"text","text":"that are related to channels, "},{"type":"codeVoice","code":"ConnectionDelegate"},{"type":"text","text":" for managing the connection status, updating the current user’s information,"},{"type":"text","text":" "},{"type":"text","text":"registration for APNS push notification and blocking other users."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendbirdChat"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createBlockedUserListQueryWithParamsBuilder:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBlockedUserListQueryWithParamsBuilder:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BlockedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBlockedUserListQuery","text":"SBDBlockedUserListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createBlockedUserListQueryWithParamsBuilder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDBlockedUserListQueryParams *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDBlockedUserListQueryParams)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"paramsBuilder"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1createBlockedUserListQuery(paramsBuilder:)\/title","value":"createBlockedUserListQueryWithParamsBuilder:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1createBlockedUserListQuery(paramsBuilder:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBlockedUserListQueryWithParamsBuilder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BlockedUserListQueryParams\/title","value":"SBDBlockedUserListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BlockedUserListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDBlockedUserListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BlockedUserListQuery\/title","value":"SBDBlockedUserListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BlockedUserListQuery\/fragments","value":[{"kind":"identifier","text":"SBDBlockedUserListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/title","value":"SendbirdChat"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/fragments","value":[{"kind":"identifier","text":"SendbirdChat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}