{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createScheduledMessageListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledMessageListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledMessageListQueryParams","text":"ScheduledMessageListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledMessageListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledMessageListQuery","text":"ScheduledMessageListQuery"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The scheduled message list query object."}]}]},{"kind":"parameters","parameters":[{"name":"channelURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The channel URL. If "},{"type":"codeVoice","code":"channelURL"},{"type":"text","text":" is nil, you will get scheduled messages for all channels."}]}]},{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The params object to change query condition."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/createscheduledmessagelistquery(channelurl:params:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/createscheduledmessagelistquery(channelurl:params:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/createScheduledMessageListQuery(channelURL:params:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"ScheduledMessageListQuery"},{"type":"text","text":" for getting the list of scheduled messages."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createScheduledMessageListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledMessageListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledMessageListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ScheduledMessageListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledMessageListQuery"}],"title":"createScheduledMessageListQuery(channelURL:params:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SendbirdChat(cm)createScheduledMessageListQueryWithChannelURL:params:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"createScheduledMessageListQueryWithChannelURL:params:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledMessageListQuery":{"role":"symbol","title":"ScheduledMessageListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledMessageListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ScheduledMessageListQuery"},{"type":"text","text":" class is a query class for getting the list of scheduled messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledMessageListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledMessageListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledmessagelistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledMessageListQueryParams":{"role":"symbol","title":"ScheduledMessageListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledMessageListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledMessageListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledMessageListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledmessagelistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat/createScheduledMessageListQuery(channelURL:params:)":{"role":"symbol","title":"createScheduledMessageListQuery(channelURL:params:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createScheduledMessageListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledMessageListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledMessageListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ScheduledMessageListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledMessageListQuery"}],"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"ScheduledMessageListQuery"},{"type":"text","text":" for getting the list of scheduled messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/createScheduledMessageListQuery(channelURL:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createScheduledMessageListQueryWithChannelURL:params:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat\/createscheduledmessagelistquery(channelurl:params:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat":{"role":"symbol","title":"SendbirdChat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendbirdChat"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":" is the core class for Sendbird. This class is singletone instance which is initialized by Application ID."},{"type":"text","text":" "},{"type":"text","text":"This class provides the methods for overall operations. The methods include "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" registration for receiving events"},{"type":"text","text":" "},{"type":"text","text":"that are related to channels, "},{"type":"codeVoice","code":"ConnectionDelegate"},{"type":"text","text":" for managing the connection status, updating the current user’s information,"},{"type":"text","text":" "},{"type":"text","text":"registration for APNS push notification and blocking other users."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendbirdChat"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createScheduledMessageListQueryWithChannelURL:params:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createScheduledMessageListQueryWithChannelURL:params:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledMessageListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledMessageListQuery","text":"SBDScheduledMessageListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createScheduledMessageListQueryWithChannelURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"params:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledMessageListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledMessageListQueryParams","text":"SBDScheduledMessageListQueryParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledMessageListQuery\/title","value":"SBDScheduledMessageListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledMessageListQuery\/fragments","value":[{"kind":"identifier","text":"SBDScheduledMessageListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledMessageListQueryParams\/title","value":"SBDScheduledMessageListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledMessageListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDScheduledMessageListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1createScheduledMessageListQuery(channelURL:params:)\/title","value":"createScheduledMessageListQueryWithChannelURL:params:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1createScheduledMessageListQuery(channelURL:params:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createScheduledMessageListQueryWithChannelURL:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/title","value":"SendbirdChat"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/fragments","value":[{"kind":"identifier","text":"SendbirdChat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}