{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createFriendListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramsBuilder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FriendListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFriendListQueryParams","text":"FriendListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FriendListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFriendListQuery","text":"FriendListQuery"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"FriendListQuery"},{"type":"text","text":" instance"}]}]},{"kind":"parameters","parameters":[{"name":"paramsBuilder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The builder closure for setting "},{"type":"codeVoice","code":"FriendListQueryParams"},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/createfriendlistquery(paramsbuilder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/createfriendlistquery(paramsbuilder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/createFriendListQuery(paramsBuilder:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"FriendListQuery"},{"type":"text","text":" instance for friend list"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createFriendListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramsBuilder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"FriendListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFriendListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FriendListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFriendListQuery"}],"title":"createFriendListQuery(paramsBuilder:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SendbirdChat(cm)createFriendListQueryWithParamsBuilder:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"createFriendListQueryWithParamsBuilder:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FriendListQuery":{"role":"symbol","title":"FriendListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FriendListQuery"}],"abstract":[{"type":"text","text":"A object to retrieve friend list"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FriendListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FriendListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/friendlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat/createFriendListQuery(paramsBuilder:)":{"role":"symbol","title":"createFriendListQuery(paramsBuilder:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createFriendListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramsBuilder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"FriendListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFriendListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FriendListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFriendListQuery"}],"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"FriendListQuery"},{"type":"text","text":" instance for friend list"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/createFriendListQuery(paramsBuilder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createFriendListQueryWithParamsBuilder:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat\/createfriendlistquery(paramsbuilder:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FriendListQueryParams":{"role":"symbol","title":"FriendListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FriendListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FriendListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FriendListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/friendlistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat":{"role":"symbol","title":"SendbirdChat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendbirdChat"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":" is the core class for Sendbird. This class is singletone instance which is initialized by Application ID."},{"type":"text","text":" "},{"type":"text","text":"This class provides the methods for overall operations. The methods include "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" registration for receiving events"},{"type":"text","text":" "},{"type":"text","text":"that are related to channels, "},{"type":"codeVoice","code":"ConnectionDelegate"},{"type":"text","text":" for managing the connection status, updating the current user’s information,"},{"type":"text","text":" "},{"type":"text","text":"registration for APNS push notification and blocking other users."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendbirdChat"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createFriendListQueryWithParamsBuilder:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createFriendListQueryWithParamsBuilder:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FriendListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFriendListQuery","text":"SBDFriendListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createFriendListQueryWithParamsBuilder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDFriendListQueryParams *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDFriendListQueryParams)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"paramsBuilder"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FriendListQuery\/title","value":"SBDFriendListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FriendListQuery\/fragments","value":[{"kind":"identifier","text":"SBDFriendListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1createFriendListQuery(paramsBuilder:)\/title","value":"createFriendListQueryWithParamsBuilder:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1createFriendListQuery(paramsBuilder:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createFriendListQueryWithParamsBuilder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FriendListQueryParams\/title","value":"SBDFriendListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FriendListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDFriendListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/title","value":"SendbirdChat"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/fragments","value":[{"kind":"identifier","text":"SendbirdChat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}