{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllEmojis"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"emojiContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiContainer","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDEmojiContainer","text":"EmojiContainer"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError","text":"SBError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to execute after request is completed"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.180"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/getallemojis(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/getallemojis(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/getAllEmojis(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Requests a emoji container which contains hash and list of emoji category."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllEmojis"},{"kind":"text","text":"((("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"emojiContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EmojiContainer","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDEmojiContainer"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"title":"getAllEmojis(_:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SendbirdChat(cm)getAllEmojis:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getAllEmojis:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/EmojiContainer":{"role":"symbol","title":"EmojiContainer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmojiContainer"}],"abstract":[{"type":"text","text":"An object contains list of "},{"type":"codeVoice","code":"EmojiCategory"},{"type":"text","text":" and hash"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmojiContainer"}],"url":"\/documentation\/sendbirdchatsdk\/emojicontainer"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat/getAllEmojis(_:)":{"role":"symbol","title":"getAllEmojis(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllEmojis"},{"kind":"text","text":"((("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"emojiContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EmojiContainer","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDEmojiContainer"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Requests a emoji container which contains hash and list of emoji category."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/getAllEmojis(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAllEmojis:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat\/getallemojis(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBError":{"role":"symbol","title":"SBError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBError"}],"abstract":[{"type":"text","text":"Sendbird error class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBError"}],"url":"\/documentation\/sendbirdchatsdk\/sberror"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat":{"role":"symbol","title":"SendbirdChat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendbirdChat"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":" is the core class for Sendbird. This class is singletone instance which is initialized by Application ID."},{"type":"text","text":" "},{"type":"text","text":"This class provides the methods for overall operations. The methods include "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" registration for receiving events"},{"type":"text","text":" "},{"type":"text","text":"that are related to channels, "},{"type":"codeVoice","code":"ConnectionDelegate"},{"type":"text","text":" for managing the connection status, updating the current user’s information,"},{"type":"text","text":" "},{"type":"text","text":"registration for APNS push notification and blocking other users."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendbirdChat"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getAllEmojis:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getAllEmojis:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getAllEmojis:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDEmojiContainer *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDEmojiContainer#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiContainer\/title","value":"SBDEmojiContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiContainer\/fragments","value":[{"kind":"identifier","text":"SBDEmojiContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1getAllEmojis(_:)\/title","value":"getAllEmojis:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1getAllEmojis(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getAllEmojis:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SBError\/title","value":"SBError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SBError\/fragments","value":[{"kind":"identifier","text":"SBError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/title","value":"SendbirdChat"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/fragments","value":[{"kind":"identifier","text":"SendbirdChat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}