{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(getMyGroupChannelChangeLogsWithTimestamp:params:completionHandler:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMyGroupChannelChangeLogs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelChangeLogsParams","text":"GroupChannelChangeLogsParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelChangeLogsHandler","preciseIdentifier":"s:15SendbirdChatSDK24ChannelChangeLogsHandlera","text":"ChannelChangeLogsHandler"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"timestamp","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The number of milli-seconds(msec). Requests changelogs from that time. This value must not be \/\/\/negative."}]}]},{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the parameter object that filters a result. See "},{"type":"codeVoice","code":"GroupChannelChangeLogsParams"},{"type":"text","text":" for more detail"}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler type of "},{"type":"codeVoice","code":"ChannelChangeLogsHandler"},{"type":"text","text":" block to"},{"type":"text","text":" "},{"type":"text","text":"execute. The "},{"type":"codeVoice","code":"updatedChannels"},{"type":"text","text":" is the channels that were updated. The "},{"type":"codeVoice","code":"deletedChannelURLs"},{"type":"text","text":" "},{"type":"text","text":"is the list of the deleted channel URLs. If there are more changelogs that are not returned yet, the"},{"type":"text","text":" "},{"type":"codeVoice","code":"hasMore"},{"type":"text","text":" is "},{"type":"codeVoice","code":"true"},{"type":"text","text":". The "},{"type":"codeVoice","code":"token"},{"type":"text","text":" can be used to get more changedlogs."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.182"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/getmygroupchannelchangelogs(timestamp:params:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/getmygroupchannelchangelogs(timestamp:params:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/getMyGroupChannelChangeLogs(timestamp:params:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Requests updated channels and deleted channel URLs since the timestamp."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMyGroupChannelChangeLogs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelChangeLogsParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelChangeLogsHandler","preciseIdentifier":"s:15SendbirdChatSDK24ChannelChangeLogsHandlera"},{"kind":"text","text":")"}],"title":"getMyGroupChannelChangeLogs(timestamp:params:completionHandler:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SendbirdChat(cm)getMyGroupChannelChangeLogsWithTimestamp:params:completionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getMyGroupChannelChangeLogsWithTimestamp:params:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelChangeLogsParams":{"role":"symbol","title":"GroupChannelChangeLogsParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelChangeLogsParams"}],"abstract":[{"type":"text","text":"An object that represents the parameters for the The method returns channels according to the properties in this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelChangeLogsParams"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat":{"role":"symbol","title":"SendbirdChat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendbirdChat"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":" is the core class for Sendbird. This class is singletone instance which is initialized by Application ID."},{"type":"text","text":" "},{"type":"text","text":"This class provides the methods for overall operations. The methods include "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" registration for receiving events"},{"type":"text","text":" "},{"type":"text","text":"that are related to channels, "},{"type":"codeVoice","code":"ConnectionDelegate"},{"type":"text","text":" for managing the connection status, updating the current user’s information,"},{"type":"text","text":" "},{"type":"text","text":"registration for APNS push notification and blocking other users."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendbirdChat"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat/getMyGroupChannelChangeLogs(timestamp:params:completionHandler:)":{"role":"symbol","title":"getMyGroupChannelChangeLogs(timestamp:params:completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMyGroupChannelChangeLogs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelChangeLogsParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelChangeLogsHandler","preciseIdentifier":"s:15SendbirdChatSDK24ChannelChangeLogsHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Requests updated channels and deleted channel URLs since the timestamp."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/getMyGroupChannelChangeLogs(timestamp:params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getMyGroupChannelChangeLogsWithTimestamp:params:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat\/getmygroupchannelchangelogs(timestamp:params:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelChangeLogsHandler":{"role":"symbol","title":"ChannelChangeLogsHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelChangeLogsHandler"}],"abstract":[{"type":"text","text":"Channel Change log handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelChangeLogsHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelChangeLogsHandler"}],"url":"\/documentation\/sendbirdchatsdk\/channelchangelogshandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getMyGroupChannelChangeLogsWithTimestamp:params:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getMyGroupChannelChangeLogsWithTimestamp:params:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getMyGroupChannelChangeLogsWithTimestamp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"timestamp"},{"kind":"text","text":" "},{"kind":"identifier","text":"params:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelChangeLogsParams","text":"SBDGroupChannelChangeLogsParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<SBDGroupChannel *> *, NSArray<NSString *> *, _Bool, NSString *, SBError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*QS4_#b#*$objc(cs)NSString#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams\/title","value":"SBDGroupChannelChangeLogsParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelChangeLogsParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/title","value":"SendbirdChat"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/fragments","value":[{"kind":"identifier","text":"SendbirdChat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1getMyGroupChannelChangeLogs(timestamp:params:completionHandler:)\/title","value":"getMyGroupChannelChangeLogsWithTimestamp:params:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1getMyGroupChannelChangeLogs(timestamp:params:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getMyGroupChannelChangeLogsWithTimestamp:params:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}