{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMimeType"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"file"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns mime type of the file."}]}]},{"kind":"parameters","parameters":[{"name":"file","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"File to get mime type."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/getmimetype(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/getmimetype(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/getMimeType(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets mime type of file."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMimeType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"getMimeType(_:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SendbirdChat(cm)getMimeType:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getMimeType:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat/getMimeType(_:)":{"role":"symbol","title":"getMimeType(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMimeType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Gets mime type of file."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/getMimeType(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getMimeType:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat\/getmimetype(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat":{"role":"symbol","title":"SendbirdChat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendbirdChat"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":" is the core class for Sendbird. This class is singletone instance which is initialized by Application ID."},{"type":"text","text":" "},{"type":"text","text":"This class provides the methods for overall operations. The methods include "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" registration for receiving events"},{"type":"text","text":" "},{"type":"text","text":"that are related to channels, "},{"type":"codeVoice","code":"ConnectionDelegate"},{"type":"text","text":" for managing the connection status, updating the current user’s information,"},{"type":"text","text":" "},{"type":"text","text":"registration for APNS push notification and blocking other users."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendbirdChat"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getMimeType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getMimeType:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getMimeType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"file"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1getMimeType(_:)\/title","value":"getMimeType:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1getMimeType(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getMimeType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/title","value":"SendbirdChat"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/fragments","value":[{"kind":"identifier","text":"SendbirdChat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}