{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/InitParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDInitParams","text":"InitParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"migrationStartHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/VoidHandler","preciseIdentifier":"s:15SendbirdChatSDK11VoidHandlera","text":"VoidHandler"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera","text":"SBErrorHandler"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the applicationID is set."}]}]},{"kind":"parameters","parameters":[{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"InitParams"},{"type":"text","text":" object"}]}]},{"name":"migrationStartHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"handler that notifies when local cache migration has started"}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"handler that notifies when local cache is ready to use"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Application ID is on Sendbird dashboard. This method has to be run first in order to user Sendbird."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.227"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/initialize(params:migrationstarthandler:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/initialize(params:migrationstarthandler:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/initialize(params:migrationStartHandler:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":" singleton instance with Sendbird Application ID."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InitParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDInitParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"migrationStartHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoidHandler","preciseIdentifier":"s:15SendbirdChatSDK11VoidHandlera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"initialize(params:migrationStartHandler:completionHandler:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SendbirdChat(cm)initializeWithParams:migrationStartHandler:completionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initializeWithParams:migrationStartHandler:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBErrorHandler":{"role":"symbol","title":"SBErrorHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBErrorHandler"}],"abstract":[{"type":"text","text":"Error handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBErrorHandler"}],"url":"\/documentation\/sendbirdchatsdk\/sberrorhandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat":{"role":"symbol","title":"SendbirdChat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendbirdChat"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":" is the core class for Sendbird. This class is singletone instance which is initialized by Application ID."},{"type":"text","text":" "},{"type":"text","text":"This class provides the methods for overall operations. The methods include "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" registration for receiving events"},{"type":"text","text":" "},{"type":"text","text":"that are related to channels, "},{"type":"codeVoice","code":"ConnectionDelegate"},{"type":"text","text":" for managing the connection status, updating the current user’s information,"},{"type":"text","text":" "},{"type":"text","text":"registration for APNS push notification and blocking other users."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendbirdChat"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/InitParams":{"role":"symbol","title":"InitParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InitParams"}],"abstract":[{"type":"text","text":"An object to initialize SendbirdChat"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/InitParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InitParams"}],"url":"\/documentation\/sendbirdchatsdk\/initparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat/initialize(params:migrationStartHandler:completionHandler:)":{"role":"symbol","title":"initialize(params:migrationStartHandler:completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InitParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDInitParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"migrationStartHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoidHandler","preciseIdentifier":"s:15SendbirdChatSDK11VoidHandlera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Initializes "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":" singleton instance with Sendbird Application ID."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/initialize(params:migrationStartHandler:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeWithParams:migrationStartHandler:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat\/initialize(params:migrationstarthandler:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/VoidHandler":{"role":"symbol","title":"VoidHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoidHandler"}],"abstract":[{"type":"text","text":"Void handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/VoidHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VoidHandler"}],"url":"\/documentation\/sendbirdchatsdk\/voidhandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"initializeWithParams:migrationStartHandler:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeWithParams:migrationStartHandler:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"initializeWithParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/InitParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDInitParams","text":"SBDInitParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":" "},{"kind":"identifier","text":"migrationStartHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":")"},{"kind":"internalParam","text":"migrationStartHandler"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/title","value":"SendbirdChat"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/fragments","value":[{"kind":"identifier","text":"SendbirdChat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1InitParams\/title","value":"SBDInitParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1InitParams\/fragments","value":[{"kind":"identifier","text":"SBDInitParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1initialize(params:migrationStartHandler:completionHandler:)\/title","value":"initializeWithParams:migrationStartHandler:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1initialize(params:migrationStartHandler:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeWithParams:migrationStartHandler:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}