{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markAsDelivered"},{"kind":"text","text":"("},{"kind":"externalParam","text":"remoteNotificationPayload"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera","text":"SBErrorHandler"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"remoteNotificationPayload","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The remote notification payload"}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to execute"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.183"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/markasdelivered(remotenotificationpayload:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/markasdelivered(remotenotificationpayload:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/markAsDelivered(remoteNotificationPayload:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Marks as delivered with the payload of the remote notification."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markAsDelivered"},{"kind":"text","text":"("},{"kind":"externalParam","text":"remoteNotificationPayload"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"title":"markAsDelivered(remoteNotificationPayload:completionHandler:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SendbirdChat(cm)markAsDeliveredWithRemoteNotificationPayload:completionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"markAsDeliveredWithRemoteNotificationPayload:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat":{"role":"symbol","title":"SendbirdChat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendbirdChat"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":" is the core class for Sendbird. This class is singletone instance which is initialized by Application ID."},{"type":"text","text":" "},{"type":"text","text":"This class provides the methods for overall operations. The methods include "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" registration for receiving events"},{"type":"text","text":" "},{"type":"text","text":"that are related to channels, "},{"type":"codeVoice","code":"ConnectionDelegate"},{"type":"text","text":" for managing the connection status, updating the current user’s information,"},{"type":"text","text":" "},{"type":"text","text":"registration for APNS push notification and blocking other users."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendbirdChat"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat/markAsDelivered(remoteNotificationPayload:completionHandler:)":{"role":"symbol","title":"markAsDelivered(remoteNotificationPayload:completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markAsDelivered"},{"kind":"text","text":"("},{"kind":"externalParam","text":"remoteNotificationPayload"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Marks as delivered with the payload of the remote notification."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/markAsDelivered(remoteNotificationPayload:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"markAsDeliveredWithRemoteNotificationPayload:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat\/markasdelivered(remotenotificationpayload:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBErrorHandler":{"role":"symbol","title":"SBErrorHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBErrorHandler"}],"abstract":[{"type":"text","text":"Error handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBErrorHandler"}],"url":"\/documentation\/sendbirdchatsdk\/sberrorhandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"markAsDeliveredWithRemoteNotificationPayload:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"markAsDeliveredWithRemoteNotificationPayload:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"markAsDeliveredWithRemoteNotificationPayload:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"remoteNotificationPayload"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/title","value":"SendbirdChat"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/fragments","value":[{"kind":"identifier","text":"SendbirdChat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1markAsDelivered(remoteNotificationPayload:completionHandler:)\/title","value":"markAsDeliveredWithRemoteNotificationPayload:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1markAsDelivered(remoteNotificationPayload:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"markAsDeliveredWithRemoteNotificationPayload:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}