{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLogLevel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDLogLevel","text":"LogLevel"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"logLevel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Log level."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/setloglevel(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchat\/setloglevel(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/setLogLevel(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the log level. The log level is defined by "},{"type":"codeVoice","code":"LogLevel"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLogLevel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDLogLevel"},{"kind":"text","text":")"}],"title":"setLogLevel(_:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SendbirdChat(cm)setLogLevel:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"setLogLevel:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel":{"role":"symbol","title":"LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/sendbirdchatsdk\/loglevel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat/setLogLevel(_:)":{"role":"symbol","title":"setLogLevel(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLogLevel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDLogLevel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the log level. The log level is defined by "},{"type":"codeVoice","code":"LogLevel"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat\/setLogLevel(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLogLevel:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat\/setloglevel(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChat":{"role":"symbol","title":"SendbirdChat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendbirdChat"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":" is the core class for Sendbird. This class is singletone instance which is initialized by Application ID."},{"type":"text","text":" "},{"type":"text","text":"This class provides the methods for overall operations. The methods include "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" registration for receiving events"},{"type":"text","text":" "},{"type":"text","text":"that are related to channels, "},{"type":"codeVoice","code":"ConnectionDelegate"},{"type":"text","text":" for managing the connection status, updating the current user’s information,"},{"type":"text","text":" "},{"type":"text","text":"registration for APNS push notification and blocking other users."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendbirdChat"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchat"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"setLogLevel:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setLogLevel:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setLogLevel:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDLogLevel","text":"SBDLogLevel"},{"kind":"text","text":")"},{"kind":"internalParam","text":"logLevel"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel\/title","value":"SBDLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel\/fragments","value":[{"kind":"identifier","text":"SBDLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1setLogLevel(_:)\/title","value":"setLogLevel:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat~1setLogLevel(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setLogLevel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/title","value":"SendbirdChat"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChat\/fragments","value":[{"kind":"identifier","text":"SendbirdChat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}