{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scheduledAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An initialized scheduled user message params."}]}]},{"kind":"parameters","parameters":[{"name":"scheduledAt","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The time to send the message, in Unix milliseconds format. Term between current time and "},{"type":"codeVoice","code":"scheduledAt"},{"type":"text","text":" should be more than 5 minutes."}]}]},{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The message to text."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/scheduledusermessagecreateparams\/init(scheduledat:message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/scheduledusermessagecreateparams\/init(scheduledat:message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledUserMessageCreateParams\/init(scheduledAt:message:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes and returns a params object for creating a scheduled user message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scheduledAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"init(scheduledAt:message:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledUserMessageCreateParams(im)initWithScheduledAt:message:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithScheduledAt:message:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledUserMessageCreateParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledUserMessageCreateParams/init(scheduledAt:message:)":{"role":"symbol","title":"init(scheduledAt:message:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scheduledAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes and returns a params object for creating a scheduled user message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledUserMessageCreateParams\/init(scheduledAt:message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithScheduledAt:message:"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledusermessagecreateparams\/init(scheduledat:message:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledUserMessageCreateParams":{"role":"symbol","title":"ScheduledUserMessageCreateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledUserMessageCreateParams"}],"abstract":[{"type":"text","text":"An object that has parameters to create a scheduled message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledUserMessageCreateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledUserMessageCreateParams"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledusermessagecreateparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithScheduledAt:message:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithScheduledAt:message:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithScheduledAt:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"scheduledAt"},{"kind":"text","text":" "},{"kind":"identifier","text":"message:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledUserMessageCreateParams~1init(scheduledAt:message:)\/title","value":"initWithScheduledAt:message:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledUserMessageCreateParams~1init(scheduledAt:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithScheduledAt:message:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledUserMessageCreateParams\/title","value":"SBDScheduledUserMessageCreateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledUserMessageCreateParams\/fragments","value":[{"kind":"identifier","text":"SBDScheduledUserMessageCreateParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}