{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelMutedUsers"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/userlistquerytype\/openchannelmutedusers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/userlistquerytype\/openchannelmutedusers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/openChannelMutedUsers","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelMutedUsers"}],"title":"UserListQueryType.openChannelMutedUsers","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDUserListQueryType@SBDUserListQueryTypeOpenChannelMutedUsers","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelMutedUsers"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQueryType/openChannelMutedUsers":{"role":"symbol","title":"UserListQueryType.openChannelMutedUsers","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelMutedUsers"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/openChannelMutedUsers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelMutedUsers"}],"url":"\/documentation\/sendbirdchatsdk\/userlistquerytype\/openchannelmutedusers"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQueryType":{"role":"symbol","title":"UserListQueryType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserListQueryType"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserListQueryType"}],"url":"\/documentation\/sendbirdchatsdk\/userlistquerytype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDUserListQueryTypeOpenChannelMutedUsers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelMutedUsers"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelMutedUsers"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1openChannelMutedUsers\/title","value":"SBDUserListQueryTypeOpenChannelMutedUsers"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1openChannelMutedUsers\/fragments","value":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelMutedUsers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType\/title","value":"SBDUserListQueryType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType\/fragments","value":[{"kind":"identifier","text":"SBDUserListQueryType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}