{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelBannedUsers"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/userlistquerytype\/openchannelbannedusers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/userlistquerytype\/openchannelbannedusers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/openChannelBannedUsers","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelBannedUsers"}],"title":"UserListQueryType.openChannelBannedUsers","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDUserListQueryType@SBDUserListQueryTypeOpenChannelBannedUsers","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelBannedUsers"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQueryType":{"role":"symbol","title":"UserListQueryType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserListQueryType"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserListQueryType"}],"url":"\/documentation\/sendbirdchatsdk\/userlistquerytype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQueryType/openChannelBannedUsers":{"role":"symbol","title":"UserListQueryType.openChannelBannedUsers","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelBannedUsers"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/openChannelBannedUsers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelBannedUsers"}],"url":"\/documentation\/sendbirdchatsdk\/userlistquerytype\/openchannelbannedusers"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDUserListQueryTypeOpenChannelBannedUsers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelBannedUsers"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelBannedUsers"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType\/title","value":"SBDUserListQueryType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType\/fragments","value":[{"kind":"identifier","text":"SBDUserListQueryType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1openChannelBannedUsers\/title","value":"SBDUserListQueryTypeOpenChannelBannedUsers"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1openChannelBannedUsers\/fragments","value":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelBannedUsers"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}