{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"abilitiesToUnion"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions","text":"ScheduledStatusOptions"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/init(abilitiestounion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/init(abilitiestounion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/init(abilitiesToUnion:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithAbilitiesToUnion:"}],"role":"symbol","title":"init(abilitiesToUnion:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"abilitiesToUnion"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ScheduledStatusOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions"},{"kind":"text","text":"])"}],"symbolKind":"init","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions(im)initWithAbilitiesToUnion:","modules":[{"name":"SendbirdChatSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions/init(abilitiesToUnion:)":{"role":"symbol","title":"init(abilitiesToUnion:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"abilitiesToUnion"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ScheduledStatusOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/init(abilitiesToUnion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAbilitiesToUnion:"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/init(abilitiestounion:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions":{"role":"symbol","title":"ScheduledStatusOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledStatusOptions"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledStatusOptions"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithAbilitiesToUnion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAbilitiesToUnion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAbilitiesToUnion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBDScheduledStatusOptions *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"abilitiesToUnion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1init(abilitiesToUnion:)\/title","value":"initWithAbilitiesToUnion:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1init(abilitiesToUnion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAbilitiesToUnion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions\/title","value":"SBDScheduledStatusOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions\/fragments","value":[{"kind":"identifier","text":"SBDScheduledStatusOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}