{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new instance initialized with "},{"type":"codeVoice","code":"rawValue"},{"type":"text","text":" will be equivalent to this"},{"type":"text","text":" "},{"type":"text","text":"instance. For example:"}]},{"type":"codeListing","syntax":null,"code":["enum PaperSize: String {","    case A4, A5, Letter, Legal","}","","let selectedSize = PaperSize.Letter","print(selectedSize.rawValue)","\/\/ Prints \"Letter\"","","print(selectedSize == PaperSize(rawValue: selectedSize.rawValue)!)","\/\/ Prints \"true\""]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/rawvalue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/rawvalue"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/rawValue","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The corresponding value of the raw type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"rawValue","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions(py)rawValue","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"rawValue"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions/rawValue":{"role":"symbol","title":"rawValue","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The corresponding value of the raw type."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/rawValue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rawValue"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/rawvalue"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions":{"role":"symbol","title":"ScheduledStatusOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledStatusOptions"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledStatusOptions"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"rawValue"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rawValue"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"identifier","text":"rawValue"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1rawValue\/title","value":"rawValue"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1rawValue\/fragments","value":[{"kind":"identifier","text":"rawValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions\/title","value":"SBDScheduledStatusOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions\/fragments","value":[{"kind":"identifier","text":"SBDScheduledStatusOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}