{"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/participantlistqueryparams\/nscopying-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/participantlistqueryparams\/nscopying-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQueryParams\/NSCopying-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQueryParams\/copy(with:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"SendbirdChatSDK"}],"role":"collectionGroup","title":"NSCopying Implementations"},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQueryParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ParticipantListQueryParams":{"role":"symbol","title":"ParticipantListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ParticipantListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/participantlistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ParticipantListQueryParams/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQueryParams\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/sendbirdchatsdk\/participantlistqueryparams\/copy(with:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQueryParams\/copy(with:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQueryParams\/title","value":"SBDParticipantListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDParticipantListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQueryParams~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQueryParams~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}