{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appleCriticalAlertOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppleCriticalAlertOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDAppleCriticalAlertOptions","text":"AppleCriticalAlertOptions"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/scheduledbasemessageupdateparams\/applecriticalalertoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/scheduledbasemessageupdateparams\/applecriticalalertoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageUpdateParams\/appleCriticalAlertOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The push notification options for the Apple critical alert. The default value is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appleCriticalAlertOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AppleCriticalAlertOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDAppleCriticalAlertOptions"},{"kind":"text","text":"?"}],"title":"appleCriticalAlertOptions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledBaseMessageUpdateParams(py)appleCriticalAlertOptions","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"appleCriticalAlertOptions"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageUpdateParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppleCriticalAlertOptions":{"role":"symbol","title":"AppleCriticalAlertOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleCriticalAlertOptions"}],"abstract":[{"type":"text","text":"Represents the options for the Apple Critical Alert."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppleCriticalAlertOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppleCriticalAlertOptions"}],"url":"\/documentation\/sendbirdchatsdk\/applecriticalalertoptions"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledBaseMessageUpdateParams/appleCriticalAlertOptions":{"role":"symbol","title":"appleCriticalAlertOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appleCriticalAlertOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AppleCriticalAlertOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDAppleCriticalAlertOptions"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The push notification options for the Apple critical alert. The default value is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageUpdateParams\/appleCriticalAlertOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appleCriticalAlertOptions"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledbasemessageupdateparams\/applecriticalalertoptions"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledBaseMessageUpdateParams":{"role":"symbol","title":"ScheduledBaseMessageUpdateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledBaseMessageUpdateParams"}],"abstract":[{"type":"text","text":"A base class to update a scheduled message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageUpdateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledBaseMessageUpdateParams"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledbasemessageupdateparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"appleCriticalAlertOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"appleCriticalAlertOptions"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppleCriticalAlertOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDAppleCriticalAlertOptions","text":"SBDAppleCriticalAlertOptions"},{"kind":"text","text":" *"},{"kind":"identifier","text":"appleCriticalAlertOptions"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppleCriticalAlertOptions\/title","value":"SBDAppleCriticalAlertOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppleCriticalAlertOptions\/fragments","value":[{"kind":"identifier","text":"SBDAppleCriticalAlertOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageUpdateParams~1appleCriticalAlertOptions\/title","value":"appleCriticalAlertOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageUpdateParams~1appleCriticalAlertOptions\/fragments","value":[{"kind":"identifier","text":"appleCriticalAlertOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageUpdateParams\/title","value":"SBDScheduledBaseMessageUpdateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageUpdateParams\/fragments","value":[{"kind":"identifier","text":"SBDScheduledBaseMessageUpdateParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}