{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaArrays"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageMetaArray","text":"MessageMetaArray"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/scheduledbasemessageupdateparams\/metaarrays"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/scheduledbasemessageupdateparams\/metaarrays"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageUpdateParams\/metaArrays","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The meta arrays with keys and values."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaArrays"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MessageMetaArray","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageMetaArray"},{"kind":"text","text":"]?"}],"title":"metaArrays","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledBaseMessageUpdateParams(py)metaArrays","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"metaArrays"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageUpdateParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledBaseMessageUpdateParams":{"role":"symbol","title":"ScheduledBaseMessageUpdateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledBaseMessageUpdateParams"}],"abstract":[{"type":"text","text":"A base class to update a scheduled message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageUpdateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledBaseMessageUpdateParams"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledbasemessageupdateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledBaseMessageUpdateParams/metaArrays":{"role":"symbol","title":"metaArrays","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaArrays"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MessageMetaArray","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageMetaArray"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The meta arrays with keys and values."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageUpdateParams\/metaArrays","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metaArrays"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledbasemessageupdateparams\/metaarrays"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageMetaArray":{"role":"symbol","title":"MessageMetaArray","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageMetaArray"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MessageMetaArray"},{"type":"text","text":" instance has a string type of key and an array type of value."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageMetaArray"}],"url":"\/documentation\/sendbirdchatsdk\/messagemetaarray"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"metaArrays"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"metaArrays"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBDMessageMetaArray *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *"},{"kind":"identifier","text":"metaArrays"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageUpdateParams\/title","value":"SBDScheduledBaseMessageUpdateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageUpdateParams\/fragments","value":[{"kind":"identifier","text":"SBDScheduledBaseMessageUpdateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageUpdateParams~1metaArrays\/title","value":"metaArrays"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageUpdateParams~1metaArrays\/fragments","value":[{"kind":"identifier","text":"metaArrays"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray\/title","value":"SBDMessageMetaArray"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray\/fragments","value":[{"kind":"identifier","text":"SBDMessageMetaArray"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}