{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"exactMatch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagesearchqueryparams\/exactmatch"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagesearchqueryparams\/exactmatch"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryParams\/exactMatch","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Should search as a complete, exact phrase. Default is "},{"type":"codeVoice","code":"false"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"exactMatch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"exactMatch","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageSearchQueryParams(py)exactMatch","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"exactMatch"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQueryParams/exactMatch":{"role":"symbol","title":"exactMatch","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"exactMatch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Should search as a complete, exact phrase. Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryParams\/exactMatch","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"exactMatch"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchqueryparams\/exactmatch"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQueryParams":{"role":"symbol","title":"MessageSearchQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSearchQueryParams"}],"abstract":[{"type":"text","text":"Message search query builder"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageSearchQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchqueryparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"exactMatch"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"exactMatch"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"identifier","text":"exactMatch"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryParams~1exactMatch\/title","value":"exactMatch"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryParams~1exactMatch\/fragments","value":[{"kind":"identifier","text":"exactMatch"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryParams\/title","value":"SBDMessageSearchQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDMessageSearchQueryParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}