{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"builder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageSearchQueryParams","text":"MessageSearchQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An initialized params object."}]}]},{"kind":"parameters","parameters":[{"name":"builder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The builder closure."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagesearchqueryparams\/init(builder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagesearchqueryparams\/init(builder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryParams\/init(builder:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes and returns a newly allocated params object that mutated through builder closure."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"builder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MessageSearchQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageSearchQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"init(builder:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageSearchQueryParams(im)initWithBuilder:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBuilder:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQueryParams/init(builder:)":{"role":"symbol","title":"init(builder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"builder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MessageSearchQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageSearchQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes and returns a newly allocated params object that mutated through builder closure."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryParams\/init(builder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBuilder:"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchqueryparams\/init(builder:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQueryParams":{"role":"symbol","title":"MessageSearchQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSearchQueryParams"}],"abstract":[{"type":"text","text":"Message search query builder"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageSearchQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithBuilder:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBuilder:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBuilder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDMessageSearchQueryParams *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDMessageSearchQueryParams)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"builder"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryParams~1init(builder:)\/title","value":"initWithBuilder:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryParams~1init(builder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBuilder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryParams\/title","value":"SBDMessageSearchQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDMessageSearchQueryParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}