{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"file"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagetypefilter\/file"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagetypefilter\/file"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/file","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Filter of file message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"file"}],"title":"MessageTypeFilter.file","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDMessageTypeFilter@SBDMessageTypeFilterFile","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDMessageTypeFilterFile"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageTypeFilter/file":{"role":"symbol","title":"MessageTypeFilter.file","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"file"}],"abstract":[{"type":"text","text":"Filter of file message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/file","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageTypeFilterFile"}],"url":"\/documentation\/sendbirdchatsdk\/messagetypefilter\/file"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageTypeFilter":{"role":"symbol","title":"MessageTypeFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageTypeFilter"}],"abstract":[{"type":"text","text":"Message type for filtering"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageTypeFilter"}],"url":"\/documentation\/sendbirdchatsdk\/messagetypefilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageTypeFilterFile"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageTypeFilterFile"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDMessageTypeFilterFile"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter~1file\/title","value":"SBDMessageTypeFilterFile"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter~1file\/fragments","value":[{"kind":"identifier","text":"SBDMessageTypeFilterFile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter\/title","value":"SBDMessageTypeFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter\/fragments","value":[{"kind":"identifier","text":"SBDMessageTypeFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}