{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel","text":"GroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidLeave"},{"kind":"text","text":" "},{"kind":"internalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser","text":"User"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"channel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The group channel."}]}]},{"name":"user","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The member left from the channel."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchanneldelegate\/channel(_:userdidleave:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchanneldelegate\/channel(_:userdidleave:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channel(_:userDidLeave:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A callback when current member left from the group channel."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"channel:userDidLeave:"}],"role":"symbol","title":"channel(_:userDidLeave:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidLeave"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDGroupChannelDelegate(im)channel:userDidLeave:","required":true,"modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate/channel(_:userDidLeave:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:userDidLeave:"}],"role":"symbol","title":"channel(_:userDidLeave:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidLeave"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when current member left from the group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channel(_:userDidLeave:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate\/channel(_:userdidleave:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel":{"role":"symbol","title":"GroupChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" class represents a group channel which is a private chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate":{"role":"symbol","title":"GroupChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User":{"role":"symbol","title":"User","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"User"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"User"},{"type":"text","text":" class represents a user. The user is identified by the "},{"type":"codeVoice","code":"userID"},{"type":"text","text":", so the "},{"type":"codeVoice","code":"userID"},{"type":"text","text":" has"},{"type":"text","text":" "},{"type":"text","text":"to be unique. The "},{"type":"codeVoice","code":"userID"},{"type":"text","text":", "},{"type":"codeVoice","code":"nickname"},{"type":"text","text":" and "},{"type":"codeVoice","code":"profileURL"},{"type":"text","text":" are valid in every "},{"type":"codeVoice","code":"User"},{"type":"text","text":" "},{"type":"text","text":"instance, however the "},{"type":"codeVoice","code":"connectionStatus"},{"type":"text","text":" and "},{"type":"codeVoice","code":"lastSeenAt"},{"type":"text","text":" is valid in "},{"type":"codeVoice","code":"User"},{"type":"text","text":" instance"},{"type":"text","text":" "},{"type":"text","text":"from "},{"type":"codeVoice","code":"UserListQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"User"}],"url":"\/documentation\/sendbirdchatsdk\/user"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"channel:userDidLeave:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userDidLeave:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"channel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel","text":"SBDGroupChannel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channel"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidLeave:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser","text":"SBDUser"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"user"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channel(_:userDidLeave:)\/title","value":"channel:userDidLeave:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channel(_:userDidLeave:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userDidLeave:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/title","value":"SBDGroupChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate\/title","value":"SBDGroupChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User\/title","value":"SBDUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User\/fragments","value":[{"kind":"identifier","text":"SBDUser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}