{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidUpdateReadStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel","text":"GroupChannel"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"channel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The group channel where the read status updated."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchanneldelegate\/channeldidupdatereadstatus(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchanneldelegate\/channeldidupdatereadstatus(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelDidUpdateReadStatus(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A callback when read status updated."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"channelDidUpdateReadStatus:"}],"role":"symbol","title":"channelDidUpdateReadStatus(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidUpdateReadStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDGroupChannelDelegate(im)channelDidUpdateReadStatus:","required":true,"modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate/channelDidUpdateReadStatus(_:)":{"navigatorTitle":[{"kind":"identifier","text":"channelDidUpdateReadStatus:"}],"role":"symbol","title":"channelDidUpdateReadStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidUpdateReadStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when read status updated."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelDidUpdateReadStatus(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate\/channeldidupdatereadstatus(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate":{"role":"symbol","title":"GroupChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel":{"role":"symbol","title":"GroupChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" class represents a group channel which is a private chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"channelDidUpdateReadStatus:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidUpdateReadStatus:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"channelDidUpdateReadStatus:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel","text":"SBDGroupChannel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channel"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channelDidUpdateReadStatus(_:)\/title","value":"channelDidUpdateReadStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channelDidUpdateReadStatus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidUpdateReadStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate\/title","value":"SBDGroupChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/title","value":"SBDGroupChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}