{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagerequeststate\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRequestState\/init","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageRequestState(im)init","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRequestState"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageRequestState":{"role":"symbol","title":"MessageRequestState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageRequestState"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRequestState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageRequestState"}],"url":"\/documentation\/sendbirdchatsdk\/messagerequeststate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageRequestState/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRequestState\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirdchatsdk\/messagerequeststate\/init"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRequestState\/title","value":"SBDMessageRequestState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRequestState\/fragments","value":[{"kind":"identifier","text":"SBDMessageRequestState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}