{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel","text":"BaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userWasBanned"},{"kind":"text","text":" "},{"kind":"internalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser","text":"User"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"channel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The channel."}]}]},{"name":"user","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user who was banned."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagecollection\/channel(_:userwasbanned:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagecollection\/channel(_:userwasbanned:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channel(_:userWasBanned:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A callback when a user was banned in the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userWasBanned"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"title":"channel(_:userWasBanned:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDMessageCollection(im)channel:userWasBanned:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"channel:userWasBanned:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/BaseChannelDelegate-Implementations"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User":{"role":"symbol","title":"User","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"User"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"User"},{"type":"text","text":" class represents a user. The user is identified by the "},{"type":"codeVoice","code":"userID"},{"type":"text","text":", so the "},{"type":"codeVoice","code":"userID"},{"type":"text","text":" has"},{"type":"text","text":" "},{"type":"text","text":"to be unique. The "},{"type":"codeVoice","code":"userID"},{"type":"text","text":", "},{"type":"codeVoice","code":"nickname"},{"type":"text","text":" and "},{"type":"codeVoice","code":"profileURL"},{"type":"text","text":" are valid in every "},{"type":"codeVoice","code":"User"},{"type":"text","text":" "},{"type":"text","text":"instance, however the "},{"type":"codeVoice","code":"connectionStatus"},{"type":"text","text":" and "},{"type":"codeVoice","code":"lastSeenAt"},{"type":"text","text":" is valid in "},{"type":"codeVoice","code":"User"},{"type":"text","text":" instance"},{"type":"text","text":" "},{"type":"text","text":"from "},{"type":"codeVoice","code":"UserListQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"User"}],"url":"\/documentation\/sendbirdchatsdk\/user"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/BaseChannelDelegate-Implementations":{"role":"collectionGroup","title":"BaseChannelDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/BaseChannelDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagecollection\/basechanneldelegate-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/channel(_:userWasBanned:)":{"role":"symbol","title":"channel(_:userWasBanned:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userWasBanned"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a user was banned in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channel(_:userWasBanned:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:userWasBanned:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/channel(_:userwasbanned:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection":{"role":"symbol","title":"MessageCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollection"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"channel:userWasBanned:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userWasBanned:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"channel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel","text":"SBDBaseChannel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channel"},{"kind":"text","text":" "},{"kind":"identifier","text":"userWasBanned:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser","text":"SBDUser"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"user"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User\/title","value":"SBDUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User\/fragments","value":[{"kind":"identifier","text":"SBDUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channel(_:userWasBanned:)\/title","value":"channel:userWasBanned:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channel(_:userWasBanned:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userWasBanned:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/title","value":"SBDMessageCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}