{"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagecollection\/groupchanneldelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagecollection\/groupchanneldelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/GroupChannelDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channel(_:didDeclineInvitation:inviter:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channel(_:didReceiveInvitation:inviter:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channel(_:userDidJoin:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channel(_:userDidLeave:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channelDidChangeMemberCount(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channelDidUpdateDeliveryStatus(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channelDidUpdateReadStatus(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channelDidUpdateTypingStatus(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channelWasHidden(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"SendbirdChatSDK"}],"role":"collectionGroup","title":"GroupChannelDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/channelWasHidden(_:)":{"role":"symbol","title":"channelWasHidden(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelWasHidden"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when the channel was hidden on the other device or by Platform API."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channelWasHidden(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelWasHidden:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/channelwashidden(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection":{"role":"symbol","title":"MessageCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollection"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/channelDidChangeMemberCount(_:)":{"role":"symbol","title":"channelDidChangeMemberCount(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidChangeMemberCount"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"A callback when member count has been changed for broadcast channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channelDidChangeMemberCount(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelDidChangeMemberCount:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/channeldidchangemembercount(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/channel(_:didReceiveInvitation:inviter:)":{"role":"symbol","title":"channel(_:didReceiveInvitation:inviter:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveInvitation"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"inviter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"A callback when users are invited by inviter."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channel(_:didReceiveInvitation:inviter:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:didReceiveInvitation:inviter:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/channel(_:didreceiveinvitation:inviter:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/channelDidUpdateDeliveryStatus(_:)":{"role":"symbol","title":"channelDidUpdateDeliveryStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidUpdateDeliveryStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when delivery status updated."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channelDidUpdateDeliveryStatus(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelDidUpdateDeliveryStatus:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/channeldidupdatedeliverystatus(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/channel(_:didDeclineInvitation:inviter:)":{"role":"symbol","title":"channel(_:didDeclineInvitation:inviter:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDeclineInvitation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inviter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"A callback when user declined the invitation."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channel(_:didDeclineInvitation:inviter:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:didDeclineInvitation:inviter:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/channel(_:diddeclineinvitation:inviter:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/channelDidUpdateReadStatus(_:)":{"role":"symbol","title":"channelDidUpdateReadStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidUpdateReadStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when read status updated."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channelDidUpdateReadStatus(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelDidUpdateReadStatus:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/channeldidupdatereadstatus(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/channel(_:userDidLeave:)":{"role":"symbol","title":"channel(_:userDidLeave:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidLeave"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when current member left from the group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channel(_:userDidLeave:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:userDidLeave:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/channel(_:userdidleave:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/channelDidUpdateTypingStatus(_:)":{"role":"symbol","title":"channelDidUpdateTypingStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidUpdateTypingStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when user sends typing status."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channelDidUpdateTypingStatus(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelDidUpdateTypingStatus:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/channeldidupdatetypingstatus(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/channel(_:userDidJoin:)":{"role":"symbol","title":"channel(_:userDidJoin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidJoin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when new member joined to the group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channel(_:userDidJoin:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:userDidJoin:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/channel(_:userdidjoin:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channel(_:didDeclineInvitation:inviter:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channel(_:didReceiveInvitation:inviter:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channel(_:userDidJoin:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channel(_:userDidLeave:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channelDidChangeMemberCount(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channelDidUpdateDeliveryStatus(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channelDidUpdateReadStatus(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channelDidUpdateTypingStatus(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/channelWasHidden(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channelWasHidden(_:)\/title","value":"channelWasHidden:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channelWasHidden(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelWasHidden:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/title","value":"SBDMessageCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channelDidChangeMemberCount(_:)\/title","value":"channelDidChangeMemberCount:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channelDidChangeMemberCount(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidChangeMemberCount:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channel(_:didReceiveInvitation:inviter:)\/title","value":"channel:didReceiveInvitation:inviter:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channel(_:didReceiveInvitation:inviter:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didReceiveInvitation:inviter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channelDidUpdateDeliveryStatus(_:)\/title","value":"channelDidUpdateDeliveryStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channelDidUpdateDeliveryStatus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidUpdateDeliveryStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channel(_:didDeclineInvitation:inviter:)\/title","value":"channel:didDeclineInvitation:inviter:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channel(_:didDeclineInvitation:inviter:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didDeclineInvitation:inviter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channelDidUpdateReadStatus(_:)\/title","value":"channelDidUpdateReadStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channelDidUpdateReadStatus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidUpdateReadStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channel(_:userDidLeave:)\/title","value":"channel:userDidLeave:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channel(_:userDidLeave:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userDidLeave:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channelDidUpdateTypingStatus(_:)\/title","value":"channelDidUpdateTypingStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channelDidUpdateTypingStatus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidUpdateTypingStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channel(_:userDidJoin:)\/title","value":"channel:userDidJoin:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1channel(_:userDidJoin:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userDidJoin:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}