{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera","text":"SBErrorHandler"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter completionHandler The callback to call when the method is complete."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"error"},{"type":"text","text":" will be returned when the removing failed messages failed."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagecollection\/removeallfailed(completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagecollection\/removeallfailed(completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/removeAllFailed(completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Removes all failed messages."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"title":"removeAllFailed(completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection(im)removeAllFailedWithCompletionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"removeAllFailedWithCompletionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection":{"role":"symbol","title":"MessageCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollection"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBErrorHandler":{"role":"symbol","title":"SBErrorHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBErrorHandler"}],"abstract":[{"type":"text","text":"Error handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBErrorHandler"}],"url":"\/documentation\/sendbirdchatsdk\/sberrorhandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/removeAllFailed(completionHandler:)":{"role":"symbol","title":"removeAllFailed(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Removes all failed messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/removeAllFailed(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeAllFailedWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/removeallfailed(completionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeAllFailedWithCompletionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAllFailedWithCompletionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeAllFailedWithCompletionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/title","value":"SBDMessageCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1removeAllFailed(completionHandler:)\/title","value":"removeAllFailedWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1removeAllFailed(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAllFailedWithCompletionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}