{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage","text":"BaseMessage"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRequestIDsHandler","preciseIdentifier":"s:15SendbirdChatSDK24MessageRequestIDsHandlera","text":"MessageRequestIDsHandler"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameters messages The failed messages to be removed from DB."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter completionHandler The callback to call when the method is complete."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"error"},{"type":"text","text":" will be returned when the removing failed messages failed."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagecollection\/removefailed(messages:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagecollection\/removefailed(messages:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/removeFailed(messages:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Removes failed messages from DB."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageRequestIDsHandler","preciseIdentifier":"s:15SendbirdChatSDK24MessageRequestIDsHandlera"},{"kind":"text","text":"?)"}],"title":"removeFailed(messages:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection(im)removeFailedWithMessages:completionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"removeFailedWithMessages:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageRequestIDsHandler":{"role":"symbol","title":"MessageRequestIDsHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageRequestIDsHandler"}],"abstract":[{"type":"text","text":"Message request IDs handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRequestIDsHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageRequestIDsHandler"}],"url":"\/documentation\/sendbirdchatsdk\/messagerequestidshandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/removeFailed(messages:completionHandler:)":{"role":"symbol","title":"removeFailed(messages:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageRequestIDsHandler","preciseIdentifier":"s:15SendbirdChatSDK24MessageRequestIDsHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Removes failed messages from DB."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/removeFailed(messages:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeFailedWithMessages:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/removefailed(messages:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection":{"role":"symbol","title":"MessageCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollection"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage":{"role":"symbol","title":"BaseMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessage"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":" class represents the base message which is generated by a user or an admin."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":", the "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"AdminMessage"},{"type":"text","text":" are derived from this class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessage"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeFailedWithMessages:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeFailedWithMessages:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeFailedWithMessages:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBDBaseMessage *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messages"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<NSString *> *, SBError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1removeFailed(messages:completionHandler:)\/title","value":"removeFailedWithMessages:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1removeFailed(messages:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeFailedWithMessages:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/title","value":"SBDMessageCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/title","value":"SBDBaseMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}