{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCollection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"initPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionInitPolicy","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageCollectionInitPolicy","text":"MessageCollectionInitPolicy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cacheResultHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListHandler","preciseIdentifier":"s:15SendbirdChatSDK18MessageListHandlera","text":"MessageListHandler"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"apiResultHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListHandler","preciseIdentifier":"s:15SendbirdChatSDK18MessageListHandlera","text":"MessageListHandler"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"initPolicy","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The policy for the message collection."}]}]},{"name":"cacheResultHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback to call when the messages are loaded from the cache."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"messages"},{"type":"text","text":" is the messages that are loaded from the cache. The "},{"type":"codeVoice","code":"error"},{"type":"text","text":" will be returned when the loading message failed."}]}]},{"name":"apiResultHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback to call when the messages are loaded from the server."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"messages"},{"type":"text","text":" is the messages that are loaded from the server. The "},{"type":"codeVoice","code":"error"},{"type":"text","text":" will be returned when the loading message failed."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagecollection\/startcollection(initpolicy:cacheresulthandler:apiresulthandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagecollection\/startcollection(initpolicy:cacheresulthandler:apiresulthandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/startCollection(initPolicy:cacheResultHandler:apiResultHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts the message collection with the policy. The result of the"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCollection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"initPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageCollectionInitPolicy","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageCollectionInitPolicy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cacheResultHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListHandler","preciseIdentifier":"s:15SendbirdChatSDK18MessageListHandlera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"apiResultHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListHandler","preciseIdentifier":"s:15SendbirdChatSDK18MessageListHandlera"},{"kind":"text","text":"?)"}],"title":"startCollection(initPolicy:cacheResultHandler:apiResultHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection(im)startCollectionWithInitPolicy:cacheResultHandler:apiResultHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"startCollectionWithInitPolicy:cacheResultHandler:apiResultHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionInitPolicy":{"role":"symbol","title":"MessageCollectionInitPolicy","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollectionInitPolicy"}],"abstract":[{"type":"text","text":"The policy for the message collection initialization."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionInitPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollectionInitPolicy"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollectioninitpolicy"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection":{"role":"symbol","title":"MessageCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollection"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/startCollection(initPolicy:cacheResultHandler:apiResultHandler:)":{"role":"symbol","title":"startCollection(initPolicy:cacheResultHandler:apiResultHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCollection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"initPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageCollectionInitPolicy","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageCollectionInitPolicy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cacheResultHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListHandler","preciseIdentifier":"s:15SendbirdChatSDK18MessageListHandlera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"apiResultHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListHandler","preciseIdentifier":"s:15SendbirdChatSDK18MessageListHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Starts the message collection with the policy. The result of the"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/startCollection(initPolicy:cacheResultHandler:apiResultHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCollectionWithInitPolicy:cacheResultHandler:apiResultHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/startcollection(initpolicy:cacheresulthandler:apiresulthandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListHandler":{"role":"symbol","title":"MessageListHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListHandler"}],"abstract":[{"type":"text","text":"Message List handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageListHandler"}],"url":"\/documentation\/sendbirdchatsdk\/messagelisthandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startCollectionWithInitPolicy:cacheResultHandler:apiResultHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCollectionWithInitPolicy:cacheResultHandler:apiResultHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startCollectionWithInitPolicy:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionInitPolicy","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageCollectionInitPolicy","text":"SBDMessageCollectionInitPolicy"},{"kind":"text","text":")"},{"kind":"internalParam","text":"initPolicy"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheResultHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<SBDBaseMessage *> *, SBError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cacheResultHandler"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiResultHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<SBDBaseMessage *> *, SBError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"apiResultHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionInitPolicy\/title","value":"SBDMessageCollectionInitPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionInitPolicy\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollectionInitPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/title","value":"SBDMessageCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1startCollection(initPolicy:cacheResultHandler:apiResultHandler:)\/title","value":"startCollectionWithInitPolicy:cacheResultHandler:apiResultHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1startCollection(initPolicy:cacheResultHandler:apiResultHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCollectionWithInitPolicy:cacheResultHandler:apiResultHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}