{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restrictionInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDRestrictionInfo","text":"RestrictionInfo"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Since 3.0.236"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/member\/restrictioninfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/member\/restrictioninfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/restrictionInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Restriction information of a muted member."},{"type":"text","text":" "},{"type":"text","text":"This property is nil for an unmuted member."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restrictionInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RestrictionInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDRestrictionInfo"},{"kind":"text","text":"?"}],"title":"restrictionInfo","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMember(py)restrictionInfo","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"restrictionInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member":{"role":"symbol","title":"Member","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Member"}],"abstract":[{"type":"text","text":"Represents a member in "},{"type":"codeVoice","code":"GroupChannel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Member"}],"url":"\/documentation\/sendbirdchatsdk\/member"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member/restrictionInfo":{"role":"symbol","title":"restrictionInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restrictionInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RestrictionInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDRestrictionInfo"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Restriction information of a muted member."},{"type":"text","text":" "},{"type":"text","text":"This property is nil for an unmuted member."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/restrictionInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"restrictionInfo"}],"url":"\/documentation\/sendbirdchatsdk\/member\/restrictioninfo"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionInfo":{"role":"symbol","title":"RestrictionInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictionInfo"}],"abstract":[{"type":"text","text":"An object contains information about restriction"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RestrictionInfo"}],"url":"\/documentation\/sendbirdchatsdk\/restrictioninfo"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"restrictionInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"restrictionInfo"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDRestrictionInfo","text":"SBDRestrictionInfo"},{"kind":"text","text":" *"},{"kind":"identifier","text":"restrictionInfo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member\/title","value":"SBDMember"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member\/fragments","value":[{"kind":"identifier","text":"SBDMember"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1restrictionInfo\/title","value":"restrictionInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1restrictionInfo\/fragments","value":[{"kind":"identifier","text":"restrictionInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionInfo\/title","value":"SBDRestrictionInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionInfo\/fragments","value":[{"kind":"identifier","text":"SBDRestrictionInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}