{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"role"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDRole","text":"Role"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.174"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/member\/role"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/member\/role"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/role","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The role of current user in the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"role"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Role","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDRole"}],"title":"role","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMember(py)role","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"role"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member/role":{"role":"symbol","title":"role","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"role"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Role","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDRole"}],"abstract":[{"type":"text","text":"The role of current user in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/role","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"role"}],"url":"\/documentation\/sendbirdchatsdk\/member\/role"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Role":{"role":"symbol","title":"Role","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Role"}],"abstract":[{"type":"text","text":"The users’s role which gives different behaviors, permisions to user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Role"}],"url":"\/documentation\/sendbirdchatsdk\/role"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member":{"role":"symbol","title":"Member","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Member"}],"abstract":[{"type":"text","text":"Represents a member in "},{"type":"codeVoice","code":"GroupChannel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Member"}],"url":"\/documentation\/sendbirdchatsdk\/member"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"role"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"role"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDRole","text":"SBDRole"},{"kind":"identifier","text":"role"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1role\/title","value":"role"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1role\/fragments","value":[{"kind":"identifier","text":"role"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Role\/title","value":"SBDRole"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Role\/fragments","value":[{"kind":"identifier","text":"SBDRole"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member\/title","value":"SBDMember"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member\/fragments","value":[{"kind":"identifier","text":"SBDMember"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}