{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberState","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberState","text":"MemberState"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/member\/state"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/member\/state"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/state","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The state for invitation. The values of the property are "},{"type":"codeVoice","code":"invited"},{"type":"text","text":" and "},{"type":"codeVoice","code":"joined"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"invited"},{"type":"text","text":" means that the user doesn’t accept the invitation yet and the "},{"type":"codeVoice","code":"joined"},{"type":"text","text":" "},{"type":"text","text":"means that the user accepted the invitation manually or automatically."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MemberState","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberState"}],"title":"state","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMember(py)state","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"state"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member":{"role":"symbol","title":"Member","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Member"}],"abstract":[{"type":"text","text":"Represents a member in "},{"type":"codeVoice","code":"GroupChannel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Member"}],"url":"\/documentation\/sendbirdchatsdk\/member"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberState":{"role":"symbol","title":"MemberState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberState"}],"abstract":[{"type":"text","text":"Member state in group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberState"}],"url":"\/documentation\/sendbirdchatsdk\/memberstate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member/state":{"role":"symbol","title":"state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MemberState","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberState"}],"abstract":[{"type":"text","text":"The state for invitation. The values of the property are "},{"type":"codeVoice","code":"invited"},{"type":"text","text":" and "},{"type":"codeVoice","code":"joined"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"invited"},{"type":"text","text":" means that the user doesn’t accept the invitation yet and the "},{"type":"codeVoice","code":"joined"},{"type":"text","text":" "},{"type":"text","text":"means that the user accepted the invitation manually or automatically."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/state","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"state"}],"url":"\/documentation\/sendbirdchatsdk\/member\/state"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"state"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"state"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberState","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberState","text":"SBDMemberState"},{"kind":"identifier","text":"state"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member\/title","value":"SBDMember"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member\/fragments","value":[{"kind":"identifier","text":"SBDMember"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberState\/title","value":"SBDMemberState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberState\/fragments","value":[{"kind":"identifier","text":"SBDMemberState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1state\/title","value":"state"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1state\/fragments","value":[{"kind":"identifier","text":"state"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}