{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The message to text."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/usermessageupdateparams\/init(message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/usermessageupdateparams\/init(message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/init(message:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes an instance of a user message params with message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(message:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessageUpdateParams(im)initWithMessage:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMessage:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageUpdateParams":{"role":"symbol","title":"UserMessageUpdateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMessageUpdateParams"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UserMessageUpdateParams"},{"type":"text","text":" class is used to send a user message in "},{"type":"codeVoice","code":"BaseChannel"},{"type":"text","text":". This is a child class of "},{"type":"codeVoice","code":"BaseMessageUpdateParams"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserMessageUpdateParams"}],"url":"\/documentation\/sendbirdchatsdk\/usermessageupdateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageUpdateParams/init(message:)":{"role":"symbol","title":"init(message:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initializes an instance of a user message params with message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/init(message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMessage:"}],"url":"\/documentation\/sendbirdchatsdk\/usermessageupdateparams\/init(message:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithMessage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMessage:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams\/title","value":"SBDUserMessageUpdateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams\/fragments","value":[{"kind":"identifier","text":"SBDUserMessageUpdateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams~1init(message:)\/title","value":"initWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams~1init(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMessage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}