{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/unreadchannelfilter\/all"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/unreadchannelfilter\/all"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/all","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Shows all my group channels."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"title":"UnreadChannelFilter.all","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDUnreadChannelFilter@SBDUnreadChannelFilterAll","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDUnreadChannelFilterAll"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadChannelFilter/all":{"role":"symbol","title":"UnreadChannelFilter.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[{"type":"text","text":"Shows all my group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUnreadChannelFilterAll"}],"url":"\/documentation\/sendbirdchatsdk\/unreadchannelfilter\/all"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadChannelFilter":{"role":"symbol","title":"UnreadChannelFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadChannelFilter"}],"abstract":[{"type":"text","text":"The enum type to filter my group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnreadChannelFilter"}],"url":"\/documentation\/sendbirdchatsdk\/unreadchannelfilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDUnreadChannelFilterAll"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUnreadChannelFilterAll"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDUnreadChannelFilterAll"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadChannelFilter~1all\/title","value":"SBDUnreadChannelFilterAll"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadChannelFilter~1all\/fragments","value":[{"kind":"identifier","text":"SBDUnreadChannelFilterAll"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadChannelFilter\/title","value":"SBDUnreadChannelFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadChannelFilter\/fragments","value":[{"kind":"identifier","text":"SBDUnreadChannelFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}