{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadMessage"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/unreadchannelfilter\/unreadmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/unreadchannelfilter\/unreadmessage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/unreadMessage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Shows my group channels that have unread messages."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadMessage"}],"title":"UnreadChannelFilter.unreadMessage","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDUnreadChannelFilter@SBDUnreadChannelFilterUnreadMessage","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDUnreadChannelFilterUnreadMessage"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadChannelFilter":{"role":"symbol","title":"UnreadChannelFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadChannelFilter"}],"abstract":[{"type":"text","text":"The enum type to filter my group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnreadChannelFilter"}],"url":"\/documentation\/sendbirdchatsdk\/unreadchannelfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadChannelFilter/unreadMessage":{"role":"symbol","title":"UnreadChannelFilter.unreadMessage","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadMessage"}],"abstract":[{"type":"text","text":"Shows my group channels that have unread messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/unreadMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUnreadChannelFilterUnreadMessage"}],"url":"\/documentation\/sendbirdchatsdk\/unreadchannelfilter\/unreadmessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDUnreadChannelFilterUnreadMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUnreadChannelFilterUnreadMessage"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDUnreadChannelFilterUnreadMessage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadChannelFilter\/title","value":"SBDUnreadChannelFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadChannelFilter\/fragments","value":[{"kind":"identifier","text":"SBDUnreadChannelFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadChannelFilter~1unreadMessage\/title","value":"SBDUnreadChannelFilterUnreadMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadChannelFilter~1unreadMessage\/fragments","value":[{"kind":"identifier","text":"SBDUnreadChannelFilterUnreadMessage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}