{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nicknameAlphabetical"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/memberlistorder\/nicknamealphabetical"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/memberlistorder\/nicknamealphabetical"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/nicknameAlphabetical","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nicknameAlphabetical"}],"title":"MemberListOrder.nicknameAlphabetical","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDMemberListOrder@SBDMemberListOrderNicknameAlphabetical","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDMemberListOrderNicknameAlphabetical"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListOrder":{"role":"symbol","title":"MemberListOrder","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListOrder"}],"abstract":[{"type":"text","text":"The order type for member list query."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListOrder"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistorder"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListOrder/nicknameAlphabetical":{"role":"symbol","title":"MemberListOrder.nicknameAlphabetical","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nicknameAlphabetical"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/nicknameAlphabetical","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMemberListOrderNicknameAlphabetical"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistorder\/nicknamealphabetical"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDMemberListOrderNicknameAlphabetical"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMemberListOrderNicknameAlphabetical"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDMemberListOrderNicknameAlphabetical"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder\/title","value":"SBDMemberListOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder\/fragments","value":[{"kind":"identifier","text":"SBDMemberListOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder~1nicknameAlphabetical\/title","value":"SBDMemberListOrderNicknameAlphabetical"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder~1nicknameAlphabetical\/fragments","value":[{"kind":"identifier","text":"SBDMemberListOrderNicknameAlphabetical"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}