{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatorThenMemberNicknameAlphabetical"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/memberlistorder\/operatorthenmembernicknamealphabetical"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/memberlistorder\/operatorthenmembernicknamealphabetical"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/operatorThenMemberNicknameAlphabetical","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatorThenMemberNicknameAlphabetical"}],"title":"MemberListOrder.operatorThenMemberNicknameAlphabetical","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDMemberListOrder@SBDMemberListOrderOperatorThenMemberNicknameAlphabetical","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDMemberListOrderOperatorThenMemberNicknameAlphabetical"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListOrder/operatorThenMemberNicknameAlphabetical":{"role":"symbol","title":"MemberListOrder.operatorThenMemberNicknameAlphabetical","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatorThenMemberNicknameAlphabetical"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/operatorThenMemberNicknameAlphabetical","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMemberListOrderOperatorThenMemberNicknameAlphabetical"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistorder\/operatorthenmembernicknamealphabetical"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListOrder":{"role":"symbol","title":"MemberListOrder","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListOrder"}],"abstract":[{"type":"text","text":"The order type for member list query."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListOrder"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistorder"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDMemberListOrderOperatorThenMemberNicknameAlphabetical"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMemberListOrderOperatorThenMemberNicknameAlphabetical"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDMemberListOrderOperatorThenMemberNicknameAlphabetical"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder~1operatorThenMemberNicknameAlphabetical\/title","value":"SBDMemberListOrderOperatorThenMemberNicknameAlphabetical"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder~1operatorThenMemberNicknameAlphabetical\/fragments","value":[{"kind":"identifier","text":"SBDMemberListOrderOperatorThenMemberNicknameAlphabetical"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder\/title","value":"SBDMemberListOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder\/fragments","value":[{"kind":"identifier","text":"SBDMemberListOrder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}