{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelHiddenStateFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelHiddenStateFilter","text":"ChannelHiddenStateFilter"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.122"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/channelhiddenstatefilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/channelhiddenstatefilter"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/channelHiddenStateFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets to filter channels by the hidden state. The default value is "},{"type":"codeVoice","code":"ChannelHiddenStateFilter.unhiddenOnly"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelHiddenStateFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelHiddenStateFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelHiddenStateFilter"}],"title":"channelHiddenStateFilter","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQueryParams(py)channelHiddenStateFilter","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"channelHiddenStateFilter"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelHiddenStateFilter":{"role":"symbol","title":"ChannelHiddenStateFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelHiddenStateFilter"}],"abstract":[{"type":"text","text":"The enum type to filter my group channels with the hidden state."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelHiddenStateFilter"}],"url":"\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/channelHiddenStateFilter":{"role":"symbol","title":"channelHiddenStateFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelHiddenStateFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelHiddenStateFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelHiddenStateFilter"}],"abstract":[{"type":"text","text":"Sets to filter channels by the hidden state. The default value is "},{"type":"codeVoice","code":"ChannelHiddenStateFilter.unhiddenOnly"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/channelHiddenStateFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelHiddenStateFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/channelhiddenstatefilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams":{"role":"symbol","title":"GroupChannelListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"channelHiddenStateFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"channelHiddenStateFilter"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelHiddenStateFilter","text":"SBDChannelHiddenStateFilter"},{"kind":"identifier","text":"channelHiddenStateFilter"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter\/title","value":"SBDChannelHiddenStateFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter\/fragments","value":[{"kind":"identifier","text":"SBDChannelHiddenStateFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1channelHiddenStateFilter\/title","value":"channelHiddenStateFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1channelHiddenStateFilter\/fragments","value":[{"kind":"identifier","text":"channelHiddenStateFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams\/title","value":"SBDGroupChannelListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQueryParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}