{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicChannelFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPublicChannelFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPublicChannelFilter","text":"GroupChannelPublicChannelFilter"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/publicchannelfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/publicchannelfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/publicChannelFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets to filter public channel.Default is "},{"type":"codeVoice","code":".all"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicChannelFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelPublicChannelFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPublicChannelFilter"}],"title":"publicChannelFilter","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQueryParams(py)publicChannelFilter","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"publicChannelFilter"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/publicChannelFilter":{"role":"symbol","title":"publicChannelFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicChannelFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelPublicChannelFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPublicChannelFilter"}],"abstract":[{"type":"text","text":"Sets to filter public channel.Default is "},{"type":"codeVoice","code":".all"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/publicChannelFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publicChannelFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/publicchannelfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams":{"role":"symbol","title":"GroupChannelListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelPublicChannelFilter":{"role":"symbol","title":"GroupChannelPublicChannelFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelPublicChannelFilter"}],"abstract":[{"type":"text","text":"Filter public group channel or private one in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPublicChannelFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelPublicChannelFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelpublicchannelfilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"publicChannelFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"publicChannelFilter"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPublicChannelFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPublicChannelFilter","text":"SBDGroupChannelPublicChannelFilter"},{"kind":"identifier","text":"publicChannelFilter"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1publicChannelFilter\/title","value":"publicChannelFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1publicChannelFilter\/fragments","value":[{"kind":"identifier","text":"publicChannelFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams\/title","value":"SBDGroupChannelListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPublicChannelFilter\/title","value":"SBDGroupChannelPublicChannelFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPublicChannelFilter\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelPublicChannelFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}