{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListQueryType","text":"GroupChannelListQueryType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/querytype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/querytype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/queryType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets query type for "},{"type":"codeVoice","code":"includeMemberList"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQueryType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListQueryType"}],"title":"queryType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQueryParams(py)queryType","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"queryType"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams":{"role":"symbol","title":"GroupChannelListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryType":{"role":"symbol","title":"GroupChannelListQueryType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQueryType"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQueryType"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerytype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/queryType":{"role":"symbol","title":"queryType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQueryType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListQueryType"}],"abstract":[{"type":"text","text":"Sets query type for "},{"type":"codeVoice","code":"includeMemberList"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/queryType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"queryType"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/querytype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"queryType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"queryType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListQueryType","text":"SBDGroupChannelListQueryType"},{"kind":"identifier","text":"queryType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams\/title","value":"SBDGroupChannelListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryType\/title","value":"SBDGroupChannelListQueryType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryType\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQueryType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1queryType\/title","value":"queryType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1queryType\/fragments","value":[{"kind":"identifier","text":"queryType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}