{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserIDsIncludeFilter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"queryType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListQueryType","text":"GroupChannelListQueryType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"userIDs","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"User IDs to search."}]}]},{"name":"queryType ","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Logical condition applied to filter. If you pass "},{"type":"codeVoice","code":"GroupChannelListQueryTypeAnd"},{"type":"text","text":" "},{"type":"text","text":"to "},{"type":"codeVoice","code":"queryType"},{"type":"text","text":" and A, B to "},{"type":"codeVoice","code":"userIDs"},{"type":"text","text":", the channels whose members containing A and B will be returned."},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"codeVoice","code":"GroupChannelListQueryTypeOr"},{"type":"text","text":" is set, the members of the queried channels will be A or B."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The group channels which have the members that contain user IDs are returned by "},{"type":"codeVoice","code":"loadNext:"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/setuseridsincludefilter(_:querytype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/setuseridsincludefilter(_:querytype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/setUserIDsIncludeFilter(_:queryType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the filter with user IDs."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserIDsIncludeFilter"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"queryType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQueryType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListQueryType"},{"kind":"text","text":")"}],"title":"setUserIDsIncludeFilter(_:queryType:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQueryParams(im)setUserIDsIncludeFilter:queryType:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"setUserIDsIncludeFilter:queryType:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryType":{"role":"symbol","title":"GroupChannelListQueryType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQueryType"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQueryType"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerytype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams":{"role":"symbol","title":"GroupChannelListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/setUserIDsIncludeFilter(_:queryType:)":{"role":"symbol","title":"setUserIDsIncludeFilter(_:queryType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserIDsIncludeFilter"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"queryType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQueryType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListQueryType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the filter with user IDs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/setUserIDsIncludeFilter(_:queryType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setUserIDsIncludeFilter:queryType:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/setuseridsincludefilter(_:querytype:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setUserIDsIncludeFilter:queryType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserIDsIncludeFilter:queryType:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setUserIDsIncludeFilter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userIDs"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListQueryType","text":"SBDGroupChannelListQueryType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"queryType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryType\/title","value":"SBDGroupChannelListQueryType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryType\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQueryType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams\/title","value":"SBDGroupChannelListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1setUserIDsIncludeFilter(_:queryType:)\/title","value":"setUserIDsIncludeFilter:queryType:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1setUserIDsIncludeFilter(_:queryType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserIDsIncludeFilter:queryType:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}