{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetMessageID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/threadinfoupdateevent\/targetmessageid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/threadinfoupdateevent\/targetmessageid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadInfoUpdateEvent\/targetMessageID","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The unique ID of the message that contains thread information."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetMessageID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"title":"targetMessageID","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadInfoUpdateEvent(py)targetMessageID","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"targetMessageID"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadInfoUpdateEvent"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadInfoUpdateEvent/targetMessageID":{"role":"symbol","title":"targetMessageID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetMessageID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The unique ID of the message that contains thread information."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadInfoUpdateEvent\/targetMessageID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"targetMessageID"}],"url":"\/documentation\/sendbirdchatsdk\/threadinfoupdateevent\/targetmessageid"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadInfoUpdateEvent":{"role":"symbol","title":"ThreadInfoUpdateEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThreadInfoUpdateEvent"}],"abstract":[{"type":"text","text":"An object that is returned through the event handler when a threaded reply is added or deleted."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadInfoUpdateEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThreadInfoUpdateEvent"}],"url":"\/documentation\/sendbirdchatsdk\/threadinfoupdateevent"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"targetMessageID"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"targetMessageID"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"identifier","text":"targetMessageID"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadInfoUpdateEvent~1targetMessageID\/title","value":"targetMessageID"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadInfoUpdateEvent~1targetMessageID\/fragments","value":[{"kind":"identifier","text":"targetMessageID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadInfoUpdateEvent\/title","value":"SBDThreadInfoUpdateEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadInfoUpdateEvent\/fragments","value":[{"kind":"identifier","text":"SBDThreadInfoUpdateEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}