{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"threadInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadInfo","text":"ThreadInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/threadinfoupdateevent\/threadinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/threadinfoupdateevent\/threadinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadInfoUpdateEvent\/threadInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object that has the information about threaded messages."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"threadInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThreadInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadInfo"}],"title":"threadInfo","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadInfoUpdateEvent(py)threadInfo","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"threadInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadInfoUpdateEvent"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadInfo":{"role":"symbol","title":"ThreadInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThreadInfo"}],"abstract":[{"type":"text","text":"An object that represents the information about threaded messages, whose properties show how many"},{"type":"text","text":" "},{"type":"text","text":"replies the thread has received, who left the replies, and when the last reply was added."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThreadInfo"}],"url":"\/documentation\/sendbirdchatsdk\/threadinfo"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadInfoUpdateEvent":{"role":"symbol","title":"ThreadInfoUpdateEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThreadInfoUpdateEvent"}],"abstract":[{"type":"text","text":"An object that is returned through the event handler when a threaded reply is added or deleted."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadInfoUpdateEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThreadInfoUpdateEvent"}],"url":"\/documentation\/sendbirdchatsdk\/threadinfoupdateevent"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadInfoUpdateEvent/threadInfo":{"role":"symbol","title":"threadInfo","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"threadInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThreadInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadInfo"}],"abstract":[{"type":"text","text":"An object that has the information about threaded messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadInfoUpdateEvent\/threadInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"threadInfo"}],"url":"\/documentation\/sendbirdchatsdk\/threadinfoupdateevent\/threadinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"threadInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"threadInfo"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadInfo","text":"SBDThreadInfo"},{"kind":"text","text":" *"},{"kind":"identifier","text":"threadInfo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadInfo\/title","value":"SBDThreadInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadInfo\/fragments","value":[{"kind":"identifier","text":"SBDThreadInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadInfoUpdateEvent\/title","value":"SBDThreadInfoUpdateEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadInfoUpdateEvent\/fragments","value":[{"kind":"identifier","text":"SBDThreadInfoUpdateEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadInfoUpdateEvent~1threadInfo\/title","value":"threadInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadInfoUpdateEvent~1threadInfo\/fragments","value":[{"kind":"identifier","text":"threadInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}