{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyReplyToChannel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/replytype\/onlyreplytochannel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/replytype\/onlyreplytochannel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReplyType\/onlyReplyToChannel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyReplyToChannel"}],"title":"ReplyType.onlyReplyToChannel","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDReplyType@SBDReplyTypeOnlyReplyToChannel","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDReplyTypeOnlyReplyToChannel"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReplyType"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReplyType/onlyReplyToChannel":{"role":"symbol","title":"ReplyType.onlyReplyToChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyReplyToChannel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReplyType\/onlyReplyToChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDReplyTypeOnlyReplyToChannel"}],"url":"\/documentation\/sendbirdchatsdk\/replytype\/onlyreplytochannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReplyType":{"role":"symbol","title":"ReplyType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReplyType"}],"abstract":[{"type":"text","text":"Reply type filter"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReplyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReplyType"}],"url":"\/documentation\/sendbirdchatsdk\/replytype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDReplyTypeOnlyReplyToChannel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDReplyTypeOnlyReplyToChannel"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDReplyTypeOnlyReplyToChannel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReplyType~1onlyReplyToChannel\/title","value":"SBDReplyTypeOnlyReplyToChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReplyType~1onlyReplyToChannel\/fragments","value":[{"kind":"identifier","text":"SBDReplyTypeOnlyReplyToChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReplyType\/title","value":"SBDReplyType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReplyType\/fragments","value":[{"kind":"identifier","text":"SBDReplyType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}