{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formSymmetricDifference"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"other"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuerySearchField","text":"GroupChannelListQuerySearchField"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"other","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A set of the same type."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In the following example, the elements of the "},{"type":"codeVoice","code":"employees"},{"type":"text","text":" set that are"},{"type":"text","text":" "},{"type":"text","text":"also members of "},{"type":"codeVoice","code":"neighbors"},{"type":"text","text":" are removed from "},{"type":"codeVoice","code":"employees"},{"type":"text","text":", while the"},{"type":"text","text":" "},{"type":"text","text":"elements of "},{"type":"codeVoice","code":"neighbors"},{"type":"text","text":" that are not members of "},{"type":"codeVoice","code":"employees"},{"type":"text","text":" are added to"},{"type":"text","text":" "},{"type":"codeVoice","code":"employees"},{"type":"text","text":". In particular, the names "},{"type":"codeVoice","code":"\"Bethany\""},{"type":"text","text":" and "},{"type":"codeVoice","code":"\"Eric\""},{"type":"text","text":" are"},{"type":"text","text":" "},{"type":"text","text":"removed from "},{"type":"codeVoice","code":"employees"},{"type":"text","text":" while the name "},{"type":"codeVoice","code":"\"Forlani\""},{"type":"text","text":" is added."}]},{"type":"codeListing","syntax":null,"code":["var employees: Set = [\"Alicia\", \"Bethany\", \"Diana\", \"Eric\"]","let neighbors: Set = [\"Bethany\", \"Eric\", \"Forlani\"]","employees.formSymmetricDifference(neighbors)","print(employees)","\/\/ Prints \"[\"Diana\", \"Forlani\", \"Alicia\"]\""]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/formsymmetricdifference(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/formsymmetricdifference(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/formSymmetricDifference(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Removes the elements of the set that are also in the given set and adds"},{"type":"text","text":" "},{"type":"text","text":"the members of the given set that are not already in the set."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formSymmetricDifference"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannelListQuerySearchField","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuerySearchField"},{"kind":"text","text":")"}],"title":"formSymmetricDifference(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuerySearchField(im)formSymmetricDifference:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"formSymmetricDifference:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/formSymmetricDifference(_:)":{"role":"symbol","title":"formSymmetricDifference(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formSymmetricDifference"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannelListQuerySearchField","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuerySearchField"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes the elements of the set that are also in the given set and adds"},{"type":"text","text":" "},{"type":"text","text":"the members of the given set that are not already in the set."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/formSymmetricDifference(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formSymmetricDifference:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/formsymmetricdifference(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField":{"role":"symbol","title":"GroupChannelListQuerySearchField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQuerySearchField"}],"abstract":[{"type":"text","text":"Filter types to query with "},{"type":"codeVoice","code":"GroupChannelListQuery"},{"type":"text","text":". You can combine search fields to query."},{"type":"text","text":" "},{"type":"text","text":"used for "},{"type":"codeVoice","code":"setSearchFilter(_:fields:)"},{"type":"text","text":" of "},{"type":"codeVoice","code":"GroupChannelListQuery"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQuerySearchField"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"formSymmetricDifference:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formSymmetricDifference:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"formSymmetricDifference:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuerySearchField","text":"SBDGroupChannelListQuerySearchField"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"other"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1formSymmetricDifference(_:)\/title","value":"formSymmetricDifference:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1formSymmetricDifference(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formSymmetricDifference:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField\/title","value":"SBDGroupChannelListQuerySearchField"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQuerySearchField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}