{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restrictionInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDRestrictionInfo","text":"RestrictionInfo"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/restricteduser\/restrictioninfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/restricteduser\/restrictioninfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictedUser\/restrictionInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Restriction info for this user"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restrictionInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RestrictionInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDRestrictionInfo"},{"kind":"text","text":"?"}],"title":"restrictionInfo","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDRestrictedUser(py)restrictionInfo","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"restrictionInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictedUser"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictedUser/restrictionInfo":{"role":"symbol","title":"restrictionInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restrictionInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RestrictionInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDRestrictionInfo"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Restriction info for this user"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictedUser\/restrictionInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"restrictionInfo"}],"url":"\/documentation\/sendbirdchatsdk\/restricteduser\/restrictioninfo"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictedUser":{"role":"symbol","title":"RestrictedUser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictedUser"}],"abstract":[{"type":"text","text":"Represents a user who has been restricted in a channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictedUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RestrictedUser"}],"url":"\/documentation\/sendbirdchatsdk\/restricteduser"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionInfo":{"role":"symbol","title":"RestrictionInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictionInfo"}],"abstract":[{"type":"text","text":"An object contains information about restriction"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RestrictionInfo"}],"url":"\/documentation\/sendbirdchatsdk\/restrictioninfo"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"restrictionInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"restrictionInfo"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDRestrictionInfo","text":"SBDRestrictionInfo"},{"kind":"text","text":" *"},{"kind":"identifier","text":"restrictionInfo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictedUser~1restrictionInfo\/title","value":"restrictionInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictedUser~1restrictionInfo\/fragments","value":[{"kind":"identifier","text":"restrictionInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictedUser\/title","value":"SBDRestrictedUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictedUser\/fragments","value":[{"kind":"identifier","text":"SBDRestrictedUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionInfo\/title","value":"SBDRestrictionInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionInfo\/fragments","value":[{"kind":"identifier","text":"SBDRestrictionInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}