{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"previousResultSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" = 0, "},{"kind":"externalParam","text":"nextResultSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" = 0, "},{"kind":"externalParam","text":"isInclusive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"reverse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"messageTypeFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageTypeFilter","text":"MessageTypeFilter"},{"kind":"text","text":" = .all, "},{"kind":"externalParam","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"senderUserIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"includeMetaArray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"includeReactions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"includeParentMessageInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"customTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/init(previousresultsize:nextresultsize:isinclusive:reverse:messagetypefilter:customtype:senderuserids:includemetaarray:includereactions:includeparentmessageinfo:customtypes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/init(previousresultsize:nextresultsize:isinclusive:reverse:messagetypefilter:customtype:senderuserids:includemetaarray:includereactions:includeparentmessageinfo:customtypes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Parameter constructor."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"previousResultSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nextResultSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isInclusive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reverse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageTypeFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageTypeFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageTypeFilter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"senderUserIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"includeMetaArray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeReactions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeParentMessageInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"title":"init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadedMessageListParams(im)initWithPreviousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPreviousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams":{"role":"symbol","title":"ThreadedMessageListParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThreadedMessageListParams"}],"abstract":[{"type":"text","text":"An object contains set of options to retrieve threaded messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThreadedMessageListParams"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams/init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:)":{"role":"symbol","title":"init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"previousResultSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nextResultSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isInclusive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reverse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageTypeFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageTypeFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageTypeFilter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"senderUserIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"includeMetaArray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeReactions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeParentMessageInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Parameter constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPreviousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/init(previousresultsize:nextresultsize:isinclusive:reverse:messagetypefilter:customtype:senderuserids:includemetaarray:includereactions:includeparentmessageinfo:customtypes:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageTypeFilter":{"role":"symbol","title":"MessageTypeFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageTypeFilter"}],"abstract":[{"type":"text","text":"Message type for filtering"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageTypeFilter"}],"url":"\/documentation\/sendbirdchatsdk\/messagetypefilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithPreviousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreviousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPreviousResultSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"previousResultSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextResultSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"nextResultSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInclusive:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isInclusive"},{"kind":"text","text":" "},{"kind":"identifier","text":"reverse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"reverse"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageTypeFilter:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageTypeFilter","text":"SBDMessageTypeFilter"},{"kind":"text","text":")"},{"kind":"internalParam","text":"messageTypeFilter"},{"kind":"text","text":" "},{"kind":"identifier","text":"customType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"customType"},{"kind":"text","text":" "},{"kind":"identifier","text":"senderUserIDs:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"senderUserIDs"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeMetaArray:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"includeMetaArray"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeReactions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"includeReactions"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeParentMessageInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"includeParentMessageInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"customTypes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"customTypes"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams\/title","value":"SBDThreadedMessageListParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams\/fragments","value":[{"kind":"identifier","text":"SBDThreadedMessageListParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:)\/title","value":"initWithPreviousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreviousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter\/title","value":"SBDMessageTypeFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter\/fragments","value":[{"kind":"identifier","text":"SBDMessageTypeFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}