{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/websocketconnectionstate\/closed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/websocketconnectionstate\/closed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/closed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Closed"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"}],"title":"WebSocketConnectionState.closed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDWebSocketConnectionState@SBDWebSocketConnectionStateClosed","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDWebSocketConnectionStateClosed"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/WebSocketConnectionState/closed":{"role":"symbol","title":"WebSocketConnectionState.closed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"}],"abstract":[{"type":"text","text":"Closed"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/closed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDWebSocketConnectionStateClosed"}],"url":"\/documentation\/sendbirdchatsdk\/websocketconnectionstate\/closed"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/WebSocketConnectionState":{"role":"symbol","title":"WebSocketConnectionState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebSocketConnectionState"}],"abstract":[{"type":"text","text":"Connection state"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebSocketConnectionState"}],"url":"\/documentation\/sendbirdchatsdk\/websocketconnectionstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDWebSocketConnectionStateClosed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDWebSocketConnectionStateClosed"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDWebSocketConnectionStateClosed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState~1closed\/title","value":"SBDWebSocketConnectionStateClosed"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState~1closed\/fragments","value":[{"kind":"identifier","text":"SBDWebSocketConnectionStateClosed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState\/title","value":"SBDWebSocketConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState\/fragments","value":[{"kind":"identifier","text":"SBDWebSocketConnectionState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}