{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/websocketconnectionstate\/connecting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/websocketconnectionstate\/connecting"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/connecting","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Connecting"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"title":"WebSocketConnectionState.connecting","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDWebSocketConnectionState@SBDWebSocketConnectionStateConnecting","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDWebSocketConnectionStateConnecting"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/WebSocketConnectionState/connecting":{"role":"symbol","title":"WebSocketConnectionState.connecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"abstract":[{"type":"text","text":"Connecting"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/connecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDWebSocketConnectionStateConnecting"}],"url":"\/documentation\/sendbirdchatsdk\/websocketconnectionstate\/connecting"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/WebSocketConnectionState":{"role":"symbol","title":"WebSocketConnectionState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebSocketConnectionState"}],"abstract":[{"type":"text","text":"Connection state"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebSocketConnectionState"}],"url":"\/documentation\/sendbirdchatsdk\/websocketconnectionstate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDWebSocketConnectionStateConnecting"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDWebSocketConnectionStateConnecting"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDWebSocketConnectionStateConnecting"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState~1connecting\/title","value":"SBDWebSocketConnectionStateConnecting"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState~1connecting\/fragments","value":[{"kind":"identifier","text":"SBDWebSocketConnectionStateConnecting"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState\/title","value":"SBDWebSocketConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState\/fragments","value":[{"kind":"identifier","text":"SBDWebSocketConnectionState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}