{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenAllowAutoUnhide"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/hiddenallowautounhide"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/hiddenallowautounhide"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/hiddenAllowAutoUnhide","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Shows the channel will be unhidden automatically when there is a new message in the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenAllowAutoUnhide"}],"title":"GroupChannelHiddenState.hiddenAllowAutoUnhide","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDGroupChannelHiddenState@SBDGroupChannelHiddenStateHiddenAllowAutoUnhide","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateHiddenAllowAutoUnhide"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHiddenState/hiddenAllowAutoUnhide":{"role":"symbol","title":"GroupChannelHiddenState.hiddenAllowAutoUnhide","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenAllowAutoUnhide"}],"abstract":[{"type":"text","text":"Shows the channel will be unhidden automatically when there is a new message in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/hiddenAllowAutoUnhide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateHiddenAllowAutoUnhide"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/hiddenallowautounhide"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHiddenState":{"role":"symbol","title":"GroupChannelHiddenState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelHiddenState"}],"abstract":[{"type":"text","text":"The enum type for the hidden state of a group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelHiddenState"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelHiddenStateHiddenAllowAutoUnhide"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateHiddenAllowAutoUnhide"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateHiddenAllowAutoUnhide"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState~1hiddenAllowAutoUnhide\/title","value":"SBDGroupChannelHiddenStateHiddenAllowAutoUnhide"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState~1hiddenAllowAutoUnhide\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateHiddenAllowAutoUnhide"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState\/title","value":"SBDGroupChannelHiddenState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelHiddenState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}