{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenPreventAutoUnhide"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/hiddenpreventautounhide"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/hiddenpreventautounhide"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/hiddenPreventAutoUnhide","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Shows the channel will not be unhidden automatically."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenPreventAutoUnhide"}],"title":"GroupChannelHiddenState.hiddenPreventAutoUnhide","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDGroupChannelHiddenState@SBDGroupChannelHiddenStateHiddenPreventAutoUnhide","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateHiddenPreventAutoUnhide"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHiddenState":{"role":"symbol","title":"GroupChannelHiddenState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelHiddenState"}],"abstract":[{"type":"text","text":"The enum type for the hidden state of a group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelHiddenState"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHiddenState/hiddenPreventAutoUnhide":{"role":"symbol","title":"GroupChannelHiddenState.hiddenPreventAutoUnhide","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenPreventAutoUnhide"}],"abstract":[{"type":"text","text":"Shows the channel will not be unhidden automatically."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/hiddenPreventAutoUnhide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateHiddenPreventAutoUnhide"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/hiddenpreventautounhide"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelHiddenStateHiddenPreventAutoUnhide"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateHiddenPreventAutoUnhide"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateHiddenPreventAutoUnhide"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState\/title","value":"SBDGroupChannelHiddenState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelHiddenState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState~1hiddenPreventAutoUnhide\/title","value":"SBDGroupChannelHiddenStateHiddenPreventAutoUnhide"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState~1hiddenPreventAutoUnhide\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateHiddenPreventAutoUnhide"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}