{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unhidden"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/unhidden"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/unhidden"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/unhidden","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Shows the channel is unhidden."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unhidden"}],"title":"GroupChannelHiddenState.unhidden","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDGroupChannelHiddenState@SBDGroupChannelHiddenStateUnhidden","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateUnhidden"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHiddenState/unhidden":{"role":"symbol","title":"GroupChannelHiddenState.unhidden","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unhidden"}],"abstract":[{"type":"text","text":"Shows the channel is unhidden."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/unhidden","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateUnhidden"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/unhidden"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHiddenState":{"role":"symbol","title":"GroupChannelHiddenState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelHiddenState"}],"abstract":[{"type":"text","text":"The enum type for the hidden state of a group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelHiddenState"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelHiddenStateUnhidden"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateUnhidden"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateUnhidden"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState~1unhidden\/title","value":"SBDGroupChannelHiddenStateUnhidden"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState~1unhidden\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateUnhidden"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState\/title","value":"SBDGroupChannelHiddenState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelHiddenState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}