{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidChangeParticipantCount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channels"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel","text":"OpenChannel"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"channels","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The open channel that member count has been updated"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.219"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/openchanneldelegate\/channeldidchangeparticipantcount(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/openchanneldelegate\/channeldidchangeparticipantcount(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate\/channelDidChangeParticipantCount(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A callback when participant count has been changed for open channel"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"channelDidChangeParticipantCount:"}],"role":"symbol","title":"channelDidChangeParticipantCount(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidChangeParticipantCount"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDOpenChannelDelegate(im)channelDidChangeParticipantCount:","required":true,"modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelDelegate":{"role":"symbol","title":"OpenChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/openchanneldelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel":{"role":"symbol","title":"OpenChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" class represents a open channel which is a public chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannel"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelDelegate/channelDidChangeParticipantCount(_:)":{"navigatorTitle":[{"kind":"identifier","text":"channelDidChangeParticipantCount:"}],"role":"symbol","title":"channelDidChangeParticipantCount(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidChangeParticipantCount"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"A callback when participant count has been changed for open channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate\/channelDidChangeParticipantCount(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/openchanneldelegate\/channeldidchangeparticipantcount(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"channelDidChangeParticipantCount:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidChangeParticipantCount:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"channelDidChangeParticipantCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBDOpenChannel *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channels"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelDelegate\/title","value":"SBDOpenChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannelDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel\/title","value":"SBDOpenChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelDelegate~1channelDidChangeParticipantCount(_:)\/title","value":"channelDidChangeParticipantCount:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelDelegate~1channelDidChangeParticipantCount(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidChangeParticipantCount:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}