{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDAppInfo) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/appinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/appinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object contains application information"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppInfo"}],"title":"AppInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDAppInfo","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"AppInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/applicationAttributes","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/backOffDelay","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/concurrentCallLimit","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/emojiHash","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/premiumFeatureList","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/uploadSizeLimit","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/useNativeWS","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/useReaction"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/isEmojiUpdateNeeded(prevEmojiHash:)"]}],"references":{"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppInfo/useNativeWS":{"role":"symbol","title":"useNativeWS","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useNativeWS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"This is the application attribute to tell SDK use native websocket"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/useNativeWS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"useNativeWS"}],"url":"\/documentation\/sendbirdchatsdk\/appinfo\/usenativews"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppInfo/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/appinfo\/init(from:)"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppInfo/isEmojiUpdateNeeded(prevEmojiHash:)":{"role":"symbol","title":"isEmojiUpdateNeeded(prevEmojiHash:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEmojiUpdateNeeded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"prevEmojiHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"This function can check if Emoji information needs to be updated to date."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/isEmojiUpdateNeeded(prevEmojiHash:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEmojiUpdateNeededWithPrevEmojiHash:"}],"url":"\/documentation\/sendbirdchatsdk\/appinfo\/isemojiupdateneeded(prevemojihash:)"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppInfo/backOffDelay":{"role":"symbol","title":"backOffDelay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backOffDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/backOffDelay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backOffDelay"}],"url":"\/documentation\/sendbirdchatsdk\/appinfo\/backoffdelay"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppInfo/useReaction":{"role":"symbol","title":"useReaction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useReaction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"This is the state of using the reaction feature."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/useReaction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"useReaction"}],"url":"\/documentation\/sendbirdchatsdk\/appinfo\/usereaction"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppInfo/applicationAttributes":{"role":"symbol","title":"applicationAttributes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationAttributes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"This is the application attributes list using on your Application ID."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/applicationAttributes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationAttributes"}],"url":"\/documentation\/sendbirdchatsdk\/appinfo\/applicationattributes"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppInfo/premiumFeatureList":{"role":"symbol","title":"premiumFeatureList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"premiumFeatureList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"This is the premium feature list using on your Application ID."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/premiumFeatureList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"premiumFeatureList"}],"url":"\/documentation\/sendbirdchatsdk\/appinfo\/premiumfeaturelist"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppInfo/uploadSizeLimit":{"role":"symbol","title":"uploadSizeLimit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uploadSizeLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"This is the uploadable file size limit. (The unit is bytes.)"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/uploadSizeLimit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"uploadSizeLimit"}],"url":"\/documentation\/sendbirdchatsdk\/appinfo\/uploadsizelimit"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppInfo/concurrentCallLimit":{"role":"symbol","title":"concurrentCallLimit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"concurrentCallLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/concurrentCallLimit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"concurrentCallLimit"}],"url":"\/documentation\/sendbirdchatsdk\/appinfo\/concurrentcalllimit"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppInfo/emojiHash":{"role":"symbol","title":"emojiHash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emojiHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"This is the latest hash value for Emoji."},{"type":"text","text":" "},{"type":"text","text":"Default value is empty string."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/emojiHash","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"emojiHash"}],"url":"\/documentation\/sendbirdchatsdk\/appinfo\/emojihash"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppInfo":{"role":"symbol","title":"AppInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppInfo"}],"abstract":[{"type":"text","text":"An object contains application information"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppInfo"}],"url":"\/documentation\/sendbirdchatsdk\/appinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDAppInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDAppInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDAppInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/applicationAttributes","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/backOffDelay","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/concurrentCallLimit","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/emojiHash","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/premiumFeatureList","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/uploadSizeLimit","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/useNativeWS","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/useReaction"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/isEmojiUpdateNeeded(prevEmojiHash:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDAppInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1useNativeWS\/title","value":"useNativeWS"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1useNativeWS\/fragments","value":[{"kind":"identifier","text":"useNativeWS"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1isEmojiUpdateNeeded(prevEmojiHash:)\/title","value":"isEmojiUpdateNeededWithPrevEmojiHash:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1isEmojiUpdateNeeded(prevEmojiHash:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEmojiUpdateNeededWithPrevEmojiHash:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1backOffDelay\/title","value":"backOffDelay"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1backOffDelay\/fragments","value":[{"kind":"identifier","text":"backOffDelay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1useReaction\/title","value":"useReaction"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1useReaction\/fragments","value":[{"kind":"identifier","text":"useReaction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1applicationAttributes\/title","value":"applicationAttributes"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1applicationAttributes\/fragments","value":[{"kind":"identifier","text":"applicationAttributes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1premiumFeatureList\/title","value":"premiumFeatureList"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1premiumFeatureList\/fragments","value":[{"kind":"identifier","text":"premiumFeatureList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1uploadSizeLimit\/title","value":"uploadSizeLimit"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1uploadSizeLimit\/fragments","value":[{"kind":"identifier","text":"uploadSizeLimit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1concurrentCallLimit\/title","value":"concurrentCallLimit"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1concurrentCallLimit\/fragments","value":[{"kind":"identifier","text":"concurrentCallLimit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1emojiHash\/title","value":"emojiHash"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1emojiHash\/fragments","value":[{"kind":"identifier","text":"emojiHash"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo\/title","value":"SBDAppInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo\/fragments","value":[{"kind":"identifier","text":"SBDAppInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}