{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDBaseChannelDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannelDelegate"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"aside","style":"warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If the object that adopts the "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" protocol is invalid, the delegate has to"},{"type":"text","text":" "},{"type":"text","text":"be removed by the identifier via "},{"type":"codeVoice","code":"removeChannelDelegate(forIdentifier:)"},{"type":"text","text":" in "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":"."}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol deals with the below events."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives a message in the "},{"type":"reference","isActive":true,"identifier":"..\/Classes\/BaseChannel.html"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when a message is updated in the "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"BaseChannel"}],"isActive":true,"type":"reference","identifier":"..\/Classes\/BaseChannel.html","overridingTitle":"BaseChannel"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when the property of the "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"BaseChannel"}],"isActive":true,"type":"reference","identifier":"..\/Classes\/BaseChannel.html","overridingTitle":"BaseChannel"},{"type":"text","text":" was changed."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when the "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"BaseChannel"}],"isActive":true,"type":"reference","identifier":"..\/Classes\/BaseChannel.html","overridingTitle":"BaseChannel"},{"type":"text","text":" was deleted."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when a message in the "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"BaseChannel"}],"isActive":true,"type":"reference","identifier":"..\/Classes\/BaseChannel.html","overridingTitle":"BaseChannel"},{"type":"text","text":" was deleted."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when meta data in the "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"BaseChannel"}],"isActive":true,"type":"reference","identifier":"..\/Classes\/BaseChannel.html","overridingTitle":"BaseChannel"},{"type":"text","text":" was changed."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when meta counters in the "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"BaseChannel"}],"isActive":true,"type":"reference","identifier":"..\/Classes\/BaseChannel.html","overridingTitle":"BaseChannel"},{"type":"text","text":" were changed."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when a group channel was hidden."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when a user was muted or unmuted in the "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"BaseChannel"}],"isActive":true,"type":"reference","identifier":"..\/Classes\/BaseChannel.html","overridingTitle":"BaseChannel"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when a user was banned or unbanned in the "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"BaseChannel"}],"isActive":true,"type":"reference","identifier":"..\/Classes\/BaseChannel.html","overridingTitle":"BaseChannel"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when operators are updated."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when a reaction of message in a channel was updated."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechanneldelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechanneldelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events"},{"type":"text","text":" "},{"type":"text","text":"in the channel. Delegate methods in "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" are common for the "},{"type":"codeVoice","code":"BaseChannel"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Exclusive delegate methods for "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" can be found in"},{"type":"text","text":" "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":". You must use "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":" instead of using "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" by using "},{"type":"codeVoice","code":"add(_:identifier:)"},{"type":"text","text":" in "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannelDelegate"}],"title":"BaseChannelDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDBaseChannelDelegate","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"BaseChannelDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:createdMetaCounters:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:createdMetaData:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:deletedMetaCountersKeys:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:deletedMetaDataKeys:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:didReceive:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:didReceiveMention:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:didUpdate:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:didUpdateThreadInfo:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:messageWasDeleted:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:updatedMetaCounters:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:updatedMetaData:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:updatedReaction:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:userWasBanned:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:userWasMuted:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:userWasUnbanned:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:userWasUnmuted:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channelDidUpdateOperators(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channelWasChanged(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channelWasDeleted(_:channelType:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channelWasFrozen(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channelWasUnfrozen(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/didUpdatePoll(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/didVotePoll(_:)"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection":{"role":"symbol","title":"MessageCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollection"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:deletedMetaDataKeys:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:deletedMetaDataKeys:"}],"role":"symbol","title":"channel(_:deletedMetaDataKeys:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedMetaDataKeys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"A callback when meta data was deleted in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:deletedMetaDataKeys:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:deletedmetadatakeys:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelDelegate":{"role":"symbol","title":"OpenChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/openchanneldelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channelWasChanged(_:)":{"navigatorTitle":[{"kind":"identifier","text":"channelWasChanged:"}],"role":"symbol","title":"channelWasChanged(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelWasChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when an open channel was changed."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channelWasChanged(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channelwaschanged(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:didReceive:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:didReceiveMessage:"}],"role":"symbol","title":"channel(_:didReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a message is received."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:didReceive:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:didreceive:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:deletedMetaCountersKeys:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:deletedMetaCountersKeys:"}],"role":"symbol","title":"channel(_:deletedMetaCountersKeys:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedMetaCountersKeys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"A callback when meta counters were deleted in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:deletedMetaCountersKeys:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:deletedmetacounterskeys:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection":{"role":"symbol","title":"GroupChannelCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelCollection"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:updatedReaction:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:updatedReaction:"}],"role":"symbol","title":"channel(_:updatedReaction:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"updatedReaction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReactionEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDReactionEvent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a reaction was updated."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:updatedReaction:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:updatedreaction:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channelWasDeleted(_:channelType:)":{"navigatorTitle":[{"kind":"identifier","text":"channelWasDeleted:channelType:"}],"role":"symbol","title":"channelWasDeleted(_:channelType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelWasDeleted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when an open channel was deleted."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channelWasDeleted(_:channelType:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channelwasdeleted(_:channeltype:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:createdMetaCounters:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:createdMetaCounters:"}],"role":"symbol","title":"channel(_:createdMetaCounters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"createdMetaCounters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"A callback when meta counters were created in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:createdMetaCounters:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:createdmetacounters:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:userWasUnbanned:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:userWasUnbanned:"}],"role":"symbol","title":"channel(_:userWasUnbanned:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userWasUnbanned"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a user was unbanned in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:userWasUnbanned:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:userwasunbanned:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/didVotePoll(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didVotePoll:"}],"role":"symbol","title":"didVotePoll(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didVotePoll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PollVoteEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollVoteEvent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when vote has been occurred."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/didVotePoll(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/didvotepoll(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:userWasMuted:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:userWasMuted:"}],"role":"symbol","title":"channel(_:userWasMuted:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userWasMuted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a user was muted in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:userWasMuted:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:userwasmuted:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate":{"role":"symbol","title":"BaseChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events"},{"type":"text","text":" "},{"type":"text","text":"in the channel. Delegate methods in "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" are common for the "},{"type":"codeVoice","code":"BaseChannel"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Exclusive delegate methods for "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" can be found in"},{"type":"text","text":" "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":". You must use "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":" instead of using "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" by using "},{"type":"codeVoice","code":"add(_:identifier:)"},{"type":"text","text":" in "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channelWasUnfrozen(_:)":{"navigatorTitle":[{"kind":"identifier","text":"channelWasUnfrozen:"}],"role":"symbol","title":"channelWasUnfrozen(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelWasUnfrozen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when an channel was unfrozen."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channelWasUnfrozen(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channelwasunfrozen(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate":{"role":"symbol","title":"GroupChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:updatedMetaData:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:updatedMetaData:"}],"role":"symbol","title":"channel(_:updatedMetaData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"updatedMetaData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"A callback when meta data was updated in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:updatedMetaData:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:updatedmetadata:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:createdMetaData:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:createdMetaData:"}],"role":"symbol","title":"channel(_:createdMetaData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"createdMetaData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"A callback when meta data was created in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:createdMetaData:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:createdmetadata:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:userWasUnmuted:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:userWasUnmuted:"}],"role":"symbol","title":"channel(_:userWasUnmuted:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userWasUnmuted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a user was unmuted in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:userWasUnmuted:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:userwasunmuted:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:userWasBanned:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:userWasBanned:"}],"role":"symbol","title":"channel(_:userWasBanned:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userWasBanned"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a user was banned in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:userWasBanned:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:userwasbanned:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channelWasFrozen(_:)":{"navigatorTitle":[{"kind":"identifier","text":"channelWasFrozen:"}],"role":"symbol","title":"channelWasFrozen(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelWasFrozen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when an channel was frozen."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channelWasFrozen(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channelwasfrozen(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:didUpdate:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:didUpdateMessage:"}],"role":"symbol","title":"channel(_:didUpdate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a message is updated."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:didUpdate:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:didupdate:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/didUpdatePoll(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didUpdatePoll:"}],"role":"symbol","title":"didUpdatePoll(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdatePoll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PollUpdateEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollUpdateEvent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when the poll has been updated."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/didUpdatePoll(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/didupdatepoll(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:didReceiveMention:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:didReceiveMention:"}],"role":"symbol","title":"channel(_:didReceiveMention:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveMention"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A delegate is called when someone mentioned the user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:didReceiveMention:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:didreceivemention:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:didUpdateThreadInfo:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:didUpdateThreadInfo:"}],"role":"symbol","title":"channel(_:didUpdateThreadInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateThreadInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThreadInfoUpdateEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadInfoUpdateEvent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Invoked when the thread information is updated."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:didUpdateThreadInfo:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:didupdatethreadinfo:)"},"../Classes/BaseChannel.html":{"title":"BaseChannel","titleInlineContent":[{"type":"codeVoice","code":"BaseChannel"}],"type":"link","identifier":"..\/Classes\/BaseChannel.html","url":"..\/Classes\/BaseChannel.html"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:updatedMetaCounters:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:updatedMetaCounters:"}],"role":"symbol","title":"channel(_:updatedMetaCounters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"updatedMetaCounters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"A callback when meta counters were updated in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:updatedMetaCounters:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:updatedmetacounters:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channelDidUpdateOperators(_:)":{"navigatorTitle":[{"kind":"identifier","text":"channelDidUpdateOperators:"}],"role":"symbol","title":"channelDidUpdateOperators(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidUpdateOperators"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when operators were updated in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channelDidUpdateOperators(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channeldidupdateoperators(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate/channel(_:messageWasDeleted:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:messageWasDeleted:"}],"role":"symbol","title":"channel(_:messageWasDeleted:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageWasDeleted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a message was removed in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:messageWasDeleted:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate\/channel(_:messagewasdeleted:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBDBaseChannelDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannelDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDBaseChannelDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:createdMetaCounters:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:createdMetaData:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:deletedMetaCountersKeys:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:deletedMetaDataKeys:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:didReceive:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:didReceiveMention:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:didUpdate:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:didUpdateThreadInfo:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:messageWasDeleted:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:updatedMetaCounters:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:updatedMetaData:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:updatedReaction:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:userWasBanned:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:userWasMuted:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:userWasUnbanned:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channel(_:userWasUnmuted:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channelDidUpdateOperators(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channelWasChanged(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channelWasDeleted(_:channelType:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channelWasFrozen(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/channelWasUnfrozen(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/didUpdatePoll(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate\/didVotePoll(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDBaseChannelDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/title","value":"SBDMessageCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:deletedMetaDataKeys:)\/title","value":"channel:deletedMetaDataKeys:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:deletedMetaDataKeys:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:deletedMetaDataKeys:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelDelegate\/title","value":"SBDOpenChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannelDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channelWasChanged(_:)\/title","value":"channelWasChanged:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channelWasChanged(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelWasChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:didReceive:)\/title","value":"channel:didReceiveMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:didReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didReceiveMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:deletedMetaCountersKeys:)\/title","value":"channel:deletedMetaCountersKeys:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:deletedMetaCountersKeys:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:deletedMetaCountersKeys:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection\/title","value":"SBDGroupChannelCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:updatedReaction:)\/title","value":"channel:updatedReaction:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:updatedReaction:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:updatedReaction:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channelWasDeleted(_:channelType:)\/title","value":"channelWasDeleted:channelType:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channelWasDeleted(_:channelType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelWasDeleted:channelType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:createdMetaCounters:)\/title","value":"channel:createdMetaCounters:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:createdMetaCounters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:createdMetaCounters:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:userWasUnbanned:)\/title","value":"channel:userWasUnbanned:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:userWasUnbanned:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userWasUnbanned:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1didVotePoll(_:)\/title","value":"didVotePoll:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1didVotePoll(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didVotePoll:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:userWasMuted:)\/title","value":"channel:userWasMuted:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:userWasMuted:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userWasMuted:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate\/title","value":"SBDBaseChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannelDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channelWasUnfrozen(_:)\/title","value":"channelWasUnfrozen:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channelWasUnfrozen(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelWasUnfrozen:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate\/title","value":"SBDGroupChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:updatedMetaData:)\/title","value":"channel:updatedMetaData:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:updatedMetaData:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:updatedMetaData:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:createdMetaData:)\/title","value":"channel:createdMetaData:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:createdMetaData:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:createdMetaData:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:userWasUnmuted:)\/title","value":"channel:userWasUnmuted:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:userWasUnmuted:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userWasUnmuted:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:userWasBanned:)\/title","value":"channel:userWasBanned:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:userWasBanned:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userWasBanned:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channelWasFrozen(_:)\/title","value":"channelWasFrozen:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channelWasFrozen(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelWasFrozen:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:didUpdate:)\/title","value":"channel:didUpdateMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:didUpdate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didUpdateMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1didUpdatePoll(_:)\/title","value":"didUpdatePoll:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1didUpdatePoll(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdatePoll:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:didReceiveMention:)\/title","value":"channel:didReceiveMention:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:didReceiveMention:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didReceiveMention:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:didUpdateThreadInfo:)\/title","value":"channel:didUpdateThreadInfo:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:didUpdateThreadInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didUpdateThreadInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:updatedMetaCounters:)\/title","value":"channel:updatedMetaCounters:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:updatedMetaCounters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:updatedMetaCounters:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channelDidUpdateOperators(_:)\/title","value":"channelDidUpdateOperators:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channelDidUpdateOperators(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidUpdateOperators:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:messageWasDeleted:)\/title","value":"channel:messageWasDeleted:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate~1channel(_:messageWasDeleted:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:messageWasDeleted:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}