{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDBaseMessage) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessage"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basemessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basemessage"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AdminMessage","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Serializable","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/s12IdentifiableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":" class represents the base message which is generated by a user or an admin."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":", the "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"AdminMessage"},{"type":"text","text":" are derived from this class."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessage"}],"title":"BaseMessage","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"BaseMessage"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/channelType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/channelURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/createdAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/customType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/data","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/errorCode","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/id-3azpc","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isOperatorMessage","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isReplyToChannel","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isSilent","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/mentionType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/mentionedMessageTemplate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/mentionedUsers","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/message","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/messageID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/messageParams","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/messageSurvivalSeconds","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/metaArrays","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/ogMetaData","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/parentMessage","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/parentMessageID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/plugins","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/reactions","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/requestID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/requestedMentionUserIDs","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/scheduledInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/sender","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/sendingStatus","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/silent","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/threadInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/updatedAt"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/apply(_:)-640ud","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/apply(_:)-v8su","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/copyWithFailedState()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/copyWithFailedState(errorCode:)-93sn7","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/copyWithFailedState(errorCode:)-gz6s","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/encode(to:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/getThreadedMessages(timestamp:params:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isGroupChannel()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isOpenChannel()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isResendable()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/metaArrays(keys:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/build(fromSerializedData:desiredState:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/getMessage(params:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/getScheduledMessage(params:completionHandler:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/Identifiable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/Mappable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/NSCopying-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/Serializable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/customType":{"role":"symbol","title":"customType","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Custom message type."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/customType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customType"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/customtype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/mentionedUsers":{"role":"symbol","title":"mentionedUsers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionedUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The list of users who was mentioned together with the message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/mentionedUsers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mentionedUsers"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/mentionedusers"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/parentMessageID":{"role":"symbol","title":"parentMessageID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentMessageID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The unique ID of the parent message. If the message object is a parent message or a single message"},{"type":"text","text":" "},{"type":"text","text":"without any reply, the value of this property is 0. If the object is a reply, the value is the unique ID of its parent message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/parentMessageID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parentMessageID"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/parentmessageid"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage":{"role":"symbol","title":"BaseMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessage"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":" class represents the base message which is generated by a user or an admin."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":", the "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"AdminMessage"},{"type":"text","text":" are derived from this class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessage"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/copyWithFailedState()":{"role":"symbol","title":"copyWithFailedState()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copyWithFailedState"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Copies this message with fail state"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/copyWithFailedState()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithFailedState"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/copywithfailedstate()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/data":{"role":"symbol","title":"data","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The custom data for message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/data","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"data"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/data"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/isOpenChannel()":{"role":"symbol","title":"isOpenChannel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOpenChannel"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checks the channel type is open channel or not."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isOpenChannel()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isOpenChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/isopenchannel()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/apply(_:)-640ud":{"role":"symbol","title":"apply(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apply"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ThreadInfoUpdateEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadInfoUpdateEvent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Applies the update of the thread information to the message object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/apply(_:)-640ud","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applyThreadInfoUpdateEvent:"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/apply(_:)-640ud"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/createdAt":{"role":"symbol","title":"createdAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"createdAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Message created time in millisecond(UTC)."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/createdAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createdAt"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/createdat"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/channelType":{"role":"symbol","title":"channelType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"}],"abstract":[{"type":"text","text":"Channel type of this message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/channelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelType"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/channeltype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/requestedMentionUserIDs":{"role":"symbol","title":"requestedMentionUserIDs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestedMentionUserIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Represents target user IDs to mention when success to send the message."},{"type":"text","text":" "},{"type":"text","text":"This value is valid only when the message is a pending message or failed message."},{"type":"text","text":" "},{"type":"text","text":"If the message is a succeeded message, see "},{"type":"codeVoice","code":"mentionedUserIDs"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/requestedMentionUserIDs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestedMentionUserIDs"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/requestedmentionuserids"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/mentionedMessageTemplate":{"role":"symbol","title":"mentionedMessageTemplate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionedMessageTemplate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The template for the message that has the mentioned users."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/mentionedMessageTemplate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mentionedMessageTemplate"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/mentionedmessagetemplate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/basemessage\/init(from:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Mappable":{"role":"symbol","title":"Mappable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mappable"}],"abstract":[{"type":"text","text":"Mappable protocol to initialize sendbird object from a given dictionary."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Mappable"}],"url":"\/documentation\/sendbirdchatsdk\/mappable"},"https://docs.sendbird.com/platform#messages_3_send":{"title":"Send a message","titleInlineContent":[{"type":"text","text":"Send a message"}],"type":"link","identifier":"https:\/\/docs.sendbird.com\/platform#messages_3_send","url":"https:\/\/docs.sendbird.com\/platform#messages_3_send"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/messageParams":{"role":"symbol","title":"messageParams","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessageCreateParams"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"An object that was used to resend this message. This property is valid when the sendingStatus is "},{"type":"codeVoice","code":"MessageSendingStatus.pending"},{"type":"text","text":" or "},{"type":"codeVoice","code":"MessageSendingStatus.failed"},{"type":"text","text":". When this message is trying to be resent, this property will be used as well. If the message object is "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":" class, then the "},{"type":"codeVoice","code":"messageParams"},{"type":"text","text":" has to be casted to "},{"type":"codeVoice","code":"UserMessageCreateParams"},{"type":"text","text":" class. If the message object is "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" class, then the "},{"type":"codeVoice","code":"messageParams"},{"type":"text","text":" has to be casted to "},{"type":"codeVoice","code":"FileMessageCreateParams"},{"type":"text","text":" class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/messageParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageParams"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/messageparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/metaArrays(keys:)":{"role":"symbol","title":"metaArrays(keys:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaArrays"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> ["},{"kind":"typeIdentifier","text":"MessageMetaArray","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageMetaArray"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Returns an array of meta arrays for keys."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/metaArrays(keys:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metaArraysWithKeys:"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/metaarrays(keys:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/messageID":{"role":"symbol","title":"messageID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Unique message ID."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/messageID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageID"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/messageid"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/message":{"role":"symbol","title":"message","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Message text."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/message","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"message"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/message"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/isOperatorMessage":{"role":"symbol","title":"isOperatorMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOperatorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Represents whether this message was created by an operator."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isOperatorMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isOperatorMessage"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/isoperatormessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/build(fromSerializedData:desiredState:)":{"role":"symbol","title":"build(fromSerializedData:desiredState:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromSerializedData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"desiredState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageSendingStatus","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageSendingStatus"},{"kind":"text","text":") -> `Self`"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Deserializes and reconstructs the object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/build(fromSerializedData:desiredState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildFromSerializedData:desiredState:"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/build(fromserializeddata:desiredstate:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage":{"role":"symbol","title":"FileMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessage"}],"abstract":[{"type":"text","text":"Represents a mesage object that contains a file. Derived from "},{"type":"codeVoice","code":"BaseMessage"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessage"}],"url":"\/documentation\/sendbirdchatsdk\/filemessage"},"doc://com.sendbird.chat/s12IdentifiableP":{"type":"unresolvable","title":"Swift.Identifiable","identifier":"doc:\/\/com.sendbird.chat\/s12IdentifiableP"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AdminMessage":{"role":"symbol","title":"AdminMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdminMessage"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"AdminMessage"},{"type":"text","text":" class represents a "},{"type":"text","text":"message"},{"type":"text","text":" which is sent by an admin"},{"type":"text","text":" "},{"type":"text","text":"via "},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.sendbird.com\/platform"},{"type":"text","text":". The admin "},{"type":"text","text":"message"},{"type":"text","text":" "},{"type":"text","text":"doesn’t have a sender. This "},{"type":"text","text":"message"},{"type":"text","text":" is sutable for a notice to inform the members"},{"type":"text","text":" "},{"type":"text","text":"in a group channel or the participants in an open channel. If you would like to know about the Platform API"},{"type":"text","text":" "},{"type":"text","text":"for the "},{"type":"text","text":"message"},{"type":"text","text":", see "},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.sendbird.com\/platform#messages_3_send"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AdminMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdminMessage"}],"url":"\/documentation\/sendbirdchatsdk\/adminmessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/copyWithFailedState(errorCode:)-gz6s":{"role":"symbol","title":"copyWithFailedState(errorCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copyWithFailedState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Copies this message with fail state"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/copyWithFailedState(errorCode:)-gz6s","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/basemessage\/copywithfailedstate(errorcode:)-gz6s"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/threadInfo":{"role":"symbol","title":"threadInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"threadInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThreadInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadInfo"}],"abstract":[{"type":"text","text":"The thread info that belongs to this message object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/threadInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"threadInfo"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/threadinfo"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/getScheduledMessage(params:completionHandler:)":{"role":"symbol","title":"getScheduledMessage(params:completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getScheduledMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledMessageRetrievalParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledMessageRetrievalParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18BaseMessageHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get a message to be sent at the specified time."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/getScheduledMessage(params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getScheduledMessageWithParams:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/getscheduledmessage(params:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/isResendable()":{"role":"symbol","title":"isResendable()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isResendable"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checks message can resend."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isResendable()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isResendable"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/isresendable()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/isGroupChannel()":{"role":"symbol","title":"isGroupChannel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isGroupChannel"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checks the channel type is group channel or not."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isGroupChannel()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isGroupChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/isgroupchannel()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/apply(_:)-v8su":{"role":"symbol","title":"apply(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apply"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ReactionEvent","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDReactionEvent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Applies reaction event to this message"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/apply(_:)-v8su","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applyReactionEvent:"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/apply(_:)-v8su"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/id-3azpc":{"role":"symbol","title":"id","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"}],"abstract":[{"type":"text","text":"Identifier for the message conforming to "},{"type":"codeVoice","code":"Identifiable"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/id-3azpc","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"id"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/id-3azpc"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/requestID":{"role":"symbol","title":"requestID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/requestID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestID"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/requestid"},"https://docs.sendbird.com/platform":{"title":"Platform API","titleInlineContent":[{"type":"text","text":"Platform API"}],"type":"link","identifier":"https:\/\/docs.sendbird.com\/platform","url":"https:\/\/docs.sendbird.com\/platform"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/reactions":{"role":"symbol","title":"reactions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reactions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Reaction","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDReaction"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Reaction list on this message"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/reactions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reactions"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/reactions"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/Identifiable-Implementations":{"role":"collectionGroup","title":"Identifiable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/Identifiable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/basemessage\/identifiable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Encodes this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/basemessage\/encode(to:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/ogMetaData":{"role":"symbol","title":"ogMetaData","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ogMetaData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OGMetaData","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOGMetaData"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Optional open graph information if the message contains links."},{"type":"text","text":" "},{"type":"text","text":"We only support first open graph tag appearance on the first link"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/ogMetaData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ogMetaData"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/ogmetadata"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Compares this object with given other object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/isequal(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessage":{"role":"symbol","title":"UserMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMessage"}],"abstract":[{"type":"text","text":"Represents a mesage object that contains a text message. Derived from "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserMessage"}],"url":"\/documentation\/sendbirdchatsdk\/usermessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/metaArrays":{"role":"symbol","title":"metaArrays","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaArrays"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MessageMetaArray","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageMetaArray"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Gets an array of meta arrays sorted by chronological order."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/metaArrays","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metaArrays"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/metaarrays"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/parentMessage":{"role":"symbol","title":"parentMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Current message’s parent message object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/parentMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parentMessage"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/parentmessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/getThreadedMessages(timestamp:params:completionHandler:)":{"role":"symbol","title":"getThreadedMessages(timestamp:params:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getThreadedMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThreadedMessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadedMessageListParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThreadedMessageListHandler","preciseIdentifier":"s:15SendbirdChatSDK26ThreadedMessageListHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Retrieves the threaded replies of the current message depending on the timestamp. If the current message doesn’t have replies, the result is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/getThreadedMessages(timestamp:params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getThreadedMessagesWithTimestamp:params:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/getthreadedmessages(timestamp:params:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/channelURL":{"role":"symbol","title":"channelURL","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Channel URL which has this message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/channelURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelURL"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/channelurl"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/silent":{"role":"symbol","title":"silent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"silent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the message is silent or not"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/silent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"silent"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/silent"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/getMessage(params:completionHandler:)":{"role":"symbol","title":"getMessage(params:completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageRetrievalParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageRetrievalParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18BaseMessageHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Retrieves a message with a specified message ID."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/getMessage(params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getMessageWithParams:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/getmessage(params:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/Mappable-Implementations":{"role":"collectionGroup","title":"Mappable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/Mappable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/basemessage\/mappable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/updatedAt":{"role":"symbol","title":"updatedAt","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Message updated time in millisecond(UTC)."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/updatedAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updatedAt"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/updatedat"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/mentionType":{"role":"symbol","title":"mentionType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MentionType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMentionType"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/mentionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mentionType"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/mentiontype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/scheduledInfo":{"role":"symbol","title":"scheduledInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduledInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledInfo"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The scheduled info of the message if this is a scheduled message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/scheduledInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scheduledInfo"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/scheduledinfo"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/Serializable-Implementations":{"role":"collectionGroup","title":"Serializable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/Serializable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/basemessage\/serializable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/sender":{"role":"symbol","title":"sender","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Sender","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDSender"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sender of the "},{"type":"strong","inlineContent":[{"type":"text","text":"message"}]},{"type":"text","text":". This is represented by "},{"type":"codeVoice","code":"Sender"},{"type":"text","text":" class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/sender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sender"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/sender"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/messageSurvivalSeconds":{"role":"symbol","title":"messageSurvivalSeconds","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageSurvivalSeconds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Message survival seconds, default is -1"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/messageSurvivalSeconds","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageSurvivalSeconds"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/messagesurvivalseconds"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/isSilent":{"role":"symbol","title":"isSilent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSilent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the message is silent or not"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isSilent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isSilent"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/issilent"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/errorCode":{"role":"symbol","title":"errorCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The error code of file."},{"type":"text","text":" "},{"type":"text","text":"This value generated only when message send fails."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/errorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"errorCode"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/errorcode"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/plugins":{"role":"symbol","title":"plugins","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"plugins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Plugin","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPlugin"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"List of plugin that are corresponding to this message"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/plugins","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"plugins"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/plugins"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/isReplyToChannel":{"role":"symbol","title":"isReplyToChannel","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isReplyToChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether current message is also shown on channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isReplyToChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isReplyToChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/isreplytochannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/NSCopying-Implementations":{"role":"collectionGroup","title":"NSCopying Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/NSCopying-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/basemessage\/nscopying-implementations"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Serializable":{"role":"symbol","title":"Serializable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Serializable"}],"abstract":[{"type":"text","text":"Protocol to provide serialization"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Serializable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Serializable"}],"url":"\/documentation\/sendbirdchatsdk\/serializable"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/copyWithFailedState(errorCode:)-93sn7":{"role":"symbol","title":"copyWithFailedState(errorCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copyWithFailedState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Copies this message with fail state"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/copyWithFailedState(errorCode:)-93sn7","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithFailedStateWithErrorCode:"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/copywithfailedstate(errorcode:)-93sn7"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage/sendingStatus":{"role":"symbol","title":"sendingStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendingStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageSendingStatus","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageSendingStatus"}],"abstract":[{"type":"text","text":"Represents the dispatch state of the message."},{"type":"text","text":" "},{"type":"text","text":"If message is not dispatched completely to the Sendbird server, the value is "},{"type":"codeVoice","code":".pending"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If failed to send the message, the value is "},{"type":"codeVoice","code":".failed"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"And if success to send the message, the value is "},{"type":"codeVoice","code":".succeeded"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/sendingStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendingStatus"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage\/sendingstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDBaseMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessage"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDBaseMessage"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/channelType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/channelURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/createdAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/customType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/data","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/errorCode","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/id-3azpc","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isOperatorMessage","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isReplyToChannel","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isSilent","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/mentionType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/mentionedMessageTemplate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/mentionedUsers","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/message","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/messageID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/messageParams","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/messageSurvivalSeconds","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/metaArrays","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/ogMetaData","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/parentMessage","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/parentMessageID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/plugins","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/reactions","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/requestID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/requestedMentionUserIDs","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/scheduledInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/sender","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/sendingStatus","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/silent","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/threadInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/updatedAt"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/apply(_:)-640ud","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/apply(_:)-v8su","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/copyWithFailedState()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/copyWithFailedState(errorCode:)-93sn7","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/getThreadedMessages(timestamp:params:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isGroupChannel()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isOpenChannel()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/isResendable()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/metaArrays(keys:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/build(fromSerializedData:desiredState:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/getMessage(params:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/getScheduledMessage(params:completionHandler:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/Mappable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/NSCopying-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage\/Serializable-Implementations"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDBaseMessage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1customType\/title","value":"customType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1customType\/fragments","value":[{"kind":"identifier","text":"customType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1mentionedUsers\/title","value":"mentionedUsers"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1mentionedUsers\/fragments","value":[{"kind":"identifier","text":"mentionedUsers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1parentMessageID\/title","value":"parentMessageID"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1parentMessageID\/fragments","value":[{"kind":"identifier","text":"parentMessageID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/title","value":"SBDBaseMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1copyWithFailedState()\/title","value":"copyWithFailedState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1copyWithFailedState()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithFailedState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1data\/title","value":"data"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1data\/fragments","value":[{"kind":"identifier","text":"data"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1isOpenChannel()\/title","value":"isOpenChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1isOpenChannel()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isOpenChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1apply(_:)-640ud\/title","value":"applyThreadInfoUpdateEvent:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1apply(_:)-640ud\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyThreadInfoUpdateEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1createdAt\/title","value":"createdAt"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1createdAt\/fragments","value":[{"kind":"identifier","text":"createdAt"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1channelType\/title","value":"channelType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1channelType\/fragments","value":[{"kind":"identifier","text":"channelType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1requestedMentionUserIDs\/title","value":"requestedMentionUserIDs"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1requestedMentionUserIDs\/fragments","value":[{"kind":"identifier","text":"requestedMentionUserIDs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1mentionedMessageTemplate\/title","value":"mentionedMessageTemplate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1mentionedMessageTemplate\/fragments","value":[{"kind":"identifier","text":"mentionedMessageTemplate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/title","value":"Mappable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/fragments","value":[{"kind":"identifier","text":"Mappable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1messageParams\/title","value":"messageParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1messageParams\/fragments","value":[{"kind":"identifier","text":"messageParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1metaArrays(keys:)\/title","value":"metaArraysWithKeys:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1metaArrays(keys:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"metaArraysWithKeys:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1messageID\/title","value":"messageID"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1messageID\/fragments","value":[{"kind":"identifier","text":"messageID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1message\/title","value":"message"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1message\/fragments","value":[{"kind":"identifier","text":"message"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1isOperatorMessage\/title","value":"isOperatorMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1isOperatorMessage\/fragments","value":[{"kind":"identifier","text":"isOperatorMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1build(fromSerializedData:desiredState:)\/title","value":"buildFromSerializedData:desiredState:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1build(fromSerializedData:desiredState:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildFromSerializedData:desiredState:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage\/title","value":"SBDFileMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage\/fragments","value":[{"kind":"identifier","text":"SBDFileMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AdminMessage\/title","value":"SBDAdminMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AdminMessage\/fragments","value":[{"kind":"identifier","text":"SBDAdminMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1threadInfo\/title","value":"threadInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1threadInfo\/fragments","value":[{"kind":"identifier","text":"threadInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1getScheduledMessage(params:completionHandler:)\/title","value":"getScheduledMessageWithParams:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1getScheduledMessage(params:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getScheduledMessageWithParams:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1isResendable()\/title","value":"isResendable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1isResendable()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isResendable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1isGroupChannel()\/title","value":"isGroupChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1isGroupChannel()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isGroupChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1apply(_:)-v8su\/title","value":"applyReactionEvent:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1apply(_:)-v8su\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyReactionEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1id-3azpc\/title","value":"id"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1id-3azpc\/fragments","value":[{"kind":"identifier","text":"id"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1requestID\/title","value":"requestID"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1requestID\/fragments","value":[{"kind":"identifier","text":"requestID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1reactions\/title","value":"reactions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1reactions\/fragments","value":[{"kind":"identifier","text":"reactions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1ogMetaData\/title","value":"ogMetaData"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1ogMetaData\/fragments","value":[{"kind":"identifier","text":"ogMetaData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessage\/title","value":"SBDUserMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessage\/fragments","value":[{"kind":"identifier","text":"SBDUserMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1metaArrays\/title","value":"metaArrays"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1metaArrays\/fragments","value":[{"kind":"identifier","text":"metaArrays"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1parentMessage\/title","value":"parentMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1parentMessage\/fragments","value":[{"kind":"identifier","text":"parentMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1getThreadedMessages(timestamp:params:completionHandler:)\/title","value":"getThreadedMessagesWithTimestamp:params:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1getThreadedMessages(timestamp:params:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getThreadedMessagesWithTimestamp:params:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1channelURL\/title","value":"channelURL"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1channelURL\/fragments","value":[{"kind":"identifier","text":"channelURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1silent\/title","value":"silent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1silent\/fragments","value":[{"kind":"identifier","text":"silent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1getMessage(params:completionHandler:)\/title","value":"getMessageWithParams:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1getMessage(params:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getMessageWithParams:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1updatedAt\/title","value":"updatedAt"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1updatedAt\/fragments","value":[{"kind":"identifier","text":"updatedAt"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1mentionType\/title","value":"mentionType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1mentionType\/fragments","value":[{"kind":"identifier","text":"mentionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1scheduledInfo\/title","value":"scheduledInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1scheduledInfo\/fragments","value":[{"kind":"identifier","text":"scheduledInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1sender\/title","value":"sender"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1sender\/fragments","value":[{"kind":"identifier","text":"sender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1messageSurvivalSeconds\/title","value":"messageSurvivalSeconds"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1messageSurvivalSeconds\/fragments","value":[{"kind":"identifier","text":"messageSurvivalSeconds"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1isSilent\/title","value":"isSilent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1isSilent\/fragments","value":[{"kind":"identifier","text":"isSilent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1errorCode\/title","value":"errorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1errorCode\/fragments","value":[{"kind":"identifier","text":"errorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1plugins\/title","value":"plugins"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1plugins\/fragments","value":[{"kind":"identifier","text":"plugins"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1isReplyToChannel\/title","value":"isReplyToChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1isReplyToChannel\/fragments","value":[{"kind":"identifier","text":"isReplyToChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Serializable\/title","value":"Serializable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Serializable\/fragments","value":[{"kind":"identifier","text":"Serializable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1copyWithFailedState(errorCode:)-93sn7\/title","value":"copyWithFailedStateWithErrorCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1copyWithFailedState(errorCode:)-93sn7\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithFailedStateWithErrorCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1sendingStatus\/title","value":"sendingStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage~1sendingStatus\/fragments","value":[{"kind":"identifier","text":"sendingStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}