{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDChannelMetaCountersUpdateMode) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelMetaCountersUpdateMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/decrease","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/increase","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/set"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelMetaCountersUpdateMode"}],"title":"ChannelMetaCountersUpdateMode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDChannelMetaCountersUpdateMode","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ChannelMetaCountersUpdateMode"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"references":{"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelMetaCountersUpdateMode/decrease":{"role":"symbol","title":"ChannelMetaCountersUpdateMode.decrease","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decrease"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/decrease","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeDecrease"}],"url":"\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/decrease"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelMetaCountersUpdateMode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelMetaCountersUpdateMode/set":{"role":"symbol","title":"ChannelMetaCountersUpdateMode.set","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/set","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeSet"}],"url":"\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/set"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelMetaCountersUpdateMode/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/decodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelMetaCountersUpdateMode":{"role":"symbol","title":"ChannelMetaCountersUpdateMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelMetaCountersUpdateMode"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelMetaCountersUpdateMode"}],"url":"\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelMetaCountersUpdateMode/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/encodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelMetaCountersUpdateMode/increase":{"role":"symbol","title":"ChannelMetaCountersUpdateMode.increase","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"increase"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/increase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeIncrease"}],"url":"\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/increase"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelMetaCountersUpdateMode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/channelmetacountersupdatemode\/rawrepresentable-implementations"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDChannelMetaCountersUpdateMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/decrease","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/increase","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelMetaCountersUpdateMode\/set"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDChannelMetaCountersUpdateMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode~1decrease\/title","value":"SBDChannelMetaCountersUpdateModeDecrease"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode~1decrease\/fragments","value":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeDecrease"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode~1set\/title","value":"SBDChannelMetaCountersUpdateModeSet"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode~1set\/fragments","value":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeSet"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode\/title","value":"SBDChannelMetaCountersUpdateMode"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode\/fragments","value":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode~1increase\/title","value":"SBDChannelMetaCountersUpdateModeIncrease"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelMetaCountersUpdateMode~1increase\/fragments","value":[{"kind":"identifier","text":"SBDChannelMetaCountersUpdateModeIncrease"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}