{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDChannelHiddenStateFilter) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelHiddenStateFilter"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.122"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The enum type to filter my group channels with the hidden state."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelHiddenStateFilter"}],"title":"ChannelHiddenStateFilter","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDChannelHiddenStateFilter","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ChannelHiddenStateFilter"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/all","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/hiddenAllowAutoUnhide","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/hiddenOnly","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/hiddenPreventAutoUnhide","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/unhiddenOnly"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelHiddenStateFilter/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter\/encodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelHiddenStateFilter/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter\/equatable-implementations"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelHiddenStateFilter/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter\/decodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelHiddenStateFilter/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelHiddenStateFilter":{"role":"symbol","title":"ChannelHiddenStateFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelHiddenStateFilter"}],"abstract":[{"type":"text","text":"The enum type to filter my group channels with the hidden state."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelHiddenStateFilter"}],"url":"\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelHiddenStateFilter/all":{"role":"symbol","title":"ChannelHiddenStateFilter.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[{"type":"text","text":"Shows all channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDChannelHiddenStateFilterAll"}],"url":"\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter\/all"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelHiddenStateFilter/unhiddenOnly":{"role":"symbol","title":"ChannelHiddenStateFilter.unhiddenOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unhiddenOnly"}],"abstract":[{"type":"text","text":"Shows the unhidden channels only."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/unhiddenOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDChannelHiddenStateFilterUnhiddenOnly"}],"url":"\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter\/unhiddenonly"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelHiddenStateFilter/hiddenAllowAutoUnhide":{"role":"symbol","title":"ChannelHiddenStateFilter.hiddenAllowAutoUnhide","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenAllowAutoUnhide"}],"abstract":[{"type":"text","text":"Shows the channels will be unhidden automatically when there is a new message in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/hiddenAllowAutoUnhide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDChannelHiddenStateFilterHiddenAllowAutoUnhide"}],"url":"\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter\/hiddenallowautounhide"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelHiddenStateFilter/hiddenOnly":{"role":"symbol","title":"ChannelHiddenStateFilter.hiddenOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenOnly"}],"abstract":[{"type":"text","text":"Shows the hidden channels only."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/hiddenOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDChannelHiddenStateFilterHiddenOnly"}],"url":"\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter\/hiddenonly"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelHiddenStateFilter/hiddenPreventAutoUnhide":{"role":"symbol","title":"ChannelHiddenStateFilter.hiddenPreventAutoUnhide","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenPreventAutoUnhide"}],"abstract":[{"type":"text","text":"Shows the channels will not be unhidden automatically."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/hiddenPreventAutoUnhide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDChannelHiddenStateFilterHiddenPreventAutoUnhide"}],"url":"\/documentation\/sendbirdchatsdk\/channelhiddenstatefilter\/hiddenpreventautounhide"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDChannelHiddenStateFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDChannelHiddenStateFilter"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDChannelHiddenStateFilter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/all","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/hiddenAllowAutoUnhide","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/hiddenOnly","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/hiddenPreventAutoUnhide","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelHiddenStateFilter\/unhiddenOnly"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDChannelHiddenStateFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter\/title","value":"SBDChannelHiddenStateFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter\/fragments","value":[{"kind":"identifier","text":"SBDChannelHiddenStateFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter~1all\/title","value":"SBDChannelHiddenStateFilterAll"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter~1all\/fragments","value":[{"kind":"identifier","text":"SBDChannelHiddenStateFilterAll"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter~1unhiddenOnly\/title","value":"SBDChannelHiddenStateFilterUnhiddenOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter~1unhiddenOnly\/fragments","value":[{"kind":"identifier","text":"SBDChannelHiddenStateFilterUnhiddenOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter~1hiddenAllowAutoUnhide\/title","value":"SBDChannelHiddenStateFilterHiddenAllowAutoUnhide"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter~1hiddenAllowAutoUnhide\/fragments","value":[{"kind":"identifier","text":"SBDChannelHiddenStateFilterHiddenAllowAutoUnhide"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter~1hiddenOnly\/title","value":"SBDChannelHiddenStateFilterHiddenOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter~1hiddenOnly\/fragments","value":[{"kind":"identifier","text":"SBDChannelHiddenStateFilterHiddenOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter~1hiddenPreventAutoUnhide\/title","value":"SBDChannelHiddenStateFilterHiddenPreventAutoUnhide"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelHiddenStateFilter~1hiddenPreventAutoUnhide\/fragments","value":[{"kind":"identifier","text":"SBDChannelHiddenStateFilterHiddenPreventAutoUnhide"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}