{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDCollectionEventSource) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionEventSource"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Since 3.0.227"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/collectioneventsource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/collectioneventsource"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Channel sources that represents where the channel object comes from."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionEventSource"}],"title":"CollectionEventSource","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDCollectionEventSource","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CollectionEventSource"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/channelChangelog","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelChanged","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelDeleted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelFrozen","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelHidden","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelMemberCountChanged","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelUnfrozen","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventDeliveryStatusUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMention","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMessageDeleted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMessageReceived","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMessageSent","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMessageUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaCounterCreated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaCounterDeleted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaCounterUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaDataCreated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaDataDeleted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaDataUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventOperatorUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventReactionUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventReadStatusUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventThreadInfoUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventTypingStatusUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserBanned","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserDeclinedInvitation","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserJoined","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserLeft","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserMuted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserReceivedInvitation","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserUnbanned","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserUnmuted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/localMessageCanceled","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/localMessageFailed","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/localMessagePendingCreated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/localMessageResendStarted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/messageChangelog","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/messageFill"]},{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventReactionUpdated":{"role":"symbol","title":"CollectionEventSource.eventReactionUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventReactionUpdated"}],"abstract":[{"type":"text","text":"Reaction has been updated"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventReactionUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventReactionUpdated"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventreactionupdated"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventMetaCounterDeleted":{"role":"symbol","title":"CollectionEventSource.eventMetaCounterDeleted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventMetaCounterDeleted"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaCounterDeleted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMetaCounterDeleted"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventmetacounterdeleted"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventMessageReceived":{"role":"symbol","title":"CollectionEventSource.eventMessageReceived","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventMessageReceived"}],"abstract":[{"type":"text","text":"Message has been received"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMessageReceived","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMessageReceived"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventmessagereceived"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventThreadInfoUpdated":{"role":"symbol","title":"CollectionEventSource.eventThreadInfoUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventThreadInfoUpdated"}],"abstract":[{"type":"text","text":"Message thread info has been updated"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventThreadInfoUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventThreadInfoUpdated"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventthreadinfoupdated"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/messageChangelog":{"role":"symbol","title":"CollectionEventSource.messageChangelog","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageChangelog"}],"abstract":[{"type":"text","text":"Message change log"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/messageChangelog","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceMessageChangelog"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/messagechangelog"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/localMessagePendingCreated":{"role":"symbol","title":"CollectionEventSource.localMessagePendingCreated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localMessagePendingCreated"}],"abstract":[{"type":"text","text":"Pending message has been created"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/localMessagePendingCreated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceLocalMessagePendingCreated"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/localmessagependingcreated"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/channelChangelog":{"role":"symbol","title":"CollectionEventSource.channelChangelog","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelChangelog"}],"abstract":[{"type":"text","text":"Channel change log"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/channelChangelog","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceChannelChangelog"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/channelchangelog"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource":{"role":"symbol","title":"CollectionEventSource","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionEventSource"}],"abstract":[{"type":"text","text":"Channel sources that represents where the channel object comes from."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CollectionEventSource"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventChannelDeleted":{"role":"symbol","title":"CollectionEventSource.eventChannelDeleted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventChannelDeleted"}],"abstract":[{"type":"text","text":"Channel has been deleted"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelDeleted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelDeleted"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventchanneldeleted"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventUserBanned":{"role":"symbol","title":"CollectionEventSource.eventUserBanned","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventUserBanned"}],"abstract":[{"type":"text","text":"User has been banned"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserBanned","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserBanned"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventuserbanned"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventUserReceivedInvitation":{"role":"symbol","title":"CollectionEventSource.eventUserReceivedInvitation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventUserReceivedInvitation"}],"abstract":[{"type":"text","text":"User receives group channel invitation"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserReceivedInvitation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserReceivedInvitation"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventuserreceivedinvitation"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventChannelUnfrozen":{"role":"symbol","title":"CollectionEventSource.eventChannelUnfrozen","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventChannelUnfrozen"}],"abstract":[{"type":"text","text":"Channel has been unfrozen"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelUnfrozen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelUnfrozen"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventchannelunfrozen"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventMetaCounterUpdated":{"role":"symbol","title":"CollectionEventSource.eventMetaCounterUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventMetaCounterUpdated"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaCounterUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMetaCounterUpdated"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventmetacounterupdated"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/init(rawvalue:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventChannelChanged":{"role":"symbol","title":"CollectionEventSource.eventChannelChanged","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventChannelChanged"}],"abstract":[{"type":"text","text":"Channel has been changed"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelChanged","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelChanged"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventchannelchanged"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventUserUnmuted":{"role":"symbol","title":"CollectionEventSource.eventUserUnmuted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventUserUnmuted"}],"abstract":[{"type":"text","text":"User has been umuted"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserUnmuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserUnmuted"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventuserunmuted"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventMessageUpdated":{"role":"symbol","title":"CollectionEventSource.eventMessageUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventMessageUpdated"}],"abstract":[{"type":"text","text":"Message has been updated"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMessageUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMessageUpdated"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventmessageupdated"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/localMessageResendStarted":{"role":"symbol","title":"CollectionEventSource.localMessageResendStarted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localMessageResendStarted"}],"abstract":[{"type":"text","text":"Message has been resent"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/localMessageResendStarted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceLocalMessageResendStarted"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/localmessageresendstarted"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventOperatorUpdated":{"role":"symbol","title":"CollectionEventSource.eventOperatorUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventOperatorUpdated"}],"abstract":[{"type":"text","text":"Channel’s operators have been updated"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventOperatorUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventOperatorUpdated"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventoperatorupdated"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/localMessageFailed":{"role":"symbol","title":"CollectionEventSource.localMessageFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localMessageFailed"}],"abstract":[{"type":"text","text":"Message has been failed"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/localMessageFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceLocalMessageFailed"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/localmessagefailed"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventChannelMemberCountChanged":{"role":"symbol","title":"CollectionEventSource.eventChannelMemberCountChanged","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventChannelMemberCountChanged"}],"abstract":[{"type":"text","text":"Channel member count has been changed"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelMemberCountChanged","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelMemberCountChanged"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventchannelmembercountchanged"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventUserJoined":{"role":"symbol","title":"CollectionEventSource.eventUserJoined","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventUserJoined"}],"abstract":[{"type":"text","text":"User joins group channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserJoined","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserJoined"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventuserjoined"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventChannelFrozen":{"role":"symbol","title":"CollectionEventSource.eventChannelFrozen","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventChannelFrozen"}],"abstract":[{"type":"text","text":"Channel has been frozen"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelFrozen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelFrozen"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventchannelfrozen"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventUserUnbanned":{"role":"symbol","title":"CollectionEventSource.eventUserUnbanned","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventUserUnbanned"}],"abstract":[{"type":"text","text":"User has been unbanned"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserUnbanned","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserUnbanned"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventuserunbanned"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/messageFill":{"role":"symbol","title":"CollectionEventSource.messageFill","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageFill"}],"abstract":[{"type":"text","text":"Message gap has been filled"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/messageFill","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceMessageFill"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/messagefill"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventDeliveryStatusUpdated":{"role":"symbol","title":"CollectionEventSource.eventDeliveryStatusUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventDeliveryStatusUpdated"}],"abstract":[{"type":"text","text":"Channel delivery status has been updated"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventDeliveryStatusUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventDeliveryStatusUpdated"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventdeliverystatusupdated"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventUserMuted":{"role":"symbol","title":"CollectionEventSource.eventUserMuted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventUserMuted"}],"abstract":[{"type":"text","text":"User has been muted"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserMuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserMuted"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventusermuted"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventUserLeft":{"role":"symbol","title":"CollectionEventSource.eventUserLeft","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventUserLeft"}],"abstract":[{"type":"text","text":"User leave group channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserLeft","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserLeft"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventuserleft"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventMetaDataDeleted":{"role":"symbol","title":"CollectionEventSource.eventMetaDataDeleted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventMetaDataDeleted"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaDataDeleted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMetaDataDeleted"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventmetadatadeleted"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventMetaDataCreated":{"role":"symbol","title":"CollectionEventSource.eventMetaDataCreated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventMetaDataCreated"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaDataCreated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMetaDataCreated"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventmetadatacreated"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventMetaCounterCreated":{"role":"symbol","title":"CollectionEventSource.eventMetaCounterCreated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventMetaCounterCreated"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaCounterCreated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMetaCounterCreated"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventmetacountercreated"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventChannelHidden":{"role":"symbol","title":"CollectionEventSource.eventChannelHidden","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventChannelHidden"}],"abstract":[{"type":"text","text":"Channel has been hidden"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelHidden","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelHidden"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventchannelhidden"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventMetaDataUpdated":{"role":"symbol","title":"CollectionEventSource.eventMetaDataUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventMetaDataUpdated"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaDataUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMetaDataUpdated"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventmetadataupdated"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventMessageSent":{"role":"symbol","title":"CollectionEventSource.eventMessageSent","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventMessageSent"}],"abstract":[{"type":"text","text":"Message has been sent"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMessageSent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMessageSent"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventmessagesent"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/localMessageCanceled":{"role":"symbol","title":"CollectionEventSource.localMessageCanceled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localMessageCanceled"}],"abstract":[{"type":"text","text":"Message has been canceled"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/localMessageCanceled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceLocalMessageCanceled"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/localmessagecanceled"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventMention":{"role":"symbol","title":"CollectionEventSource.eventMention","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventMention"}],"abstract":[{"type":"text","text":"Message mention has been received"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMention","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMention"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventmention"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventUserDeclinedInvitation":{"role":"symbol","title":"CollectionEventSource.eventUserDeclinedInvitation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventUserDeclinedInvitation"}],"abstract":[{"type":"text","text":"User declines group channel invitation"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserDeclinedInvitation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserDeclinedInvitation"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventuserdeclinedinvitation"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventReadStatusUpdated":{"role":"symbol","title":"CollectionEventSource.eventReadStatusUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventReadStatusUpdated"}],"abstract":[{"type":"text","text":"Channel read status has been updated"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventReadStatusUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventReadStatusUpdated"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventreadstatusupdated"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventMessageDeleted":{"role":"symbol","title":"CollectionEventSource.eventMessageDeleted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventMessageDeleted"}],"abstract":[{"type":"text","text":"Message has been deleted"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMessageDeleted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMessageDeleted"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventmessagedeleted"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CollectionEventSource/eventTypingStatusUpdated":{"role":"symbol","title":"CollectionEventSource.eventTypingStatusUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventTypingStatusUpdated"}],"abstract":[{"type":"text","text":"Typing status has been udpated"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventTypingStatusUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCollectionEventSourceEventTypingStatusUpdated"}],"url":"\/documentation\/sendbirdchatsdk\/collectioneventsource\/eventtypingstatusupdated"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDCollectionEventSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSource"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDCollectionEventSource"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/channelChangelog","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelChanged","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelDeleted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelFrozen","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelHidden","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelMemberCountChanged","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventChannelUnfrozen","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventDeliveryStatusUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMention","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMessageDeleted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMessageReceived","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMessageSent","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMessageUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaCounterCreated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaCounterDeleted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaCounterUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaDataCreated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaDataDeleted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventMetaDataUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventOperatorUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventReactionUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventReadStatusUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventThreadInfoUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventTypingStatusUpdated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserBanned","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserDeclinedInvitation","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserJoined","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserLeft","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserMuted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserReceivedInvitation","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserUnbanned","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/eventUserUnmuted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/localMessageCanceled","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/localMessageFailed","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/localMessagePendingCreated","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/localMessageResendStarted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/messageChangelog","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CollectionEventSource\/messageFill"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDCollectionEventSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventReactionUpdated\/title","value":"SBDCollectionEventSourceEventReactionUpdated"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventReactionUpdated\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventReactionUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMetaCounterDeleted\/title","value":"SBDCollectionEventSourceEventMetaCounterDeleted"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMetaCounterDeleted\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMetaCounterDeleted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMessageReceived\/title","value":"SBDCollectionEventSourceEventMessageReceived"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMessageReceived\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMessageReceived"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventThreadInfoUpdated\/title","value":"SBDCollectionEventSourceEventThreadInfoUpdated"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventThreadInfoUpdated\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventThreadInfoUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1messageChangelog\/title","value":"SBDCollectionEventSourceMessageChangelog"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1messageChangelog\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceMessageChangelog"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1localMessagePendingCreated\/title","value":"SBDCollectionEventSourceLocalMessagePendingCreated"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1localMessagePendingCreated\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceLocalMessagePendingCreated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1channelChangelog\/title","value":"SBDCollectionEventSourceChannelChangelog"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1channelChangelog\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceChannelChangelog"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource\/title","value":"SBDCollectionEventSource"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSource"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelDeleted\/title","value":"SBDCollectionEventSourceEventChannelDeleted"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelDeleted\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelDeleted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserBanned\/title","value":"SBDCollectionEventSourceEventUserBanned"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserBanned\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserBanned"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserReceivedInvitation\/title","value":"SBDCollectionEventSourceEventUserReceivedInvitation"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserReceivedInvitation\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserReceivedInvitation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelUnfrozen\/title","value":"SBDCollectionEventSourceEventChannelUnfrozen"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelUnfrozen\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelUnfrozen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMetaCounterUpdated\/title","value":"SBDCollectionEventSourceEventMetaCounterUpdated"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMetaCounterUpdated\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMetaCounterUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelChanged\/title","value":"SBDCollectionEventSourceEventChannelChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelChanged\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserUnmuted\/title","value":"SBDCollectionEventSourceEventUserUnmuted"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserUnmuted\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserUnmuted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMessageUpdated\/title","value":"SBDCollectionEventSourceEventMessageUpdated"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMessageUpdated\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMessageUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1localMessageResendStarted\/title","value":"SBDCollectionEventSourceLocalMessageResendStarted"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1localMessageResendStarted\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceLocalMessageResendStarted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventOperatorUpdated\/title","value":"SBDCollectionEventSourceEventOperatorUpdated"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventOperatorUpdated\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventOperatorUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1localMessageFailed\/title","value":"SBDCollectionEventSourceLocalMessageFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1localMessageFailed\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceLocalMessageFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelMemberCountChanged\/title","value":"SBDCollectionEventSourceEventChannelMemberCountChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelMemberCountChanged\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelMemberCountChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserJoined\/title","value":"SBDCollectionEventSourceEventUserJoined"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserJoined\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserJoined"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelFrozen\/title","value":"SBDCollectionEventSourceEventChannelFrozen"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelFrozen\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelFrozen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserUnbanned\/title","value":"SBDCollectionEventSourceEventUserUnbanned"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserUnbanned\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserUnbanned"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1messageFill\/title","value":"SBDCollectionEventSourceMessageFill"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1messageFill\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceMessageFill"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventDeliveryStatusUpdated\/title","value":"SBDCollectionEventSourceEventDeliveryStatusUpdated"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventDeliveryStatusUpdated\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventDeliveryStatusUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserMuted\/title","value":"SBDCollectionEventSourceEventUserMuted"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserMuted\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserMuted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserLeft\/title","value":"SBDCollectionEventSourceEventUserLeft"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserLeft\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserLeft"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMetaDataDeleted\/title","value":"SBDCollectionEventSourceEventMetaDataDeleted"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMetaDataDeleted\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMetaDataDeleted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMetaDataCreated\/title","value":"SBDCollectionEventSourceEventMetaDataCreated"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMetaDataCreated\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMetaDataCreated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMetaCounterCreated\/title","value":"SBDCollectionEventSourceEventMetaCounterCreated"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMetaCounterCreated\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMetaCounterCreated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelHidden\/title","value":"SBDCollectionEventSourceEventChannelHidden"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventChannelHidden\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventChannelHidden"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMetaDataUpdated\/title","value":"SBDCollectionEventSourceEventMetaDataUpdated"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMetaDataUpdated\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMetaDataUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMessageSent\/title","value":"SBDCollectionEventSourceEventMessageSent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMessageSent\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMessageSent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1localMessageCanceled\/title","value":"SBDCollectionEventSourceLocalMessageCanceled"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1localMessageCanceled\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceLocalMessageCanceled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMention\/title","value":"SBDCollectionEventSourceEventMention"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMention\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMention"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserDeclinedInvitation\/title","value":"SBDCollectionEventSourceEventUserDeclinedInvitation"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventUserDeclinedInvitation\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventUserDeclinedInvitation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventReadStatusUpdated\/title","value":"SBDCollectionEventSourceEventReadStatusUpdated"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventReadStatusUpdated\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventReadStatusUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMessageDeleted\/title","value":"SBDCollectionEventSourceEventMessageDeleted"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventMessageDeleted\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventMessageDeleted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventTypingStatusUpdated\/title","value":"SBDCollectionEventSourceEventTypingStatusUpdated"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CollectionEventSource~1eventTypingStatusUpdated\/fragments","value":[{"kind":"identifier","text":"SBDCollectionEventSourceEventTypingStatusUpdated"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}