{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDConnectionDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/connectiondelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/connectiondelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents a delegate to receive connection relates events"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionDelegate"}],"title":"ConnectionDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDConnectionDelegate","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ConnectionDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate\/didConnect(userID:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate\/didDisconnect(userID:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate\/didFailReconnection()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate\/didStartReconnection()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate\/didSucceedReconnection()"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ConnectionDelegate":{"role":"symbol","title":"ConnectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionDelegate"}],"abstract":[{"type":"text","text":"Represents a delegate to receive connection relates events"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/connectiondelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ConnectionDelegate/didSucceedReconnection()":{"navigatorTitle":[{"kind":"identifier","text":"didSucceedReconnection"}],"role":"symbol","title":"didSucceedReconnection()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSucceedReconnection"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Invoked when reconnection is succeeded."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate\/didSucceedReconnection()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/connectiondelegate\/didsucceedreconnection()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection":{"role":"symbol","title":"GroupChannelCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelCollection"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection":{"role":"symbol","title":"MessageCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollection"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ConnectionDelegate/didConnect(userID:)":{"navigatorTitle":[{"kind":"identifier","text":"didConnectWithUserID:"}],"role":"symbol","title":"didConnect(userID:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didConnect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Invoked when connected."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate\/didConnect(userID:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/connectiondelegate\/didconnect(userid:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ConnectionDelegate/didStartReconnection()":{"navigatorTitle":[{"kind":"identifier","text":"didStartReconnection"}],"role":"symbol","title":"didStartReconnection()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartReconnection"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Invoked when reconnection starts."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate\/didStartReconnection()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/connectiondelegate\/didstartreconnection()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ConnectionDelegate/didFailReconnection()":{"navigatorTitle":[{"kind":"identifier","text":"didFailReconnection"}],"role":"symbol","title":"didFailReconnection()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailReconnection"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Invoked when reconnection is failed."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate\/didFailReconnection()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/connectiondelegate\/didfailreconnection()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ConnectionDelegate/didDisconnect(userID:)":{"navigatorTitle":[{"kind":"identifier","text":"didDisconnectWithUserID:"}],"role":"symbol","title":"didDisconnect(userID:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDisconnect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Invoked when disconnected."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate\/didDisconnect(userID:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/connectiondelegate\/diddisconnect(userid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBDConnectionDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDConnectionDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDConnectionDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate\/didConnect(userID:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate\/didDisconnect(userID:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate\/didFailReconnection()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate\/didStartReconnection()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate\/didSucceedReconnection()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDConnectionDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate\/title","value":"SBDConnectionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate\/fragments","value":[{"kind":"identifier","text":"SBDConnectionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate~1didSucceedReconnection()\/title","value":"didSucceedReconnection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate~1didSucceedReconnection()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didSucceedReconnection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection\/title","value":"SBDGroupChannelCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/title","value":"SBDMessageCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate~1didConnect(userID:)\/title","value":"didConnectWithUserID:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate~1didConnect(userID:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didConnectWithUserID:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate~1didStartReconnection()\/title","value":"didStartReconnection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate~1didStartReconnection()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didStartReconnection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate~1didFailReconnection()\/title","value":"didFailReconnection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate~1didFailReconnection()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFailReconnection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate~1didDisconnect(userID:)\/title","value":"didDisconnectWithUserID:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate~1didDisconnect(userID:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didDisconnectWithUserID:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}