{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBCoreError) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/coreerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/coreerror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorCode","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/s5ErrorP","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY","doc:\/\/com.sendbird.chat\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Core error code"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreError"}],"title":"CoreError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBCoreError","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CoreError"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/fileSizeLimitExceeded","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/fileUploadCancelFailed","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/fileUploadCanceled","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/fileUploadTimeout","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/internalServerError","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/malformedData","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/networkError","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/networkRoutingError","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/requestFailed","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/unknownError"]},{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/code","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/message"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/Error-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/RawRepresentable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/SBErrorCode-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/internalServerError":{"role":"symbol","title":"CoreError.internalServerError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServerError"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/internalServerError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBCoreErrorInternalServerError"}],"url":"\/documentation\/sendbirdchatsdk\/coreerror\/internalservererror"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/networkRoutingError":{"role":"symbol","title":"CoreError.networkRoutingError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkRoutingError"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/networkRoutingError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBCoreErrorNetworkRoutingError"}],"url":"\/documentation\/sendbirdchatsdk\/coreerror\/networkroutingerror"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/coreerror\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/SBErrorCode-Implementations":{"role":"collectionGroup","title":"SBErrorCode Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/SBErrorCode-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/coreerror\/sberrorcode-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/requestFailed":{"role":"symbol","title":"CoreError.requestFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestFailed"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/requestFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBCoreErrorRequestFailed"}],"url":"\/documentation\/sendbirdchatsdk\/coreerror\/requestfailed"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBErrorCode":{"role":"symbol","title":"SBErrorCode","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBErrorCode"}],"url":"\/documentation\/sendbirdchatsdk\/sberrorcode"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.sendbird.chat\/s8SendableP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/fileUploadCanceled":{"role":"symbol","title":"CoreError.fileUploadCanceled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileUploadCanceled"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/fileUploadCanceled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBCoreErrorFileUploadCanceled"}],"url":"\/documentation\/sendbirdchatsdk\/coreerror\/fileuploadcanceled"},"doc://com.sendbird.chat/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.sendbird.chat\/s5ErrorP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError":{"role":"symbol","title":"CoreError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreError"}],"abstract":[{"type":"text","text":"Core error code"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CoreError"}],"url":"\/documentation\/sendbirdchatsdk\/coreerror"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/code":{"role":"symbol","title":"code","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/code","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/coreerror\/code"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/coreerror\/init(rawvalue:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/fileUploadCancelFailed":{"role":"symbol","title":"CoreError.fileUploadCancelFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileUploadCancelFailed"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/fileUploadCancelFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBCoreErrorFileUploadCancelFailed"}],"url":"\/documentation\/sendbirdchatsdk\/coreerror\/fileuploadcancelfailed"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/message":{"role":"symbol","title":"message","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/message","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/coreerror\/message"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/unknownError":{"role":"symbol","title":"CoreError.unknownError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/unknownError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBCoreErrorUnknownError"}],"url":"\/documentation\/sendbirdchatsdk\/coreerror\/unknownerror"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/malformedData":{"role":"symbol","title":"CoreError.malformedData","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"malformedData"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/malformedData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBCoreErrorMalformedData"}],"url":"\/documentation\/sendbirdchatsdk\/coreerror\/malformeddata"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/coreerror\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/fileUploadTimeout":{"role":"symbol","title":"CoreError.fileUploadTimeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileUploadTimeout"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/fileUploadTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBCoreErrorFileUploadTimeout"}],"url":"\/documentation\/sendbirdchatsdk\/coreerror\/fileuploadtimeout"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/fileSizeLimitExceeded":{"role":"symbol","title":"CoreError.fileSizeLimitExceeded","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileSizeLimitExceeded"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/fileSizeLimitExceeded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBCoreErrorFileSizeLimitExceeded"}],"url":"\/documentation\/sendbirdchatsdk\/coreerror\/filesizelimitexceeded"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/coreerror\/error-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError/networkError":{"role":"symbol","title":"CoreError.networkError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkError"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/networkError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBCoreErrorNetworkError"}],"url":"\/documentation\/sendbirdchatsdk\/coreerror\/networkerror"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBCoreError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBCoreError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBCoreError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/fileSizeLimitExceeded","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/fileUploadCancelFailed","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/fileUploadCanceled","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/fileUploadTimeout","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/internalServerError","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/malformedData","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/networkError","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/networkRoutingError","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/requestFailed","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError\/unknownError"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBCoreError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1internalServerError\/title","value":"SBCoreErrorInternalServerError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1internalServerError\/fragments","value":[{"kind":"identifier","text":"SBCoreErrorInternalServerError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1networkRoutingError\/title","value":"SBCoreErrorNetworkRoutingError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1networkRoutingError\/fragments","value":[{"kind":"identifier","text":"SBCoreErrorNetworkRoutingError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1requestFailed\/title","value":"SBCoreErrorRequestFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1requestFailed\/fragments","value":[{"kind":"identifier","text":"SBCoreErrorRequestFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1fileUploadCanceled\/title","value":"SBCoreErrorFileUploadCanceled"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1fileUploadCanceled\/fragments","value":[{"kind":"identifier","text":"SBCoreErrorFileUploadCanceled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError\/title","value":"SBCoreError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError\/fragments","value":[{"kind":"identifier","text":"SBCoreError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1fileUploadCancelFailed\/title","value":"SBCoreErrorFileUploadCancelFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1fileUploadCancelFailed\/fragments","value":[{"kind":"identifier","text":"SBCoreErrorFileUploadCancelFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1unknownError\/title","value":"SBCoreErrorUnknownError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1unknownError\/fragments","value":[{"kind":"identifier","text":"SBCoreErrorUnknownError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1malformedData\/title","value":"SBCoreErrorMalformedData"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1malformedData\/fragments","value":[{"kind":"identifier","text":"SBCoreErrorMalformedData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1fileUploadTimeout\/title","value":"SBCoreErrorFileUploadTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1fileUploadTimeout\/fragments","value":[{"kind":"identifier","text":"SBCoreErrorFileUploadTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1fileSizeLimitExceeded\/title","value":"SBCoreErrorFileSizeLimitExceeded"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1fileSizeLimitExceeded\/fragments","value":[{"kind":"identifier","text":"SBCoreErrorFileSizeLimitExceeded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1networkError\/title","value":"SBCoreErrorNetworkError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError~1networkError\/fragments","value":[{"kind":"identifier","text":"SBCoreErrorNetworkError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}