{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDCountPreference) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CountPreference"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/countpreference"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/countpreference"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The enum type to represent various kinds of counts."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CountPreference"}],"title":"CountPreference","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDCountPreference","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CountPreference"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/all","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/off","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/unreadMentionCountOnly","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/unreadMessageCountOnly"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CountPreference/unreadMessageCountOnly":{"role":"symbol","title":"CountPreference.unreadMessageCountOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadMessageCountOnly"}],"abstract":[{"type":"text","text":"The channel of this preference has only unread message count."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/unreadMessageCountOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCountPreferenceUnreadMessageCountOnly"}],"url":"\/documentation\/sendbirdchatsdk\/countpreference\/unreadmessagecountonly"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CountPreference/all":{"role":"symbol","title":"CountPreference.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[{"type":"text","text":"The channel of this preference has all of count."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCountPreferenceAll"}],"url":"\/documentation\/sendbirdchatsdk\/countpreference\/all"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CountPreference/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/countpreference\/decodable-implementations"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CountPreference":{"role":"symbol","title":"CountPreference","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CountPreference"}],"abstract":[{"type":"text","text":"The enum type to represent various kinds of counts."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CountPreference"}],"url":"\/documentation\/sendbirdchatsdk\/countpreference"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CountPreference/unreadMentionCountOnly":{"role":"symbol","title":"CountPreference.unreadMentionCountOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadMentionCountOnly"}],"abstract":[{"type":"text","text":"The channel of this preference has only unread mention count."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/unreadMentionCountOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCountPreferenceUnreadMentionCountOnly"}],"url":"\/documentation\/sendbirdchatsdk\/countpreference\/unreadmentioncountonly"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CountPreference/off":{"role":"symbol","title":"CountPreference.off","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"abstract":[{"type":"text","text":"The channel of this preference does not get any count."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/off","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDCountPreferenceOff"}],"url":"\/documentation\/sendbirdchatsdk\/countpreference\/off"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CountPreference/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/countpreference\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CountPreference/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/countpreference\/rawrepresentable-implementations"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CountPreference/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/countpreference\/encodable-implementations"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDCountPreference"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDCountPreference"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDCountPreference"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/all","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/off","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/unreadMentionCountOnly","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CountPreference\/unreadMessageCountOnly"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDCountPreference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CountPreference~1unreadMessageCountOnly\/title","value":"SBDCountPreferenceUnreadMessageCountOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CountPreference~1unreadMessageCountOnly\/fragments","value":[{"kind":"identifier","text":"SBDCountPreferenceUnreadMessageCountOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CountPreference~1all\/title","value":"SBDCountPreferenceAll"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CountPreference~1all\/fragments","value":[{"kind":"identifier","text":"SBDCountPreferenceAll"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CountPreference\/title","value":"SBDCountPreference"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CountPreference\/fragments","value":[{"kind":"identifier","text":"SBDCountPreference"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CountPreference~1unreadMentionCountOnly\/title","value":"SBDCountPreferenceUnreadMentionCountOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CountPreference~1unreadMentionCountOnly\/fragments","value":[{"kind":"identifier","text":"SBDCountPreferenceUnreadMentionCountOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CountPreference~1off\/title","value":"SBDCountPreferenceOff"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CountPreference~1off\/fragments","value":[{"kind":"identifier","text":"SBDCountPreferenceOff"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}