{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDFileMessage) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessage"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This class doesn’t include a binary "},{"type":"strong","inlineContent":[{"type":"text","text":"data"}]},{"type":"text","text":" for the file. It is just a URL."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/filemessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/filemessage"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Serializable","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/s12IdentifiableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents a mesage object that contains a file. Derived from "},{"type":"codeVoice","code":"BaseMessage"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessage"}],"title":"FileMessage","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FileMessage"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/name","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/plainURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/size","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/thumbnails","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/type","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/url"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/encode(to:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/isEqual(_:)"]}],"references":{"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage/thumbnails":{"role":"symbol","title":"thumbnails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnails"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Thumbnail","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnail"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Image thumbnails."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/thumbnails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnails"}],"url":"\/documentation\/sendbirdchatsdk\/filemessage\/thumbnails"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/s12IdentifiableP":{"type":"unresolvable","title":"Swift.Identifiable","identifier":"doc:\/\/com.sendbird.chat\/s12IdentifiableP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/filemessage\/init(from:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage":{"role":"symbol","title":"BaseMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessage"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":" class represents the base message which is generated by a user or an admin."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":", the "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"AdminMessage"},{"type":"text","text":" are derived from this class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessage"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The type of file."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/sendbirdchatsdk\/filemessage\/type"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Mappable":{"role":"symbol","title":"Mappable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mappable"}],"abstract":[{"type":"text","text":"Mappable protocol to initialize sendbird object from a given dictionary."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Mappable"}],"url":"\/documentation\/sendbirdchatsdk\/mappable"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Copies this object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/sendbirdchatsdk\/filemessage\/copy(with:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Serializable":{"role":"symbol","title":"Serializable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Serializable"}],"abstract":[{"type":"text","text":"Protocol to provide serialization"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Serializable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Serializable"}],"url":"\/documentation\/sendbirdchatsdk\/serializable"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The name of file."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/sendbirdchatsdk\/filemessage\/name"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage/plainURL":{"role":"symbol","title":"plainURL","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"plainURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The file URL without the ekey."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/plainURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"plainURL"}],"url":"\/documentation\/sendbirdchatsdk\/filemessage\/plainurl"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Compares this object with given other object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/sendbirdchatsdk\/filemessage\/isequal(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage":{"role":"symbol","title":"FileMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessage"}],"abstract":[{"type":"text","text":"Represents a mesage object that contains a file. Derived from "},{"type":"codeVoice","code":"BaseMessage"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessage"}],"url":"\/documentation\/sendbirdchatsdk\/filemessage"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Encodes this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/filemessage\/encode(to:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage/size":{"role":"symbol","title":"size","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The size of file."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/size","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"size"}],"url":"\/documentation\/sendbirdchatsdk\/filemessage\/size"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage/url":{"role":"symbol","title":"url","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The file URL."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/url","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"url"}],"url":"\/documentation\/sendbirdchatsdk\/filemessage\/url"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDFileMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDFileMessage"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDFileMessage"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/name","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/plainURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/size","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/thumbnails","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/type","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/url"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage\/isEqual(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDFileMessage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage","text":"SBDBaseMessage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1thumbnails\/title","value":"thumbnails"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1thumbnails\/fragments","value":[{"kind":"identifier","text":"thumbnails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/title","value":"SBDBaseMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/title","value":"Mappable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/fragments","value":[{"kind":"identifier","text":"Mappable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Serializable\/title","value":"Serializable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Serializable\/fragments","value":[{"kind":"identifier","text":"Serializable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1plainURL\/title","value":"plainURL"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1plainURL\/fragments","value":[{"kind":"identifier","text":"plainURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage\/title","value":"SBDFileMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage\/fragments","value":[{"kind":"identifier","text":"SBDFileMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1size\/title","value":"size"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1size\/fragments","value":[{"kind":"identifier","text":"size"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1url\/title","value":"url"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage~1url\/fragments","value":[{"kind":"identifier","text":"url"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}