{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDGroupChannelDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(pl)SBDBaseChannelDelegate","text":"BaseChannelDelegate"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol deals with the below events."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when a member read a message in the "},{"type":"reference","isActive":true,"identifier":"..\/Classes\/GroupChannel.html"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when a member typed something in the "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"GroupChannel"}],"isActive":true,"type":"reference","identifier":"..\/Classes\/GroupChannel.html","overridingTitle":"GroupChannel"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when a new member joined the "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"GroupChannel"}],"isActive":true,"type":"reference","identifier":"..\/Classes\/GroupChannel.html","overridingTitle":"GroupChannel"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when a member left from the "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"GroupChannel"}],"isActive":true,"type":"reference","identifier":"..\/Classes\/GroupChannel.html","overridingTitle":"GroupChannel"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when a group channel was hidden."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchanneldelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchanneldelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events in the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelDelegate"}],"title":"GroupChannelDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDGroupChannelDelegate","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GroupChannelDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channel(_:didDeclineInvitation:inviter:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channel(_:didReceiveInvitation:inviter:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channel(_:userDidJoin:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channel(_:userDidLeave:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelDidChangeMemberCount(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelDidUpdateDeliveryStatus(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelDidUpdateReadStatus(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelDidUpdateTypingStatus(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelWasHidden(_:)"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate/channelDidUpdateTypingStatus(_:)":{"navigatorTitle":[{"kind":"identifier","text":"channelDidUpdateTypingStatus:"}],"role":"symbol","title":"channelDidUpdateTypingStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidUpdateTypingStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when user sends typing status."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelDidUpdateTypingStatus(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate\/channeldidupdatetypingstatus(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate/channel(_:didReceiveInvitation:inviter:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:didReceiveInvitation:inviter:"}],"role":"symbol","title":"channel(_:didReceiveInvitation:inviter:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveInvitation"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"inviter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"A callback when users are invited by inviter."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channel(_:didReceiveInvitation:inviter:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate\/channel(_:didreceiveinvitation:inviter:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate/channelDidUpdateDeliveryStatus(_:)":{"navigatorTitle":[{"kind":"identifier","text":"channelDidUpdateDeliveryStatus:"}],"role":"symbol","title":"channelDidUpdateDeliveryStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidUpdateDeliveryStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when delivery status updated."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelDidUpdateDeliveryStatus(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate\/channeldidupdatedeliverystatus(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate":{"role":"symbol","title":"BaseChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events"},{"type":"text","text":" "},{"type":"text","text":"in the channel. Delegate methods in "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" are common for the "},{"type":"codeVoice","code":"BaseChannel"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Exclusive delegate methods for "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" can be found in"},{"type":"text","text":" "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":". You must use "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":" instead of using "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" by using "},{"type":"codeVoice","code":"add(_:identifier:)"},{"type":"text","text":" in "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate/channelDidChangeMemberCount(_:)":{"navigatorTitle":[{"kind":"identifier","text":"channelDidChangeMemberCount:"}],"role":"symbol","title":"channelDidChangeMemberCount(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidChangeMemberCount"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"A callback when member count has been changed for broadcast channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelDidChangeMemberCount(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate\/channeldidchangemembercount(_:)"},"../Classes/GroupChannel.html":{"title":"GroupChannel","titleInlineContent":[{"type":"codeVoice","code":"GroupChannel"}],"type":"link","identifier":"..\/Classes\/GroupChannel.html","url":"..\/Classes\/GroupChannel.html"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate":{"role":"symbol","title":"GroupChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate/channelDidUpdateReadStatus(_:)":{"navigatorTitle":[{"kind":"identifier","text":"channelDidUpdateReadStatus:"}],"role":"symbol","title":"channelDidUpdateReadStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidUpdateReadStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when read status updated."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelDidUpdateReadStatus(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate\/channeldidupdatereadstatus(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate/channel(_:userDidJoin:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:userDidJoin:"}],"role":"symbol","title":"channel(_:userDidJoin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidJoin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when new member joined to the group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channel(_:userDidJoin:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate\/channel(_:userdidjoin:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection":{"role":"symbol","title":"MessageCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollection"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate/channel(_:didDeclineInvitation:inviter:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:didDeclineInvitation:inviter:"}],"role":"symbol","title":"channel(_:didDeclineInvitation:inviter:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDeclineInvitation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inviter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"A callback when user declined the invitation."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channel(_:didDeclineInvitation:inviter:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate\/channel(_:diddeclineinvitation:inviter:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate/channel(_:userDidLeave:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:userDidLeave:"}],"role":"symbol","title":"channel(_:userDidLeave:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidLeave"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when current member left from the group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channel(_:userDidLeave:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate\/channel(_:userdidleave:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate/channelWasHidden(_:)":{"navigatorTitle":[{"kind":"identifier","text":"channelWasHidden:"}],"role":"symbol","title":"channelWasHidden(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelWasHidden"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when the channel was hidden on the other device or by Platform API."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelWasHidden(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate\/channelwashidden(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection":{"role":"symbol","title":"GroupChannelCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelCollection"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDGroupChannelDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channel(_:didDeclineInvitation:inviter:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channel(_:didReceiveInvitation:inviter:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channel(_:userDidJoin:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channel(_:userDidLeave:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelDidChangeMemberCount(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelDidUpdateDeliveryStatus(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelDidUpdateReadStatus(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelDidUpdateTypingStatus(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate\/channelWasHidden(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDGroupChannelDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"SBDBaseChannelDelegate"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channelDidUpdateTypingStatus(_:)\/title","value":"channelDidUpdateTypingStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channelDidUpdateTypingStatus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidUpdateTypingStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channel(_:didReceiveInvitation:inviter:)\/title","value":"channel:didReceiveInvitation:inviter:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channel(_:didReceiveInvitation:inviter:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didReceiveInvitation:inviter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channelDidUpdateDeliveryStatus(_:)\/title","value":"channelDidUpdateDeliveryStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channelDidUpdateDeliveryStatus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidUpdateDeliveryStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate\/title","value":"SBDBaseChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannelDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channelDidChangeMemberCount(_:)\/title","value":"channelDidChangeMemberCount:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channelDidChangeMemberCount(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidChangeMemberCount:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate\/title","value":"SBDGroupChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channelDidUpdateReadStatus(_:)\/title","value":"channelDidUpdateReadStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channelDidUpdateReadStatus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidUpdateReadStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channel(_:userDidJoin:)\/title","value":"channel:userDidJoin:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channel(_:userDidJoin:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userDidJoin:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/title","value":"SBDMessageCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channel(_:didDeclineInvitation:inviter:)\/title","value":"channel:didDeclineInvitation:inviter:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channel(_:didDeclineInvitation:inviter:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didDeclineInvitation:inviter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channel(_:userDidLeave:)\/title","value":"channel:userDidLeave:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channel(_:userDidLeave:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userDidLeave:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channelWasHidden(_:)\/title","value":"channelWasHidden:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate~1channelWasHidden(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelWasHidden:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection\/title","value":"SBDGroupChannelCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelCollection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}