{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDGroupChannelPushTriggerOption) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelPushTriggerOption"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.128"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The options to choose which push notification for the current user to receive in a group channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelPushTriggerOption"}],"title":"GroupChannelPushTriggerOption","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPushTriggerOption","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GroupChannelPushTriggerOption"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/all","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/default","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/mentionOnly","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/off"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelPushTriggerOption/default":{"role":"symbol","title":"GroupChannelPushTriggerOption.default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"abstract":[{"type":"text","text":"Follow the push trigger of current user. See "},{"type":"codeVoice","code":"PushTriggerOption"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionDefault"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption\/default"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelPushTriggerOption/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption\/decodable-implementations"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelPushTriggerOption/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption\/rawrepresentable-implementations"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelPushTriggerOption/off":{"role":"symbol","title":"GroupChannelPushTriggerOption.off","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"abstract":[{"type":"text","text":"Do NOT receive any remote push notification."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/off","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionOff"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption\/off"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelPushTriggerOption/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption\/encodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelPushTriggerOption/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelPushTriggerOption":{"role":"symbol","title":"GroupChannelPushTriggerOption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelPushTriggerOption"}],"abstract":[{"type":"text","text":"The options to choose which push notification for the current user to receive in a group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelPushTriggerOption"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelPushTriggerOption/mentionOnly":{"role":"symbol","title":"GroupChannelPushTriggerOption.mentionOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionOnly"}],"abstract":[{"type":"text","text":"Receive only mentioned messages’s notification."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/mentionOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionMentionOnly"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption\/mentiononly"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelPushTriggerOption/all":{"role":"symbol","title":"GroupChannelPushTriggerOption.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[{"type":"text","text":"Receive all of remote push notification."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionAll"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelpushtriggeroption\/all"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelPushTriggerOption"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOption"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOption"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/all","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/default","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/mentionOnly","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelPushTriggerOption\/off"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDGroupChannelPushTriggerOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption~1default\/title","value":"SBDGroupChannelPushTriggerOptionDefault"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption~1default\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionDefault"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption~1off\/title","value":"SBDGroupChannelPushTriggerOptionOff"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption~1off\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionOff"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption\/title","value":"SBDGroupChannelPushTriggerOption"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption~1mentionOnly\/title","value":"SBDGroupChannelPushTriggerOptionMentionOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption~1mentionOnly\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionMentionOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption~1all\/title","value":"SBDGroupChannelPushTriggerOptionAll"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelPushTriggerOption~1all\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelPushTriggerOptionAll"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}