{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDGroupChannelTotalUnreadChannelCountParams) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelTotalUnreadChannelCountParams"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchanneltotalunreadchannelcountparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchanneltotalunreadchannelcountparams"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelTotalUnreadChannelCountParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object contains set of options to retrieve total unread channel count"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelTotalUnreadChannelCountParams"}],"title":"GroupChannelTotalUnreadChannelCountParams","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelTotalUnreadChannelCountParams","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GroupChannelTotalUnreadChannelCountParams"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelTotalUnreadChannelCountParams\/customTypesFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelTotalUnreadChannelCountParams\/superChannelFilter"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelTotalUnreadChannelCountParams":{"role":"symbol","title":"GroupChannelTotalUnreadChannelCountParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelTotalUnreadChannelCountParams"}],"abstract":[{"type":"text","text":"An object contains set of options to retrieve total unread channel count"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelTotalUnreadChannelCountParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelTotalUnreadChannelCountParams"}],"url":"\/documentation\/sendbirdchatsdk\/groupchanneltotalunreadchannelcountparams"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelTotalUnreadChannelCountParams/customTypesFilter":{"role":"symbol","title":"customTypesFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customTypesFilter"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Array filter of channel custom types."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelTotalUnreadChannelCountParams\/customTypesFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customTypesFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchanneltotalunreadchannelcountparams\/customtypesfilter"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelTotalUnreadChannelCountParams/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelTotalUnreadChannelCountParams\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirdchatsdk\/groupchanneltotalunreadchannelcountparams\/init"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelTotalUnreadChannelCountParams/superChannelFilter":{"role":"symbol","title":"superChannelFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"superChannelFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelSuperChannelFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelSuperChannelFilter"}],"abstract":[{"type":"text","text":"The enumerator filter of super channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelTotalUnreadChannelCountParams\/superChannelFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"superChannelFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchanneltotalunreadchannelcountparams\/superchannelfilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelTotalUnreadChannelCountParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelTotalUnreadChannelCountParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDGroupChannelTotalUnreadChannelCountParams"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelTotalUnreadChannelCountParams\/customTypesFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelTotalUnreadChannelCountParams\/superChannelFilter"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelTotalUnreadChannelCountParams\/init"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDGroupChannelTotalUnreadChannelCountParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelTotalUnreadChannelCountParams\/title","value":"SBDGroupChannelTotalUnreadChannelCountParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelTotalUnreadChannelCountParams\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelTotalUnreadChannelCountParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelTotalUnreadChannelCountParams~1customTypesFilter\/title","value":"customTypesFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelTotalUnreadChannelCountParams~1customTypesFilter\/fragments","value":[{"kind":"identifier","text":"customTypesFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelTotalUnreadChannelCountParams~1superChannelFilter\/title","value":"superChannelFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelTotalUnreadChannelCountParams~1superChannelFilter\/fragments","value":[{"kind":"identifier","text":"superChannelFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}