{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDGroupChannelChangeLogsParams) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelChangeLogsParams"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.182"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object that represents the parameters for the The method returns channels according to the properties in this object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelChangeLogsParams"}],"title":"GroupChannelChangeLogsParams","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelChangeLogsParams","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GroupChannelChangeLogsParams"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/customTypes","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/includeEmptyChannel","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/includeFrozenChannel"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/create(query:)"]}],"references":{"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelChangeLogsParams/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams\/init"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelChangeLogsParams/includeEmptyChannel":{"role":"symbol","title":"includeEmptyChannel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeEmptyChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include the empty channels in the results."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/includeEmptyChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeEmptyChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams\/includeemptychannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelChangeLogsParams":{"role":"symbol","title":"GroupChannelChangeLogsParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelChangeLogsParams"}],"abstract":[{"type":"text","text":"An object that represents the parameters for the The method returns channels according to the properties in this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelChangeLogsParams"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelChangeLogsParams/create(query:)":{"role":"symbol","title":"create(query:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GroupChannelChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelChangeLogsParams"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"GroupChannelChangeLogsParams"},{"type":"text","text":" from a given GroupChannelListQuery instance."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/create(query:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithGroupChannelListQuery:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams\/create(query:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelChangeLogsParams/customTypes":{"role":"symbol","title":"customTypes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Sets the custom types filter."},{"type":"text","text":" "},{"type":"text","text":"The property filters channels which have one of custom types."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/customTypes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customTypes"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams\/customtypes"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelChangeLogsParams/includeFrozenChannel":{"role":"symbol","title":"includeFrozenChannel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeFrozenChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include the frozen channels in the results."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/includeFrozenChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeFrozenChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelchangelogsparams\/includefrozenchannel"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelChangeLogsParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelChangeLogsParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDGroupChannelChangeLogsParams"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/customTypes","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/includeEmptyChannel","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/includeFrozenChannel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/init"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelChangeLogsParams\/create(query:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDGroupChannelChangeLogsParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams~1includeEmptyChannel\/title","value":"includeEmptyChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams~1includeEmptyChannel\/fragments","value":[{"kind":"identifier","text":"includeEmptyChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams\/title","value":"SBDGroupChannelChangeLogsParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelChangeLogsParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams~1create(query:)\/title","value":"createWithGroupChannelListQuery:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams~1create(query:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithGroupChannelListQuery:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams~1customTypes\/title","value":"customTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams~1customTypes\/fragments","value":[{"kind":"identifier","text":"customTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams~1includeFrozenChannel\/title","value":"includeFrozenChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelChangeLogsParams~1includeFrozenChannel\/fragments","value":[{"kind":"identifier","text":"includeFrozenChannel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}