{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDGroupChannelCollectionDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelCollectionDelegate"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.227"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelcollectiondelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelcollectiondelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollectionDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Methods that are invoked when the event of the channel collection occurs."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelCollectionDelegate"}],"title":"GroupChannelCollectionDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDGroupChannelCollectionDelegate","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GroupChannelCollectionDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollectionDelegate\/channelCollection(_:context:addedChannels:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollectionDelegate\/channelCollection(_:context:deletedChannelURLs:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollectionDelegate\/channelCollection(_:context:updatedChannels:)"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollectionDelegate":{"role":"symbol","title":"GroupChannelCollectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelCollectionDelegate"}],"abstract":[{"type":"text","text":"Methods that are invoked when the event of the channel collection occurs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelCollectionDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollectiondelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollectionDelegate/channelCollection(_:context:deletedChannelURLs:)":{"navigatorTitle":[{"kind":"identifier","text":"channelCollection:context:deletedChannelURLs:"}],"role":"symbol","title":"channelCollection(_:context:deletedChannelURLs:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannelCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDChannelContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedChannelURLs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"A callback when the channels are deleted."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollectionDelegate\/channelCollection(_:context:deletedChannelURLs:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelcollectiondelegate\/channelcollection(_:context:deletedchannelurls:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollectionDelegate/channelCollection(_:context:updatedChannels:)":{"navigatorTitle":[{"kind":"identifier","text":"channelCollection:context:updatedChannels:"}],"role":"symbol","title":"channelCollection(_:context:updatedChannels:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannelCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDChannelContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"updatedChannels"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"A callback when the channels are updated."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollectionDelegate\/channelCollection(_:context:updatedChannels:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelcollectiondelegate\/channelcollection(_:context:updatedchannels:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollectionDelegate/channelCollection(_:context:addedChannels:)":{"navigatorTitle":[{"kind":"identifier","text":"channelCollection:context:addedChannels:"}],"role":"symbol","title":"channelCollection(_:context:addedChannels:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannelCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDChannelContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedChannels"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"A callback when the channels are added."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollectionDelegate\/channelCollection(_:context:addedChannels:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelcollectiondelegate\/channelcollection(_:context:addedchannels:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelCollectionDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelCollectionDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDGroupChannelCollectionDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollectionDelegate\/channelCollection(_:context:addedChannels:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollectionDelegate\/channelCollection(_:context:deletedChannelURLs:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollectionDelegate\/channelCollection(_:context:updatedChannels:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDGroupChannelCollectionDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollectionDelegate\/title","value":"SBDGroupChannelCollectionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollectionDelegate\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelCollectionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollectionDelegate~1channelCollection(_:context:deletedChannelURLs:)\/title","value":"channelCollection:context:deletedChannelURLs:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollectionDelegate~1channelCollection(_:context:deletedChannelURLs:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelCollection:context:deletedChannelURLs:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollectionDelegate~1channelCollection(_:context:updatedChannels:)\/title","value":"channelCollection:context:updatedChannels:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollectionDelegate~1channelCollection(_:context:updatedChannels:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelCollection:context:updatedChannels:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollectionDelegate~1channelCollection(_:context:addedChannels:)\/title","value":"channelCollection:context:addedChannels:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollectionDelegate~1channelCollection(_:context:addedChannels:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelCollection:context:addedChannels:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}