{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDGroupChannelUpdateParams) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelUpdateParams"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelupdateparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelupdateparams"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object contains a set of options to update a group channel"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelUpdateParams"}],"title":"GroupChannelUpdateParams","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelUpdateParams","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GroupChannelUpdateParams"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/accessCode","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/coverImage","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/coverURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/customType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/data","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/isDiscoverable","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/isDistinct","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/isPublic","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/messageSurvivalSeconds","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/name","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/operatorUserIDs"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/encode(to:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/setOperators(_:)"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams/data":{"role":"symbol","title":"data","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Channel data"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/data","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"data"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams\/data"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams/accessCode":{"role":"symbol","title":"accessCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A string that allows access to the public group channel. ONLY use for public group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/accessCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accessCode"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams\/accesscode"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams/coverURL":{"role":"symbol","title":"coverURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Channel cover image url"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/coverURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"coverURL"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams\/coverurl"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams/customType":{"role":"symbol","title":"customType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Channel custom type"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/customType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customType"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams\/customtype"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Encodes this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams\/encode(to:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams/isDiscoverable":{"role":"symbol","title":"isDiscoverable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDiscoverable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"set true if this channel is discoverable"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/isDiscoverable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isDiscoverable"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams\/isdiscoverable"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams":{"role":"symbol","title":"GroupChannelUpdateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelUpdateParams"}],"abstract":[{"type":"text","text":"An object contains a set of options to update a group channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelUpdateParams"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams/messageSurvivalSeconds":{"role":"symbol","title":"messageSurvivalSeconds","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageSurvivalSeconds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"A value that sets the message survival time in seconds."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/messageSurvivalSeconds","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageSurvivalSeconds"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams\/messagesurvivalseconds"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams/coverImage":{"role":"symbol","title":"coverImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Channel cover image data"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/coverImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"coverImage"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams\/coverimage"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams/isPublic":{"role":"symbol","title":"isPublic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPublic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether the channel is public or not"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/isPublic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isPublic"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams\/ispublic"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams/isDistinct":{"role":"symbol","title":"isDistinct","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDistinct"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"set true if channel need to be updated as distinct"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/isDistinct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isDistinct"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams\/isdistinct"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams/operatorUserIDs":{"role":"symbol","title":"operatorUserIDs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatorUserIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"channel’s operator user IDs"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/operatorUserIDs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"operatorUserIDs"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams\/operatoruserids"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Channel name"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams\/name"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams/setOperators(_:)":{"role":"symbol","title":"setOperators(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setOperators"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Set operators with list of user instance."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/setOperators(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setOperators:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams\/setoperators(_:)"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams\/init()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelUpdateParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelUpdateParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDGroupChannelUpdateParams"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/accessCode","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/coverImage","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/coverURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/customType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/data","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/isDiscoverable","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/isDistinct","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/isPublic","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/messageSurvivalSeconds","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/name","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/operatorUserIDs"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams\/setOperators(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDGroupChannelUpdateParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1data\/title","value":"data"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1data\/fragments","value":[{"kind":"identifier","text":"data"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1accessCode\/title","value":"accessCode"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1accessCode\/fragments","value":[{"kind":"identifier","text":"accessCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1coverURL\/title","value":"coverURL"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1coverURL\/fragments","value":[{"kind":"identifier","text":"coverURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1customType\/title","value":"customType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1customType\/fragments","value":[{"kind":"identifier","text":"customType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1isDiscoverable\/title","value":"isDiscoverable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1isDiscoverable\/fragments","value":[{"kind":"identifier","text":"isDiscoverable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams\/title","value":"SBDGroupChannelUpdateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelUpdateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1messageSurvivalSeconds\/title","value":"messageSurvivalSeconds"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1messageSurvivalSeconds\/fragments","value":[{"kind":"identifier","text":"messageSurvivalSeconds"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1coverImage\/title","value":"coverImage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1coverImage\/fragments","value":[{"kind":"identifier","text":"coverImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1isPublic\/title","value":"isPublic"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1isPublic\/fragments","value":[{"kind":"identifier","text":"isPublic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1isDistinct\/title","value":"isDistinct"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1isDistinct\/fragments","value":[{"kind":"identifier","text":"isDistinct"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1operatorUserIDs\/title","value":"operatorUserIDs"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1operatorUserIDs\/fragments","value":[{"kind":"identifier","text":"operatorUserIDs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1setOperators(_:)\/title","value":"setOperators:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1setOperators(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setOperators:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}