{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDGroupChannelHiddenState) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelHiddenState"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.122"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The enum type for the hidden state of a group channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelHiddenState"}],"title":"GroupChannelHiddenState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDGroupChannelHiddenState","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GroupChannelHiddenState"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/hiddenAllowAutoUnhide","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/hiddenPreventAutoUnhide","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/unhidden"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHiddenState":{"role":"symbol","title":"GroupChannelHiddenState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelHiddenState"}],"abstract":[{"type":"text","text":"The enum type for the hidden state of a group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelHiddenState"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHiddenState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHiddenState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHiddenState/unhidden":{"role":"symbol","title":"GroupChannelHiddenState.unhidden","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unhidden"}],"abstract":[{"type":"text","text":"Shows the channel is unhidden."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/unhidden","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateUnhidden"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/unhidden"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHiddenState/hiddenAllowAutoUnhide":{"role":"symbol","title":"GroupChannelHiddenState.hiddenAllowAutoUnhide","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenAllowAutoUnhide"}],"abstract":[{"type":"text","text":"Shows the channel will be unhidden automatically when there is a new message in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/hiddenAllowAutoUnhide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateHiddenAllowAutoUnhide"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/hiddenallowautounhide"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHiddenState/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/decodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHiddenState/hiddenPreventAutoUnhide":{"role":"symbol","title":"GroupChannelHiddenState.hiddenPreventAutoUnhide","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenPreventAutoUnhide"}],"abstract":[{"type":"text","text":"Shows the channel will not be unhidden automatically."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/hiddenPreventAutoUnhide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateHiddenPreventAutoUnhide"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/hiddenpreventautounhide"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHiddenState/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelhiddenstate\/encodable-implementations"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelHiddenState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelHiddenState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDGroupChannelHiddenState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/hiddenAllowAutoUnhide","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/hiddenPreventAutoUnhide","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHiddenState\/unhidden"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDGroupChannelHiddenState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState\/title","value":"SBDGroupChannelHiddenState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelHiddenState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState~1unhidden\/title","value":"SBDGroupChannelHiddenStateUnhidden"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState~1unhidden\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateUnhidden"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState~1hiddenAllowAutoUnhide\/title","value":"SBDGroupChannelHiddenStateHiddenAllowAutoUnhide"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState~1hiddenAllowAutoUnhide\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateHiddenAllowAutoUnhide"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState~1hiddenPreventAutoUnhide\/title","value":"SBDGroupChannelHiddenStateHiddenPreventAutoUnhide"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelHiddenState~1hiddenPreventAutoUnhide\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelHiddenStateHiddenPreventAutoUnhide"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}