{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDGroupChannelCollection) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelCollection"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.1.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelcollection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelcollection"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseCollection"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object that accesses the cache for the group channels."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelCollection"}],"title":"GroupChannelCollection","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GroupChannelCollection"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/changelogsToken","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelList","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/defaultTs","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/delegate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/hasNext","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/isLive","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/needMoreData","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/query"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/dispose()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/loadMore(completionHandler:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/BaseChannelDelegate-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/ConnectionDelegate-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/GroupChannelDelegate-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/BaseChannelDelegate-Implementations":{"role":"collectionGroup","title":"BaseChannelDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/BaseChannelDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/basechanneldelegate-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate":{"role":"symbol","title":"BaseChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events"},{"type":"text","text":" "},{"type":"text","text":"in the channel. Delegate methods in "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" are common for the "},{"type":"codeVoice","code":"BaseChannel"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Exclusive delegate methods for "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" can be found in"},{"type":"text","text":" "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":". You must use "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":" instead of using "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" by using "},{"type":"codeVoice","code":"add(_:identifier:)"},{"type":"text","text":" in "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/channelList":{"role":"symbol","title":"channelList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The channels that the collection has fetched."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelList"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/channellist"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/needMoreData":{"role":"symbol","title":"needMoreData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"needMoreData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Represents the collection needs to fetch more data to satisfy query limit"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/needMoreData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"needMoreData"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/needmoredata"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/changelogsToken":{"role":"symbol","title":"changelogsToken","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"changelogsToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Token for channel change log."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/changelogsToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changelogsToken"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/changelogstoken"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/loadMore(completionHandler:)":{"role":"symbol","title":"loadMore(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMore"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListHandler","preciseIdentifier":"s:15SendbirdChatSDK23GroupChannelListHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Loads next page."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/loadMore(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadMoreWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/loadmore(completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/defaultTs":{"role":"symbol","title":"defaultTs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultTs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Default timestamp for group channel change logs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/defaultTs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultTs"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/defaultts"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/isLive":{"role":"symbol","title":"isLive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Represents that the collection is going to display the real-time messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/isLive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isLive"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/islive"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseCollection":{"role":"symbol","title":"BaseCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseCollection"}],"abstract":[{"type":"text","text":"An base object for collection"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseCollection"}],"url":"\/documentation\/sendbirdchatsdk\/basecollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelCollectionDelegate","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(pl)SBDGroupChannelCollectionDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Collection delegate."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/delegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate":{"role":"symbol","title":"GroupChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/GroupChannelDelegate-Implementations":{"role":"collectionGroup","title":"GroupChannelDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/GroupChannelDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/groupchanneldelegate-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ConnectionDelegate":{"role":"symbol","title":"ConnectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionDelegate"}],"abstract":[{"type":"text","text":"Represents a delegate to receive connection relates events"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/connectiondelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/ConnectionDelegate-Implementations":{"role":"collectionGroup","title":"ConnectionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/ConnectionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/connectiondelegate-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/hasNext":{"role":"symbol","title":"hasNext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasNext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"If "},{"type":"codeVoice","code":"true"},{"type":"text","text":", the next page might exist."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/hasNext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasNext"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/hasnext"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/query":{"role":"symbol","title":"query","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery"}],"abstract":[{"type":"text","text":"Group channel list query"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/query","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"query"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/query"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection":{"role":"symbol","title":"GroupChannelCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelCollection"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection/dispose()":{"role":"symbol","title":"dispose()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dispose"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Invalidates the object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/dispose()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dispose"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection\/dispose()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelCollection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelCollection"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDGroupChannelCollection"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/changelogsToken","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/channelList","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/defaultTs","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/delegate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/hasNext","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/isLive","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/needMoreData","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/query"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/dispose()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/loadMore(completionHandler:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/BaseChannelDelegate-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/ConnectionDelegate-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection\/GroupChannelDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDGroupChannelCollection"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseCollection","text":"SBDBaseCollection"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate\/title","value":"SBDBaseChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannelDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channelList\/title","value":"channelList"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1channelList\/fragments","value":[{"kind":"identifier","text":"channelList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1needMoreData\/title","value":"needMoreData"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1needMoreData\/fragments","value":[{"kind":"identifier","text":"needMoreData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1changelogsToken\/title","value":"changelogsToken"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1changelogsToken\/fragments","value":[{"kind":"identifier","text":"changelogsToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1loadMore(completionHandler:)\/title","value":"loadMoreWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1loadMore(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadMoreWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1defaultTs\/title","value":"defaultTs"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1defaultTs\/fragments","value":[{"kind":"identifier","text":"defaultTs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1isLive\/title","value":"isLive"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1isLive\/fragments","value":[{"kind":"identifier","text":"isLive"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseCollection\/title","value":"SBDBaseCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseCollection\/fragments","value":[{"kind":"identifier","text":"SBDBaseCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate\/title","value":"SBDGroupChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate\/title","value":"SBDConnectionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate\/fragments","value":[{"kind":"identifier","text":"SBDConnectionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1hasNext\/title","value":"hasNext"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1hasNext\/fragments","value":[{"kind":"identifier","text":"hasNext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1query\/title","value":"query"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1query\/fragments","value":[{"kind":"identifier","text":"query"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection\/title","value":"SBDGroupChannelCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1dispose()\/title","value":"dispose"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection~1dispose()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dispose"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}