{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDGroupChannelListOrder) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListOrder"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistorder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistorder"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The order type for "},{"type":"codeVoice","code":"GroupChannelListQuery"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListOrder"}],"title":"GroupChannelListOrder","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListOrder","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GroupChannelListOrder"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/channelMetaDataValueAlphabetical","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/channelNameAlphabetical","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/chronological","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/latestLastMessage"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListOrder/chronological":{"role":"symbol","title":"GroupChannelListOrder.chronological","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chronological"}],"abstract":[{"type":"text","text":"Chronological order for group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/chronological","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelListOrderChronological"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistorder\/chronological"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListOrder":{"role":"symbol","title":"GroupChannelListOrder","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListOrder"}],"abstract":[{"type":"text","text":"The order type for "},{"type":"codeVoice","code":"GroupChannelListQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListOrder"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistorder"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListOrder/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannellistorder\/equatable-implementations"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListOrder/channelNameAlphabetical":{"role":"symbol","title":"GroupChannelListOrder.channelNameAlphabetical","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelNameAlphabetical"}],"abstract":[{"type":"text","text":"Alphabetical name order for group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/channelNameAlphabetical","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelListOrderChannelNameAlphabetical"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistorder\/channelnamealphabetical"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListOrder/channelMetaDataValueAlphabetical":{"role":"symbol","title":"GroupChannelListOrder.channelMetaDataValueAlphabetical","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelMetaDataValueAlphabetical"}],"abstract":[{"type":"text","text":"Alphabetical value order of a selected key in meta data for group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/channelMetaDataValueAlphabetical","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelListOrderChannelMetaDataValueAlphabetical"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistorder\/channelmetadatavaluealphabetical"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListOrder/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannellistorder\/decodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListOrder/latestLastMessage":{"role":"symbol","title":"GroupChannelListOrder.latestLastMessage","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"latestLastMessage"}],"abstract":[{"type":"text","text":"Lastest last message order for group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/latestLastMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelListOrderLatestLastMessage"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistorder\/latestlastmessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListOrder/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannellistorder\/rawrepresentable-implementations"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListOrder/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannellistorder\/encodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelListOrder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListOrder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDGroupChannelListOrder"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/channelMetaDataValueAlphabetical","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/channelNameAlphabetical","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/chronological","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder\/latestLastMessage"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDGroupChannelListOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder~1chronological\/title","value":"SBDGroupChannelListOrderChronological"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder~1chronological\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListOrderChronological"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder\/title","value":"SBDGroupChannelListOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder~1channelNameAlphabetical\/title","value":"SBDGroupChannelListOrderChannelNameAlphabetical"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder~1channelNameAlphabetical\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListOrderChannelNameAlphabetical"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder~1channelMetaDataValueAlphabetical\/title","value":"SBDGroupChannelListOrderChannelMetaDataValueAlphabetical"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder~1channelMetaDataValueAlphabetical\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListOrderChannelMetaDataValueAlphabetical"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder~1latestLastMessage\/title","value":"SBDGroupChannelListOrderLatestLastMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder~1latestLastMessage\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListOrderLatestLastMessage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}