{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDGroupChannelSuperChannelFilter) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelSuperChannelFilter"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Channel filter for super mode in group channels."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelSuperChannelFilter"}],"title":"GroupChannelSuperChannelFilter","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDGroupChannelSuperChannelFilter","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GroupChannelSuperChannelFilter"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/all","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/broadcastOnly","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/exclusiveOnly","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/nonSuper","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/super"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelSuperChannelFilter/all":{"role":"symbol","title":"GroupChannelSuperChannelFilter.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[{"type":"text","text":"Without filter"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilterAll"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter\/all"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelSuperChannelFilter/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelSuperChannelFilter/broadcastOnly":{"role":"symbol","title":"GroupChannelSuperChannelFilter.broadcastOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"broadcastOnly"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/broadcastOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilterBroadcastOnly"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter\/broadcastonly"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelSuperChannelFilter/super":{"role":"symbol","title":"GroupChannelSuperChannelFilter.super","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`super`"}],"abstract":[{"type":"text","text":"Filter super group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/super","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilterSuper"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter\/super"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelSuperChannelFilter/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter\/encodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelSuperChannelFilter/nonSuper":{"role":"symbol","title":"GroupChannelSuperChannelFilter.nonSuper","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonSuper"}],"abstract":[{"type":"text","text":"Filter non-super group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/nonSuper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilterNonSuper"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter\/nonsuper"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelSuperChannelFilter/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter\/decodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelSuperChannelFilter":{"role":"symbol","title":"GroupChannelSuperChannelFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelSuperChannelFilter"}],"abstract":[{"type":"text","text":"Channel filter for super mode in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelSuperChannelFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelSuperChannelFilter/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelSuperChannelFilter/exclusiveOnly":{"role":"symbol","title":"GroupChannelSuperChannelFilter.exclusiveOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"exclusiveOnly"}],"abstract":[{"type":"text","text":"Filter exclusive group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/exclusiveOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilterExclusiveOnly"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelsuperchannelfilter\/exclusiveonly"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelSuperChannelFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilter"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/all","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/broadcastOnly","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/exclusiveOnly","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/nonSuper","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelSuperChannelFilter\/super"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter~1all\/title","value":"SBDGroupChannelSuperChannelFilterAll"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter~1all\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilterAll"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter~1broadcastOnly\/title","value":"SBDGroupChannelSuperChannelFilterBroadcastOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter~1broadcastOnly\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilterBroadcastOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter~1super\/title","value":"SBDGroupChannelSuperChannelFilterSuper"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter~1super\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilterSuper"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter~1nonSuper\/title","value":"SBDGroupChannelSuperChannelFilterNonSuper"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter~1nonSuper\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilterNonSuper"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter\/title","value":"SBDGroupChannelSuperChannelFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter~1exclusiveOnly\/title","value":"SBDGroupChannelSuperChannelFilterExclusiveOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelSuperChannelFilter~1exclusiveOnly\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelSuperChannelFilterExclusiveOnly"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}