{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDGroupChannelListQueryParams) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQueryParams"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/init(builder:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/channelHiddenStateFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/channelNameContainsFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/channelURLsFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/customTypeStartsWithFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/customTypesFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/includeEmptyChannel","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/includeFrozenChannel","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/includeMemberList","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/includeMetaData","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/limit","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/memberStateFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/metaDataKeyFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/metaDataOrderKeyFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/metaDataValueStartsWithFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/metaDataValuesFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/nicknameContainsFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/order","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/publicChannelFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/queryType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/searchFields","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/searchQuery","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/superChannelFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/unreadChannelFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/userIDsExactFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/userIDsIncludeFilter"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/setMetaDataFilter(_:valueStartsWith:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/setMetaDataFilter(_:values:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/setSearchFilter(_:fields:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/setUserIDsIncludeFilter(_:queryType:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/NSCopying-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQueryParams"}],"title":"GroupChannelListQueryParams","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQueryParams","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQueryParams"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/queryType":{"role":"symbol","title":"queryType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQueryType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListQueryType"}],"abstract":[{"type":"text","text":"Sets query type for "},{"type":"codeVoice","code":"includeMemberList"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/queryType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"queryType"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/querytype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/includeFrozenChannel":{"role":"symbol","title":"includeFrozenChannel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeFrozenChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines channel list includes frozen channel. Default is "},{"type":"codeVoice","code":"true"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/includeFrozenChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeFrozenChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/includefrozenchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/includeMetaData":{"role":"symbol","title":"includeMetaData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeMetaData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines channel object of the list includes meta data property."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/includeMetaData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeMetaData"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/includemetadata"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/isequal(_:)"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/setMetaDataFilter(_:values:)":{"role":"symbol","title":"setMetaDataFilter(_:values:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMetaDataFilter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"values"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Sets meta data filter"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/setMetaDataFilter(_:values:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMetaDataFilterWithKey:values:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/setmetadatafilter(_:values:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/metaDataValueStartsWithFilter":{"role":"symbol","title":"metaDataValueStartsWithFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaDataValueStartsWithFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Searches for group channels with metadata containing an item with the key specified by the metaDataKey"},{"type":"text","text":" "},{"type":"text","text":"and the values of that item start with the specified value"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/metaDataValueStartsWithFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metaDataValueStartsWithFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/metadatavaluestartswithfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/channelURLsFilter":{"role":"symbol","title":"channelURLsFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelURLsFilter"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Sets "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" URLs filter. "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" list containing"},{"type":"text","text":" "},{"type":"text","text":"only and exactly the passed "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" URLs will be returned."},{"type":"text","text":" "},{"type":"text","text":"This does not cooperate with other filters."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/channelURLsFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelURLsFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/channelurlsfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/NSCopying-Implementations":{"role":"collectionGroup","title":"NSCopying Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/NSCopying-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/nscopying-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams":{"role":"symbol","title":"GroupChannelListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/includeEmptyChannel":{"role":"symbol","title":"includeEmptyChannel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeEmptyChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines channel list includes empty channel. Default is "},{"type":"codeVoice","code":"true"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/includeEmptyChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeEmptyChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/includeemptychannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/init(builder:)":{"role":"symbol","title":"init(builder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"builder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"GroupChannelListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes and returns a newly allocated params object that mutated through builder closure."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/init(builder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBuilder:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/init(builder:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/metaDataValuesFilter":{"role":"symbol","title":"metaDataValuesFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaDataValuesFilter"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Searches for group channels with metadata containing an item with the key specified by the metaDataKey"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/metaDataValuesFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metaDataValuesFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/metadatavaluesfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/searchFields":{"role":"symbol","title":"searchFields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchFields"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQuerySearchField","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuerySearchField"}],"abstract":[{"type":"text","text":"The fields properties of the query specified by "},{"type":"codeVoice","code":"setSearchFilterQuery:fields:"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/searchFields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchFields"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/searchfields"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/superChannelFilter":{"role":"symbol","title":"superChannelFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"superChannelFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelSuperChannelFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelSuperChannelFilter"}],"abstract":[{"type":"text","text":"Sets to filter super channel. Default is "},{"type":"codeVoice","code":".all"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/superChannelFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"superChannelFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/superchannelfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/searchQuery":{"role":"symbol","title":"searchQuery","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchQuery"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The query property of the query specified by "},{"type":"codeVoice","code":"setSearchFilterQuery:fields:"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/searchQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchQuery"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/searchquery"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/publicChannelFilter":{"role":"symbol","title":"publicChannelFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicChannelFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelPublicChannelFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPublicChannelFilter"}],"abstract":[{"type":"text","text":"Sets to filter public channel.Default is "},{"type":"codeVoice","code":".all"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/publicChannelFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publicChannelFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/publicchannelfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/nicknameContainsFilter":{"role":"symbol","title":"nicknameContainsFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nicknameContainsFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sets the filter with nickname. The group channels which have the member that has nickname"},{"type":"text","text":" "},{"type":"text","text":"are returned by "},{"type":"codeVoice","code":"loadNextPage:"},{"type":"text","text":"(LIKE search)."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/nicknameContainsFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nicknameContainsFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/nicknamecontainsfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/limit":{"role":"symbol","title":"limit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"limit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Specifies the number of results to return per call. (Default: 20)"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/limit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"limit"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/limit"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/init(from:)"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/userIDsExactFilter":{"role":"symbol","title":"userIDsExactFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userIDsExactFilter"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Sets the filter with user IDs. The group channels which have the members that have user"},{"type":"text","text":" "},{"type":"text","text":"IDs are returned by "},{"type":"codeVoice","code":"loadNextPage:"},{"type":"text","text":". The channels have the "},{"type":"codeVoice","code":"userIDs"},{"type":"text","text":" members only."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/userIDsExactFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userIDsExactFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/useridsexactfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/channelHiddenStateFilter":{"role":"symbol","title":"channelHiddenStateFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelHiddenStateFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelHiddenStateFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelHiddenStateFilter"}],"abstract":[{"type":"text","text":"Sets to filter channels by the hidden state. The default value is "},{"type":"codeVoice","code":"ChannelHiddenStateFilter.unhiddenOnly"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/channelHiddenStateFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelHiddenStateFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/channelhiddenstatefilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/setMetaDataFilter(_:valueStartsWith:)":{"role":"symbol","title":"setMetaDataFilter(_:valueStartsWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMetaDataFilter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"valueStartsWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets meta data filter"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/setMetaDataFilter(_:valueStartsWith:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMetaDataFilterWithKey:valueStartsWith:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/setmetadatafilter(_:valuestartswith:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/memberStateFilter":{"role":"symbol","title":"memberStateFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memberStateFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MemberStateFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberStateFilter"}],"abstract":[{"type":"text","text":"Sets the member state filter."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/memberStateFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"memberStateFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/memberstatefilter"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/userIDsIncludeFilter":{"role":"symbol","title":"userIDsIncludeFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userIDsIncludeFilter"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Sets the filter with user IDs. The group channels which have the members that contain user"},{"type":"text","text":" "},{"type":"text","text":"IDs are returned by "},{"type":"codeVoice","code":"loadNextPage:"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/userIDsIncludeFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userIDsIncludeFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/useridsincludefilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/includeMemberList":{"role":"symbol","title":"includeMemberList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeMemberList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines channel object of the list includes members list."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/includeMemberList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeMemberList"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/includememberlist"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/init()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/metaDataKeyFilter":{"role":"symbol","title":"metaDataKeyFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaDataKeyFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Searches for group channels with metadata containing an item with the specified value as its key"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/metaDataKeyFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metaDataKeyFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/metadatakeyfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/customTypeStartsWithFilter":{"role":"symbol","title":"customTypeStartsWithFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customTypeStartsWithFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sets to filter channels by custom type that starts with."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/customTypeStartsWithFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customTypeStartsWithFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/customtypestartswithfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/customTypesFilter":{"role":"symbol","title":"customTypesFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customTypesFilter"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Sets the custom types filter. The custom types to search."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/customTypesFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customTypesFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/customtypesfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/unreadChannelFilter":{"role":"symbol","title":"unreadChannelFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadChannelFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnreadChannelFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDUnreadChannelFilter"}],"abstract":[{"type":"text","text":"Sets to filter channels by the unread messages. The default value is "},{"type":"codeVoice","code":".all"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/unreadChannelFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unreadChannelFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/unreadchannelfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/metaDataOrderKeyFilter":{"role":"symbol","title":"metaDataOrderKeyFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaDataOrderKeyFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sets a key for ordering by value in the metadata. This is valid when the "},{"type":"codeVoice","code":"order"},{"type":"text","text":" "},{"type":"text","text":"is "},{"type":"codeVoice","code":"GroupChannelListOrder.channelMetaDataValueAlphabetical"},{"type":"text","text":" only."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/metaDataOrderKeyFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metaDataOrderKeyFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/metadataorderkeyfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/channelNameContainsFilter":{"role":"symbol","title":"channelNameContainsFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelNameContainsFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sets a filter to return only channels that contains the specified group channel name."},{"type":"text","text":" "},{"type":"text","text":"The channel name to search. The query will return the channels include "},{"type":"codeVoice","code":"channelName"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/channelNameContainsFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelNameContainsFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/channelnamecontainsfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/setUserIDsIncludeFilter(_:queryType:)":{"role":"symbol","title":"setUserIDsIncludeFilter(_:queryType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserIDsIncludeFilter"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"queryType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQueryType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListQueryType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the filter with user IDs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/setUserIDsIncludeFilter(_:queryType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setUserIDsIncludeFilter:queryType:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/setuseridsincludefilter(_:querytype:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/setSearchFilter(_:fields:)":{"role":"symbol","title":"setSearchFilter(_:fields:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSearchFilter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQuerySearchField","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuerySearchField"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the search query and search fields of the query specified a given query and a given fields."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/setSearchFilter(_:fields:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSearchFilter:fields:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/setsearchfilter(_:fields:)"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQueryParams/order":{"role":"symbol","title":"order","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListOrder","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListOrder"}],"abstract":[{"type":"text","text":"Sets the order of the list. The order is defined in "},{"type":"codeVoice","code":"GroupChannelListOrder"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/order","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"order"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistqueryparams\/order"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelListQueryParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQueryParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDGroupChannelListQueryParams"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/channelHiddenStateFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/channelNameContainsFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/channelURLsFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/customTypeStartsWithFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/customTypesFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/includeEmptyChannel","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/includeFrozenChannel","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/includeMemberList","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/includeMetaData","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/limit","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/memberStateFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/metaDataKeyFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/metaDataOrderKeyFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/metaDataValueStartsWithFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/metaDataValuesFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/nicknameContainsFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/order","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/publicChannelFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/queryType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/searchFields","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/searchQuery","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/superChannelFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/unreadChannelFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/userIDsExactFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/userIDsIncludeFilter"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/init(builder:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/setMetaDataFilter(_:valueStartsWith:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/setMetaDataFilter(_:values:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/setSearchFilter(_:fields:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/setUserIDsIncludeFilter(_:queryType:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQueryParams\/NSCopying-Implementations"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDGroupChannelListQueryParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1queryType\/title","value":"queryType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1queryType\/fragments","value":[{"kind":"identifier","text":"queryType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1includeFrozenChannel\/title","value":"includeFrozenChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1includeFrozenChannel\/fragments","value":[{"kind":"identifier","text":"includeFrozenChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1includeMetaData\/title","value":"includeMetaData"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1includeMetaData\/fragments","value":[{"kind":"identifier","text":"includeMetaData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1setMetaDataFilter(_:values:)\/title","value":"setMetaDataFilterWithKey:values:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1setMetaDataFilter(_:values:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMetaDataFilterWithKey:values:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1metaDataValueStartsWithFilter\/title","value":"metaDataValueStartsWithFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1metaDataValueStartsWithFilter\/fragments","value":[{"kind":"identifier","text":"metaDataValueStartsWithFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1channelURLsFilter\/title","value":"channelURLsFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1channelURLsFilter\/fragments","value":[{"kind":"identifier","text":"channelURLsFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams\/title","value":"SBDGroupChannelListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1includeEmptyChannel\/title","value":"includeEmptyChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1includeEmptyChannel\/fragments","value":[{"kind":"identifier","text":"includeEmptyChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1init(builder:)\/title","value":"initWithBuilder:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1init(builder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBuilder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1metaDataValuesFilter\/title","value":"metaDataValuesFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1metaDataValuesFilter\/fragments","value":[{"kind":"identifier","text":"metaDataValuesFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1searchFields\/title","value":"searchFields"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1searchFields\/fragments","value":[{"kind":"identifier","text":"searchFields"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1superChannelFilter\/title","value":"superChannelFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1superChannelFilter\/fragments","value":[{"kind":"identifier","text":"superChannelFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1searchQuery\/title","value":"searchQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1searchQuery\/fragments","value":[{"kind":"identifier","text":"searchQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1publicChannelFilter\/title","value":"publicChannelFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1publicChannelFilter\/fragments","value":[{"kind":"identifier","text":"publicChannelFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1nicknameContainsFilter\/title","value":"nicknameContainsFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1nicknameContainsFilter\/fragments","value":[{"kind":"identifier","text":"nicknameContainsFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1limit\/title","value":"limit"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1limit\/fragments","value":[{"kind":"identifier","text":"limit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1userIDsExactFilter\/title","value":"userIDsExactFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1userIDsExactFilter\/fragments","value":[{"kind":"identifier","text":"userIDsExactFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1channelHiddenStateFilter\/title","value":"channelHiddenStateFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1channelHiddenStateFilter\/fragments","value":[{"kind":"identifier","text":"channelHiddenStateFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1setMetaDataFilter(_:valueStartsWith:)\/title","value":"setMetaDataFilterWithKey:valueStartsWith:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1setMetaDataFilter(_:valueStartsWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMetaDataFilterWithKey:valueStartsWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1memberStateFilter\/title","value":"memberStateFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1memberStateFilter\/fragments","value":[{"kind":"identifier","text":"memberStateFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1userIDsIncludeFilter\/title","value":"userIDsIncludeFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1userIDsIncludeFilter\/fragments","value":[{"kind":"identifier","text":"userIDsIncludeFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1includeMemberList\/title","value":"includeMemberList"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1includeMemberList\/fragments","value":[{"kind":"identifier","text":"includeMemberList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1metaDataKeyFilter\/title","value":"metaDataKeyFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1metaDataKeyFilter\/fragments","value":[{"kind":"identifier","text":"metaDataKeyFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1customTypeStartsWithFilter\/title","value":"customTypeStartsWithFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1customTypeStartsWithFilter\/fragments","value":[{"kind":"identifier","text":"customTypeStartsWithFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1customTypesFilter\/title","value":"customTypesFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1customTypesFilter\/fragments","value":[{"kind":"identifier","text":"customTypesFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1unreadChannelFilter\/title","value":"unreadChannelFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1unreadChannelFilter\/fragments","value":[{"kind":"identifier","text":"unreadChannelFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1metaDataOrderKeyFilter\/title","value":"metaDataOrderKeyFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1metaDataOrderKeyFilter\/fragments","value":[{"kind":"identifier","text":"metaDataOrderKeyFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1channelNameContainsFilter\/title","value":"channelNameContainsFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1channelNameContainsFilter\/fragments","value":[{"kind":"identifier","text":"channelNameContainsFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1setUserIDsIncludeFilter(_:queryType:)\/title","value":"setUserIDsIncludeFilter:queryType:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1setUserIDsIncludeFilter(_:queryType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserIDsIncludeFilter:queryType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1setSearchFilter(_:fields:)\/title","value":"setSearchFilter:fields:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1setSearchFilter(_:fields:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSearchFilter:fields:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1order\/title","value":"order"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQueryParams~1order\/fragments","value":[{"kind":"identifier","text":"order"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}