{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDGroupChannelListQuerySearchField) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQuerySearchField"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.144"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/s25ExpressibleByArrayLiteralP","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/s9OptionSetP","doc:\/\/com.sendbird.chat\/SY","doc:\/\/com.sendbird.chat\/s10SetAlgebraP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Filter types to query with "},{"type":"codeVoice","code":"GroupChannelListQuery"},{"type":"text","text":". You can combine search fields to query."},{"type":"text","text":" "},{"type":"text","text":"used for "},{"type":"codeVoice","code":"setSearchFilter(_:fields:)"},{"type":"text","text":" of "},{"type":"codeVoice","code":"GroupChannelListQuery"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQuerySearchField"}],"title":"GroupChannelListQuerySearchField","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuerySearchField","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQuerySearchField"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/init(fields:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/init(from:)-rgae","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/hash","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/rawValue"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/encode(to:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/formIntersection(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/formSymmetricDifference(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/formUnion(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/isEqual(_:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/channelName","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/memberNickname"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/OptionSet-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/RawRepresentable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/SetAlgebra-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/OptionSet-Implementations":{"role":"collectionGroup","title":"OptionSet Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/OptionSet-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/optionset-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/hash":{"role":"symbol","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/hash","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/hash"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/channelName":{"role":"symbol","title":"channelName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQuerySearchField","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuerySearchField"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/channelName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelName"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/channelname"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/memberNickname":{"role":"symbol","title":"memberNickname","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"memberNickname"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQuerySearchField","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuerySearchField"}],"abstract":[{"type":"text","text":"filter type to query for member nickname"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/memberNickname","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"memberNickname"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/membernickname"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField":{"role":"symbol","title":"GroupChannelListQuerySearchField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListQuerySearchField"}],"abstract":[{"type":"text","text":"Filter types to query with "},{"type":"codeVoice","code":"GroupChannelListQuery"},{"type":"text","text":". You can combine search fields to query."},{"type":"text","text":" "},{"type":"text","text":"used for "},{"type":"codeVoice","code":"setSearchFilter(_:fields:)"},{"type":"text","text":" of "},{"type":"codeVoice","code":"GroupChannelListQuery"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListQuerySearchField"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Encodes this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/encode(to:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/rawValue":{"role":"symbol","title":"rawValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The corresponding value of the raw type."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/rawValue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rawValue"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/rawvalue"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a new option set from the given raw value."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/init(rawValue:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRawValue:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/init(rawvalue:)"},"doc://com.sendbird.chat/s25ExpressibleByArrayLiteralP":{"type":"unresolvable","title":"Swift.ExpressibleByArrayLiteral","identifier":"doc:\/\/com.sendbird.chat\/s25ExpressibleByArrayLiteralP"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Compares this object with given other object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/isequal(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/formUnion(_:)":{"role":"symbol","title":"formUnion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formUnion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannelListQuerySearchField","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuerySearchField"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Adds the elements of the given set to the set."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/formUnion(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formUnion:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/formunion(_:)"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/s9OptionSetP":{"type":"unresolvable","title":"Swift.OptionSet","identifier":"doc:\/\/com.sendbird.chat\/s9OptionSetP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/init(from:)-rgae":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/init(from:)-rgae","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/init(from:)-rgae"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/s10SetAlgebraP":{"type":"unresolvable","title":"Swift.SetAlgebra","identifier":"doc:\/\/com.sendbird.chat\/s10SetAlgebraP"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/SetAlgebra-Implementations":{"role":"collectionGroup","title":"SetAlgebra Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/SetAlgebra-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/setalgebra-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/formIntersection(_:)":{"role":"symbol","title":"formIntersection(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formIntersection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannelListQuerySearchField","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuerySearchField"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes the elements of this set that aren’t also in the given set."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/formIntersection(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formIntersection:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/formintersection(_:)"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/init(fields:)":{"role":"symbol","title":"init(fields:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GroupChannelListQuerySearchField","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuerySearchField"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/init(fields:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFields:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/init(fields:)"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListQuerySearchField/formSymmetricDifference(_:)":{"role":"symbol","title":"formSymmetricDifference(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formSymmetricDifference"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannelListQuerySearchField","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuerySearchField"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes the elements of the set that are also in the given set and adds"},{"type":"text","text":" "},{"type":"text","text":"the members of the given set that are not already in the set."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/formSymmetricDifference(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formSymmetricDifference:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistquerysearchfield\/formsymmetricdifference(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDGroupChannelListQuerySearchField"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQuerySearchField"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDGroupChannelListQuerySearchField"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/channelName","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/hash","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/memberNickname","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/rawValue"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/formIntersection(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/formSymmetricDifference(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/formUnion(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/init(fields:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/init(rawValue:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListQuerySearchField\/isEqual(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDGroupChannelListQuerySearchField"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1channelName\/title","value":"channelName"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1channelName\/fragments","value":[{"kind":"identifier","text":"channelName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1memberNickname\/title","value":"memberNickname"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1memberNickname\/fragments","value":[{"kind":"identifier","text":"memberNickname"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField\/title","value":"SBDGroupChannelListQuerySearchField"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListQuerySearchField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1rawValue\/title","value":"rawValue"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1rawValue\/fragments","value":[{"kind":"identifier","text":"rawValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1init(rawValue:)\/title","value":"initWithRawValue:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1init(rawValue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRawValue:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1formUnion(_:)\/title","value":"formUnion:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1formUnion(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formUnion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1formIntersection(_:)\/title","value":"formIntersection:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1formIntersection(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formIntersection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1init(fields:)\/title","value":"initWithFields:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1init(fields:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFields:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1formSymmetricDifference(_:)\/title","value":"formSymmetricDifference:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListQuerySearchField~1formSymmetricDifference(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formSymmetricDifference:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}