{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDLogLevel) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/loglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/loglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/SL","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel","interfaceLanguage":"swift"},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/==(_:_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/_(_:_:)-1zpma"]},{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/debug","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/error","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/info","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/none","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/verbose","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/warning"]},{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/init(from:)-9bkql","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/init(rawValue:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/encode(to:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/Comparable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"title":"LogLevel","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDLogLevel","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"LogLevel"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"references":{"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel/init(from:)-9bkql":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/init(from:)-9bkql","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/loglevel\/init(from:)-9bkql"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/loglevel\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel/-Implementations":{"role":"collectionGroup","title":" Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/loglevel\/-implementations"},"doc://com.sendbird.chat/SL":{"type":"unresolvable","title":"Swift.Comparable","identifier":"doc:\/\/com.sendbird.chat\/SL"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/loglevel\/init(rawvalue:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel/debug":{"role":"symbol","title":"LogLevel.debug","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/debug","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDLogLevelDebug"}],"url":"\/documentation\/sendbirdchatsdk\/loglevel\/debug"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel/==(_:_:)":{"role":"symbol","title":"==(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"=="},{"kind":"text","text":" "},{"kind":"text","text":"(`Self`"},{"kind":"text","text":", `Self`"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/==(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/loglevel\/==(_:_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel/error":{"role":"symbol","title":"LogLevel.error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDLogLevelError"}],"url":"\/documentation\/sendbirdchatsdk\/loglevel\/error"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel/warning":{"role":"symbol","title":"LogLevel.warning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/warning","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDLogLevelWarning"}],"url":"\/documentation\/sendbirdchatsdk\/loglevel\/warning"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel":{"role":"symbol","title":"LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/sendbirdchatsdk\/loglevel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel/none":{"role":"symbol","title":"LogLevel.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDLogLevelNone"}],"url":"\/documentation\/sendbirdchatsdk\/loglevel\/none"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/loglevel\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel/verbose":{"role":"symbol","title":"LogLevel.verbose","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/verbose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDLogLevelVerbose"}],"url":"\/documentation\/sendbirdchatsdk\/loglevel\/verbose"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel/Comparable-Implementations":{"role":"collectionGroup","title":"Comparable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/Comparable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/loglevel\/comparable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel/_(_:_:)-1zpma":{"role":"symbol","title":"<(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"<"},{"kind":"text","text":" "},{"kind":"text","text":"(`Self`"},{"kind":"text","text":", `Self`"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/_(_:_:)-1zpma","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/loglevel\/_(_:_:)-1zpma"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/loglevel\/encode(to:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/LogLevel/info":{"role":"symbol","title":"LogLevel.info","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/info","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDLogLevelInfo"}],"url":"\/documentation\/sendbirdchatsdk\/loglevel\/info"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDLogLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDLogLevel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDLogLevel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/debug","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/error","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/info","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/none","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/verbose","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/LogLevel\/warning"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDLogLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel~1debug\/title","value":"SBDLogLevelDebug"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel~1debug\/fragments","value":[{"kind":"identifier","text":"SBDLogLevelDebug"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel~1error\/title","value":"SBDLogLevelError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel~1error\/fragments","value":[{"kind":"identifier","text":"SBDLogLevelError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel~1warning\/title","value":"SBDLogLevelWarning"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel~1warning\/fragments","value":[{"kind":"identifier","text":"SBDLogLevelWarning"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel\/title","value":"SBDLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel\/fragments","value":[{"kind":"identifier","text":"SBDLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel~1none\/title","value":"SBDLogLevelNone"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel~1none\/fragments","value":[{"kind":"identifier","text":"SBDLogLevelNone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel~1verbose\/title","value":"SBDLogLevelVerbose"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel~1verbose\/fragments","value":[{"kind":"identifier","text":"SBDLogLevelVerbose"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel~1info\/title","value":"SBDLogLevelInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1LogLevel~1info\/fragments","value":[{"kind":"identifier","text":"SBDLogLevelInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}