{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDMember) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Member"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/member"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/member"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Serializable","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/s12IdentifiableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents a member in "},{"type":"codeVoice","code":"GroupChannel"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Member"}],"title":"Member","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMember","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"Member"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/isBlockedByMe","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/isBlockingMe","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/isMuted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/restrictionInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/role","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/state"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/encode(to:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/serialize()"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/build(fromSerializedData:)"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member/build(fromSerializedData:)":{"role":"symbol","title":"build(fromSerializedData:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromSerializedData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?) -> `Self`"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Deserializes and reconstructs the object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/build(fromSerializedData:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildFromSerializedData:"}],"url":"\/documentation\/sendbirdchatsdk\/member\/build(fromserializeddata:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member/serialize()":{"role":"symbol","title":"serialize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"serialize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Serializes this object into data"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/serialize()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serialize"}],"url":"\/documentation\/sendbirdchatsdk\/member\/serialize()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User":{"role":"symbol","title":"User","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"User"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"User"},{"type":"text","text":" class represents a user. The user is identified by the "},{"type":"codeVoice","code":"userID"},{"type":"text","text":", so the "},{"type":"codeVoice","code":"userID"},{"type":"text","text":" has"},{"type":"text","text":" "},{"type":"text","text":"to be unique. The "},{"type":"codeVoice","code":"userID"},{"type":"text","text":", "},{"type":"codeVoice","code":"nickname"},{"type":"text","text":" and "},{"type":"codeVoice","code":"profileURL"},{"type":"text","text":" are valid in every "},{"type":"codeVoice","code":"User"},{"type":"text","text":" "},{"type":"text","text":"instance, however the "},{"type":"codeVoice","code":"connectionStatus"},{"type":"text","text":" and "},{"type":"codeVoice","code":"lastSeenAt"},{"type":"text","text":" is valid in "},{"type":"codeVoice","code":"User"},{"type":"text","text":" instance"},{"type":"text","text":" "},{"type":"text","text":"from "},{"type":"codeVoice","code":"UserListQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"User"}],"url":"\/documentation\/sendbirdchatsdk\/user"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Compares this object with given other object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/sendbirdchatsdk\/member\/isequal(_:)"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member/isMuted":{"role":"symbol","title":"isMuted","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMuted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"The muted state of the member in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/isMuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isMuted"}],"url":"\/documentation\/sendbirdchatsdk\/member\/ismuted"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/member\/init(from:)"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Mappable":{"role":"symbol","title":"Mappable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mappable"}],"abstract":[{"type":"text","text":"Mappable protocol to initialize sendbird object from a given dictionary."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Mappable"}],"url":"\/documentation\/sendbirdchatsdk\/mappable"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member/isBlockedByMe":{"role":"symbol","title":"isBlockedByMe","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isBlockedByMe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether this member has been blocked by me"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/isBlockedByMe","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isBlockedByMe"}],"url":"\/documentation\/sendbirdchatsdk\/member\/isblockedbyme"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member/state":{"role":"symbol","title":"state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MemberState","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberState"}],"abstract":[{"type":"text","text":"The state for invitation. The values of the property are "},{"type":"codeVoice","code":"invited"},{"type":"text","text":" and "},{"type":"codeVoice","code":"joined"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"invited"},{"type":"text","text":" means that the user doesn’t accept the invitation yet and the "},{"type":"codeVoice","code":"joined"},{"type":"text","text":" "},{"type":"text","text":"means that the user accepted the invitation manually or automatically."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/state","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"state"}],"url":"\/documentation\/sendbirdchatsdk\/member\/state"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member":{"role":"symbol","title":"Member","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Member"}],"abstract":[{"type":"text","text":"Represents a member in "},{"type":"codeVoice","code":"GroupChannel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Member"}],"url":"\/documentation\/sendbirdchatsdk\/member"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Copies this object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/sendbirdchatsdk\/member\/copy(with:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member/restrictionInfo":{"role":"symbol","title":"restrictionInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restrictionInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RestrictionInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDRestrictionInfo"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Restriction information of a muted member."},{"type":"text","text":" "},{"type":"text","text":"This property is nil for an unmuted member."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/restrictionInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"restrictionInfo"}],"url":"\/documentation\/sendbirdchatsdk\/member\/restrictioninfo"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/s12IdentifiableP":{"type":"unresolvable","title":"Swift.Identifiable","identifier":"doc:\/\/com.sendbird.chat\/s12IdentifiableP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member/isBlockingMe":{"role":"symbol","title":"isBlockingMe","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isBlockingMe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether this member has blocked me"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/isBlockingMe","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isBlockingMe"}],"url":"\/documentation\/sendbirdchatsdk\/member\/isblockingme"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member/role":{"role":"symbol","title":"role","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"role"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Role","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDRole"}],"abstract":[{"type":"text","text":"The role of current user in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/role","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"role"}],"url":"\/documentation\/sendbirdchatsdk\/member\/role"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Serializable":{"role":"symbol","title":"Serializable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Serializable"}],"abstract":[{"type":"text","text":"Protocol to provide serialization"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Serializable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Serializable"}],"url":"\/documentation\/sendbirdchatsdk\/serializable"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Encodes this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/member\/encode(to:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDMember"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMember"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDMember"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/isBlockedByMe","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/isBlockingMe","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/isMuted","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/restrictionInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/role","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/state"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/serialize()"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member\/build(fromSerializedData:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDMember"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser","text":"SBDUser"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1build(fromSerializedData:)\/title","value":"buildFromSerializedData:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1build(fromSerializedData:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildFromSerializedData:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1serialize()\/title","value":"serialize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1serialize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"serialize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User\/title","value":"SBDUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User\/fragments","value":[{"kind":"identifier","text":"SBDUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1isMuted\/title","value":"isMuted"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1isMuted\/fragments","value":[{"kind":"identifier","text":"isMuted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/title","value":"Mappable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/fragments","value":[{"kind":"identifier","text":"Mappable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1isBlockedByMe\/title","value":"isBlockedByMe"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1isBlockedByMe\/fragments","value":[{"kind":"identifier","text":"isBlockedByMe"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1state\/title","value":"state"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1state\/fragments","value":[{"kind":"identifier","text":"state"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member\/title","value":"SBDMember"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member\/fragments","value":[{"kind":"identifier","text":"SBDMember"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1restrictionInfo\/title","value":"restrictionInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1restrictionInfo\/fragments","value":[{"kind":"identifier","text":"restrictionInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1isBlockingMe\/title","value":"isBlockingMe"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1isBlockingMe\/fragments","value":[{"kind":"identifier","text":"isBlockingMe"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1role\/title","value":"role"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member~1role\/fragments","value":[{"kind":"identifier","text":"role"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Serializable\/title","value":"Serializable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Serializable\/fragments","value":[{"kind":"identifier","text":"Serializable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}