{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDMemberListOrder) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListOrder"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.198"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/memberlistorder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/memberlistorder"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The order type for member list query."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListOrder"}],"title":"MemberListOrder","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDMemberListOrder","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MemberListOrder"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/nicknameAlphabetical","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/operatorThenMemberNicknameAlphabetical"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListOrder/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/memberlistorder\/rawrepresentable-implementations"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListOrder/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/memberlistorder\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListOrder/nicknameAlphabetical":{"role":"symbol","title":"MemberListOrder.nicknameAlphabetical","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nicknameAlphabetical"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/nicknameAlphabetical","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMemberListOrderNicknameAlphabetical"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistorder\/nicknamealphabetical"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListOrder/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/memberlistorder\/decodable-implementations"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListOrder/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/memberlistorder\/encodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListOrder/operatorThenMemberNicknameAlphabetical":{"role":"symbol","title":"MemberListOrder.operatorThenMemberNicknameAlphabetical","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatorThenMemberNicknameAlphabetical"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/operatorThenMemberNicknameAlphabetical","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMemberListOrderOperatorThenMemberNicknameAlphabetical"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistorder\/operatorthenmembernicknamealphabetical"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListOrder":{"role":"symbol","title":"MemberListOrder","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListOrder"}],"abstract":[{"type":"text","text":"The order type for member list query."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListOrder"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistorder"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDMemberListOrder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMemberListOrder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDMemberListOrder"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/nicknameAlphabetical","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder\/operatorThenMemberNicknameAlphabetical"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDMemberListOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder~1nicknameAlphabetical\/title","value":"SBDMemberListOrderNicknameAlphabetical"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder~1nicknameAlphabetical\/fragments","value":[{"kind":"identifier","text":"SBDMemberListOrderNicknameAlphabetical"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder~1operatorThenMemberNicknameAlphabetical\/title","value":"SBDMemberListOrderOperatorThenMemberNicknameAlphabetical"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder~1operatorThenMemberNicknameAlphabetical\/fragments","value":[{"kind":"identifier","text":"SBDMemberListOrderOperatorThenMemberNicknameAlphabetical"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder\/title","value":"SBDMemberListOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder\/fragments","value":[{"kind":"identifier","text":"SBDMemberListOrder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}