{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDMemberListQuery) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListQuery"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The instance of this class is created by "},{"type":"codeVoice","code":"createMemberListQuery()"},{"type":"text","text":" in "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" class."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/memberlistquery"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/memberlistquery"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MemberListQuery"},{"type":"text","text":" class is a query class for getting the list member in group channels."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListQuery"}],"title":"MemberListQuery","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQuery","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MemberListQuery"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/hasNext","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/isLoading","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/limit","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/memberStateFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/mutedMemberFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/operatorFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/order"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/loadNextPage(completionHandler:)"]}],"references":{"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Copies this object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery\/copy(with:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery/order":{"role":"symbol","title":"order","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MemberListOrder","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberListOrder"}],"abstract":[{"type":"text","text":"Sets how the query result should be ordered."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/order","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"order"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery\/order"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery/isLoading":{"role":"symbol","title":"isLoading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Indicates the query is currently loading or not"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/isLoading","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isLoading"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery\/isloading"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery/limit":{"role":"symbol","title":"limit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"limit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Specifies the number of results to return per call. (Default: 20)"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/limit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"limit"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery\/limit"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery/mutedMemberFilter":{"role":"symbol","title":"mutedMemberFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mutedMemberFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelMutedMemberFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelMutedMemberFilter"}],"abstract":[{"type":"text","text":"Sets a filter to query muted member list."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/mutedMemberFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mutedMemberFilter"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery\/mutedmemberfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery/hasNext":{"role":"symbol","title":"hasNext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasNext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Boolean indicates there are more data to fetch"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/hasNext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasNext"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery\/hasnext"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery/operatorFilter":{"role":"symbol","title":"operatorFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatorFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelOperatorFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelOperatorFilter"}],"abstract":[{"type":"text","text":"Sets a filter to query operators."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/operatorFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"operatorFilter"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery\/operatorfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery":{"role":"symbol","title":"MemberListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MemberListQuery"},{"type":"text","text":" class is a query class for getting the list member in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery/params":{"role":"symbol","title":"params","fragments":[{"kind":"identifier","text":"params"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/params","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/memberlistquery\/params"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery/loadNextPage(completionHandler:)":{"role":"symbol","title":"loadNextPage(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadNextPage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MemberListHandler","preciseIdentifier":"s:15SendbirdChatSDK17MemberListHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Fetches next page"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/loadNextPage(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadNextPageWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery\/loadnextpage(completionhandler:)"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery/memberStateFilter":{"role":"symbol","title":"memberStateFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memberStateFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MemberStateFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberStateFilter"}],"abstract":[{"type":"text","text":"Sets a filter to query member list with member state."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/memberStateFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"memberStateFilter"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery\/memberstatefilter"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDMemberListQuery"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMemberListQuery"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDMemberListQuery"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/hasNext","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/isLoading","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/limit","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/memberStateFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/mutedMemberFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/operatorFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/order","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/params"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/loadNextPage(completionHandler:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDMemberListQuery"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1order\/title","value":"order"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1order\/fragments","value":[{"kind":"identifier","text":"order"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1isLoading\/title","value":"isLoading"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1isLoading\/fragments","value":[{"kind":"identifier","text":"isLoading"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1limit\/title","value":"limit"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1limit\/fragments","value":[{"kind":"identifier","text":"limit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1mutedMemberFilter\/title","value":"mutedMemberFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1mutedMemberFilter\/fragments","value":[{"kind":"identifier","text":"mutedMemberFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1hasNext\/title","value":"hasNext"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1hasNext\/fragments","value":[{"kind":"identifier","text":"hasNext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1operatorFilter\/title","value":"operatorFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1operatorFilter\/fragments","value":[{"kind":"identifier","text":"operatorFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery\/title","value":"SBDMemberListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery\/fragments","value":[{"kind":"identifier","text":"SBDMemberListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1loadNextPage(completionHandler:)\/title","value":"loadNextPageWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1loadNextPage(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadNextPageWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1memberStateFilter\/title","value":"memberStateFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1memberStateFilter\/fragments","value":[{"kind":"identifier","text":"memberStateFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}