{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDMemberStateFilter) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberStateFilter"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/memberstatefilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/memberstatefilter"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Member state filter for group channel list query and group channel count"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberStateFilter"}],"title":"MemberStateFilter","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDMemberStateFilter","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MemberStateFilter"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/all","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/invitedByFriend","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/invitedByNonFriend","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/invitedOnly","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/joinedOnly"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberStateFilter/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/memberstatefilter\/equatable-implementations"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberStateFilter/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/memberstatefilter\/encodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberStateFilter/invitedByFriend":{"role":"symbol","title":"MemberStateFilter.invitedByFriend","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invitedByFriend"}],"abstract":[{"type":"text","text":"Filter of invited by friend state only."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/invitedByFriend","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMemberStateFilterInvitedByFriend"}],"url":"\/documentation\/sendbirdchatsdk\/memberstatefilter\/invitedbyfriend"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberStateFilter":{"role":"symbol","title":"MemberStateFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberStateFilter"}],"abstract":[{"type":"text","text":"Member state filter for group channel list query and group channel count"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberStateFilter"}],"url":"\/documentation\/sendbirdchatsdk\/memberstatefilter"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberStateFilter/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/memberstatefilter\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberStateFilter/invitedByNonFriend":{"role":"symbol","title":"MemberStateFilter.invitedByNonFriend","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invitedByNonFriend"}],"abstract":[{"type":"text","text":"Filter of invited by non-friend state only."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/invitedByNonFriend","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMemberStateFilterInvitedByNonFriend"}],"url":"\/documentation\/sendbirdchatsdk\/memberstatefilter\/invitedbynonfriend"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberStateFilter/invitedOnly":{"role":"symbol","title":"MemberStateFilter.invitedOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invitedOnly"}],"abstract":[{"type":"text","text":"Filter of invited state only. This contains "},{"type":"codeVoice","code":".invitedByFriend"},{"type":"text","text":"and "},{"type":"codeVoice","code":"invitedByNonFriend"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/invitedOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMemberStateFilterInvitedOnly"}],"url":"\/documentation\/sendbirdchatsdk\/memberstatefilter\/invitedonly"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberStateFilter/joinedOnly":{"role":"symbol","title":"MemberStateFilter.joinedOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinedOnly"}],"abstract":[{"type":"text","text":"Filter of joined state only."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/joinedOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMemberStateFilterJoinedOnly"}],"url":"\/documentation\/sendbirdchatsdk\/memberstatefilter\/joinedonly"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberStateFilter/all":{"role":"symbol","title":"MemberStateFilter.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[{"type":"text","text":"Filter of all member states."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMemberStateFilterAll"}],"url":"\/documentation\/sendbirdchatsdk\/memberstatefilter\/all"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberStateFilter/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/memberstatefilter\/decodable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDMemberStateFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMemberStateFilter"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDMemberStateFilter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/all","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/invitedByFriend","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/invitedByNonFriend","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/invitedOnly","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter\/joinedOnly"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDMemberStateFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter~1invitedByFriend\/title","value":"SBDMemberStateFilterInvitedByFriend"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter~1invitedByFriend\/fragments","value":[{"kind":"identifier","text":"SBDMemberStateFilterInvitedByFriend"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter\/title","value":"SBDMemberStateFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter\/fragments","value":[{"kind":"identifier","text":"SBDMemberStateFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter~1invitedByNonFriend\/title","value":"SBDMemberStateFilterInvitedByNonFriend"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter~1invitedByNonFriend\/fragments","value":[{"kind":"identifier","text":"SBDMemberStateFilterInvitedByNonFriend"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter~1invitedOnly\/title","value":"SBDMemberStateFilterInvitedOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter~1invitedOnly\/fragments","value":[{"kind":"identifier","text":"SBDMemberStateFilterInvitedOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter~1joinedOnly\/title","value":"SBDMemberStateFilterJoinedOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter~1joinedOnly\/fragments","value":[{"kind":"identifier","text":"SBDMemberStateFilterJoinedOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter~1all\/title","value":"SBDMemberStateFilterAll"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter~1all\/fragments","value":[{"kind":"identifier","text":"SBDMemberStateFilterAll"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}