{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDMessageCollectionDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollectionDelegate"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.1.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagecollectiondelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagecollectiondelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Methods that are invoked when the event of the message collection occurs."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollectionDelegate"}],"title":"MessageCollectionDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDMessageCollectionDelegate","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MessageCollectionDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/didDetectHugeGap(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:channel:addedMessages:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:channel:deletedMessages:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:channel:updatedMessages:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:deletedChannel:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:updatedChannel:)"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionDelegate":{"role":"symbol","title":"MessageCollectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollectionDelegate"}],"abstract":[{"type":"text","text":"Methods that are invoked when the event of the message collection occurs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollectionDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollectiondelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionDelegate/messageCollection(_:context:channel:addedMessages:)":{"navigatorTitle":[{"kind":"identifier","text":"messageCollection:context:channel:addedMessages:"}],"role":"symbol","title":"messageCollection(_:context:channel:addedMessages:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedMessages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Invoked when the messages are added."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:channel:addedMessages:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagecollectiondelegate\/messagecollection(_:context:channel:addedmessages:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionDelegate/messageCollection(_:context:channel:updatedMessages:)":{"navigatorTitle":[{"kind":"identifier","text":"messageCollection:context:channel:updatedMessages:"}],"role":"symbol","title":"messageCollection(_:context:channel:updatedMessages:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"updatedMessages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Invoked when the message are updated."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:channel:updatedMessages:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagecollectiondelegate\/messagecollection(_:context:channel:updatedmessages:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionDelegate/didDetectHugeGap(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didDetectHugeGap:"}],"role":"symbol","title":"didDetectHugeGap(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDetectHugeGap"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Invoked when the huge gap has been detected."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/didDetectHugeGap(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagecollectiondelegate\/diddetecthugegap(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionDelegate/messageCollection(_:context:updatedChannel:)":{"navigatorTitle":[{"kind":"identifier","text":"messageCollection:context:updatedChannel:"}],"role":"symbol","title":"messageCollection(_:context:updatedChannel:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"updatedChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Invoked when the channel that has the message collection is changed."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:updatedChannel:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagecollectiondelegate\/messagecollection(_:context:updatedchannel:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionDelegate/messageCollection(_:context:channel:deletedMessages:)":{"navigatorTitle":[{"kind":"identifier","text":"messageCollection:context:channel:deletedMessages:"}],"role":"symbol","title":"messageCollection(_:context:channel:deletedMessages:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedMessages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Invoked when the message are deleted."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:channel:deletedMessages:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagecollectiondelegate\/messagecollection(_:context:channel:deletedmessages:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollectionDelegate/messageCollection(_:context:deletedChannel:)":{"navigatorTitle":[{"kind":"identifier","text":"messageCollection:context:deletedChannel:"}],"role":"symbol","title":"messageCollection(_:context:deletedChannel:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Invoked when the channel that has the message collection is deleted."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:deletedChannel:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagecollectiondelegate\/messagecollection(_:context:deletedchannel:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageCollectionDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollectionDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDMessageCollectionDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/didDetectHugeGap(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:channel:addedMessages:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:channel:deletedMessages:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:channel:updatedMessages:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:deletedChannel:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollectionDelegate\/messageCollection(_:context:updatedChannel:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDMessageCollectionDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate\/title","value":"SBDMessageCollectionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollectionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1messageCollection(_:context:channel:addedMessages:)\/title","value":"messageCollection:context:channel:addedMessages:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1messageCollection(_:context:channel:addedMessages:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageCollection:context:channel:addedMessages:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1messageCollection(_:context:channel:updatedMessages:)\/title","value":"messageCollection:context:channel:updatedMessages:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1messageCollection(_:context:channel:updatedMessages:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageCollection:context:channel:updatedMessages:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1didDetectHugeGap(_:)\/title","value":"didDetectHugeGap:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1didDetectHugeGap(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didDetectHugeGap:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1messageCollection(_:context:updatedChannel:)\/title","value":"messageCollection:context:updatedChannel:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1messageCollection(_:context:updatedChannel:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageCollection:context:updatedChannel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1messageCollection(_:context:channel:deletedMessages:)\/title","value":"messageCollection:context:channel:deletedMessages:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1messageCollection(_:context:channel:deletedMessages:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageCollection:context:channel:deletedMessages:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1messageCollection(_:context:deletedChannel:)\/title","value":"messageCollection:context:deletedChannel:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollectionDelegate~1messageCollection(_:context:deletedChannel:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageCollection:context:deletedChannel:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}