{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDMessageSearchQueryOrder) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSearchQueryOrder"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.162"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagesearchqueryorder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagesearchqueryorder"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The order type for "},{"type":"codeVoice","code":"MessageSearchQuery"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSearchQueryOrder"}],"title":"MessageSearchQueryOrder","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDMessageSearchQueryOrder","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MessageSearchQueryOrder"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/score","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/timeStamp"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQueryOrder/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagesearchqueryorder\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQueryOrder/score":{"role":"symbol","title":"MessageSearchQueryOrder.score","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"score"}],"abstract":[{"type":"text","text":"Score type Returns the result as by their matching score."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/score","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageSearchQueryOrderScore"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchqueryorder\/score"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQueryOrder/timeStamp":{"role":"symbol","title":"MessageSearchQueryOrder.timeStamp","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeStamp"}],"abstract":[{"type":"text","text":"Timestamp type Returns the result as by "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":"’s timestamp."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/timeStamp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageSearchQueryOrderTimeStamp"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchqueryorder\/timestamp"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQueryOrder/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagesearchqueryorder\/decodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQueryOrder":{"role":"symbol","title":"MessageSearchQueryOrder","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSearchQueryOrder"}],"abstract":[{"type":"text","text":"The order type for "},{"type":"codeVoice","code":"MessageSearchQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageSearchQueryOrder"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchqueryorder"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQueryOrder/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagesearchqueryorder\/equatable-implementations"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageSearchQueryOrder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageSearchQueryOrder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDMessageSearchQueryOrder"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/score","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryOrder\/timeStamp"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDMessageSearchQueryOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryOrder~1score\/title","value":"SBDMessageSearchQueryOrderScore"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryOrder~1score\/fragments","value":[{"kind":"identifier","text":"SBDMessageSearchQueryOrderScore"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryOrder~1timeStamp\/title","value":"SBDMessageSearchQueryOrderTimeStamp"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryOrder~1timeStamp\/fragments","value":[{"kind":"identifier","text":"SBDMessageSearchQueryOrderTimeStamp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryOrder\/title","value":"SBDMessageSearchQueryOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryOrder\/fragments","value":[{"kind":"identifier","text":"SBDMessageSearchQueryOrder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}