{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDMessageListParams) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListParams"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.181"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagelistparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagelistparams"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object contains set of options for get message methods"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListParams"}],"title":"MessageListParams","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListParams"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:showSubChannelMessagesOnly:customTypes:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/customType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/customTypes","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/includeMetaArray","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/includeParentMessageInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/includePollDetails","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/includeReactions","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/includeThreadInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/isInclusive","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/messageTypeFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/nextResultSize","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/previousResultSize","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/replyType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/reverse","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/senderUserIDs","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/showSubChannelMessagesOnly"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/belongsTo(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/belongsToMessageParams(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/isEqual(_:)"]}],"references":{"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams":{"role":"symbol","title":"MessageListParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListParams"}],"abstract":[{"type":"text","text":"An object contains set of options for get message methods"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageListParams"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/includeMetaArray":{"role":"symbol","title":"includeMetaArray","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeMetaArray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include the metaarray information of the messages in the results. Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/includeMetaArray","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeMetaArray"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/includemetaarray"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/nextResultSize":{"role":"symbol","title":"nextResultSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextResultSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The number of messages to retrieve that were sent after the specified timestamp or message ID. Default is 0"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/nextResultSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nextResultSize"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/nextresultsize"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/replyType":{"role":"symbol","title":"replyType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"replyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReplyType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReplyType"}],"abstract":[{"type":"text","text":"Determines which reply types to include. Default is "},{"type":"codeVoice","code":".none"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/replyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"replyType"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/replytype"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/messageTypeFilter":{"role":"symbol","title":"messageTypeFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageTypeFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageTypeFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageTypeFilter"}],"abstract":[{"type":"text","text":"Restricts the search scope only to retrieve messages with the specified message type. Default is "},{"type":"codeVoice","code":".all"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/messageTypeFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageTypeFilter"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/messagetypefilter"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/senderUserIDs":{"role":"symbol","title":"senderUserIDs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"senderUserIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Restricts the search scope only to retrieve the messages sent by the users with the specified user IDs."},{"type":"text","text":" "},{"type":"text","text":"When the user ID filtering is not needed, the value should be set to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/senderUserIDs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"senderUserIDs"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/senderuserids"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/init()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/customTypes":{"role":"symbol","title":"customTypes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Restricts the search scope only to retrieve the messages with the multiple specified custom message"},{"type":"text","text":" "},{"type":"text","text":"types. When the custom type filtering is not needed, the value should be set to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/customTypes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customTypes"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/customtypes"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/includeReactions":{"role":"symbol","title":"includeReactions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeReactions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include the reactions to the messages in the results. Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/includeReactions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeReactions"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/includereactions"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Copies this object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/copy(with:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/reverse":{"role":"symbol","title":"reverse","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reverse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to sort the retrieved messages in reverse order. If "},{"type":"codeVoice","code":"false"},{"type":"text","text":", the results are in ascending order.  Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/reverse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reverse"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/reverse"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/belongsTo(_:)":{"role":"symbol","title":"belongsTo(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"belongsTo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checks whether given message is belonged to this params"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/belongsTo(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"belongsTo:"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/belongsto(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/includePollDetails":{"role":"symbol","title":"includePollDetails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includePollDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include poll information in the message. Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/includePollDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includePollDetails"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/includepolldetails"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/includeParentMessageInfo":{"role":"symbol","title":"includeParentMessageInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeParentMessageInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include parent message info. Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/includeParentMessageInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeParentMessageInfo"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/includeparentmessageinfo"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/customType":{"role":"symbol","title":"customType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Restricts the search scope only to retrieve the messages with the specified custom message type."},{"type":"text","text":" "},{"type":"text","text":"When the custom type filtering is not needed, the value should be set to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If the "},{"type":"codeVoice","code":"customTypes"},{"type":"text","text":" is set, this property is ignored."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/customType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customType"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/customtype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/previousResultSize":{"role":"symbol","title":"previousResultSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousResultSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The number of messages to retrieve that were sent before the specified timestamp or message ID. Default is 20"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/previousResultSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"previousResultSize"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/previousresultsize"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/isequal(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/isInclusive":{"role":"symbol","title":"isInclusive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInclusive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include the messages with the matching timestamp or message ID in the results. Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/isInclusive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isInclusive"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/isinclusive"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:showSubChannelMessagesOnly:customTypes:)":{"role":"symbol","title":"init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:showSubChannelMessagesOnly:customTypes:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"previousResultSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nextResultSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isInclusive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reverse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageTypeFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageTypeFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageTypeFilter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"senderUserIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"includeMetaArray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeReactions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeThreadInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includePollDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeParentMessageInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReplyType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReplyType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showSubChannelMessagesOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Parameter constructor"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:showSubChannelMessagesOnly:customTypes:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPreviousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:showSubChannelMessagesOnly:customTypes:"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/init(previousresultsize:nextresultsize:isinclusive:reverse:messagetypefilter:customtype:senderuserids:includemetaarray:includereactions:includethreadinfo:includepolldetails:includeparentmessageinfo:replytype:showsubchannelmessagesonly:custo-65076"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/showSubChannelMessagesOnly":{"role":"symbol","title":"showSubChannelMessagesOnly","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSubChannelMessagesOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include only messages from the subChannel to which you belong in the results. Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/showSubChannelMessagesOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showSubChannelMessagesOnly"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/showsubchannelmessagesonly"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/belongsToMessageParams(_:)":{"role":"symbol","title":"belongsToMessageParams(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"belongsToMessageParams"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessageCreateParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checks whether the given params is belonged to this object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/belongsToMessageParams(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"belongsToMessageParams:"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/belongstomessageparams(_:)"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageListParams/includeThreadInfo":{"role":"symbol","title":"includeThreadInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeThreadInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include the thread information of the messages in the results when the results contain root messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/includeThreadInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeThreadInfo"}],"url":"\/documentation\/sendbirdchatsdk\/messagelistparams\/includethreadinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageListParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageListParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDMessageListParams"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/customType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/customTypes","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/includeMetaArray","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/includeParentMessageInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/includePollDetails","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/includeReactions","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/includeThreadInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/isInclusive","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/messageTypeFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/nextResultSize","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/previousResultSize","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/replyType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/reverse","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/senderUserIDs","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/showSubChannelMessagesOnly"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/belongsTo(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/belongsToMessageParams(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:showSubChannelMessagesOnly:customTypes:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageListParams\/isEqual(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDMessageListParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams\/title","value":"SBDMessageListParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams\/fragments","value":[{"kind":"identifier","text":"SBDMessageListParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1includeMetaArray\/title","value":"includeMetaArray"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1includeMetaArray\/fragments","value":[{"kind":"identifier","text":"includeMetaArray"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1nextResultSize\/title","value":"nextResultSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1nextResultSize\/fragments","value":[{"kind":"identifier","text":"nextResultSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1replyType\/title","value":"replyType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1replyType\/fragments","value":[{"kind":"identifier","text":"replyType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1messageTypeFilter\/title","value":"messageTypeFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1messageTypeFilter\/fragments","value":[{"kind":"identifier","text":"messageTypeFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1senderUserIDs\/title","value":"senderUserIDs"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1senderUserIDs\/fragments","value":[{"kind":"identifier","text":"senderUserIDs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1customTypes\/title","value":"customTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1customTypes\/fragments","value":[{"kind":"identifier","text":"customTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1includeReactions\/title","value":"includeReactions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1includeReactions\/fragments","value":[{"kind":"identifier","text":"includeReactions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1reverse\/title","value":"reverse"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1reverse\/fragments","value":[{"kind":"identifier","text":"reverse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1belongsTo(_:)\/title","value":"belongsTo:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1belongsTo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"belongsTo:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1includePollDetails\/title","value":"includePollDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1includePollDetails\/fragments","value":[{"kind":"identifier","text":"includePollDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1includeParentMessageInfo\/title","value":"includeParentMessageInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1includeParentMessageInfo\/fragments","value":[{"kind":"identifier","text":"includeParentMessageInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1customType\/title","value":"customType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1customType\/fragments","value":[{"kind":"identifier","text":"customType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1previousResultSize\/title","value":"previousResultSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1previousResultSize\/fragments","value":[{"kind":"identifier","text":"previousResultSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1isInclusive\/title","value":"isInclusive"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1isInclusive\/fragments","value":[{"kind":"identifier","text":"isInclusive"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:showSubChannelMessagesOnly:customTypes:)\/title","value":"initWithPreviousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:showSubChannelMessagesOnly:customTypes:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:showSubChannelMessagesOnly:customTypes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreviousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:showSubChannelMessagesOnly:customTypes:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1showSubChannelMessagesOnly\/title","value":"showSubChannelMessagesOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1showSubChannelMessagesOnly\/fragments","value":[{"kind":"identifier","text":"showSubChannelMessagesOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1belongsToMessageParams(_:)\/title","value":"belongsToMessageParams:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1belongsToMessageParams(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"belongsToMessageParams:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1includeThreadInfo\/title","value":"includeThreadInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageListParams~1includeThreadInfo\/fragments","value":[{"kind":"identifier","text":"includeThreadInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}