{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDMessageMetaArray) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageMetaArray"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The value consists of a string."},{"type":"text","text":" "},{"type":"text","text":"It usually can be used for ‘vote’ or ‘reaction’ for the message."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagemetaarray"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagemetaarray"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Serializable","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MessageMetaArray"},{"type":"text","text":" instance has a string type of key and an array type of value."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageMetaArray"}],"title":"MessageMetaArray","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageMetaArray","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MessageMetaArray"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/init(from:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/init(key:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/init(key:value:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/key","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/value"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/addValue(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/addValue(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/removeValue(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/removeValue(with:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/NSCopying-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/Serializable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageMetaArray/addValue(_:)":{"role":"symbol","title":"addValue(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addValue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">)"}],"abstract":[{"type":"text","text":"Adds an set type of the value to the receiver’s value field."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/addValue(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addValue:"}],"url":"\/documentation\/sendbirdchatsdk\/messagemetaarray\/addvalue(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Serializable":{"role":"symbol","title":"Serializable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Serializable"}],"abstract":[{"type":"text","text":"Protocol to provide serialization"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Serializable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Serializable"}],"url":"\/documentation\/sendbirdchatsdk\/serializable"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageMetaArray/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Compares this object with given other object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/sendbirdchatsdk\/messagemetaarray\/isequal(_:)"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageMetaArray/NSCopying-Implementations":{"role":"collectionGroup","title":"NSCopying Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/NSCopying-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagemetaarray\/nscopying-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageMetaArray/value":{"role":"symbol","title":"value","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The value consists of a string."},{"type":"text","text":" "},{"type":"text","text":"The value guarantees de-duplicated string."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/value","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"value"}],"url":"\/documentation\/sendbirdchatsdk\/messagemetaarray\/value"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageMetaArray/init(key:)":{"role":"symbol","title":"init(key:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes an message meta array with the given key and an empty array of the value."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/init(key:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithKey:"}],"url":"\/documentation\/sendbirdchatsdk\/messagemetaarray\/init(key:)"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageMetaArray/removeValue(_:)":{"role":"symbol","title":"removeValue(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeValue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">)"}],"abstract":[{"type":"text","text":"Removes an set type of the value from the receiver’s value field."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/removeValue(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeValue:"}],"url":"\/documentation\/sendbirdchatsdk\/messagemetaarray\/removevalue(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageMetaArray/removeValue(with:)":{"role":"symbol","title":"removeValue(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Removes an array type of the value from the receiver’s value field."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/removeValue(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeValueWithArray:"}],"url":"\/documentation\/sendbirdchatsdk\/messagemetaarray\/removevalue(with:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageMetaArray":{"role":"symbol","title":"MessageMetaArray","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageMetaArray"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MessageMetaArray"},{"type":"text","text":" instance has a string type of key and an array type of value."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageMetaArray"}],"url":"\/documentation\/sendbirdchatsdk\/messagemetaarray"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageMetaArray/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagemetaarray\/init(from:)"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageMetaArray/Serializable-Implementations":{"role":"collectionGroup","title":"Serializable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/Serializable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagemetaarray\/serializable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageMetaArray/key":{"role":"symbol","title":"key","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"A string type of key."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/key","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"key"}],"url":"\/documentation\/sendbirdchatsdk\/messagemetaarray\/key"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageMetaArray/init(key:value:)":{"role":"symbol","title":"init(key:value:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Initializes an message meta array with the given key and the given value."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/init(key:value:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithKey:value:"}],"url":"\/documentation\/sendbirdchatsdk\/messagemetaarray\/init(key:value:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageMetaArray/addValue(with:)":{"role":"symbol","title":"addValue(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Adds an array type of the value to the receiver’s value field."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/addValue(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addValueWithArray:"}],"url":"\/documentation\/sendbirdchatsdk\/messagemetaarray\/addvalue(with:)"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageMetaArray"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageMetaArray"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDMessageMetaArray"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/key","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/value"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/addValue(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/addValue(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/init(key:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/init(key:value:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/removeValue(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/removeValue(with:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/NSCopying-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray\/Serializable-Implementations"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDMessageMetaArray"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1addValue(_:)\/title","value":"addValue:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1addValue(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addValue:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Serializable\/title","value":"Serializable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Serializable\/fragments","value":[{"kind":"identifier","text":"Serializable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1value\/title","value":"value"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1value\/fragments","value":[{"kind":"identifier","text":"value"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1init(key:)\/title","value":"initWithKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1init(key:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1removeValue(_:)\/title","value":"removeValue:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1removeValue(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeValue:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1removeValue(with:)\/title","value":"removeValueWithArray:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1removeValue(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeValueWithArray:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray\/title","value":"SBDMessageMetaArray"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray\/fragments","value":[{"kind":"identifier","text":"SBDMessageMetaArray"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1key\/title","value":"key"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1key\/fragments","value":[{"kind":"identifier","text":"key"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1init(key:value:)\/title","value":"initWithKey:value:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1init(key:value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKey:value:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1addValue(with:)\/title","value":"addValueWithArray:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray~1addValue(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addValueWithArray:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}