{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDMessageCollection) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollection"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.1.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagecollection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagecollection"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseCollection"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object that accesses the cache for the messages."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollection"}],"title":"MessageCollection","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MessageCollection"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/delegate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/failedMessages","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/hasNext","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/hasPrevious","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/pendingMessages","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/startingPoint","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/succeededMessages"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/dispose()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/loadNext(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/loadPrevious(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/removeAllFailed(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/removeFailed(messages:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/startCollection(initPolicy:cacheResultHandler:apiResultHandler:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/BaseChannelDelegate-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/ConnectionDelegate-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/GroupChannelDelegate-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageCollectionDelegate","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(pl)SBDMessageCollectionDelegate"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/delegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/BaseChannelDelegate-Implementations":{"role":"collectionGroup","title":"BaseChannelDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/BaseChannelDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagecollection\/basechanneldelegate-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/GroupChannelDelegate-Implementations":{"role":"collectionGroup","title":"GroupChannelDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/GroupChannelDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagecollection\/groupchanneldelegate-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/startingPoint":{"role":"symbol","title":"startingPoint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startingPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Message collection delegate."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/startingPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startingPoint"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/startingpoint"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/loadPrevious(completionHandler:)":{"role":"symbol","title":"loadPrevious(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadPrevious"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListHandler","preciseIdentifier":"s:15SendbirdChatSDK18MessageListHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Loads messages of the previous page."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/loadPrevious(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadPreviousWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/loadprevious(completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/hasNext":{"role":"symbol","title":"hasNext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasNext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"If "},{"type":"codeVoice","code":"true"},{"type":"text","text":", there may be the messages on the next page."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/hasNext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasNext"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/hasnext"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/failedMessages":{"role":"symbol","title":"failedMessages","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedMessages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Returns the failed messages that are already loaded in memory."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/failedMessages","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"failedMessages"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/failedmessages"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/startCollection(initPolicy:cacheResultHandler:apiResultHandler:)":{"role":"symbol","title":"startCollection(initPolicy:cacheResultHandler:apiResultHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCollection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"initPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageCollectionInitPolicy","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageCollectionInitPolicy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cacheResultHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListHandler","preciseIdentifier":"s:15SendbirdChatSDK18MessageListHandlera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"apiResultHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListHandler","preciseIdentifier":"s:15SendbirdChatSDK18MessageListHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Starts the message collection with the policy. The result of the"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/startCollection(initPolicy:cacheResultHandler:apiResultHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCollectionWithInitPolicy:cacheResultHandler:apiResultHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/startcollection(initpolicy:cacheresulthandler:apiresulthandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseCollection":{"role":"symbol","title":"BaseCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseCollection"}],"abstract":[{"type":"text","text":"An base object for collection"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseCollection"}],"url":"\/documentation\/sendbirdchatsdk\/basecollection"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/ConnectionDelegate-Implementations":{"role":"collectionGroup","title":"ConnectionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/ConnectionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagecollection\/connectiondelegate-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate":{"role":"symbol","title":"BaseChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events"},{"type":"text","text":" "},{"type":"text","text":"in the channel. Delegate methods in "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" are common for the "},{"type":"codeVoice","code":"BaseChannel"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Exclusive delegate methods for "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" can be found in"},{"type":"text","text":" "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":". You must use "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":" instead of using "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" by using "},{"type":"codeVoice","code":"add(_:identifier:)"},{"type":"text","text":" in "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/succeededMessages":{"role":"symbol","title":"succeededMessages","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"succeededMessages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Returns the succeeded messages that are already loaded in memory."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/succeededMessages","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"succeededMessages"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/succeededmessages"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/dispose()":{"role":"symbol","title":"dispose()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dispose"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Invalidates the object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/dispose()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dispose"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/dispose()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/removeFailed(messages:completionHandler:)":{"role":"symbol","title":"removeFailed(messages:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageRequestIDsHandler","preciseIdentifier":"s:15SendbirdChatSDK24MessageRequestIDsHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Removes failed messages from DB."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/removeFailed(messages:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeFailedWithMessages:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/removefailed(messages:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/loadNext(completionHandler:)":{"role":"symbol","title":"loadNext(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadNext"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListHandler","preciseIdentifier":"s:15SendbirdChatSDK18MessageListHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Loads messages of the next page."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/loadNext(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadNextWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/loadnext(completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelDelegate":{"role":"symbol","title":"GroupChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/groupchanneldelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/hasPrevious":{"role":"symbol","title":"hasPrevious","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasPrevious"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"If "},{"type":"codeVoice","code":"true"},{"type":"text","text":", there may be the messages on the previous page."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/hasPrevious","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasPrevious"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/hasprevious"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/pendingMessages":{"role":"symbol","title":"pendingMessages","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pendingMessages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Returns the pending messages that are already loaded in memory."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/pendingMessages","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pendingMessages"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/pendingmessages"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection":{"role":"symbol","title":"MessageCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCollection"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ConnectionDelegate":{"role":"symbol","title":"ConnectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionDelegate"}],"abstract":[{"type":"text","text":"Represents a delegate to receive connection relates events"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ConnectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/connectiondelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageCollection/removeAllFailed(completionHandler:)":{"role":"symbol","title":"removeAllFailed(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Removes all failed messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/removeAllFailed(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeAllFailedWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/messagecollection\/removeallfailed(completionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageCollection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollection"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDMessageCollection"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/delegate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/failedMessages","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/hasNext","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/hasPrevious","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/pendingMessages","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/startingPoint","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/succeededMessages"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/dispose()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/loadNext(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/loadPrevious(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/removeAllFailed(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/removeFailed(messages:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/startCollection(initPolicy:cacheResultHandler:apiResultHandler:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/BaseChannelDelegate-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/ConnectionDelegate-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageCollection\/GroupChannelDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDMessageCollection"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseCollection","text":"SBDBaseCollection"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1startingPoint\/title","value":"startingPoint"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1startingPoint\/fragments","value":[{"kind":"identifier","text":"startingPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1loadPrevious(completionHandler:)\/title","value":"loadPreviousWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1loadPrevious(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadPreviousWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1hasNext\/title","value":"hasNext"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1hasNext\/fragments","value":[{"kind":"identifier","text":"hasNext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1failedMessages\/title","value":"failedMessages"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1failedMessages\/fragments","value":[{"kind":"identifier","text":"failedMessages"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1startCollection(initPolicy:cacheResultHandler:apiResultHandler:)\/title","value":"startCollectionWithInitPolicy:cacheResultHandler:apiResultHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1startCollection(initPolicy:cacheResultHandler:apiResultHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCollectionWithInitPolicy:cacheResultHandler:apiResultHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseCollection\/title","value":"SBDBaseCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseCollection\/fragments","value":[{"kind":"identifier","text":"SBDBaseCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate\/title","value":"SBDBaseChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannelDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1succeededMessages\/title","value":"succeededMessages"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1succeededMessages\/fragments","value":[{"kind":"identifier","text":"succeededMessages"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1dispose()\/title","value":"dispose"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1dispose()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dispose"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1removeFailed(messages:completionHandler:)\/title","value":"removeFailedWithMessages:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1removeFailed(messages:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeFailedWithMessages:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1loadNext(completionHandler:)\/title","value":"loadNextWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1loadNext(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadNextWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate\/title","value":"SBDGroupChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1hasPrevious\/title","value":"hasPrevious"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1hasPrevious\/fragments","value":[{"kind":"identifier","text":"hasPrevious"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1pendingMessages\/title","value":"pendingMessages"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1pendingMessages\/fragments","value":[{"kind":"identifier","text":"pendingMessages"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/title","value":"SBDMessageCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection\/fragments","value":[{"kind":"identifier","text":"SBDMessageCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate\/title","value":"SBDConnectionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ConnectionDelegate\/fragments","value":[{"kind":"identifier","text":"SBDConnectionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1removeAllFailed(completionHandler:)\/title","value":"removeAllFailedWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageCollection~1removeAllFailed(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAllFailedWithCompletionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}