{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDMessageChangeLogsParams) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageChangeLogsParams"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.181"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagechangelogsparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagechangelogsparams"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object contains set of options for message change logs."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageChangeLogsParams"}],"title":"MessageChangeLogsParams","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MessageChangeLogsParams"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/init(includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/includeMetaArray","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/includeParentMessageInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/includePollDetails","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/includeReactions","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/includeThreadInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/replyType"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/copy(with:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/create(with:)-3gsev","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/create(with:)-6gu6z"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams/init(includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:)":{"role":"symbol","title":"init(includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"includeMetaArray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeReactions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeThreadInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includePollDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeParentMessageInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReplyType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReplyType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Default parameter constructor"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/init(includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithIncludeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/init(includemetaarray:includereactions:includethreadinfo:includepolldetails:includeparentmessageinfo:replytype:)"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams":{"role":"symbol","title":"MessageChangeLogsParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageChangeLogsParams"}],"abstract":[{"type":"text","text":"An object contains set of options for message change logs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageChangeLogsParams"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams/create(with:)-6gu6z":{"role":"symbol","title":"create(with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"MessageChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams"}],"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"MessageChangeLogParams"},{"type":"text","text":" from a given "},{"type":"codeVoice","code":"MessageListParams"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/create(with:)-6gu6z","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithMessageListParams:"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/create(with:)-6gu6z"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams/includeMetaArray":{"role":"symbol","title":"includeMetaArray","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeMetaArray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include the metaarray information of the updated messages in the results. Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/includeMetaArray","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeMetaArray"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/includemetaarray"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Copies this object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/copy(with:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/init()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams/create(with:)-3gsev":{"role":"symbol","title":"create(with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PreviousMessageListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPreviousMessageListQuery"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"MessageChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams"}],"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"PreviousMessageListQuery"},{"type":"text","text":" from a given "},{"type":"codeVoice","code":"PreviousMessageListQuery"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/create(with:)-3gsev","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithPreviousMessageListQuery:"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/create(with:)-3gsev"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams/replyType":{"role":"symbol","title":"replyType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"replyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReplyType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReplyType"}],"abstract":[{"type":"text","text":"Determines which reply types to include in the results. Default is "},{"type":"codeVoice","code":".none"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/replyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"replyType"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/replytype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams/includePollDetails":{"role":"symbol","title":"includePollDetails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includePollDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include poll information of the message in the results. Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/includePollDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includePollDetails"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/includepolldetails"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams/includeReactions":{"role":"symbol","title":"includeReactions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeReactions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include the reactions of the updated messages in the results. Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/includeReactions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeReactions"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/includereactions"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams/includeParentMessageInfo":{"role":"symbol","title":"includeParentMessageInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeParentMessageInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines wheter to include information on parent message. Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/includeParentMessageInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeParentMessageInfo"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/includeparentmessageinfo"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams/includeThreadInfo":{"role":"symbol","title":"includeThreadInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeThreadInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include the thread information of the updated messages in the results when the results contain parent messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/includeThreadInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeThreadInfo"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams\/includethreadinfo"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageChangeLogsParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageChangeLogsParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDMessageChangeLogsParams"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/includeMetaArray","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/includeParentMessageInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/includePollDetails","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/includeReactions","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/includeThreadInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/replyType"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/init(includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/create(with:)-3gsev","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams\/create(with:)-6gu6z"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDMessageChangeLogsParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1init(includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:)\/title","value":"initWithIncludeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1init(includeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithIncludeMetaArray:includeReactions:includeThreadInfo:includePollDetails:includeParentMessageInfo:replyType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams\/title","value":"SBDMessageChangeLogsParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams\/fragments","value":[{"kind":"identifier","text":"SBDMessageChangeLogsParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1create(with:)-6gu6z\/title","value":"createWithMessageListParams:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1create(with:)-6gu6z\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithMessageListParams:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1includeMetaArray\/title","value":"includeMetaArray"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1includeMetaArray\/fragments","value":[{"kind":"identifier","text":"includeMetaArray"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1create(with:)-3gsev\/title","value":"createWithPreviousMessageListQuery:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1create(with:)-3gsev\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithPreviousMessageListQuery:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1replyType\/title","value":"replyType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1replyType\/fragments","value":[{"kind":"identifier","text":"replyType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1includePollDetails\/title","value":"includePollDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1includePollDetails\/fragments","value":[{"kind":"identifier","text":"includePollDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1includeReactions\/title","value":"includeReactions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1includeReactions\/fragments","value":[{"kind":"identifier","text":"includeReactions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1includeParentMessageInfo\/title","value":"includeParentMessageInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1includeParentMessageInfo\/fragments","value":[{"kind":"identifier","text":"includeParentMessageInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1includeThreadInfo\/title","value":"includeThreadInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams~1includeThreadInfo\/fragments","value":[{"kind":"identifier","text":"includeThreadInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}