{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDMessageRetrievalParams) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageRetrievalParams"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.181"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messageretrievalparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messageretrievalparams"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object contains set of options to retrieve a message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageRetrievalParams"}],"title":"MessageRetrievalParams","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageRetrievalParams","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MessageRetrievalParams"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/init(channelURL:channelType:messageID:includeMetaArray:includeReactions:includeThreadInfo:includeParentMessageInfo:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/channelType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/channelURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/includeMetaArray","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/includeParentMessageInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/includePollDetails","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/includeReactions","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/includeThreadInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/messageID"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/copy(with:)"]}],"references":{"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageRetrievalParams/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirdchatsdk\/messageretrievalparams\/init()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageRetrievalParams/includeMetaArray":{"role":"symbol","title":"includeMetaArray","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeMetaArray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether the metaarray of the message is included in the results."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/includeMetaArray","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeMetaArray"}],"url":"\/documentation\/sendbirdchatsdk\/messageretrievalparams\/includemetaarray"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageRetrievalParams/includePollDetails":{"role":"symbol","title":"includePollDetails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includePollDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include poll information of the message in the results. Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/includePollDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includePollDetails"}],"url":"\/documentation\/sendbirdchatsdk\/messageretrievalparams\/includepolldetails"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageRetrievalParams/init(channelURL:channelType:messageID:includeMetaArray:includeReactions:includeThreadInfo:includeParentMessageInfo:)":{"role":"symbol","title":"init(channelURL:channelType:messageID:includeMetaArray:includeReactions:includeThreadInfo:includeParentMessageInfo:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeMetaArray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeReactions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeThreadInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeParentMessageInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Parameter constructor"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/init(channelURL:channelType:messageID:includeMetaArray:includeReactions:includeThreadInfo:includeParentMessageInfo:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithChannelURL:channelType:messageID:includeMetaArray:includeReactions:includeThreadInfo:includeParentMessageInfo:"}],"url":"\/documentation\/sendbirdchatsdk\/messageretrievalparams\/init(channelurl:channeltype:messageid:includemetaarray:includereactions:includethreadinfo:includeparentmessageinfo:)"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageRetrievalParams/channelType":{"role":"symbol","title":"channelType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"}],"abstract":[{"type":"text","text":"Specifies the type of the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/channelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelType"}],"url":"\/documentation\/sendbirdchatsdk\/messageretrievalparams\/channeltype"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageRetrievalParams/includeParentMessageInfo":{"role":"symbol","title":"includeParentMessageInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeParentMessageInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines wheter to include information on parent message. Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/includeParentMessageInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeParentMessageInfo"}],"url":"\/documentation\/sendbirdchatsdk\/messageretrievalparams\/includeparentmessageinfo"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageRetrievalParams/includeThreadInfo":{"role":"symbol","title":"includeThreadInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeThreadInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include the thread information of the message when it is a parent message. Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/includeThreadInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeThreadInfo"}],"url":"\/documentation\/sendbirdchatsdk\/messageretrievalparams\/includethreadinfo"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageRetrievalParams":{"role":"symbol","title":"MessageRetrievalParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageRetrievalParams"}],"abstract":[{"type":"text","text":"An object contains set of options to retrieve a message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageRetrievalParams"}],"url":"\/documentation\/sendbirdchatsdk\/messageretrievalparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageRetrievalParams/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Copies this object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/sendbirdchatsdk\/messageretrievalparams\/copy(with:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageRetrievalParams/messageID":{"role":"symbol","title":"messageID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Specifies the unique ID of the message to retrieve."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/messageID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageID"}],"url":"\/documentation\/sendbirdchatsdk\/messageretrievalparams\/messageid"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageRetrievalParams/channelURL":{"role":"symbol","title":"channelURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Specifies the URL of the channel to retrieve the message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/channelURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelURL"}],"url":"\/documentation\/sendbirdchatsdk\/messageretrievalparams\/channelurl"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageRetrievalParams/includeReactions":{"role":"symbol","title":"includeReactions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeReactions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines wheter to include reactions in the results. Default is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/includeReactions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeReactions"}],"url":"\/documentation\/sendbirdchatsdk\/messageretrievalparams\/includereactions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageRetrievalParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageRetrievalParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDMessageRetrievalParams"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/channelType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/channelURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/includeMetaArray","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/includeParentMessageInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/includePollDetails","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/includeReactions","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/includeThreadInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/messageID"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageRetrievalParams\/init(channelURL:channelType:messageID:includeMetaArray:includeReactions:includeThreadInfo:includeParentMessageInfo:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDMessageRetrievalParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1includeMetaArray\/title","value":"includeMetaArray"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1includeMetaArray\/fragments","value":[{"kind":"identifier","text":"includeMetaArray"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1includePollDetails\/title","value":"includePollDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1includePollDetails\/fragments","value":[{"kind":"identifier","text":"includePollDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1init(channelURL:channelType:messageID:includeMetaArray:includeReactions:includeThreadInfo:includeParentMessageInfo:)\/title","value":"initWithChannelURL:channelType:messageID:includeMetaArray:includeReactions:includeThreadInfo:includeParentMessageInfo:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1init(channelURL:channelType:messageID:includeMetaArray:includeReactions:includeThreadInfo:includeParentMessageInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithChannelURL:channelType:messageID:includeMetaArray:includeReactions:includeThreadInfo:includeParentMessageInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1channelType\/title","value":"channelType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1channelType\/fragments","value":[{"kind":"identifier","text":"channelType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1includeParentMessageInfo\/title","value":"includeParentMessageInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1includeParentMessageInfo\/fragments","value":[{"kind":"identifier","text":"includeParentMessageInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1includeThreadInfo\/title","value":"includeThreadInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1includeThreadInfo\/fragments","value":[{"kind":"identifier","text":"includeThreadInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams\/title","value":"SBDMessageRetrievalParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams\/fragments","value":[{"kind":"identifier","text":"SBDMessageRetrievalParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1messageID\/title","value":"messageID"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1messageID\/fragments","value":[{"kind":"identifier","text":"messageID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1channelURL\/title","value":"channelURL"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1channelURL\/fragments","value":[{"kind":"identifier","text":"channelURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1includeReactions\/title","value":"includeReactions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageRetrievalParams~1includeReactions\/fragments","value":[{"kind":"identifier","text":"includeReactions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}