{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDMessageTypeFilter) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageTypeFilter"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagetypefilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagetypefilter"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Message type for filtering"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageTypeFilter"}],"title":"MessageTypeFilter","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDMessageTypeFilter","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MessageTypeFilter"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/admin","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/all","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/file","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/user"]},{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageTypeFilter/admin":{"role":"symbol","title":"MessageTypeFilter.admin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admin"}],"abstract":[{"type":"text","text":"Filter of admin message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/admin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageTypeFilterAdmin"}],"url":"\/documentation\/sendbirdchatsdk\/messagetypefilter\/admin"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageTypeFilter/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagetypefilter\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageTypeFilter":{"role":"symbol","title":"MessageTypeFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageTypeFilter"}],"abstract":[{"type":"text","text":"Message type for filtering"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageTypeFilter"}],"url":"\/documentation\/sendbirdchatsdk\/messagetypefilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageTypeFilter/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagetypefilter\/init(rawvalue:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageTypeFilter/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagetypefilter\/rawrepresentable-implementations"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageTypeFilter/all":{"role":"symbol","title":"MessageTypeFilter.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[{"type":"text","text":"Filter of all messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageTypeFilterAll"}],"url":"\/documentation\/sendbirdchatsdk\/messagetypefilter\/all"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageTypeFilter/user":{"role":"symbol","title":"MessageTypeFilter.user","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"user"}],"abstract":[{"type":"text","text":"Filter of user message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/user","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageTypeFilterUser"}],"url":"\/documentation\/sendbirdchatsdk\/messagetypefilter\/user"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageTypeFilter/file":{"role":"symbol","title":"MessageTypeFilter.file","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"file"}],"abstract":[{"type":"text","text":"Filter of file message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/file","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageTypeFilterFile"}],"url":"\/documentation\/sendbirdchatsdk\/messagetypefilter\/file"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageTypeFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageTypeFilter"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDMessageTypeFilter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/admin","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/all","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/file","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageTypeFilter\/user"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDMessageTypeFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter~1admin\/title","value":"SBDMessageTypeFilterAdmin"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter~1admin\/fragments","value":[{"kind":"identifier","text":"SBDMessageTypeFilterAdmin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter\/title","value":"SBDMessageTypeFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter\/fragments","value":[{"kind":"identifier","text":"SBDMessageTypeFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter~1all\/title","value":"SBDMessageTypeFilterAll"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter~1all\/fragments","value":[{"kind":"identifier","text":"SBDMessageTypeFilterAll"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter~1user\/title","value":"SBDMessageTypeFilterUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter~1user\/fragments","value":[{"kind":"identifier","text":"SBDMessageTypeFilterUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter~1file\/title","value":"SBDMessageTypeFilterFile"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageTypeFilter~1file\/fragments","value":[{"kind":"identifier","text":"SBDMessageTypeFilterFile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}