{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDMessageSendingStatus) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSendingStatus"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.173"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagesendingstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagesendingstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Constants of type to describe message’s sending status."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSendingStatus"}],"title":"MessageSendingStatus","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDMessageSendingStatus","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MessageSendingStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/canceled","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/failed","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/none","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/pending","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/scheduled","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/succeeded"]},{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/init(stringValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus\/encodable-implementations"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus/init(stringValue:)":{"role":"symbol","title":"init(stringValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"stringValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/init(stringValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus\/init(stringvalue:)"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus/pending":{"role":"symbol","title":"MessageSendingStatus.pending","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"abstract":[{"type":"text","text":"Indicates the status of the message returned when trying to send a message."},{"type":"text","text":" "},{"type":"text","text":"The message with the pending status means that is not dispatched completely to the Sendbird"},{"type":"text","text":" "},{"type":"text","text":"server. The pending message should be replaced with a message (failed or succeeded)"},{"type":"text","text":" "},{"type":"text","text":"from the callback."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/pending","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageSendingStatusPending"}],"url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus\/pending"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus/failed":{"role":"symbol","title":"MessageSendingStatus.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"Indicates the status of the message that failed to send the message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageSendingStatusFailed"}],"url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus\/failed"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus/succeeded":{"role":"symbol","title":"MessageSendingStatus.succeeded","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"succeeded"}],"abstract":[{"type":"text","text":"Indicates the status of the message that success to send the message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/succeeded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageSendingStatusSucceeded"}],"url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus\/succeeded"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus\/decodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus":{"role":"symbol","title":"MessageSendingStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSendingStatus"}],"abstract":[{"type":"text","text":"Constants of type to describe message’s sending status."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageSendingStatus"}],"url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus/canceled":{"role":"symbol","title":"MessageSendingStatus.canceled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canceled"}],"abstract":[{"type":"text","text":"Indicates the status of the message that is canceled."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/canceled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageSendingStatusCanceled"}],"url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus\/canceled"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus/none":{"role":"symbol","title":"MessageSendingStatus.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"MUST NOT BE. If you got a message instance from SDK, the message can’t have this value."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageSendingStatusNone"}],"url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus\/none"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSendingStatus/scheduled":{"role":"symbol","title":"MessageSendingStatus.scheduled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduled"}],"abstract":[{"type":"text","text":"Indicates the status of the message that is scheduled."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/scheduled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDMessageSendingStatusScheduled"}],"url":"\/documentation\/sendbirdchatsdk\/messagesendingstatus\/scheduled"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDMessageSendingStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDMessageSendingStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/canceled","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/failed","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/none","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/pending","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/scheduled","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSendingStatus\/succeeded"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDMessageSendingStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1pending\/title","value":"SBDMessageSendingStatusPending"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1pending\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatusPending"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1failed\/title","value":"SBDMessageSendingStatusFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1failed\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatusFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1succeeded\/title","value":"SBDMessageSendingStatusSucceeded"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1succeeded\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatusSucceeded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus\/title","value":"SBDMessageSendingStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1canceled\/title","value":"SBDMessageSendingStatusCanceled"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1canceled\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatusCanceled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1none\/title","value":"SBDMessageSendingStatusNone"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1none\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatusNone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1scheduled\/title","value":"SBDMessageSendingStatusScheduled"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSendingStatus~1scheduled\/fragments","value":[{"kind":"identifier","text":"SBDMessageSendingStatusScheduled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}