{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDNetworkDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/networkdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/networkdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/NetworkDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents a delegate to receive network event"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkDelegate"}],"title":"NetworkDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDNetworkDelegate","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"NetworkDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/NetworkDelegate\/didReconnect()"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/NetworkDelegate/didReconnect()":{"navigatorTitle":[{"kind":"identifier","text":"didReconnect"}],"role":"symbol","title":"didReconnect()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReconnect"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Call when reconnection succeeds"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/NetworkDelegate\/didReconnect()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/networkdelegate\/didreconnect()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/NetworkDelegate":{"role":"symbol","title":"NetworkDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkDelegate"}],"abstract":[{"type":"text","text":"Represents a delegate to receive network event"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/NetworkDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/networkdelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBDNetworkDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDNetworkDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDNetworkDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/NetworkDelegate\/didReconnect()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDNetworkDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1NetworkDelegate~1didReconnect()\/title","value":"didReconnect"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1NetworkDelegate~1didReconnect()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReconnect"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1NetworkDelegate\/title","value":"SBDNetworkDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1NetworkDelegate\/fragments","value":[{"kind":"identifier","text":"SBDNetworkDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}