{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDOGMetaData) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OGMetaData"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.193"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/ogmetadata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/ogmetadata"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents OpenGraph information"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OGMetaData"}],"title":"OGMetaData","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDOGMetaData","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"OGMetaData"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/defaultImage","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/desc","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/title","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/url"]}],"references":{"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OGMetaData/defaultImage":{"role":"symbol","title":"defaultImage","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OGImage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOGImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"An image object which should represent the object within the graph"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/defaultImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultImage"}],"url":"\/documentation\/sendbirdchatsdk\/ogmetadata\/defaultimage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OGMetaData":{"role":"symbol","title":"OGMetaData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OGMetaData"}],"abstract":[{"type":"text","text":"Represents OpenGraph information"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OGMetaData"}],"url":"\/documentation\/sendbirdchatsdk\/ogmetadata"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OGMetaData/url":{"role":"symbol","title":"url","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The canonical URL of object that will be used as its permanent ID in the graph"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/url","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"url"}],"url":"\/documentation\/sendbirdchatsdk\/ogmetadata\/url"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OGMetaData/desc":{"role":"symbol","title":"desc","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"desc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A one to two sentence description of object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/desc","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"desc"}],"url":"\/documentation\/sendbirdchatsdk\/ogmetadata\/desc"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OGMetaData/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/ogmetadata\/init(from:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OGMetaData/title":{"role":"symbol","title":"title","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The title of object as it should appear within the graph"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/title","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"title"}],"url":"\/documentation\/sendbirdchatsdk\/ogmetadata\/title"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDOGMetaData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDOGMetaData"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDOGMetaData"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/defaultImage","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/desc","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/title","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/url"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDOGMetaData"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGMetaData~1defaultImage\/title","value":"defaultImage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGMetaData~1defaultImage\/fragments","value":[{"kind":"identifier","text":"defaultImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGMetaData\/title","value":"SBDOGMetaData"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGMetaData\/fragments","value":[{"kind":"identifier","text":"SBDOGMetaData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGMetaData~1url\/title","value":"url"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGMetaData~1url\/fragments","value":[{"kind":"identifier","text":"url"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGMetaData~1desc\/title","value":"desc"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGMetaData~1desc\/fragments","value":[{"kind":"identifier","text":"desc"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGMetaData~1title\/title","value":"title"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGMetaData~1title\/fragments","value":[{"kind":"identifier","text":"title"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}