{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDOpenChannelDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(pl)SBDBaseChannelDelegate","text":"BaseChannelDelegate"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol deals with the below events."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when a participant entered the "},{"type":"reference","isActive":true,"identifier":"..\/Classes\/OpenChannel.html"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when a participant exited the "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"OpenChannel"}],"isActive":true,"type":"reference","identifier":"..\/Classes\/OpenChannel.html","overridingTitle":"OpenChannel"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Receives an event when the "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"OpenChannel"}],"isActive":true,"type":"reference","identifier":"..\/Classes\/OpenChannel.html","overridingTitle":"OpenChannel"},{"type":"text","text":" was frozen or unfrozen."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/openchanneldelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/openchanneldelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events in the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelDelegate"}],"title":"OpenChannelDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDOpenChannelDelegate","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"OpenChannelDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate\/channel(_:userDidEnter:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate\/channel(_:userDidExit:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate\/channelDidChangeParticipantCount(_:)"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelDelegate/channel(_:userDidEnter:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:userDidEnter:"}],"role":"symbol","title":"channel(_:userDidEnter:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidEnter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a user enter an open channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate\/channel(_:userDidEnter:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/openchanneldelegate\/channel(_:userdidenter:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelDelegate/channel(_:userDidExit:)":{"navigatorTitle":[{"kind":"identifier","text":"channel:userDidExit:"}],"role":"symbol","title":"channel(_:userDidExit:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidExit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A callback when a user exit an open channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate\/channel(_:userDidExit:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/openchanneldelegate\/channel(_:userdidexit:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelDelegate/channelDidChangeParticipantCount(_:)":{"navigatorTitle":[{"kind":"identifier","text":"channelDidChangeParticipantCount:"}],"role":"symbol","title":"channelDidChangeParticipantCount(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelDidChangeParticipantCount"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"A callback when participant count has been changed for open channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate\/channelDidChangeParticipantCount(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/openchanneldelegate\/channeldidchangeparticipantcount(_:)"},"../Classes/OpenChannel.html":{"title":"OpenChannel","titleInlineContent":[{"type":"codeVoice","code":"OpenChannel"}],"type":"link","identifier":"..\/Classes\/OpenChannel.html","url":"..\/Classes\/OpenChannel.html"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannelDelegate":{"role":"symbol","title":"BaseChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events"},{"type":"text","text":" "},{"type":"text","text":"in the channel. Delegate methods in "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" are common for the "},{"type":"codeVoice","code":"BaseChannel"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Exclusive delegate methods for "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" can be found in"},{"type":"text","text":" "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":". You must use "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"GroupChannelDelegate"},{"type":"text","text":" instead of using "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" by using "},{"type":"codeVoice","code":"add(_:identifier:)"},{"type":"text","text":" in "},{"type":"codeVoice","code":"SendbirdChat"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/basechanneldelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelDelegate":{"role":"symbol","title":"OpenChannelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelDelegate"}],"abstract":[{"type":"text","text":"An object that adopts the "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" protocol is responsible for receiving the events in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannelDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/openchanneldelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBDOpenChannelDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannelDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDOpenChannelDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate\/channel(_:userDidEnter:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate\/channel(_:userDidExit:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelDelegate\/channelDidChangeParticipantCount(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDOpenChannelDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"SBDBaseChannelDelegate"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelDelegate~1channel(_:userDidEnter:)\/title","value":"channel:userDidEnter:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelDelegate~1channel(_:userDidEnter:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userDidEnter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelDelegate~1channel(_:userDidExit:)\/title","value":"channel:userDidExit:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelDelegate~1channel(_:userDidExit:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userDidExit:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelDelegate~1channelDidChangeParticipantCount(_:)\/title","value":"channelDidChangeParticipantCount:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelDelegate~1channelDidChangeParticipantCount(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidChangeParticipantCount:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate\/title","value":"SBDBaseChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannelDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelDelegate\/title","value":"SBDOpenChannelDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannelDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}