{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDOpenChannelListQuery) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelListQuery"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The instance of this class is created by "},{"type":"codeVoice","code":"createOpenChannelListQuery()"},{"type":"text","text":" in "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" class."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/openchannellistquery"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/openchannellistquery"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OpenChannelListQuery"},{"type":"text","text":" class is a query class for getting the list of open channels."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelListQuery"}],"title":"OpenChannelListQuery","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelListQuery","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"OpenChannelListQuery"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery\/hasNext","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery\/isLoading","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery\/params"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery\/loadNextPage(completionHandler:)"]}],"references":{"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelListQuery":{"role":"symbol","title":"OpenChannelListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OpenChannelListQuery"},{"type":"text","text":" class is a query class for getting the list of open channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannelListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/openchannellistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelListQuery/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Copies this object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannellistquery\/copy(with:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelListQuery/isLoading":{"role":"symbol","title":"isLoading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Indicates the query is currently loading or not"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery\/isLoading","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isLoading"}],"url":"\/documentation\/sendbirdchatsdk\/openchannellistquery\/isloading"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelListQuery/loadNextPage(completionHandler:)":{"role":"symbol","title":"loadNextPage(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadNextPage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelListHandler","preciseIdentifier":"s:15SendbirdChatSDK22OpenChannelListHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Fetches next page"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery\/loadNextPage(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadNextPageWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannellistquery\/loadnextpage(completionhandler:)"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelListQuery/hasNext":{"role":"symbol","title":"hasNext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasNext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Boolean indicates there are more data to fetch"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery\/hasNext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasNext"}],"url":"\/documentation\/sendbirdchatsdk\/openchannellistquery\/hasnext"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelListQuery/params":{"role":"symbol","title":"params","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelListQueryParams"}],"abstract":[{"type":"text","text":"A params object to set query condition."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery\/params","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"params"}],"url":"\/documentation\/sendbirdchatsdk\/openchannellistquery\/params"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDOpenChannelListQuery"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannelListQuery"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDOpenChannelListQuery"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery\/hasNext","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery\/isLoading","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery\/params"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelListQuery\/loadNextPage(completionHandler:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDOpenChannelListQuery"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelListQuery\/title","value":"SBDOpenChannelListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelListQuery\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannelListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelListQuery~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelListQuery~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelListQuery~1isLoading\/title","value":"isLoading"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelListQuery~1isLoading\/fragments","value":[{"kind":"identifier","text":"isLoading"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelListQuery~1loadNextPage(completionHandler:)\/title","value":"loadNextPageWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelListQuery~1loadNextPage(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadNextPageWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelListQuery~1hasNext\/title","value":"hasNext"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelListQuery~1hasNext\/fragments","value":[{"kind":"identifier","text":"hasNext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelListQuery~1params\/title","value":"params"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelListQuery~1params\/fragments","value":[{"kind":"identifier","text":"params"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}