{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDOpenChannelUpdateParams) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelUpdateParams"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/openchannelupdateparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/openchannelupdateparams"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object contains set of options to update open channel"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelUpdateParams"}],"title":"OpenChannelUpdateParams","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelUpdateParams","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"OpenChannelUpdateParams"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/init(name:coverURL:coverImage:coverImageName:data:operatorUserIDs:customType:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/coverImage","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/coverImageName","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/coverURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/customType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/data","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/name","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/operatorUserIDs"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/setOperators(_:)"]}],"references":{"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelUpdateParams/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default constructor"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelupdateparams\/init()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelUpdateParams/data":{"role":"symbol","title":"data","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Channel data"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/data","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"data"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelupdateparams\/data"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelUpdateParams/coverImage":{"role":"symbol","title":"coverImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Channel cover image data"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/coverImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"coverImage"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelupdateparams\/coverimage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelUpdateParams/customType":{"role":"symbol","title":"customType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Channel custom type"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/customType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customType"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelupdateparams\/customtype"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelUpdateParams/init(name:coverURL:coverImage:coverImageName:data:operatorUserIDs:customType:)":{"role":"symbol","title":"init(name:coverURL:coverImage:coverImageName:data:operatorUserIDs:customType:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"coverURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"coverImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"coverImageName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"operatorUserIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Parameter constructor"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/init(name:coverURL:coverImage:coverImageName:data:operatorUserIDs:customType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithName:coverURL:coverImage:coverImageName:data:operatorUserIDs:customType:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelupdateparams\/init(name:coverurl:coverimage:coverimagename:data:operatoruserids:customtype:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelUpdateParams":{"role":"symbol","title":"OpenChannelUpdateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelUpdateParams"}],"abstract":[{"type":"text","text":"An object contains set of options to update open channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannelUpdateParams"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelupdateparams"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelUpdateParams/operatorUserIDs":{"role":"symbol","title":"operatorUserIDs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatorUserIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Channel’s operator user IDs"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/operatorUserIDs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"operatorUserIDs"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelupdateparams\/operatoruserids"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelUpdateParams/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Copies this object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelupdateparams\/copy(with:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelUpdateParams/setOperators(_:)":{"role":"symbol","title":"setOperators(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setOperators"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Set operators with list of user instance."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/setOperators(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setOperators:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelupdateparams\/setoperators(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelUpdateParams/coverImageName":{"role":"symbol","title":"coverImageName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverImageName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Channel cover image name"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/coverImageName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"coverImageName"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelupdateparams\/coverimagename"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelUpdateParams/coverURL":{"role":"symbol","title":"coverURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Channel cover image URL"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/coverURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"coverURL"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelupdateparams\/coverurl"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelUpdateParams/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Channel name"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelupdateparams\/name"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDOpenChannelUpdateParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannelUpdateParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDOpenChannelUpdateParams"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/coverImage","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/coverImageName","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/coverURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/customType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/data","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/name","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/operatorUserIDs"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/init(name:coverURL:coverImage:coverImageName:data:operatorUserIDs:customType:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelUpdateParams\/setOperators(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDOpenChannelUpdateParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1data\/title","value":"data"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1data\/fragments","value":[{"kind":"identifier","text":"data"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1coverImage\/title","value":"coverImage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1coverImage\/fragments","value":[{"kind":"identifier","text":"coverImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1customType\/title","value":"customType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1customType\/fragments","value":[{"kind":"identifier","text":"customType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1init(name:coverURL:coverImage:coverImageName:data:operatorUserIDs:customType:)\/title","value":"initWithName:coverURL:coverImage:coverImageName:data:operatorUserIDs:customType:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1init(name:coverURL:coverImage:coverImageName:data:operatorUserIDs:customType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:coverURL:coverImage:coverImageName:data:operatorUserIDs:customType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams\/title","value":"SBDOpenChannelUpdateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannelUpdateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1operatorUserIDs\/title","value":"operatorUserIDs"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1operatorUserIDs\/fragments","value":[{"kind":"identifier","text":"operatorUserIDs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1setOperators(_:)\/title","value":"setOperators:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1setOperators(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setOperators:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1coverImageName\/title","value":"coverImageName"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1coverImageName\/fragments","value":[{"kind":"identifier","text":"coverImageName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1coverURL\/title","value":"coverURL"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1coverURL\/fragments","value":[{"kind":"identifier","text":"coverURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannelUpdateParams~1name\/fragments","value":[{"kind":"identifier","text":"name"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}