{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDOpenChannel) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannel"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Any users who wants to enter the channel can join freely. This class is derived from "},{"type":"codeVoice","code":"BaseChannel"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If the "},{"type":"codeVoice","code":"OpenChannelDelegate"},{"type":"text","text":" is added, the user will automatically receive all messages from the"},{"type":"text","text":" "},{"type":"text","text":"channels where the user belongs after connection. The "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" does not provide the features that"},{"type":"text","text":" "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" does, but it can handle much more users."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For more information, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.sendbird.com\/ios#open_channel"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/openchannel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/openchannel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Serializable","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/s12IdentifiableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" class represents a open channel which is a public chat."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannel"}],"title":"OpenChannel","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"OpenChannel"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/operators","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/participantCount"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(params:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(paramsBuilder:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/delete(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/encode(to:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/enter(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/exit(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/isOperator(user:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/isOperator(userID:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/refresh(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/update(params:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/update(params:progressHandler:completionHandler:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/build(fromSerializedData:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createChannel(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createChannel(params:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createChannel(params:progressHandler:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createOpenChannelListQuery()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createOpenChannelListQuery(params:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createOpenChannelListQuery(paramsBuilder:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(channelURL:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(channelURL:params:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(channelURL:paramsBuilder:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/getChannel(url:completionHandler:)"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/isOperator(userID:)":{"role":"symbol","title":"isOperator(userID:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOperator"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns the user ID is an operator or not."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/isOperator(userID:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isOperatorWithUserID:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/isoperator(userid:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/getChannel(url:completionHandler:)":{"role":"symbol","title":"getChannel(url:completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK18OpenChannelHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Gets an open channel instance from channel URL."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/getChannel(url:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getChannelWithURL:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/getchannel(url:completionhandler:)"},"https://docs.sendbird.com/ios#open_channel":{"title":"Group Channel","titleInlineContent":[{"type":"text","text":"Group Channel"}],"type":"link","identifier":"https:\/\/docs.sendbird.com\/ios#open_channel","url":"https:\/\/docs.sendbird.com\/ios#open_channel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/createParticipantListQuery(channelURL:paramsBuilder:)":{"role":"symbol","title":"createParticipantListQuery(channelURL:paramsBuilder:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createParticipantListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paramsBuilder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ParticipantListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ParticipantListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQuery"}],"abstract":[{"type":"text","text":"Creates a query instance for getting participant list of the channel with the given channel URL."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(channelURL:paramsBuilder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createParticipantListQueryWithChannelURL:paramsBuilder:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/createparticipantlistquery(channelurl:paramsbuilder:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/createParticipantListQuery(paramsBuilder:)":{"role":"symbol","title":"createParticipantListQuery(paramsBuilder:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createParticipantListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramsBuilder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ParticipantListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ParticipantListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQuery"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Creates a participant list query for this channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(paramsBuilder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createParticipantListQueryWithParamsBuilder:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/createparticipantlistquery(paramsbuilder:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Compares this object with given other object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/isequal(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/enter(completionHandler:)":{"role":"symbol","title":"enter(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Enters this channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/enter(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enterChannelWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/enter(completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/exit(completionHandler:)":{"role":"symbol","title":"exit(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Exits this channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/exit(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"exitChannelWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/exit(completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel":{"role":"symbol","title":"OpenChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" class represents a open channel which is a public chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannel"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Mappable":{"role":"symbol","title":"Mappable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mappable"}],"abstract":[{"type":"text","text":"Mappable protocol to initialize sendbird object from a given dictionary."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Mappable"}],"url":"\/documentation\/sendbirdchatsdk\/mappable"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/createOpenChannelListQuery(params:)":{"role":"symbol","title":"createOpenChannelListQuery(params:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOpenChannelListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"OpenChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelListQuery"}],"abstract":[{"type":"text","text":"Creates a query instance for open channel list."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createOpenChannelListQuery(params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createOpenChannelListQueryWithParams:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/createopenchannellistquery(params:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/createOpenChannelListQuery()":{"role":"symbol","title":"createOpenChannelListQuery()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOpenChannelListQuery"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"OpenChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelListQuery"}],"abstract":[{"type":"text","text":"Creates a query instance for open channel list."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createOpenChannelListQuery()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createOpenChannelListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/createopenchannellistquery()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/createParticipantListQuery(channelURL:)":{"role":"symbol","title":"createParticipantListQuery(channelURL:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createParticipantListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ParticipantListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQuery"}],"abstract":[{"type":"text","text":"Creates a query instance for getting participant list of the channel with the given channel URL."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(channelURL:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createParticipantListQueryWithChannelURL:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/createparticipantlistquery(channelurl:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Serializable":{"role":"symbol","title":"Serializable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Serializable"}],"abstract":[{"type":"text","text":"Protocol to provide serialization"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Serializable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Serializable"}],"url":"\/documentation\/sendbirdchatsdk\/serializable"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/openchannel\/init(from:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/isOperator(user:)":{"role":"symbol","title":"isOperator(user:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOperator"},{"kind":"text","text":"("},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns the user is an operator or not."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/isOperator(user:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isOperatorWithUser:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/isoperator(user:)"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/s12IdentifiableP":{"type":"unresolvable","title":"Swift.Identifiable","identifier":"doc:\/\/com.sendbird.chat\/s12IdentifiableP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Encodes this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/openchannel\/encode(to:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/delete(completionHandler:)":{"role":"symbol","title":"delete(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"delete"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Deletes this channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/delete(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteChannelWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/delete(completionhandler:)"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/createParticipantListQuery(channelURL:params:)":{"role":"symbol","title":"createParticipantListQuery(channelURL:params:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createParticipantListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ParticipantListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ParticipantListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQuery"}],"abstract":[{"type":"text","text":"Creates a query instance for getting participant list of the channel with the given channel URL."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(channelURL:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createParticipantListQueryWithChannelURL:params:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/createparticipantlistquery(channelurl:params:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/createChannel(params:completionHandler:)":{"role":"symbol","title":"createChannel(params:completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelCreateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK18OpenChannelHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a open channel with "},{"type":"codeVoice","code":"OpenChannelCreateParams"},{"type":"text","text":" class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createChannel(params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createChannelWithParams:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/createchannel(params:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/createChannel(completionHandler:)":{"role":"symbol","title":"createChannel(completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK18OpenChannelHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates an open channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createChannel(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createChannelWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/createchannel(completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/operators":{"role":"symbol","title":"operators","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"operators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The operators of this channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/operators","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"operators"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/operators"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/createChannel(params:progressHandler:completionHandler:)":{"role":"symbol","title":"createChannel(params:progressHandler:completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelCreateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progressHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProgressHandler","preciseIdentifier":"s:15SendbirdChatSDK15ProgressHandlera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK18OpenChannelHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a open channel with "},{"type":"codeVoice","code":"OpenChannelCreateParams"},{"type":"text","text":" class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createChannel(params:progressHandler:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createChannelWithParams:progressHandler:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/createchannel(params:progresshandler:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/createParticipantListQuery(params:)":{"role":"symbol","title":"createParticipantListQuery(params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createParticipantListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ParticipantListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ParticipantListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQuery"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Creates a participant list query for this channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createParticipantListQueryWithParams:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/createparticipantlistquery(params:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/update(params:completionHandler:)":{"role":"symbol","title":"update(params:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK18OpenChannelHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Updates this channel with "},{"type":"codeVoice","code":"OpenChannelUpdateParams"},{"type":"text","text":" class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/update(params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateChannelWithParams:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/update(params:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/participantCount":{"role":"symbol","title":"participantCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"participantCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The number of participants in this channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/participantCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"participantCount"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/participantcount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/createOpenChannelListQuery(paramsBuilder:)":{"role":"symbol","title":"createOpenChannelListQuery(paramsBuilder:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOpenChannelListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramsBuilder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"OpenChannelListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"OpenChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelListQuery"}],"abstract":[{"type":"text","text":"Creates a query instance for open channel list."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createOpenChannelListQuery(paramsBuilder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createOpenChannelListQueryWithParamsBuilder:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/createopenchannellistquery(paramsbuilder:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/update(params:progressHandler:completionHandler:)":{"role":"symbol","title":"update(params:progressHandler:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progressHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProgressHandler","preciseIdentifier":"s:15SendbirdChatSDK15ProgressHandlera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK18OpenChannelHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Updates this channel with "},{"type":"codeVoice","code":"OpenChannelUpdateParams"},{"type":"text","text":" class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/update(params:progressHandler:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateChannelWithParams:progressHandler:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/update(params:progresshandler:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/createParticipantListQuery()":{"role":"symbol","title":"createParticipantListQuery()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createParticipantListQuery"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ParticipantListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDParticipantListQuery"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Creates a participant list query for this channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createParticipantListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/createparticipantlistquery()"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/refresh(completionHandler:)":{"role":"symbol","title":"refresh(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Refreshes the channel information."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/refresh(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refreshWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/refresh(completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel/build(fromSerializedData:)":{"role":"symbol","title":"build(fromSerializedData:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromSerializedData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?) -> `Self`"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Deserializes and reconstructs the object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/build(fromSerializedData:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildFromSerializedData:"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel\/build(fromserializeddata:)"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDOpenChannel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDOpenChannel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/operators","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/participantCount"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(params:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(paramsBuilder:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/delete(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/enter(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/exit(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/isOperator(user:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/isOperator(userID:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/refresh(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/update(params:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/update(params:progressHandler:completionHandler:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/build(fromSerializedData:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createChannel(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createChannel(params:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createChannel(params:progressHandler:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createOpenChannelListQuery()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createOpenChannelListQuery(params:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createOpenChannelListQuery(paramsBuilder:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(channelURL:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(channelURL:params:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/createParticipantListQuery(channelURL:paramsBuilder:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel\/getChannel(url:completionHandler:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDOpenChannel"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel","text":"SBDBaseChannel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1isOperator(userID:)\/title","value":"isOperatorWithUserID:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1isOperator(userID:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isOperatorWithUserID:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1getChannel(url:completionHandler:)\/title","value":"getChannelWithURL:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1getChannel(url:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getChannelWithURL:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createParticipantListQuery(channelURL:paramsBuilder:)\/title","value":"createParticipantListQueryWithChannelURL:paramsBuilder:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createParticipantListQuery(channelURL:paramsBuilder:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createParticipantListQueryWithChannelURL:paramsBuilder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createParticipantListQuery(paramsBuilder:)\/title","value":"createParticipantListQueryWithParamsBuilder:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createParticipantListQuery(paramsBuilder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createParticipantListQueryWithParamsBuilder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1enter(completionHandler:)\/title","value":"enterChannelWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1enter(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enterChannelWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1exit(completionHandler:)\/title","value":"exitChannelWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1exit(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"exitChannelWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel\/title","value":"SBDOpenChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/title","value":"Mappable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/fragments","value":[{"kind":"identifier","text":"Mappable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createOpenChannelListQuery(params:)\/title","value":"createOpenChannelListQueryWithParams:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createOpenChannelListQuery(params:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createOpenChannelListQueryWithParams:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createOpenChannelListQuery()\/title","value":"createOpenChannelListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createOpenChannelListQuery()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createOpenChannelListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createParticipantListQuery(channelURL:)\/title","value":"createParticipantListQueryWithChannelURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createParticipantListQuery(channelURL:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createParticipantListQueryWithChannelURL:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Serializable\/title","value":"Serializable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Serializable\/fragments","value":[{"kind":"identifier","text":"Serializable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1isOperator(user:)\/title","value":"isOperatorWithUser:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1isOperator(user:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isOperatorWithUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1delete(completionHandler:)\/title","value":"deleteChannelWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1delete(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteChannelWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createParticipantListQuery(channelURL:params:)\/title","value":"createParticipantListQueryWithChannelURL:params:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createParticipantListQuery(channelURL:params:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createParticipantListQueryWithChannelURL:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createChannel(params:completionHandler:)\/title","value":"createChannelWithParams:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createChannel(params:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createChannelWithParams:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createChannel(completionHandler:)\/title","value":"createChannelWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createChannel(completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createChannelWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1operators\/title","value":"operators"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1operators\/fragments","value":[{"kind":"identifier","text":"operators"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createChannel(params:progressHandler:completionHandler:)\/title","value":"createChannelWithParams:progressHandler:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createChannel(params:progressHandler:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createChannelWithParams:progressHandler:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createParticipantListQuery(params:)\/title","value":"createParticipantListQueryWithParams:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createParticipantListQuery(params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createParticipantListQueryWithParams:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1update(params:completionHandler:)\/title","value":"updateChannelWithParams:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1update(params:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateChannelWithParams:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1participantCount\/title","value":"participantCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1participantCount\/fragments","value":[{"kind":"identifier","text":"participantCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createOpenChannelListQuery(paramsBuilder:)\/title","value":"createOpenChannelListQueryWithParamsBuilder:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createOpenChannelListQuery(paramsBuilder:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createOpenChannelListQueryWithParamsBuilder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1update(params:progressHandler:completionHandler:)\/title","value":"updateChannelWithParams:progressHandler:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1update(params:progressHandler:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateChannelWithParams:progressHandler:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createParticipantListQuery()\/title","value":"createParticipantListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1createParticipantListQuery()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createParticipantListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1refresh(completionHandler:)\/title","value":"refreshWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1refresh(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1build(fromSerializedData:)\/title","value":"buildFromSerializedData:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel~1build(fromSerializedData:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildFromSerializedData:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}