{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelHandler"},{"kind":"text","text":" = (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel","text":"OpenChannel"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError","text":"SBError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/openchannelhandler"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelHandler","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Group channel handler"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelHandler"}],"title":"OpenChannelHandler","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"s:15SendbirdChatSDK18OpenChannelHandlera","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"OpenChannelHandler"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannel":{"role":"symbol","title":"OpenChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" class represents a open channel which is a public chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannel"}],"url":"\/documentation\/sendbirdchatsdk\/openchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OpenChannelHandler":{"role":"symbol","title":"OpenChannelHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenChannelHandler"}],"abstract":[{"type":"text","text":"Group channel handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OpenChannelHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenChannelHandler"}],"url":"\/documentation\/sendbirdchatsdk\/openchannelhandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBError":{"role":"symbol","title":"SBError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBError"}],"abstract":[{"type":"text","text":"Sendbird error class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBError"}],"url":"\/documentation\/sendbirdchatsdk\/sberror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel\/title","value":"SBDOpenChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OpenChannel\/fragments","value":[{"kind":"identifier","text":"SBDOpenChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SBError\/title","value":"SBError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SBError\/fragments","value":[{"kind":"identifier","text":"SBError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}