{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDPollData) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollData"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.232"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/polldata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/polldata"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollData","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents a poll data"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollData"}],"title":"PollData","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDPollData","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PollData"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollData\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollData\/text"]}],"references":{"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollData/text":{"role":"symbol","title":"text","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Text representation"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollData\/text","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"text"}],"url":"\/documentation\/sendbirdchatsdk\/polldata\/text"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollData":{"role":"symbol","title":"PollData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollData"}],"abstract":[{"type":"text","text":"Represents a poll data"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PollData"}],"url":"\/documentation\/sendbirdchatsdk\/polldata"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollData/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollData\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/polldata\/init(from:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDPollData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPollData"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDPollData"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollData\/text"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDPollData"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollData~1text\/title","value":"text"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollData~1text\/fragments","value":[{"kind":"identifier","text":"text"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollData\/title","value":"SBDPollData"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollData\/fragments","value":[{"kind":"identifier","text":"SBDPollData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}