{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDPollOption) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollOption"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.232"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/polloption"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/polloption"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents an option for poll"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollOption"}],"title":"PollOption","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDPollOption","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PollOption"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/createdAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/createdBy","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/lastVotedAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/optionID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/partialVoters","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/pollID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/text","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/updatedAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/voteCount"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/delete(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/update(text:completionHandler:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/get(pollID:optionID:channelType:channelURL:completionHandler:)"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollOption/voteCount":{"role":"symbol","title":"voteCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"voteCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Number of votes casted on the option"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/voteCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"voteCount"}],"url":"\/documentation\/sendbirdchatsdk\/polloption\/votecount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollOption/delete(completionHandler:)":{"role":"symbol","title":"delete(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"delete"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Deletes this option"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/delete(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/polloption\/delete(completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollOption":{"role":"symbol","title":"PollOption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollOption"}],"abstract":[{"type":"text","text":"Represents an option for poll"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PollOption"}],"url":"\/documentation\/sendbirdchatsdk\/polloption"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollOption/updatedAt":{"role":"symbol","title":"updatedAt","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Unix timestamp at which the option is updated (millisecond)"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/updatedAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updatedAt"}],"url":"\/documentation\/sendbirdchatsdk\/polloption\/updatedat"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollOption/text":{"role":"symbol","title":"text","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The text to represent the option"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/text","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"text"}],"url":"\/documentation\/sendbirdchatsdk\/polloption\/text"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollOption/optionID":{"role":"symbol","title":"optionID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Option ID"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/optionID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"optionID"}],"url":"\/documentation\/sendbirdchatsdk\/polloption\/optionid"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollOption/createdAt":{"role":"symbol","title":"createdAt","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"createdAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Unix timestamp at which the option is created (millisecond)"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/createdAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createdAt"}],"url":"\/documentation\/sendbirdchatsdk\/polloption\/createdat"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollOption/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Compares this object with given other object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/sendbirdchatsdk\/polloption\/isequal(_:)"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollOption/createdBy":{"role":"symbol","title":"createdBy","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"createdBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"ID of the user who has created the option"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/createdBy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createdBy"}],"url":"\/documentation\/sendbirdchatsdk\/polloption\/createdby"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollOption/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/polloption\/init(from:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollOption/partialVoters":{"role":"symbol","title":"partialVoters","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"partialVoters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Users who casted the vote on this option, this field is only available when you fetch poll with "},{"type":"codeVoice","code":"showPartialVoters"},{"type":"text","text":" option"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/partialVoters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"partialVoters"}],"url":"\/documentation\/sendbirdchatsdk\/polloption\/partialvoters"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollOption/pollID":{"role":"symbol","title":"pollID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pollID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Poll ID"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/pollID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pollID"}],"url":"\/documentation\/sendbirdchatsdk\/polloption\/pollid"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollOption/lastVotedAt":{"role":"symbol","title":"lastVotedAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastVotedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Unix timestamp at which last vote occurs either cast or cancel (millisecond)"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/lastVotedAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lastVotedAt"}],"url":"\/documentation\/sendbirdchatsdk\/polloption\/lastvotedat"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollOption/get(pollID:optionID:channelType:channelURL:completionHandler:)":{"role":"symbol","title":"get(pollID:optionID:channelType:channelURL:completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pollID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"optionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollOptionHandler","preciseIdentifier":"s:15SendbirdChatSDK17PollOptionHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Gets an option with ID."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/get(pollID:optionID:channelType:channelURL:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getWithPollID:optionID:channelType:channelURL:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/polloption\/get(pollid:optionid:channeltype:channelurl:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollOption/update(text:completionHandler:)":{"role":"symbol","title":"update(text:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollHandler","preciseIdentifier":"s:15SendbirdChatSDK11PollHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Update this option with text"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/update(text:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateWithText:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/polloption\/update(text:completionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDPollOption"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPollOption"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDPollOption"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/createdAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/createdBy","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/lastVotedAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/optionID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/partialVoters","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/pollID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/text","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/updatedAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/voteCount"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/delete(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/update(text:completionHandler:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollOption\/get(pollID:optionID:channelType:channelURL:completionHandler:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDPollOption"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1voteCount\/title","value":"voteCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1voteCount\/fragments","value":[{"kind":"identifier","text":"voteCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1delete(completionHandler:)\/title","value":"deleteWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1delete(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption\/title","value":"SBDPollOption"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption\/fragments","value":[{"kind":"identifier","text":"SBDPollOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1updatedAt\/title","value":"updatedAt"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1updatedAt\/fragments","value":[{"kind":"identifier","text":"updatedAt"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1text\/title","value":"text"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1text\/fragments","value":[{"kind":"identifier","text":"text"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1optionID\/title","value":"optionID"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1optionID\/fragments","value":[{"kind":"identifier","text":"optionID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1createdAt\/title","value":"createdAt"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1createdAt\/fragments","value":[{"kind":"identifier","text":"createdAt"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1createdBy\/title","value":"createdBy"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1createdBy\/fragments","value":[{"kind":"identifier","text":"createdBy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1partialVoters\/title","value":"partialVoters"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1partialVoters\/fragments","value":[{"kind":"identifier","text":"partialVoters"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1pollID\/title","value":"pollID"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1pollID\/fragments","value":[{"kind":"identifier","text":"pollID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1lastVotedAt\/title","value":"lastVotedAt"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1lastVotedAt\/fragments","value":[{"kind":"identifier","text":"lastVotedAt"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1get(pollID:optionID:channelType:channelURL:completionHandler:)\/title","value":"getWithPollID:optionID:channelType:channelURL:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1get(pollID:optionID:channelType:channelURL:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getWithPollID:optionID:channelType:channelURL:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1update(text:completionHandler:)\/title","value":"updateWithText:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollOption~1update(text:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateWithText:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}