{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDPollDetails) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollDetails"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.232"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/polldetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/polldetails"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents a poll details information"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollDetails"}],"title":"PollDetails","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDPollDetails","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PollDetails"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/allowMutipleVotes","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/allowUserSuggestion","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/closeAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/createdAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/createdBy","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/data","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/isAnonymous","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/options","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/status","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/updatedAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/votedOptionIDs","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/voterCount"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/encode(to:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/isEqual(_:)"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/createdAt":{"role":"symbol","title":"createdAt","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"createdAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Unix timestamp at which the poll is created (millisecond)."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/createdAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createdAt"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails\/createdat"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/isAnonymous":{"role":"symbol","title":"isAnonymous","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAnonymous"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to make the votes anonymous."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/isAnonymous","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAnonymous"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails\/isanonymous"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Encodes this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/polldetails\/encode(to:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/polldetails\/init(from:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/votedOptionIDs":{"role":"symbol","title":"votedOptionIDs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"votedOptionIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Current user’s voted option list."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/votedOptionIDs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"votedOptionIDs"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails\/votedoptionids"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/voterCount":{"role":"symbol","title":"voterCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"voterCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Number of voters who casted a vote on the poll."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/voterCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"voterCount"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails\/votercount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/options":{"role":"symbol","title":"options","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PollOption","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollOption"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Possible options for which a user can vote."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/options","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"options"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails\/options"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/data":{"role":"symbol","title":"data","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollData","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollData"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"An additional text to accompany the poll."},{"type":"text","text":" "},{"type":"text","text":"Can be used to provide explanations for incorrect quiz answers"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/data","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"data"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails\/data"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/closeAt":{"role":"symbol","title":"closeAt","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Unix timestamp at which the poll has closed or will close (second)."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/closeAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"closeAt"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails\/closeat"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails":{"role":"symbol","title":"PollDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollDetails"}],"abstract":[{"type":"text","text":"Represents a poll details information"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PollDetails"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Compares this object with given other object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails\/isequal(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/allowUserSuggestion":{"role":"symbol","title":"allowUserSuggestion","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowUserSuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to allow user-suggested options."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/allowUserSuggestion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"allowUserSuggestion"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails\/allowusersuggestion"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/createdBy":{"role":"symbol","title":"createdBy","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"createdBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"User ID who creates this poll."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/createdBy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createdBy"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails\/createdby"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/allowMutipleVotes":{"role":"symbol","title":"allowMutipleVotes","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowMutipleVotes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to allow multiple vote casting."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/allowMutipleVotes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"allowMutipleVotes"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails\/allowmutiplevotes"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/status":{"role":"symbol","title":"status","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollStatus","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDPollStatus"}],"abstract":[{"type":"text","text":"Whether the poll is closed."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/status","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"status"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails\/status"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollDetails/updatedAt":{"role":"symbol","title":"updatedAt","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Unix timestamp at which the poll is updated (millisecond)."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/updatedAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updatedAt"}],"url":"\/documentation\/sendbirdchatsdk\/polldetails\/updatedat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDPollDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPollDetails"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDPollDetails"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/allowMutipleVotes","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/allowUserSuggestion","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/closeAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/createdAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/createdBy","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/data","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/isAnonymous","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/options","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/status","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/updatedAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/votedOptionIDs","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/voterCount"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollDetails\/isEqual(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDPollDetails"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1createdAt\/title","value":"createdAt"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1createdAt\/fragments","value":[{"kind":"identifier","text":"createdAt"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1isAnonymous\/title","value":"isAnonymous"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1isAnonymous\/fragments","value":[{"kind":"identifier","text":"isAnonymous"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1votedOptionIDs\/title","value":"votedOptionIDs"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1votedOptionIDs\/fragments","value":[{"kind":"identifier","text":"votedOptionIDs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1voterCount\/title","value":"voterCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1voterCount\/fragments","value":[{"kind":"identifier","text":"voterCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1options\/title","value":"options"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1options\/fragments","value":[{"kind":"identifier","text":"options"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1data\/title","value":"data"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1data\/fragments","value":[{"kind":"identifier","text":"data"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1closeAt\/title","value":"closeAt"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1closeAt\/fragments","value":[{"kind":"identifier","text":"closeAt"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails\/title","value":"SBDPollDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails\/fragments","value":[{"kind":"identifier","text":"SBDPollDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1allowUserSuggestion\/title","value":"allowUserSuggestion"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1allowUserSuggestion\/fragments","value":[{"kind":"identifier","text":"allowUserSuggestion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1createdBy\/title","value":"createdBy"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1createdBy\/fragments","value":[{"kind":"identifier","text":"createdBy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1allowMutipleVotes\/title","value":"allowMutipleVotes"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1allowMutipleVotes\/fragments","value":[{"kind":"identifier","text":"allowMutipleVotes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1status\/title","value":"status"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1status\/fragments","value":[{"kind":"identifier","text":"status"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1updatedAt\/title","value":"updatedAt"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollDetails~1updatedAt\/fragments","value":[{"kind":"identifier","text":"updatedAt"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}