{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDPoll) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Poll"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.232"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/poll"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/poll"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents a poll that users can vote"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Poll"}],"title":"Poll","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDPoll","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"Poll"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/details","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/pollID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/title"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/addOption(text:channelType:channelURL:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/close(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/delete(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/encode(to:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/update(params:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/vote(optionIDs:channelType:channelURL:completionHandler:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/create(params:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/get(params:completionHandler:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/Mappable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/addOption(text:channelType:channelURL:completionHandler:)":{"role":"symbol","title":"addOption(text:channelType:channelURL:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addOption"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollHandler","preciseIdentifier":"s:15SendbirdChatSDK11PollHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Adds an option to this poll."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/addOption(text:channelType:channelURL:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addOptionWithText:channelType:channelURL:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/poll\/addoption(text:channeltype:channelurl:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Compares this object with given other object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/sendbirdchatsdk\/poll\/isequal(_:)"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Encodes this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/poll\/encode(to:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/create(params:completionHandler:)":{"role":"symbol","title":"create(params:completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollCreateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollHandler","preciseIdentifier":"s:15SendbirdChatSDK11PollHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a poll with given params."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/create(params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithParams:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/poll\/create(params:completionhandler:)"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll":{"role":"symbol","title":"Poll","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Poll"}],"abstract":[{"type":"text","text":"Represents a poll that users can vote"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Poll"}],"url":"\/documentation\/sendbirdchatsdk\/poll"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/vote(optionIDs:channelType:channelURL:completionHandler:)":{"role":"symbol","title":"vote(optionIDs:channelType:channelURL:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"vote"},{"kind":"text","text":"("},{"kind":"externalParam","text":"optionIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollHandler","preciseIdentifier":"s:15SendbirdChatSDK11PollHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Votes on this poll."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/vote(optionIDs:channelType:channelURL:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"voteWithOptionIDs:channelType:channelURL:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/poll\/vote(optionids:channeltype:channelurl:completionhandler:)"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Mappable":{"role":"symbol","title":"Mappable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mappable"}],"abstract":[{"type":"text","text":"Mappable protocol to initialize sendbird object from a given dictionary."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Mappable"}],"url":"\/documentation\/sendbirdchatsdk\/mappable"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/get(params:completionHandler:)":{"role":"symbol","title":"get(params:completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollRetrievalParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollRetrievalParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollHandler","preciseIdentifier":"s:15SendbirdChatSDK11PollHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Gets a poll."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/get(params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getWithParams:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/poll\/get(params:completionhandler:)"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/poll\/init(from:)"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/details":{"role":"symbol","title":"details","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"details"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollDetails","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollDetails"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Detail information of this poll"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/details","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"details"}],"url":"\/documentation\/sendbirdchatsdk\/poll\/details"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/update(params:completionHandler:)":{"role":"symbol","title":"update(params:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollHandler","preciseIdentifier":"s:15SendbirdChatSDK11PollHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Updates this poll with params."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/update(params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateWithParams:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/poll\/update(params:completionhandler:)"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/pollID":{"role":"symbol","title":"pollID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pollID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Poll ID"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/pollID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pollID"}],"url":"\/documentation\/sendbirdchatsdk\/poll\/pollid"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/Mappable-Implementations":{"role":"collectionGroup","title":"Mappable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/Mappable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/poll\/mappable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/close(completionHandler:)":{"role":"symbol","title":"close(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"close"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollHandler","preciseIdentifier":"s:15SendbirdChatSDK11PollHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Closes this poll."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/close(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"closeWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/poll\/close(completionhandler:)"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/delete(completionHandler:)":{"role":"symbol","title":"delete(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"delete"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Deletes this poll."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/delete(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/poll\/delete(completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Poll/title":{"role":"symbol","title":"title","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Title of this poll"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/title","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"title"}],"url":"\/documentation\/sendbirdchatsdk\/poll\/title"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDPoll"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPoll"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDPoll"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/details","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/pollID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/title"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/addOption(text:channelType:channelURL:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/close(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/delete(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/update(params:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/vote(optionIDs:channelType:channelURL:completionHandler:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/create(params:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/get(params:completionHandler:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Poll\/Mappable-Implementations"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDPoll"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1addOption(text:channelType:channelURL:completionHandler:)\/title","value":"addOptionWithText:channelType:channelURL:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1addOption(text:channelType:channelURL:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addOptionWithText:channelType:channelURL:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1create(params:completionHandler:)\/title","value":"createWithParams:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1create(params:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithParams:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll\/title","value":"SBDPoll"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll\/fragments","value":[{"kind":"identifier","text":"SBDPoll"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1vote(optionIDs:channelType:channelURL:completionHandler:)\/title","value":"voteWithOptionIDs:channelType:channelURL:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1vote(optionIDs:channelType:channelURL:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"voteWithOptionIDs:channelType:channelURL:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/title","value":"Mappable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/fragments","value":[{"kind":"identifier","text":"Mappable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1get(params:completionHandler:)\/title","value":"getWithParams:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1get(params:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getWithParams:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1details\/title","value":"details"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1details\/fragments","value":[{"kind":"identifier","text":"details"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1update(params:completionHandler:)\/title","value":"updateWithParams:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1update(params:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateWithParams:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1pollID\/title","value":"pollID"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1pollID\/fragments","value":[{"kind":"identifier","text":"pollID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1close(completionHandler:)\/title","value":"closeWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1close(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"closeWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1delete(completionHandler:)\/title","value":"deleteWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1delete(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1title\/title","value":"title"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Poll~1title\/fragments","value":[{"kind":"identifier","text":"title"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}