{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDPollListQuery) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollListQuery"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.232"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/polllistquery"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/polllistquery"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object to retrieve list of "},{"type":"codeVoice","code":"Poll"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollListQuery"}],"title":"PollListQuery","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDPollListQuery","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PollListQuery"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery\/hasNext","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery\/isLoading","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery\/limit"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery\/loadNextPage(completionHandler:)"]}],"references":{"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollListQuery/loadNextPage(completionHandler:)":{"role":"symbol","title":"loadNextPage(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadNextPage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PollListHandler","preciseIdentifier":"s:15SendbirdChatSDK15PollListHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Fetches next page"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery\/loadNextPage(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadNextPageWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/polllistquery\/loadnextpage(completionhandler:)"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollListQuery/limit":{"role":"symbol","title":"limit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"limit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"fetch limit"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery\/limit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"limit"}],"url":"\/documentation\/sendbirdchatsdk\/polllistquery\/limit"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollListQuery/hasNext":{"role":"symbol","title":"hasNext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasNext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Boolean indicates there are more data to fetch"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery\/hasNext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasNext"}],"url":"\/documentation\/sendbirdchatsdk\/polllistquery\/hasnext"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollListQuery/isLoading":{"role":"symbol","title":"isLoading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Indicates the query is currently loading or not"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery\/isLoading","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isLoading"}],"url":"\/documentation\/sendbirdchatsdk\/polllistquery\/isloading"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollListQuery":{"role":"symbol","title":"PollListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollListQuery"}],"abstract":[{"type":"text","text":"An object to retrieve list of "},{"type":"codeVoice","code":"Poll"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PollListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/polllistquery"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollListQuery/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Copies this object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/sendbirdchatsdk\/polllistquery\/copy(with:)"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDPollListQuery"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPollListQuery"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDPollListQuery"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery\/hasNext","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery\/isLoading","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery\/limit"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollListQuery\/loadNextPage(completionHandler:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDPollListQuery"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollListQuery~1loadNextPage(completionHandler:)\/title","value":"loadNextPageWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollListQuery~1loadNextPage(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadNextPageWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollListQuery~1limit\/title","value":"limit"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollListQuery~1limit\/fragments","value":[{"kind":"identifier","text":"limit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollListQuery~1hasNext\/title","value":"hasNext"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollListQuery~1hasNext\/fragments","value":[{"kind":"identifier","text":"hasNext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollListQuery~1isLoading\/title","value":"isLoading"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollListQuery~1isLoading\/fragments","value":[{"kind":"identifier","text":"isLoading"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollListQuery\/title","value":"SBDPollListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollListQuery\/fragments","value":[{"kind":"identifier","text":"SBDPollListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollListQuery~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollListQuery~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}