{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDPublicGroupChannelListQueryParams) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicGroupChannelListQueryParams"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/init(builder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/channelNameContainsFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/channelURLsFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/customTypeStartsWithFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/customTypesFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/includeEmptyChannel","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/includeFrozenChannel","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/includeMemberList","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/includeMetaData","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/limit","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/metaDataKeyFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/metaDataOrderKeyFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/metaDataValueStartsWithFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/metaDataValuesFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/order","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/publicMembershipFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/superChannelFilter"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/setMetaDataFilter(withKey:valueStartsWith:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/setMetaDataFilter(withKey:values:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/NSCopying-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicGroupChannelListQueryParams"}],"title":"PublicGroupChannelListQueryParams","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDPublicGroupChannelListQueryParams","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PublicGroupChannelListQueryParams"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/metaDataOrderKeyFilter":{"role":"symbol","title":"metaDataOrderKeyFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaDataOrderKeyFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sets a key for ordering by value in the metadata."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/metaDataOrderKeyFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metaDataOrderKeyFilter"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/metadataorderkeyfilter"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/order":{"role":"symbol","title":"order","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PublicGroupChannelListOrder","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDPublicGroupChannelListOrder"}],"abstract":[{"type":"text","text":"Sets the order of the list. The order is defined in "},{"type":"codeVoice","code":"PublicGroupChannelListOrder"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Default is "},{"type":"codeVoice","code":".chronological"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/order","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"order"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/order"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/superChannelFilter":{"role":"symbol","title":"superChannelFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"superChannelFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelSuperChannelFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelSuperChannelFilter"}],"abstract":[{"type":"text","text":"Sets to filter super channel. Default is "},{"type":"codeVoice","code":".all"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/superChannelFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"superChannelFilter"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/superchannelfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/metaDataValuesFilter":{"role":"symbol","title":"metaDataValuesFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaDataValuesFilter"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Searches for group channels with metadata containing an item with the key specified by the metaDataKey"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/metaDataValuesFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metaDataValuesFilter"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/metadatavaluesfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/isequal(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/limit":{"role":"symbol","title":"limit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"limit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Specifies the number of results to return per call. (Default: 20)"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/limit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"limit"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/limit"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/channelNameContainsFilter":{"role":"symbol","title":"channelNameContainsFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelNameContainsFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sets "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" names filter."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/channelNameContainsFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelNameContainsFilter"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/channelnamecontainsfilter"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/metaDataKeyFilter":{"role":"symbol","title":"metaDataKeyFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaDataKeyFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Searches for group channels with metadata containing an item with the specified value as its key"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/metaDataKeyFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metaDataKeyFilter"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/metadatakeyfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/setMetaDataFilter(withKey:values:)":{"role":"symbol","title":"setMetaDataFilter(withKey:values:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMetaDataFilter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"values"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Sets meta data filter"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/setMetaDataFilter(withKey:values:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMetaDataFilterWithKey:values:"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/setmetadatafilter(withkey:values:)"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/metaDataValueStartsWithFilter":{"role":"symbol","title":"metaDataValueStartsWithFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaDataValueStartsWithFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Searches for group channels with metadata containing an item with the key specified by the metaDataKey"},{"type":"text","text":" "},{"type":"text","text":"and the values of that item start with the specified value"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/metaDataValueStartsWithFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metaDataValueStartsWithFilter"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/metadatavaluestartswithfilter"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/customTypesFilter":{"role":"symbol","title":"customTypesFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customTypesFilter"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Sets the custom types filter."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/customTypesFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customTypesFilter"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/customtypesfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/init()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/includeMemberList":{"role":"symbol","title":"includeMemberList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeMemberList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines channel list includes their members. Default is "},{"type":"codeVoice","code":"true"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/includeMemberList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeMemberList"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/includememberlist"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/includeFrozenChannel":{"role":"symbol","title":"includeFrozenChannel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeFrozenChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines channel list includes frozen channel. Default is "},{"type":"codeVoice","code":"true"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/includeFrozenChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeFrozenChannel"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/includefrozenchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/includeEmptyChannel":{"role":"symbol","title":"includeEmptyChannel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeEmptyChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines channel list includes empty channel. Deafult is "},{"type":"codeVoice","code":"true"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/includeEmptyChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeEmptyChannel"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/includeemptychannel"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/init(builder:)":{"role":"symbol","title":"init(builder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"builder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"PublicGroupChannelListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPublicGroupChannelListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes and returns a newly allocated params object that mutated through builder closure."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/init(builder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBuilder:"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/init(builder:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/publicMembershipFilter":{"role":"symbol","title":"publicMembershipFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicMembershipFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PublicGroupChannelMembershipFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDPublicGroupChannelMembershipFilter"}],"abstract":[{"type":"text","text":"Sets "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" URLs filter."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/publicMembershipFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publicMembershipFilter"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/publicmembershipfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/setMetaDataFilter(withKey:valueStartsWith:)":{"role":"symbol","title":"setMetaDataFilter(withKey:valueStartsWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMetaDataFilter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"valueStartsWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets meta data filter"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/setMetaDataFilter(withKey:valueStartsWith:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMetaDataFilterWithKey:valueStartsWith:"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/setmetadatafilter(withkey:valuestartswith:)"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams":{"role":"symbol","title":"PublicGroupChannelListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicGroupChannelListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PublicGroupChannelListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/customTypeStartsWithFilter":{"role":"symbol","title":"customTypeStartsWithFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customTypeStartsWithFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sets to filter channels by custom type that starts with."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/customTypeStartsWithFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customTypeStartsWithFilter"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/customtypestartswithfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/channelURLsFilter":{"role":"symbol","title":"channelURLsFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelURLsFilter"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Sets "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" URLs filter."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/channelURLsFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelURLsFilter"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/channelurlsfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/NSCopying-Implementations":{"role":"collectionGroup","title":"NSCopying Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/NSCopying-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/nscopying-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/includeMetaData":{"role":"symbol","title":"includeMetaData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeMetaData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines channel object of the list includes meta data property. Default is "},{"type":"codeVoice","code":"true"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/includeMetaData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeMetaData"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/includemetadata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDPublicGroupChannelListQueryParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelListQueryParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDPublicGroupChannelListQueryParams"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/channelNameContainsFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/channelURLsFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/customTypeStartsWithFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/customTypesFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/includeEmptyChannel","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/includeFrozenChannel","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/includeMemberList","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/includeMetaData","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/limit","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/metaDataKeyFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/metaDataOrderKeyFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/metaDataValueStartsWithFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/metaDataValuesFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/order","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/publicMembershipFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/superChannelFilter"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/init(builder:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/setMetaDataFilter(withKey:valueStartsWith:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/setMetaDataFilter(withKey:values:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/NSCopying-Implementations"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDPublicGroupChannelListQueryParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1metaDataOrderKeyFilter\/title","value":"metaDataOrderKeyFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1metaDataOrderKeyFilter\/fragments","value":[{"kind":"identifier","text":"metaDataOrderKeyFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1order\/title","value":"order"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1order\/fragments","value":[{"kind":"identifier","text":"order"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1superChannelFilter\/title","value":"superChannelFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1superChannelFilter\/fragments","value":[{"kind":"identifier","text":"superChannelFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1metaDataValuesFilter\/title","value":"metaDataValuesFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1metaDataValuesFilter\/fragments","value":[{"kind":"identifier","text":"metaDataValuesFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1limit\/title","value":"limit"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1limit\/fragments","value":[{"kind":"identifier","text":"limit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1channelNameContainsFilter\/title","value":"channelNameContainsFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1channelNameContainsFilter\/fragments","value":[{"kind":"identifier","text":"channelNameContainsFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1metaDataKeyFilter\/title","value":"metaDataKeyFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1metaDataKeyFilter\/fragments","value":[{"kind":"identifier","text":"metaDataKeyFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1setMetaDataFilter(withKey:values:)\/title","value":"setMetaDataFilterWithKey:values:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1setMetaDataFilter(withKey:values:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMetaDataFilterWithKey:values:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1metaDataValueStartsWithFilter\/title","value":"metaDataValueStartsWithFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1metaDataValueStartsWithFilter\/fragments","value":[{"kind":"identifier","text":"metaDataValueStartsWithFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1customTypesFilter\/title","value":"customTypesFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1customTypesFilter\/fragments","value":[{"kind":"identifier","text":"customTypesFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1includeMemberList\/title","value":"includeMemberList"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1includeMemberList\/fragments","value":[{"kind":"identifier","text":"includeMemberList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1includeFrozenChannel\/title","value":"includeFrozenChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1includeFrozenChannel\/fragments","value":[{"kind":"identifier","text":"includeFrozenChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1includeEmptyChannel\/title","value":"includeEmptyChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1includeEmptyChannel\/fragments","value":[{"kind":"identifier","text":"includeEmptyChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1init(builder:)\/title","value":"initWithBuilder:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1init(builder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBuilder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1publicMembershipFilter\/title","value":"publicMembershipFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1publicMembershipFilter\/fragments","value":[{"kind":"identifier","text":"publicMembershipFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1setMetaDataFilter(withKey:valueStartsWith:)\/title","value":"setMetaDataFilterWithKey:valueStartsWith:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1setMetaDataFilter(withKey:valueStartsWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMetaDataFilterWithKey:valueStartsWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams\/title","value":"SBDPublicGroupChannelListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1customTypeStartsWithFilter\/title","value":"customTypeStartsWithFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1customTypeStartsWithFilter\/fragments","value":[{"kind":"identifier","text":"customTypeStartsWithFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1channelURLsFilter\/title","value":"channelURLsFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1channelURLsFilter\/fragments","value":[{"kind":"identifier","text":"channelURLsFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1includeMetaData\/title","value":"includeMetaData"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1includeMetaData\/fragments","value":[{"kind":"identifier","text":"includeMetaData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}