{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDPublicGroupChannelListOrder) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicGroupChannelListOrder"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/publicgroupchannellistorder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/publicgroupchannellistorder"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The order type for "},{"type":"codeVoice","code":"PublicGroupChannelListQuery"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicGroupChannelListOrder"}],"title":"PublicGroupChannelListOrder","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDPublicGroupChannelListOrder","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PublicGroupChannelListOrder"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/channelMetaDataValueAlphabetical","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/channelNameAlphabetical","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/chronological"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListOrder":{"role":"symbol","title":"PublicGroupChannelListOrder","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicGroupChannelListOrder"}],"abstract":[{"type":"text","text":"The order type for "},{"type":"codeVoice","code":"PublicGroupChannelListQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PublicGroupChannelListOrder"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistorder"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListOrder/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistorder\/encodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListOrder/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistorder\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListOrder/channelNameAlphabetical":{"role":"symbol","title":"PublicGroupChannelListOrder.channelNameAlphabetical","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelNameAlphabetical"}],"abstract":[{"type":"text","text":"Alphabetical name order for public group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/channelNameAlphabetical","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPublicGroupChannelListOrderChannelNameAlphabetical"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistorder\/channelnamealphabetical"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListOrder/channelMetaDataValueAlphabetical":{"role":"symbol","title":"PublicGroupChannelListOrder.channelMetaDataValueAlphabetical","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelMetaDataValueAlphabetical"}],"abstract":[{"type":"text","text":"Alphabetical value order of a selected key in meta data for public group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/channelMetaDataValueAlphabetical","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPublicGroupChannelListOrderChannelMetaDataValueAlphabetical"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistorder\/channelmetadatavaluealphabetical"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListOrder/chronological":{"role":"symbol","title":"PublicGroupChannelListOrder.chronological","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chronological"}],"abstract":[{"type":"text","text":"Chronological order for public group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/chronological","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPublicGroupChannelListOrderChronological"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistorder\/chronological"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListOrder/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistorder\/decodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListOrder/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistorder\/equatable-implementations"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDPublicGroupChannelListOrder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelListOrder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDPublicGroupChannelListOrder"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/channelMetaDataValueAlphabetical","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/channelNameAlphabetical","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListOrder\/chronological"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDPublicGroupChannelListOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListOrder\/title","value":"SBDPublicGroupChannelListOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListOrder\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelListOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListOrder~1channelNameAlphabetical\/title","value":"SBDPublicGroupChannelListOrderChannelNameAlphabetical"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListOrder~1channelNameAlphabetical\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelListOrderChannelNameAlphabetical"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListOrder~1channelMetaDataValueAlphabetical\/title","value":"SBDPublicGroupChannelListOrderChannelMetaDataValueAlphabetical"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListOrder~1channelMetaDataValueAlphabetical\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelListOrderChannelMetaDataValueAlphabetical"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListOrder~1chronological\/title","value":"SBDPublicGroupChannelListOrderChronological"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListOrder~1chronological\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelListOrderChronological"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}