{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDPushTokenRegistrationStatus) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushTokenRegistrationStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/pushtokenregistrationstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/pushtokenregistrationstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Push token registration statuses"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushTokenRegistrationStatus"}],"title":"PushTokenRegistrationStatus","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDPushTokenRegistrationStatus","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PushTokenRegistrationStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/error","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/pending","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/success"]},{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenRegistrationStatus/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/pushtokenregistrationstatus\/init(rawvalue:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenRegistrationStatus/pending":{"role":"symbol","title":"PushTokenRegistrationStatus.pending","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"abstract":[{"type":"text","text":"Registration is pending."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/pending","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushTokenRegistrationStatusPending"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokenregistrationstatus\/pending"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenRegistrationStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/pushtokenregistrationstatus\/rawrepresentable-implementations"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenRegistrationStatus/error":{"role":"symbol","title":"PushTokenRegistrationStatus.error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"abstract":[{"type":"text","text":"Registartion is failed."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushTokenRegistrationStatusError"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokenregistrationstatus\/error"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenRegistrationStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/pushtokenregistrationstatus\/equatable-implementations"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenRegistrationStatus/success":{"role":"symbol","title":"PushTokenRegistrationStatus.success","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"abstract":[{"type":"text","text":"Registration succeeded."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/success","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushTokenRegistrationStatusSuccess"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokenregistrationstatus\/success"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenRegistrationStatus":{"role":"symbol","title":"PushTokenRegistrationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushTokenRegistrationStatus"}],"abstract":[{"type":"text","text":"Push token registration statuses"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushTokenRegistrationStatus"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokenregistrationstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDPushTokenRegistrationStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenRegistrationStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDPushTokenRegistrationStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/error","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/pending","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenRegistrationStatus\/success"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDPushTokenRegistrationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenRegistrationStatus~1pending\/title","value":"SBDPushTokenRegistrationStatusPending"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenRegistrationStatus~1pending\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenRegistrationStatusPending"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenRegistrationStatus~1error\/title","value":"SBDPushTokenRegistrationStatusError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenRegistrationStatus~1error\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenRegistrationStatusError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenRegistrationStatus~1success\/title","value":"SBDPushTokenRegistrationStatusSuccess"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenRegistrationStatus~1success\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenRegistrationStatusSuccess"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenRegistrationStatus\/title","value":"SBDPushTokenRegistrationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenRegistrationStatus\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenRegistrationStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}