{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDPushNotificationDeliveryOption) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationDeliveryOption"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The push option that determines how to deliver the push notification when sending a user or a file message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationDeliveryOption"}],"title":"PushNotificationDeliveryOption","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDPushNotificationDeliveryOption","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PushNotificationDeliveryOption"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/default","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/suppress"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushNotificationDeliveryOption/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption\/decodable-implementations"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushNotificationDeliveryOption/default":{"role":"symbol","title":"PushNotificationDeliveryOption.default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"abstract":[{"type":"text","text":"The push notification will be delivered by the opposite user’s setting."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOptionDefault"}],"url":"\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption\/default"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushNotificationDeliveryOption/suppress":{"role":"symbol","title":"PushNotificationDeliveryOption.suppress","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suppress"}],"abstract":[{"type":"text","text":"The push notification will never be delivered."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/suppress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOptionSuppress"}],"url":"\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption\/suppress"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushNotificationDeliveryOption":{"role":"symbol","title":"PushNotificationDeliveryOption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationDeliveryOption"}],"abstract":[{"type":"text","text":"The push option that determines how to deliver the push notification when sending a user or a file message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationDeliveryOption"}],"url":"\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushNotificationDeliveryOption/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushNotificationDeliveryOption/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption\/encodable-implementations"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushNotificationDeliveryOption/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDPushNotificationDeliveryOption"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOption"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOption"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/default","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption\/suppress"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDPushNotificationDeliveryOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption~1default\/title","value":"SBDPushNotificationDeliveryOptionDefault"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption~1default\/fragments","value":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOptionDefault"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption~1suppress\/title","value":"SBDPushNotificationDeliveryOptionSuppress"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption~1suppress\/fragments","value":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOptionSuppress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption\/title","value":"SBDPushNotificationDeliveryOption"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption\/fragments","value":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}