{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDPushTokenType) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushTokenType"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.134"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/pushtokentype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/pushtokentype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Constants of type for device push token."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushTokenType"}],"title":"PushTokenType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDPushTokenType","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PushTokenType"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/APNS","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/APNSVoIP","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/GCM","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/none"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/CustomStringConvertible-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/pushtokentype\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/pushtokentype\/decodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType/CustomStringConvertible-Implementations":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/CustomStringConvertible-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/pushtokentype\/customstringconvertible-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType/APNSVoIP":{"role":"symbol","title":"PushTokenType.APNSVoIP","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"APNSVoIP"}],"abstract":[{"type":"text","text":"Token used for VoIP from iOS device."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/APNSVoIP","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushTokenTypeAPNSVoIP"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokentype\/apnsvoip"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType":{"role":"symbol","title":"PushTokenType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushTokenType"}],"abstract":[{"type":"text","text":"Constants of type for device push token."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushTokenType"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokentype"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/pushtokentype\/encodable-implementations"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/pushtokentype\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType/GCM":{"role":"symbol","title":"PushTokenType.GCM","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCM"}],"abstract":[{"type":"text","text":"Token from Android device."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/GCM","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushTokenTypeGCM"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokentype\/gcm"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType/none":{"role":"symbol","title":"PushTokenType.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"No type."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushTokenTypeNone"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokentype\/none"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushTokenType/APNS":{"role":"symbol","title":"PushTokenType.APNS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"APNS"}],"abstract":[{"type":"text","text":"Normal Token from iOS device."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/APNS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDPushTokenTypeAPNS"}],"url":"\/documentation\/sendbirdchatsdk\/pushtokentype\/apns"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDPushTokenType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDPushTokenType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/APNS","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/APNSVoIP","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/GCM","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushTokenType\/none"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDPushTokenType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType~1APNSVoIP\/title","value":"SBDPushTokenTypeAPNSVoIP"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType~1APNSVoIP\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenTypeAPNSVoIP"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType\/title","value":"SBDPushTokenType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType~1GCM\/title","value":"SBDPushTokenTypeGCM"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType~1GCM\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenTypeGCM"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType~1none\/title","value":"SBDPushTokenTypeNone"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType~1none\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenTypeNone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType~1APNS\/title","value":"SBDPushTokenTypeAPNS"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushTokenType~1APNS\/fragments","value":[{"kind":"identifier","text":"SBDPushTokenTypeAPNS"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}