{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDReactionEvent) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReactionEvent"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The object is returned by not only the completion handler of "},{"type":"codeVoice","code":"addReaction(message:key:completionHandler:)"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"deleteReaction(message:key:completionHandler:)"},{"type":"text","text":" in "},{"type":"codeVoice","code":"BaseChannel"},{"type":"text","text":" class but also"},{"type":"text","text":" "},{"type":"codeVoice","code":"channel(_:updatedReaction:)"},{"type":"text","text":" delegate of "},{"type":"codeVoice","code":"BaseChannelDelegate"},{"type":"text","text":" protocol. The object has"},{"type":"text","text":" "},{"type":"text","text":"to be applied to the message that has the identical message ID with the "},{"type":"codeVoice","code":"apply(_:)"},{"type":"text","text":" method in "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":" class."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.169"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/reactionevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/reactionevent"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object represents reaction event info."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReactionEvent"}],"title":"ReactionEvent","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDReactionEvent","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ReactionEvent"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/key","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/messageID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/operation","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/updatedAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/userID"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/Mappable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReactionEvent":{"role":"symbol","title":"ReactionEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReactionEvent"}],"abstract":[{"type":"text","text":"An object represents reaction event info."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReactionEvent"}],"url":"\/documentation\/sendbirdchatsdk\/reactionevent"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReactionEvent/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/reactionevent\/init(from:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReactionEvent/messageID":{"role":"symbol","title":"messageID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Message ID that indentifies the message that has the reaction event."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/messageID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageID"}],"url":"\/documentation\/sendbirdchatsdk\/reactionevent\/messageid"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReactionEvent/Mappable-Implementations":{"role":"collectionGroup","title":"Mappable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/Mappable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/reactionevent\/mappable-implementations"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Mappable":{"role":"symbol","title":"Mappable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mappable"}],"abstract":[{"type":"text","text":"Mappable protocol to initialize sendbird object from a given dictionary."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Mappable"}],"url":"\/documentation\/sendbirdchatsdk\/mappable"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReactionEvent/userID":{"role":"symbol","title":"userID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The user ID that identifies the user who adds or deletes the reaction key."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/userID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userID"}],"url":"\/documentation\/sendbirdchatsdk\/reactionevent\/userid"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReactionEvent/operation":{"role":"symbol","title":"operation","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"operation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReactionEventAction","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReactionEventAction"}],"abstract":[{"type":"text","text":"The operation that the user did. It will be adding a reaction or deleting a reaction."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/operation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"operation"}],"url":"\/documentation\/sendbirdchatsdk\/reactionevent\/operation"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReactionEvent/updatedAt":{"role":"symbol","title":"updatedAt","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The timestamp that represents when the reaction event occurs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/updatedAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updatedAt"}],"url":"\/documentation\/sendbirdchatsdk\/reactionevent\/updatedat"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReactionEvent/key":{"role":"symbol","title":"key","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The reaction key."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/key","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"key"}],"url":"\/documentation\/sendbirdchatsdk\/reactionevent\/key"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDReactionEvent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDReactionEvent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDReactionEvent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/key","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/messageID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/operation","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/updatedAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/userID"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/Mappable-Implementations"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDReactionEvent"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent\/title","value":"SBDReactionEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent\/fragments","value":[{"kind":"identifier","text":"SBDReactionEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent~1messageID\/title","value":"messageID"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent~1messageID\/fragments","value":[{"kind":"identifier","text":"messageID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/title","value":"Mappable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/fragments","value":[{"kind":"identifier","text":"Mappable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent~1userID\/title","value":"userID"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent~1userID\/fragments","value":[{"kind":"identifier","text":"userID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent~1operation\/title","value":"operation"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent~1operation\/fragments","value":[{"kind":"identifier","text":"operation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent~1updatedAt\/title","value":"updatedAt"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent~1updatedAt\/fragments","value":[{"kind":"identifier","text":"updatedAt"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent~1key\/title","value":"key"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent~1key\/fragments","value":[{"kind":"identifier","text":"key"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}