{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDReportCategory) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportCategory"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.154"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/reportcategory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/reportcategory"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Categories of reporting reasons"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportCategory"}],"title":"ReportCategory","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDReportCategory","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ReportCategory"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/harassing","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/inappropriate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/spam","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/suspicious"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReportCategory/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/reportcategory\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReportCategory/inappropriate":{"role":"symbol","title":"ReportCategory.inappropriate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inappropriate"}],"abstract":[{"type":"text","text":"Report inappropriate content"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/inappropriate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDReportCategoryInappropriate"}],"url":"\/documentation\/sendbirdchatsdk\/reportcategory\/inappropriate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReportCategory":{"role":"symbol","title":"ReportCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportCategory"}],"abstract":[{"type":"text","text":"Categories of reporting reasons"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReportCategory"}],"url":"\/documentation\/sendbirdchatsdk\/reportcategory"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReportCategory/spam":{"role":"symbol","title":"ReportCategory.spam","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"spam"}],"abstract":[{"type":"text","text":"Report spam content"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/spam","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDReportCategorySpam"}],"url":"\/documentation\/sendbirdchatsdk\/reportcategory\/spam"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReportCategory/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/reportcategory\/encodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReportCategory/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/reportcategory\/decodable-implementations"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReportCategory/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/reportcategory\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReportCategory/harassing":{"role":"symbol","title":"ReportCategory.harassing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"harassing"}],"abstract":[{"type":"text","text":"Report harassing content."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/harassing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDReportCategoryHarassing"}],"url":"\/documentation\/sendbirdchatsdk\/reportcategory\/harassing"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReportCategory/suspicious":{"role":"symbol","title":"ReportCategory.suspicious","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suspicious"}],"abstract":[{"type":"text","text":"Report suspicious content"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/suspicious","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDReportCategorySuspicious"}],"url":"\/documentation\/sendbirdchatsdk\/reportcategory\/suspicious"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDReportCategory"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDReportCategory"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDReportCategory"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/harassing","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/inappropriate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/spam","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReportCategory\/suspicious"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDReportCategory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory~1inappropriate\/title","value":"SBDReportCategoryInappropriate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory~1inappropriate\/fragments","value":[{"kind":"identifier","text":"SBDReportCategoryInappropriate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory\/title","value":"SBDReportCategory"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory\/fragments","value":[{"kind":"identifier","text":"SBDReportCategory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory~1spam\/title","value":"SBDReportCategorySpam"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory~1spam\/fragments","value":[{"kind":"identifier","text":"SBDReportCategorySpam"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory~1harassing\/title","value":"SBDReportCategoryHarassing"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory~1harassing\/fragments","value":[{"kind":"identifier","text":"SBDReportCategoryHarassing"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory~1suspicious\/title","value":"SBDReportCategorySuspicious"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReportCategory~1suspicious\/fragments","value":[{"kind":"identifier","text":"SBDReportCategorySuspicious"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}