{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDRestrictedUser) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictedUser"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/restricteduser"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/restricteduser"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Serializable","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/s12IdentifiableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictedUser","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents a user who has been restricted in a channel"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictedUser"}],"title":"RestrictedUser","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDRestrictedUser","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"RestrictedUser"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictedUser\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictedUser\/restrictionInfo"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictedUser\/encode(to:)"]}],"references":{"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictedUser":{"role":"symbol","title":"RestrictedUser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictedUser"}],"abstract":[{"type":"text","text":"Represents a user who has been restricted in a channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictedUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RestrictedUser"}],"url":"\/documentation\/sendbirdchatsdk\/restricteduser"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictedUser/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictedUser\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/restricteduser\/init(from:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Mappable":{"role":"symbol","title":"Mappable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mappable"}],"abstract":[{"type":"text","text":"Mappable protocol to initialize sendbird object from a given dictionary."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Mappable"}],"url":"\/documentation\/sendbirdchatsdk\/mappable"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Serializable":{"role":"symbol","title":"Serializable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Serializable"}],"abstract":[{"type":"text","text":"Protocol to provide serialization"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Serializable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Serializable"}],"url":"\/documentation\/sendbirdchatsdk\/serializable"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User":{"role":"symbol","title":"User","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"User"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"User"},{"type":"text","text":" class represents a user. The user is identified by the "},{"type":"codeVoice","code":"userID"},{"type":"text","text":", so the "},{"type":"codeVoice","code":"userID"},{"type":"text","text":" has"},{"type":"text","text":" "},{"type":"text","text":"to be unique. The "},{"type":"codeVoice","code":"userID"},{"type":"text","text":", "},{"type":"codeVoice","code":"nickname"},{"type":"text","text":" and "},{"type":"codeVoice","code":"profileURL"},{"type":"text","text":" are valid in every "},{"type":"codeVoice","code":"User"},{"type":"text","text":" "},{"type":"text","text":"instance, however the "},{"type":"codeVoice","code":"connectionStatus"},{"type":"text","text":" and "},{"type":"codeVoice","code":"lastSeenAt"},{"type":"text","text":" is valid in "},{"type":"codeVoice","code":"User"},{"type":"text","text":" instance"},{"type":"text","text":" "},{"type":"text","text":"from "},{"type":"codeVoice","code":"UserListQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"User"}],"url":"\/documentation\/sendbirdchatsdk\/user"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictedUser/restrictionInfo":{"role":"symbol","title":"restrictionInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restrictionInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RestrictionInfo","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDRestrictionInfo"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Restriction info for this user"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictedUser\/restrictionInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"restrictionInfo"}],"url":"\/documentation\/sendbirdchatsdk\/restricteduser\/restrictioninfo"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictedUser/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Encodes this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictedUser\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/restricteduser\/encode(to:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/s12IdentifiableP":{"type":"unresolvable","title":"Swift.Identifiable","identifier":"doc:\/\/com.sendbird.chat\/s12IdentifiableP"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDRestrictedUser"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDRestrictedUser"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDRestrictedUser"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictedUser\/restrictionInfo"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDRestrictedUser"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser","text":"SBDUser"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictedUser\/title","value":"SBDRestrictedUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictedUser\/fragments","value":[{"kind":"identifier","text":"SBDRestrictedUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/title","value":"Mappable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/fragments","value":[{"kind":"identifier","text":"Mappable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Serializable\/title","value":"Serializable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Serializable\/fragments","value":[{"kind":"identifier","text":"Serializable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User\/title","value":"SBDUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User\/fragments","value":[{"kind":"identifier","text":"SBDUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictedUser~1restrictionInfo\/title","value":"restrictionInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictedUser~1restrictionInfo\/fragments","value":[{"kind":"identifier","text":"restrictionInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}