{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDRestrictionType) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictionType"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.236"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/restrictiontype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/restrictiontype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Restriction type for restrictedUser"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictionType"}],"title":"RestrictionType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDRestrictionType","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"RestrictionType"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/banned","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/muted"]},{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/init(from:)-7duk8","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/rawValue-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/encode(to:)"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/RawValue-swift.typealias"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionType/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Encodes this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/restrictiontype\/encode(to:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/restrictiontype\/equatable-implementations"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionType/init(from:)-7duk8":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/init(from:)-7duk8","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/restrictiontype\/init(from:)-7duk8"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/restrictiontype\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionType/RawValue-swift.typealias":{"role":"symbol","title":"RestrictionType.RawValue","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawValue"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/RawValue-swift.typealias","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RawValue"}],"url":"\/documentation\/sendbirdchatsdk\/restrictiontype\/rawvalue-swift.typealias"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/restrictiontype\/init(rawvalue:)"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionType/rawValue-swift.property":{"role":"symbol","title":"rawValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/rawValue-swift.property","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/restrictiontype\/rawvalue-swift.property"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionType/muted":{"role":"symbol","title":"RestrictionType.muted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"muted"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/muted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDRestrictionTypeMuted"}],"url":"\/documentation\/sendbirdchatsdk\/restrictiontype\/muted"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionType/banned":{"role":"symbol","title":"RestrictionType.banned","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"banned"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/banned","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDRestrictionTypeBanned"}],"url":"\/documentation\/sendbirdchatsdk\/restrictiontype\/banned"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictionType":{"role":"symbol","title":"RestrictionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictionType"}],"abstract":[{"type":"text","text":"Restriction type for restrictedUser"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RestrictionType"}],"url":"\/documentation\/sendbirdchatsdk\/restrictiontype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDRestrictionType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDRestrictionType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDRestrictionType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/banned","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictionType\/muted"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDRestrictionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionType~1muted\/title","value":"SBDRestrictionTypeMuted"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionType~1muted\/fragments","value":[{"kind":"identifier","text":"SBDRestrictionTypeMuted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionType~1banned\/title","value":"SBDRestrictionTypeBanned"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionType~1banned\/fragments","value":[{"kind":"identifier","text":"SBDRestrictionTypeBanned"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionType\/title","value":"SBDRestrictionType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictionType\/fragments","value":[{"kind":"identifier","text":"SBDRestrictionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}