{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDRole) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Role"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/role"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/role"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The users’s role which gives different behaviors, permisions to user."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Role"}],"title":"Role","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDRole","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"Role"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role\/none","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role\/operator"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Role/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/role\/encodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Role":{"role":"symbol","title":"Role","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Role"}],"abstract":[{"type":"text","text":"The users’s role which gives different behaviors, permisions to user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Role"}],"url":"\/documentation\/sendbirdchatsdk\/role"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Role/operator":{"role":"symbol","title":"Role.operator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`operator`"}],"abstract":[{"type":"text","text":"The role of operator."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role\/operator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDRoleOperator"}],"url":"\/documentation\/sendbirdchatsdk\/role\/operator"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Role/none":{"role":"symbol","title":"Role.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"The default role that means nothing."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDRoleNone"}],"url":"\/documentation\/sendbirdchatsdk\/role\/none"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Role/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/role\/equatable-implementations"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Role/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/role\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Role/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/role\/decodable-implementations"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDRole"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDRole"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDRole"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role\/none","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Role\/operator"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDRole"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Role\/title","value":"SBDRole"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Role\/fragments","value":[{"kind":"identifier","text":"SBDRole"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Role~1operator\/title","value":"SBDRoleOperator"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Role~1operator\/fragments","value":[{"kind":"identifier","text":"SBDRoleOperator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Role~1none\/title","value":"SBDRoleNone"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Role~1none\/fragments","value":[{"kind":"identifier","text":"SBDRoleNone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}