{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBErrorCode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sberrorcode"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/s5ErrorP","doc:\/\/com.sendbird.chat\/s8SendableP"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChatError","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorCode","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorCode\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorCode\/code","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorCode\/message"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorCode\/asSBError(message:)-7bndx"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBErrorCode"}],"title":"SBErrorCode","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:15SendbirdChatSDK11SBErrorCodeP","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBErrorCode"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChatError":{"role":"symbol","title":"ChatError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatError"}],"url":"\/documentation\/sendbirdchatsdk\/chaterror"},"doc://com.sendbird.chat/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.sendbird.chat\/s5ErrorP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBErrorCode/code":{"role":"symbol","title":"code","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorCode\/code","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/sberrorcode\/code"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBErrorCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorCode\/init(rawValue:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/sberrorcode\/init(rawvalue:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBErrorCode/message":{"role":"symbol","title":"message","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorCode\/message","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/sberrorcode\/message"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/CoreError":{"role":"symbol","title":"CoreError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreError"}],"abstract":[{"type":"text","text":"Core error code"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/CoreError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CoreError"}],"url":"\/documentation\/sendbirdchatsdk\/coreerror"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.sendbird.chat\/s8SendableP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBErrorCode":{"role":"symbol","title":"SBErrorCode","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBErrorCode"}],"url":"\/documentation\/sendbirdchatsdk\/sberrorcode"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBErrorCode/asSBError(message:)-7bndx":{"defaultImplementations":1,"role":"symbol","title":"asSBError(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asSBError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorCode\/asSBError(message:)-7bndx","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/sberrorcode\/assberror(message:)-7bndx"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChatError\/title","value":"SBChatError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChatError\/fragments","value":[{"kind":"identifier","text":"SBChatError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError\/title","value":"SBCoreError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1CoreError\/fragments","value":[{"kind":"identifier","text":"SBCoreError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}