{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDScheduledStatusOptions) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledStatusOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/scheduledstatusoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/scheduledstatusoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/s25ExpressibleByArrayLiteralP","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/s9OptionSetP","doc:\/\/com.sendbird.chat\/SY","doc:\/\/com.sendbird.chat\/s10SetAlgebraP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/init(abilitiesToUnion:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/hash","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/rawValue"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/isEqual(_:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/canceled","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/failed","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/pending","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/sent"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/OptionSet-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/RawRepresentable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/SetAlgebra-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledStatusOptions"}],"title":"ScheduledStatusOptions","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ScheduledStatusOptions"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/rawrepresentable-implementations"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions/canceled":{"role":"symbol","title":"canceled","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"canceled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledStatusOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/canceled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canceled"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/canceled"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions/init(abilitiesToUnion:)":{"role":"symbol","title":"init(abilitiesToUnion:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"abilitiesToUnion"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ScheduledStatusOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/init(abilitiesToUnion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAbilitiesToUnion:"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/init(abilitiestounion:)"},"doc://com.sendbird.chat/s10SetAlgebraP":{"type":"unresolvable","title":"Swift.SetAlgebra","identifier":"doc:\/\/com.sendbird.chat\/s10SetAlgebraP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions/failed":{"role":"symbol","title":"failed","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledStatusOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"failed"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/failed"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions/sent":{"role":"symbol","title":"sent","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledStatusOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/sent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sent"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/sent"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions/hash":{"role":"symbol","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"hash"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/hash","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/hash"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions/pending":{"role":"symbol","title":"pending","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledStatusOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/pending","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pending"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/pending"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/init(rawvalue:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions/rawValue":{"role":"symbol","title":"rawValue","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The corresponding value of the raw type."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/rawValue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rawValue"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/rawvalue"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions/SetAlgebra-Implementations":{"role":"collectionGroup","title":"SetAlgebra Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/SetAlgebra-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/setalgebra-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions":{"role":"symbol","title":"ScheduledStatusOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledStatusOptions"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledStatusOptions"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions/OptionSet-Implementations":{"role":"collectionGroup","title":"OptionSet Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/OptionSet-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/optionset-implementations"},"doc://com.sendbird.chat/s25ExpressibleByArrayLiteralP":{"type":"unresolvable","title":"Swift.ExpressibleByArrayLiteral","identifier":"doc:\/\/com.sendbird.chat\/s25ExpressibleByArrayLiteralP"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatusOptions/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Compares this object with given other object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatusoptions\/isequal(_:)"},"doc://com.sendbird.chat/s9OptionSetP":{"type":"unresolvable","title":"Swift.OptionSet","identifier":"doc:\/\/com.sendbird.chat\/s9OptionSetP"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDScheduledStatusOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDScheduledStatusOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDScheduledStatusOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/canceled","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/failed","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/hash","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/pending","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/rawValue","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/sent"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/init(abilitiesToUnion:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatusOptions\/isEqual(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDScheduledStatusOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1canceled\/title","value":"canceled"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1canceled\/fragments","value":[{"kind":"identifier","text":"canceled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1init(abilitiesToUnion:)\/title","value":"initWithAbilitiesToUnion:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1init(abilitiesToUnion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAbilitiesToUnion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1failed\/title","value":"failed"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1failed\/fragments","value":[{"kind":"identifier","text":"failed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1sent\/title","value":"sent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1sent\/fragments","value":[{"kind":"identifier","text":"sent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1pending\/title","value":"pending"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1pending\/fragments","value":[{"kind":"identifier","text":"pending"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1rawValue\/title","value":"rawValue"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1rawValue\/fragments","value":[{"kind":"identifier","text":"rawValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions\/title","value":"SBDScheduledStatusOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions\/fragments","value":[{"kind":"identifier","text":"SBDScheduledStatusOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatusOptions~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}