{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDScheduledStatus) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/scheduledstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/scheduledstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/canceled","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/failed","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/pending","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/sent"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledStatus"}],"title":"ScheduledStatus","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDScheduledStatus","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ScheduledStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatus/failed":{"role":"symbol","title":"ScheduledStatus.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDScheduledStatusFailed"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatus\/failed"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/scheduledstatus\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/scheduledstatus\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatus/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/scheduledstatus\/decodable-implementations"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatus/canceled":{"role":"symbol","title":"ScheduledStatus.canceled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canceled"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/canceled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDScheduledStatusCanceled"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatus\/canceled"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatus/pending":{"role":"symbol","title":"ScheduledStatus.pending","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/pending","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDScheduledStatusPending"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatus\/pending"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatus/sent":{"role":"symbol","title":"ScheduledStatus.sent","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sent"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/sent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDScheduledStatusSent"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatus\/sent"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatus":{"role":"symbol","title":"ScheduledStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledStatus"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledStatus"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDScheduledStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDScheduledStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDScheduledStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/canceled","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/failed","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/pending","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus\/sent"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDScheduledStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatus~1failed\/title","value":"SBDScheduledStatusFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatus~1failed\/fragments","value":[{"kind":"identifier","text":"SBDScheduledStatusFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatus~1canceled\/title","value":"SBDScheduledStatusCanceled"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatus~1canceled\/fragments","value":[{"kind":"identifier","text":"SBDScheduledStatusCanceled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatus~1pending\/title","value":"SBDScheduledStatusPending"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatus~1pending\/fragments","value":[{"kind":"identifier","text":"SBDScheduledStatusPending"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatus~1sent\/title","value":"SBDScheduledStatusSent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatus~1sent\/fragments","value":[{"kind":"identifier","text":"SBDScheduledStatusSent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatus\/title","value":"SBDScheduledStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatus\/fragments","value":[{"kind":"identifier","text":"SBDScheduledStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}