{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendbirdChatOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchatoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/sendbirdchatoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents SendbirdChat options."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendbirdChatOptions"}],"title":"SendbirdChatOptions","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SendbirdChatOptions","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SendbirdChatOptions"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/getConnectionTimeout()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/getFileTransferTimeout()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/getTypingIndicatorThrottle()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/getWebSocketResponseTimeout()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/includePollDetails()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setConnectionTimeout(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setFileTransferTimeout(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setIncludePollDetails(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setMemberInfoInMessage(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setTypingIndicatorThrottle(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setWebSocketResponseTimeout(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/useMemberInfoInMessage()"]}],"references":{"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChatOptions/setConnectionTimeout(_:)":{"role":"symbol","title":"setConnectionTimeout(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConnectionTimeout"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the timeout for connection."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setConnectionTimeout(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setConnectionTimeout:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchatoptions\/setconnectiontimeout(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChatOptions/setTypingIndicatorThrottle(_:)":{"role":"symbol","title":"setTypingIndicatorThrottle(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTypingIndicatorThrottle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets a term of typing indicator throttling in group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setTypingIndicatorThrottle(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setTypingIndicatorThrottle:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchatoptions\/settypingindicatorthrottle(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChatOptions/setIncludePollDetails(_:)":{"role":"symbol","title":"setIncludePollDetails(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIncludePollDetails"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the websocket response to include full poll representation if it exists in a message"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setIncludePollDetails(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setIncludePollDetails:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchatoptions\/setincludepolldetails(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChatOptions/getFileTransferTimeout()":{"role":"symbol","title":"getFileTransferTimeout()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFileTransferTimeout"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"Gets file trnasfer timeout"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/getFileTransferTimeout()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getFileTransferTimeout"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchatoptions\/getfiletransfertimeout()"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChatOptions/setMemberInfoInMessage(_:)":{"role":"symbol","title":"setMemberInfoInMessage(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMemberInfoInMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets "},{"type":"codeVoice","code":"useMemberAsMessageSender"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setMemberInfoInMessage(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMemberInfoInMessage:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchatoptions\/setmemberinfoinmessage(_:)"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChatOptions/getWebSocketResponseTimeout()":{"role":"symbol","title":"getWebSocketResponseTimeout()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getWebSocketResponseTimeout"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"Gets websocket response timeout"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/getWebSocketResponseTimeout()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getWebSocketResponseTimeout"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchatoptions\/getwebsocketresponsetimeout()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChatOptions/getTypingIndicatorThrottle()":{"role":"symbol","title":"getTypingIndicatorThrottle()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTypingIndicatorThrottle"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"Gets typing indicator throttle"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/getTypingIndicatorThrottle()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getTypingIndicatorThrottle"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchatoptions\/gettypingindicatorthrottle()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChatOptions/setFileTransferTimeout(_:)":{"role":"symbol","title":"setFileTransferTimeout(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFileTransferTimeout"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the timeout for file transfer."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setFileTransferTimeout(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setFileTransferTimeout:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchatoptions\/setfiletransfertimeout(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChatOptions/useMemberInfoInMessage()":{"role":"symbol","title":"useMemberInfoInMessage()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"useMemberInfoInMessage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Gets the value whether the sender information of "},{"type":"codeVoice","code":"sender"},{"type":"text","text":" of "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":" or"},{"type":"text","text":" "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" such as nickname and profile url will be returned as the latest user’s or not."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/useMemberInfoInMessage()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"useMemberInfoInMessage"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchatoptions\/usememberinfoinmessage()"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChatOptions/includePollDetails()":{"role":"symbol","title":"includePollDetails()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"includePollDetails"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Gets include poll detail"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/includePollDetails()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includePollDetails"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchatoptions\/includepolldetails()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChatOptions":{"role":"symbol","title":"SendbirdChatOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendbirdChatOptions"}],"abstract":[{"type":"text","text":"Represents SendbirdChat options."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendbirdChatOptions"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchatoptions"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChatOptions/getConnectionTimeout()":{"role":"symbol","title":"getConnectionTimeout()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConnectionTimeout"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"Gets connection timeout"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/getConnectionTimeout()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getConnectionTimeout"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchatoptions\/getconnectiontimeout()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChatOptions/setWebSocketResponseTimeout(_:)":{"role":"symbol","title":"setWebSocketResponseTimeout(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setWebSocketResponseTimeout"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the websocket response timeout used in sending\/receiving commmands by websocket."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setWebSocketResponseTimeout(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setWebSocketResponseTimeout:"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchatoptions\/setwebsocketresponsetimeout(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SendbirdChatOptions/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirdchatsdk\/sendbirdchatoptions\/init"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SendbirdChatOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SendbirdChatOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SendbirdChatOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/init"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/getConnectionTimeout()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/getFileTransferTimeout()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/getTypingIndicatorThrottle()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/getWebSocketResponseTimeout()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/includePollDetails()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setConnectionTimeout(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setFileTransferTimeout(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setIncludePollDetails(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setMemberInfoInMessage(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setTypingIndicatorThrottle(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/setWebSocketResponseTimeout(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SendbirdChatOptions\/useMemberInfoInMessage()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendbirdChatOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1setConnectionTimeout(_:)\/title","value":"setConnectionTimeout:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1setConnectionTimeout(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setConnectionTimeout:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1setTypingIndicatorThrottle(_:)\/title","value":"setTypingIndicatorThrottle:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1setTypingIndicatorThrottle(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setTypingIndicatorThrottle:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1setIncludePollDetails(_:)\/title","value":"setIncludePollDetails:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1setIncludePollDetails(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setIncludePollDetails:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1getFileTransferTimeout()\/title","value":"getFileTransferTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1getFileTransferTimeout()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getFileTransferTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1setMemberInfoInMessage(_:)\/title","value":"setMemberInfoInMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1setMemberInfoInMessage(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setMemberInfoInMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1getWebSocketResponseTimeout()\/title","value":"getWebSocketResponseTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1getWebSocketResponseTimeout()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getWebSocketResponseTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1getTypingIndicatorThrottle()\/title","value":"getTypingIndicatorThrottle"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1getTypingIndicatorThrottle()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getTypingIndicatorThrottle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1setFileTransferTimeout(_:)\/title","value":"setFileTransferTimeout:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1setFileTransferTimeout(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setFileTransferTimeout:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1useMemberInfoInMessage()\/title","value":"useMemberInfoInMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1useMemberInfoInMessage()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"useMemberInfoInMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1includePollDetails()\/title","value":"includePollDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1includePollDetails()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"includePollDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions\/title","value":"SendbirdChatOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions\/fragments","value":[{"kind":"identifier","text":"SendbirdChatOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1getConnectionTimeout()\/title","value":"getConnectionTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1getConnectionTimeout()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getConnectionTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1setWebSocketResponseTimeout(_:)\/title","value":"setWebSocketResponseTimeout:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SendbirdChatOptions~1setWebSocketResponseTimeout(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setWebSocketResponseTimeout:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}