{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDSessionDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/sessiondelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/sessiondelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents a delegate to receive session relates events"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionDelegate"}],"title":"SessionDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDSessionDelegate","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SessionDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionDidHaveError(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionTokenDidRequire(successCompletion:failCompletion:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionWasClosed()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionWasRefreshed()"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SessionDelegate/sessionWasRefreshed()":{"navigatorTitle":[{"kind":"identifier","text":"sessionWasRefreshed"}],"role":"symbol","title":"sessionWasRefreshed()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionWasRefreshed"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when SDK refreshed the session key."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionWasRefreshed()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/sessiondelegate\/sessionwasrefreshed()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SessionDelegate":{"role":"symbol","title":"SessionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionDelegate"}],"abstract":[{"type":"text","text":"Represents a delegate to receive session relates events"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/sessiondelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SessionDelegate/sessionDidHaveError(_:)":{"navigatorTitle":[{"kind":"identifier","text":"sessionDidHaveError:"}],"role":"symbol","title":"sessionDidHaveError(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionDidHaveError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the SDK run into an error while refreshing the session key."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionDidHaveError(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/sessiondelegate\/sessiondidhaveerror(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SessionDelegate/sessionWasClosed()":{"navigatorTitle":[{"kind":"identifier","text":"sessionWasClosed"}],"role":"symbol","title":"sessionWasClosed()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionWasClosed"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the SDK can’t refresh the session."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionWasClosed()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/sessiondelegate\/sessionwasclosed()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SessionDelegate/sessionTokenDidRequire(successCompletion:failCompletion:)":{"navigatorTitle":[{"kind":"identifier","text":"sessionTokenDidRequireWithSuccessCompletion:failCompletion:"}],"role":"symbol","title":"sessionTokenDidRequire(successCompletion:failCompletion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionTokenDidRequire"},{"kind":"text","text":"("},{"kind":"externalParam","text":"successCompletion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failCompletion"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"App needs to fetch a new token."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionTokenDidRequire(successCompletion:failCompletion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/sessiondelegate\/sessiontokendidrequire(successcompletion:failcompletion:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBDSessionDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDSessionDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDSessionDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionDidHaveError(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionTokenDidRequire(successCompletion:failCompletion:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionWasClosed()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SessionDelegate\/sessionWasRefreshed()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDSessionDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate~1sessionWasRefreshed()\/title","value":"sessionWasRefreshed"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate~1sessionWasRefreshed()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionWasRefreshed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate\/title","value":"SBDSessionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate\/fragments","value":[{"kind":"identifier","text":"SBDSessionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate~1sessionDidHaveError(_:)\/title","value":"sessionDidHaveError:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate~1sessionDidHaveError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionDidHaveError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate~1sessionWasClosed()\/title","value":"sessionWasClosed"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate~1sessionWasClosed()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionWasClosed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate~1sessionTokenDidRequire(successCompletion:failCompletion:)\/title","value":"sessionTokenDidRequireWithSuccessCompletion:failCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1SessionDelegate~1sessionTokenDidRequire(successCompletion:failCompletion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionTokenDidRequireWithSuccessCompletion:failCompletion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}