{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDThreadedMessageListParams) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThreadedMessageListParams"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.181"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/threadedmessagelistparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/threadedmessagelistparams"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object contains set of options to retrieve threaded messages."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThreadedMessageListParams"}],"title":"ThreadedMessageListParams","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDThreadedMessageListParams","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ThreadedMessageListParams"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/customType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/customTypes","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/includeMetaArray","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/includeParentMessageInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/includeReactions","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/isInclusive","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/messageTypeFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/nextResultSize","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/previousResultSize","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/reverse","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/senderUserIDs"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/copy(with:)"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams":{"role":"symbol","title":"ThreadedMessageListParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThreadedMessageListParams"}],"abstract":[{"type":"text","text":"An object contains set of options to retrieve threaded messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThreadedMessageListParams"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams/isInclusive":{"role":"symbol","title":"isInclusive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInclusive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include the messages with the matching timestamp or message ID in the results. Default is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/isInclusive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isInclusive"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/isinclusive"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams/customType":{"role":"symbol","title":"customType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Restricts the search scope only to retrieve the messages with the specified custom message type."},{"type":"text","text":" "},{"type":"text","text":"When the custom type filtering is not needed, the value should be set to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/customType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customType"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/customtype"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Copies this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/copy(with:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams/messageTypeFilter":{"role":"symbol","title":"messageTypeFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageTypeFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageTypeFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageTypeFilter"}],"abstract":[{"type":"text","text":"Restricts the search scope only to retrieve messages with the specified message type. Default is "},{"type":"codeVoice","code":".all"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/messageTypeFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageTypeFilter"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/messagetypefilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams/customTypes":{"role":"symbol","title":"customTypes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Restricts the search scope only to retrieve the messages with the multiple specified custom"},{"type":"text","text":" "},{"type":"text","text":"message types. When the custom type filtering is not needed, the value should be set to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/customTypes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customTypes"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/customtypes"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams/previousResultSize":{"role":"symbol","title":"previousResultSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousResultSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The number of messages to retrieve that were sent before the specified timestamp or message ID. Default is "},{"type":"codeVoice","code":"0"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/previousResultSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"previousResultSize"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/previousresultsize"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/init()"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams/nextResultSize":{"role":"symbol","title":"nextResultSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextResultSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The number of messages to retrieve that were sent after the specified timestamp or message ID. Default is "},{"type":"codeVoice","code":"0"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/nextResultSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nextResultSize"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/nextresultsize"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams/senderUserIDs":{"role":"symbol","title":"senderUserIDs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"senderUserIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Restricts the search scope only to retrieve the messages sent by the users with the specified user"},{"type":"text","text":" "},{"type":"text","text":"IDs. When the user ID filtering is not needed, the value should be set to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/senderUserIDs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"senderUserIDs"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/senderuserids"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams/includeReactions":{"role":"symbol","title":"includeReactions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeReactions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include the reactions to the messages in the results. Default is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/includeReactions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeReactions"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/includereactions"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams/init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:)":{"role":"symbol","title":"init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"previousResultSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nextResultSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isInclusive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reverse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageTypeFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageTypeFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageTypeFilter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"senderUserIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"includeMetaArray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeReactions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeParentMessageInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Parameter constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPreviousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/init(previousresultsize:nextresultsize:isinclusive:reverse:messagetypefilter:customtype:senderuserids:includemetaarray:includereactions:includeparentmessageinfo:customtypes:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams/includeParentMessageInfo":{"role":"symbol","title":"includeParentMessageInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeParentMessageInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include the parent message information to the message in the results. Default is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/includeParentMessageInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeParentMessageInfo"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/includeparentmessageinfo"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams/includeMetaArray":{"role":"symbol","title":"includeMetaArray","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeMetaArray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to include the metaarray information of the messages in the results. Default is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/includeMetaArray","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeMetaArray"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/includemetaarray"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThreadedMessageListParams/reverse":{"role":"symbol","title":"reverse","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reverse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether to sort the retrieved messages in reverse order. If "},{"type":"codeVoice","code":"false"},{"type":"text","text":", the results are in ascending order. Default is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/reverse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reverse"}],"url":"\/documentation\/sendbirdchatsdk\/threadedmessagelistparams\/reverse"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDThreadedMessageListParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDThreadedMessageListParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDThreadedMessageListParams"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/customType","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/customTypes","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/includeMetaArray","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/includeParentMessageInfo","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/includeReactions","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/isInclusive","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/messageTypeFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/nextResultSize","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/previousResultSize","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/reverse","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/senderUserIDs"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThreadedMessageListParams\/init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDThreadedMessageListParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams\/title","value":"SBDThreadedMessageListParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams\/fragments","value":[{"kind":"identifier","text":"SBDThreadedMessageListParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1isInclusive\/title","value":"isInclusive"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1isInclusive\/fragments","value":[{"kind":"identifier","text":"isInclusive"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1customType\/title","value":"customType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1customType\/fragments","value":[{"kind":"identifier","text":"customType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1messageTypeFilter\/title","value":"messageTypeFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1messageTypeFilter\/fragments","value":[{"kind":"identifier","text":"messageTypeFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1customTypes\/title","value":"customTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1customTypes\/fragments","value":[{"kind":"identifier","text":"customTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1previousResultSize\/title","value":"previousResultSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1previousResultSize\/fragments","value":[{"kind":"identifier","text":"previousResultSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1nextResultSize\/title","value":"nextResultSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1nextResultSize\/fragments","value":[{"kind":"identifier","text":"nextResultSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1senderUserIDs\/title","value":"senderUserIDs"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1senderUserIDs\/fragments","value":[{"kind":"identifier","text":"senderUserIDs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1includeReactions\/title","value":"includeReactions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1includeReactions\/fragments","value":[{"kind":"identifier","text":"includeReactions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:)\/title","value":"initWithPreviousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1init(previousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreviousResultSize:nextResultSize:isInclusive:reverse:messageTypeFilter:customType:senderUserIDs:includeMetaArray:includeReactions:includeParentMessageInfo:customTypes:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1includeParentMessageInfo\/title","value":"includeParentMessageInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1includeParentMessageInfo\/fragments","value":[{"kind":"identifier","text":"includeParentMessageInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1includeMetaArray\/title","value":"includeMetaArray"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1includeMetaArray\/fragments","value":[{"kind":"identifier","text":"includeMetaArray"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1reverse\/title","value":"reverse"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThreadedMessageListParams~1reverse\/fragments","value":[{"kind":"identifier","text":"reverse"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}