{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDThumbnailSize) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailSize"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/thumbnailsize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/thumbnailsize"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" class represents the thumbnail size of thumbnail."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailSize"}],"title":"ThumbnailSize","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ThumbnailSize"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/maxSize"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/encode(to:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/make(maxSize:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/make(maxWidth:maxHeight:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/make(thumbnail:)"]}],"references":{"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThumbnailSize/make(maxWidth:maxHeight:)":{"role":"symbol","title":"make(maxWidth:maxHeight:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"make"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize"}],"abstract":[{"type":"text","text":"Makes "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" object with width and height."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/make(maxWidth:maxHeight:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"makeWithMaxWidth:maxHeight:"}],"url":"\/documentation\/sendbirdchatsdk\/thumbnailsize\/make(maxwidth:maxheight:)"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThumbnailSize/maxSize":{"role":"symbol","title":"maxSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"The max size of the thumbnail."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/maxSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxSize"}],"url":"\/documentation\/sendbirdchatsdk\/thumbnailsize\/maxsize"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThumbnailSize/make(thumbnail:)":{"role":"symbol","title":"make(thumbnail:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"make"},{"kind":"text","text":"("},{"kind":"externalParam","text":"thumbnail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Thumbnail","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnail"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize"}],"abstract":[{"type":"text","text":"Makes "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" object with thumbnail"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/make(thumbnail:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"makeWithThumbnail:"}],"url":"\/documentation\/sendbirdchatsdk\/thumbnailsize\/make(thumbnail:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThumbnailSize/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/thumbnailsize\/init(from:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThumbnailSize/make(maxSize:)":{"role":"symbol","title":"make(maxSize:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"make"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize"}],"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" object with "},{"type":"codeVoice","code":"CGSize"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/make(maxSize:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"makeWithMaxCGSize:"}],"url":"\/documentation\/sendbirdchatsdk\/thumbnailsize\/make(maxsize:)"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThumbnailSize":{"role":"symbol","title":"ThumbnailSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailSize"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" class represents the thumbnail size of thumbnail."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThumbnailSize"}],"url":"\/documentation\/sendbirdchatsdk\/thumbnailsize"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThumbnailSize/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Encodes this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/thumbnailsize\/encode(to:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDThumbnailSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDThumbnailSize"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDThumbnailSize"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/maxSize"]},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/make(maxSize:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/make(maxWidth:maxHeight:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/make(thumbnail:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDThumbnailSize"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize~1make(maxWidth:maxHeight:)\/title","value":"makeWithMaxWidth:maxHeight:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize~1make(maxWidth:maxHeight:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"makeWithMaxWidth:maxHeight:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize~1maxSize\/title","value":"maxSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize~1maxSize\/fragments","value":[{"kind":"identifier","text":"maxSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize~1make(thumbnail:)\/title","value":"makeWithThumbnail:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize~1make(thumbnail:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"makeWithThumbnail:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize~1make(maxSize:)\/title","value":"makeWithMaxCGSize:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize~1make(maxSize:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"makeWithMaxCGSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize\/title","value":"SBDThumbnailSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize\/fragments","value":[{"kind":"identifier","text":"SBDThumbnailSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}