{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDTotalScheduledMessageCountParams) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TotalScheduledMessageCountParams"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/totalscheduledmessagecountparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/totalscheduledmessagecountparams"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object that contains a set of options to get scheduled messages count."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TotalScheduledMessageCountParams"}],"title":"TotalScheduledMessageCountParams","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDTotalScheduledMessageCountParams","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"TotalScheduledMessageCountParams"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/init(channelURL:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/channelURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/messageTypeFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/scheduledStatusOptions"]}],"references":{"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/TotalScheduledMessageCountParams":{"role":"symbol","title":"TotalScheduledMessageCountParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TotalScheduledMessageCountParams"}],"abstract":[{"type":"text","text":"An object that contains a set of options to get scheduled messages count."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TotalScheduledMessageCountParams"}],"url":"\/documentation\/sendbirdchatsdk\/totalscheduledmessagecountparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/TotalScheduledMessageCountParams/channelURL":{"role":"symbol","title":"channelURL","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Channel URL which has this message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/channelURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelURL"}],"url":"\/documentation\/sendbirdchatsdk\/totalscheduledmessagecountparams\/channelurl"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/TotalScheduledMessageCountParams/init(channelURL:)":{"role":"symbol","title":"init(channelURL:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes and returns a params object for getting total scheduled message count."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/init(channelURL:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithChannelURL:"}],"url":"\/documentation\/sendbirdchatsdk\/totalscheduledmessagecountparams\/init(channelurl:)"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/TotalScheduledMessageCountParams/scheduledStatusOptions":{"role":"symbol","title":"scheduledStatusOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduledStatusOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledStatusOptions","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledStatusOptions"}],"abstract":[{"type":"text","text":"Restricts the search scope only to retrieve the messages with the specified message status. If not specified, all messages are retrieved."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/scheduledStatusOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scheduledStatusOptions"}],"url":"\/documentation\/sendbirdchatsdk\/totalscheduledmessagecountparams\/scheduledstatusoptions"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/TotalScheduledMessageCountParams/messageTypeFilter":{"role":"symbol","title":"messageTypeFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageTypeFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageTypeFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMessageTypeFilter"}],"abstract":[{"type":"text","text":"Restricts the search scope only to retrieve messages with the specified message type. Default is "},{"type":"codeVoice","code":".all"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/messageTypeFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageTypeFilter"}],"url":"\/documentation\/sendbirdchatsdk\/totalscheduledmessagecountparams\/messagetypefilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDTotalScheduledMessageCountParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDTotalScheduledMessageCountParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDTotalScheduledMessageCountParams"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/channelURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/messageTypeFilter","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/scheduledStatusOptions"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/TotalScheduledMessageCountParams\/init(channelURL:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDTotalScheduledMessageCountParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams\/title","value":"SBDTotalScheduledMessageCountParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams\/fragments","value":[{"kind":"identifier","text":"SBDTotalScheduledMessageCountParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams~1channelURL\/title","value":"channelURL"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams~1channelURL\/fragments","value":[{"kind":"identifier","text":"channelURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams~1init(channelURL:)\/title","value":"initWithChannelURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams~1init(channelURL:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithChannelURL:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams~1scheduledStatusOptions\/title","value":"scheduledStatusOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams~1scheduledStatusOptions\/fragments","value":[{"kind":"identifier","text":"scheduledStatusOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams~1messageTypeFilter\/title","value":"messageTypeFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1TotalScheduledMessageCountParams~1messageTypeFilter\/fragments","value":[{"kind":"identifier","text":"messageTypeFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}