{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDUnreadItemKey) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadItemKey"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemkey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemkey"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/s25ExpressibleByArrayLiteralP","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/s9OptionSetP","doc:\/\/com.sendbird.chat\/SY","doc:\/\/com.sendbird.chat\/s10SetAlgebraP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The bitmask keys of count about unread messages or invitation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadItemKey"}],"title":"UnreadItemKey","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"UnreadItemKey"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/init(from:)-9nfhd","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/init(keys:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/hash","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/rawValue"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/encode(to:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/formIntersection(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/formSymmetricDifference(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/formUnion(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/isEqual(_:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/groupChannelInvitationCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/groupChannelUnreadMentionCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/groupChannelUnreadMessageCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/nonSuperInvitationCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/nonSuperUnreadMentionCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/nonSuperUnreadMessageCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/superInvitationCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/superUnreadMentionCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/superUnreadMessageCount"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/OptionSet-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/RawRepresentable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/SetAlgebra-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/nonSuperUnreadMentionCount":{"role":"symbol","title":"nonSuperUnreadMentionCount","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonSuperUnreadMentionCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"}],"abstract":[{"type":"text","text":"The bitmask key for unread mention count of non super channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/nonSuperUnreadMentionCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nonSuperUnreadMentionCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/nonsuperunreadmentioncount"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/init(rawValue:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRawValue:"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/init(rawvalue:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/nonSuperInvitationCount":{"role":"symbol","title":"nonSuperInvitationCount","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonSuperInvitationCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"}],"abstract":[{"type":"text","text":"The bitmask key for invitation count of non super channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/nonSuperInvitationCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nonSuperInvitationCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/nonsuperinvitationcount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/SetAlgebra-Implementations":{"role":"collectionGroup","title":"SetAlgebra Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/SetAlgebra-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/setalgebra-implementations"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Compares this object with given other object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/isequal(_:)"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/formUnion(_:)":{"role":"symbol","title":"formUnion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formUnion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Union other into this key"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/formUnion(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formUnion:"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/formunion(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/OptionSet-Implementations":{"role":"collectionGroup","title":"OptionSet Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/OptionSet-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/optionset-implementations"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/groupChannelUnreadMentionCount":{"role":"symbol","title":"groupChannelUnreadMentionCount","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelUnreadMentionCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"}],"abstract":[{"type":"text","text":"The bitmask key for unread mention count of group channel(super and non-super)."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/groupChannelUnreadMentionCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelUnreadMentionCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/groupchannelunreadmentioncount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/superInvitationCount":{"role":"symbol","title":"superInvitationCount","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"superInvitationCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"}],"abstract":[{"type":"text","text":"The bitmask key for invitation count of super channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/superInvitationCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"superInvitationCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/superinvitationcount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/nonSuperUnreadMessageCount":{"role":"symbol","title":"nonSuperUnreadMessageCount","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonSuperUnreadMessageCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"}],"abstract":[{"type":"text","text":"The bitmask key for unread message count of non super channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/nonSuperUnreadMessageCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nonSuperUnreadMessageCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/nonsuperunreadmessagecount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/formIntersection(_:)":{"role":"symbol","title":"formIntersection(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formIntersection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Intersects other into this key"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/formIntersection(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formIntersection:"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/formintersection(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/hash":{"role":"symbol","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"hash"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/hash","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/hash"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/groupChannelUnreadMessageCount":{"role":"symbol","title":"groupChannelUnreadMessageCount","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelUnreadMessageCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"}],"abstract":[{"type":"text","text":"The bitmask key for unread message count of group channel(super and non-super)."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/groupChannelUnreadMessageCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelUnreadMessageCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/groupchannelunreadmessagecount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Encodes this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/encode(to:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/formSymmetricDifference(_:)":{"role":"symbol","title":"formSymmetricDifference(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formSymmetricDifference"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Symmetric difference from other"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/formSymmetricDifference(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formSymmetricDifference:"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/formsymmetricdifference(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/init(from:)-9nfhd":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Constructor"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/init(from:)-9nfhd","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/init(from:)-9nfhd"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/superUnreadMentionCount":{"role":"symbol","title":"superUnreadMentionCount","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"superUnreadMentionCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"}],"abstract":[{"type":"text","text":"The bitmask key for unread mention count of non super channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/superUnreadMentionCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"superUnreadMentionCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/superunreadmentioncount"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/rawValue":{"role":"symbol","title":"rawValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The corresponding value of the raw type."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/rawValue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rawValue"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/rawvalue"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/superUnreadMessageCount":{"role":"symbol","title":"superUnreadMessageCount","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"superUnreadMessageCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"}],"abstract":[{"type":"text","text":"The bitmask key for unread message count of super channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/superUnreadMessageCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"superUnreadMessageCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/superunreadmessagecount"},"doc://com.sendbird.chat/s25ExpressibleByArrayLiteralP":{"type":"unresolvable","title":"Swift.ExpressibleByArrayLiteral","identifier":"doc:\/\/com.sendbird.chat\/s25ExpressibleByArrayLiteralP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey":{"role":"symbol","title":"UnreadItemKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadItemKey"}],"abstract":[{"type":"text","text":"The bitmask keys of count about unread messages or invitation."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnreadItemKey"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/groupChannelInvitationCount":{"role":"symbol","title":"groupChannelInvitationCount","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelInvitationCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"}],"abstract":[{"type":"text","text":"The bitmask key for invitation count of group channel(super and non-super)."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/groupChannelInvitationCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelInvitationCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/groupchannelinvitationcount"},"doc://com.sendbird.chat/s9OptionSetP":{"type":"unresolvable","title":"Swift.OptionSet","identifier":"doc:\/\/com.sendbird.chat\/s9OptionSetP"},"doc://com.sendbird.chat/s10SetAlgebraP":{"type":"unresolvable","title":"Swift.SetAlgebra","identifier":"doc:\/\/com.sendbird.chat\/s10SetAlgebraP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/init(keys:)":{"role":"symbol","title":"init(keys:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Parameter constructor"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/init(keys:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithKeys:"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/init(keys:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDUnreadItemKey"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUnreadItemKey"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDUnreadItemKey"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/groupChannelInvitationCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/groupChannelUnreadMentionCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/groupChannelUnreadMessageCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/hash","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/nonSuperInvitationCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/nonSuperUnreadMentionCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/nonSuperUnreadMessageCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/rawValue","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/superInvitationCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/superUnreadMentionCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/superUnreadMessageCount"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/formIntersection(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/formSymmetricDifference(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/formUnion(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/init(keys:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/init(rawValue:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/isEqual(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDUnreadItemKey"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1nonSuperUnreadMentionCount\/title","value":"nonSuperUnreadMentionCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1nonSuperUnreadMentionCount\/fragments","value":[{"kind":"identifier","text":"nonSuperUnreadMentionCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1init(rawValue:)\/title","value":"initWithRawValue:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1init(rawValue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRawValue:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1nonSuperInvitationCount\/title","value":"nonSuperInvitationCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1nonSuperInvitationCount\/fragments","value":[{"kind":"identifier","text":"nonSuperInvitationCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1formUnion(_:)\/title","value":"formUnion:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1formUnion(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formUnion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1groupChannelUnreadMentionCount\/title","value":"groupChannelUnreadMentionCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1groupChannelUnreadMentionCount\/fragments","value":[{"kind":"identifier","text":"groupChannelUnreadMentionCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1superInvitationCount\/title","value":"superInvitationCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1superInvitationCount\/fragments","value":[{"kind":"identifier","text":"superInvitationCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1nonSuperUnreadMessageCount\/title","value":"nonSuperUnreadMessageCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1nonSuperUnreadMessageCount\/fragments","value":[{"kind":"identifier","text":"nonSuperUnreadMessageCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1formIntersection(_:)\/title","value":"formIntersection:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1formIntersection(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formIntersection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1groupChannelUnreadMessageCount\/title","value":"groupChannelUnreadMessageCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1groupChannelUnreadMessageCount\/fragments","value":[{"kind":"identifier","text":"groupChannelUnreadMessageCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1formSymmetricDifference(_:)\/title","value":"formSymmetricDifference:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1formSymmetricDifference(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formSymmetricDifference:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1superUnreadMentionCount\/title","value":"superUnreadMentionCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1superUnreadMentionCount\/fragments","value":[{"kind":"identifier","text":"superUnreadMentionCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1rawValue\/title","value":"rawValue"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1rawValue\/fragments","value":[{"kind":"identifier","text":"rawValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1superUnreadMessageCount\/title","value":"superUnreadMessageCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1superUnreadMessageCount\/fragments","value":[{"kind":"identifier","text":"superUnreadMessageCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey\/title","value":"SBDUnreadItemKey"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey\/fragments","value":[{"kind":"identifier","text":"SBDUnreadItemKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1groupChannelInvitationCount\/title","value":"groupChannelInvitationCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1groupChannelInvitationCount\/fragments","value":[{"kind":"identifier","text":"groupChannelInvitationCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1init(keys:)\/title","value":"initWithKeys:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1init(keys:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKeys:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}