{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDUnreadItemCount) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadItemCount"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemcount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemcount"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UnreadItemCount"},{"type":"text","text":" class represents counts of messages. The instance of this class is returned"},{"type":"text","text":" "},{"type":"text","text":"from completion handler in "},{"type":"codeVoice","code":"getUnreadItemCountWithKey:completionHandler:]"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadItemCount"}],"title":"UnreadItemCount","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemCount","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"UnreadItemCount"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/groupChannelInvitationCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/groupChannelUnreadMentionCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/groupChannelUnreadMessageCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/nonSuperInvitationCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/nonSuperUnreadMentionCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/nonSuperUnreadMessageCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/superInvitationCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/superUnreadMentionCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/superUnreadMessageCount"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/has(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/unsignedIntegerForKey(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/Mappable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/nonSuperUnreadMessageCount":{"role":"symbol","title":"nonSuperUnreadMessageCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonSuperUnreadMessageCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The count of unread message in all of non super group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/nonSuperUnreadMessageCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nonSuperUnreadMessageCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/nonsuperunreadmessagecount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/superUnreadMessageCount":{"role":"symbol","title":"superUnreadMessageCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"superUnreadMessageCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The count of unread message in all of non super group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/superUnreadMessageCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"superUnreadMessageCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/superunreadmessagecount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/Mappable-Implementations":{"role":"collectionGroup","title":"Mappable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/Mappable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/mappable-implementations"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/nonSuperInvitationCount":{"role":"symbol","title":"nonSuperInvitationCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonSuperInvitationCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The count of unread message in all of non super group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/nonSuperInvitationCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nonSuperInvitationCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/nonsuperinvitationcount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Default constructor"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/init()"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Mappable":{"role":"symbol","title":"Mappable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mappable"}],"abstract":[{"type":"text","text":"Mappable protocol to initialize sendbird object from a given dictionary."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Mappable"}],"url":"\/documentation\/sendbirdchatsdk\/mappable"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/init(from:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/groupChannelUnreadMessageCount":{"role":"symbol","title":"groupChannelUnreadMessageCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelUnreadMessageCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The count of unread message in all of group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/groupChannelUnreadMessageCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelUnreadMessageCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/groupchannelunreadmessagecount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount":{"role":"symbol","title":"UnreadItemCount","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadItemCount"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UnreadItemCount"},{"type":"text","text":" class represents counts of messages. The instance of this class is returned"},{"type":"text","text":" "},{"type":"text","text":"from completion handler in "},{"type":"codeVoice","code":"getUnreadItemCountWithKey:completionHandler:]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnreadItemCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/superInvitationCount":{"role":"symbol","title":"superInvitationCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"superInvitationCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The count of unread message in all of non super group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/superInvitationCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"superInvitationCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/superinvitationcount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/groupChannelInvitationCount":{"role":"symbol","title":"groupChannelInvitationCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelInvitationCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The count of unread message in all of group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/groupChannelInvitationCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelInvitationCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/groupchannelinvitationcount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/superUnreadMentionCount":{"role":"symbol","title":"superUnreadMentionCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"superUnreadMentionCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The count of unread mention in all of non super group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/superUnreadMentionCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"superUnreadMentionCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/superunreadmentioncount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/groupChannelUnreadMentionCount":{"role":"symbol","title":"groupChannelUnreadMentionCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelUnreadMentionCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The count of unread mention in all of group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/groupChannelUnreadMentionCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelUnreadMentionCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/groupchannelunreadmentioncount"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/nonSuperUnreadMentionCount":{"role":"symbol","title":"nonSuperUnreadMentionCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonSuperUnreadMentionCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The count of unread mention in all of non super group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/nonSuperUnreadMentionCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nonSuperUnreadMentionCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/nonsuperunreadmentioncount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/unsignedIntegerForKey(_:)":{"role":"symbol","title":"unsignedIntegerForKey(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsignedIntegerForKey"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Returns count for a given key."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/unsignedIntegerForKey(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unsignedIntegerForKey:"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/unsignedintegerforkey(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemCount/has(_:)":{"role":"symbol","title":"has(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"has"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether a count of a given key is present, not NSNotFound."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/has(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"has:"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemcount\/has(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDUnreadItemCount"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUnreadItemCount"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDUnreadItemCount"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/groupChannelInvitationCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/groupChannelUnreadMentionCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/groupChannelUnreadMessageCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/nonSuperInvitationCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/nonSuperUnreadMentionCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/nonSuperUnreadMessageCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/superInvitationCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/superUnreadMentionCount","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/superUnreadMessageCount"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/has(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/unsignedIntegerForKey(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemCount\/Mappable-Implementations"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDUnreadItemCount"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1nonSuperUnreadMessageCount\/title","value":"nonSuperUnreadMessageCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1nonSuperUnreadMessageCount\/fragments","value":[{"kind":"identifier","text":"nonSuperUnreadMessageCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1superUnreadMessageCount\/title","value":"superUnreadMessageCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1superUnreadMessageCount\/fragments","value":[{"kind":"identifier","text":"superUnreadMessageCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1nonSuperInvitationCount\/title","value":"nonSuperInvitationCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1nonSuperInvitationCount\/fragments","value":[{"kind":"identifier","text":"nonSuperInvitationCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/title","value":"Mappable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/fragments","value":[{"kind":"identifier","text":"Mappable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1groupChannelUnreadMessageCount\/title","value":"groupChannelUnreadMessageCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1groupChannelUnreadMessageCount\/fragments","value":[{"kind":"identifier","text":"groupChannelUnreadMessageCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount\/title","value":"SBDUnreadItemCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount\/fragments","value":[{"kind":"identifier","text":"SBDUnreadItemCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1superInvitationCount\/title","value":"superInvitationCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1superInvitationCount\/fragments","value":[{"kind":"identifier","text":"superInvitationCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1groupChannelInvitationCount\/title","value":"groupChannelInvitationCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1groupChannelInvitationCount\/fragments","value":[{"kind":"identifier","text":"groupChannelInvitationCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1superUnreadMentionCount\/title","value":"superUnreadMentionCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1superUnreadMentionCount\/fragments","value":[{"kind":"identifier","text":"superUnreadMentionCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1groupChannelUnreadMentionCount\/title","value":"groupChannelUnreadMentionCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1groupChannelUnreadMentionCount\/fragments","value":[{"kind":"identifier","text":"groupChannelUnreadMentionCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1nonSuperUnreadMentionCount\/title","value":"nonSuperUnreadMentionCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1nonSuperUnreadMentionCount\/fragments","value":[{"kind":"identifier","text":"nonSuperUnreadMentionCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1unsignedIntegerForKey(_:)\/title","value":"unsignedIntegerForKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1unsignedIntegerForKey(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unsignedIntegerForKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1has(_:)\/title","value":"has:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemCount~1has(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"has:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}