{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDUnreadChannelFilter) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadChannelFilter"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.113"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/unreadchannelfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/unreadchannelfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The enum type to filter my group channels."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadChannelFilter"}],"title":"UnreadChannelFilter","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDUnreadChannelFilter","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"UnreadChannelFilter"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/all","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/unreadMessage"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadChannelFilter/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/unreadchannelfilter\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadChannelFilter/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/unreadchannelfilter\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadChannelFilter/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/unreadchannelfilter\/decodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadChannelFilter":{"role":"symbol","title":"UnreadChannelFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadChannelFilter"}],"abstract":[{"type":"text","text":"The enum type to filter my group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnreadChannelFilter"}],"url":"\/documentation\/sendbirdchatsdk\/unreadchannelfilter"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadChannelFilter/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/unreadchannelfilter\/encodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadChannelFilter/unreadMessage":{"role":"symbol","title":"UnreadChannelFilter.unreadMessage","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadMessage"}],"abstract":[{"type":"text","text":"Shows my group channels that have unread messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/unreadMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUnreadChannelFilterUnreadMessage"}],"url":"\/documentation\/sendbirdchatsdk\/unreadchannelfilter\/unreadmessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadChannelFilter/all":{"role":"symbol","title":"UnreadChannelFilter.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[{"type":"text","text":"Shows all my group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUnreadChannelFilterAll"}],"url":"\/documentation\/sendbirdchatsdk\/unreadchannelfilter\/all"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDUnreadChannelFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUnreadChannelFilter"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDUnreadChannelFilter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/all","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadChannelFilter\/unreadMessage"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDUnreadChannelFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadChannelFilter\/title","value":"SBDUnreadChannelFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadChannelFilter\/fragments","value":[{"kind":"identifier","text":"SBDUnreadChannelFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadChannelFilter~1unreadMessage\/title","value":"SBDUnreadChannelFilterUnreadMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadChannelFilter~1unreadMessage\/fragments","value":[{"kind":"identifier","text":"SBDUnreadChannelFilterUnreadMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadChannelFilter~1all\/title","value":"SBDUnreadChannelFilterAll"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadChannelFilter~1all\/fragments","value":[{"kind":"identifier","text":"SBDUnreadChannelFilterAll"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}