{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDUserEventDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserEventDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/usereventdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/usereventdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserEventDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents a delegate to receive user relates events"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserEventDelegate"}],"title":"UserEventDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDUserEventDelegate","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"UserEventDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserEventDelegate\/didDiscoverFriends(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserEventDelegate\/didUpdateTotalUnreadMessageCount(_:totalCountByCustomType:)"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserEventDelegate":{"role":"symbol","title":"UserEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserEventDelegate"}],"abstract":[{"type":"text","text":"Represents a delegate to receive user relates events"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserEventDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserEventDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/usereventdelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserEventDelegate/didDiscoverFriends(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didDiscoverFriends:"}],"role":"symbol","title":"didDiscoverFriends(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDiscoverFriends"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Invoked when list of users has been discovered"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserEventDelegate\/didDiscoverFriends(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/usereventdelegate\/diddiscoverfriends(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserEventDelegate/didUpdateTotalUnreadMessageCount(_:totalCountByCustomType:)":{"navigatorTitle":[{"kind":"identifier","text":"didUpdateTotalUnreadMessageCount:totalCountByCustomType:"}],"role":"symbol","title":"didUpdateTotalUnreadMessageCount(_:totalCountByCustomType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateTotalUnreadMessageCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalCountByCustomType"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Invoked when total unread message count has been updated"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserEventDelegate\/didUpdateTotalUnreadMessageCount(_:totalCountByCustomType:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/usereventdelegate\/didupdatetotalunreadmessagecount(_:totalcountbycustomtype:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBDUserEventDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUserEventDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDUserEventDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserEventDelegate\/didDiscoverFriends(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserEventDelegate\/didUpdateTotalUnreadMessageCount(_:totalCountByCustomType:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDUserEventDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserEventDelegate\/title","value":"SBDUserEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserEventDelegate\/fragments","value":[{"kind":"identifier","text":"SBDUserEventDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserEventDelegate~1didDiscoverFriends(_:)\/title","value":"didDiscoverFriends:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserEventDelegate~1didDiscoverFriends(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didDiscoverFriends:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserEventDelegate~1didUpdateTotalUnreadMessageCount(_:totalCountByCustomType:)\/title","value":"didUpdateTotalUnreadMessageCount:totalCountByCustomType:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserEventDelegate~1didUpdateTotalUnreadMessageCount(_:totalCountByCustomType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateTotalUnreadMessageCount:totalCountByCustomType:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}