{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDUserMessageCreateParams) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMessageCreateParams"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.90"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/usermessagecreateparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/usermessagecreateparams"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageCreateParams"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object contains a set of options to create "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMessageCreateParams"}],"title":"UserMessageCreateParams","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessageCreateParams","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"UserMessageCreateParams"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/init(from:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/init(message:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/mentionedMessageTemplate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/message","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/pollID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/translationTargetLanguages"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/encode(to:)"]}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageCreateParams/pollID":{"role":"symbol","title":"pollID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pollID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Links a poll with message, to unlink set it -1"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/pollID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pollID"}],"url":"\/documentation\/sendbirdchatsdk\/usermessagecreateparams\/pollid"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageCreateParams/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Copies this object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/sendbirdchatsdk\/usermessagecreateparams\/copy(with:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageCreateParams/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/usermessagecreateparams\/init(from:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageCreateParams/mentionedMessageTemplate":{"role":"symbol","title":"mentionedMessageTemplate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionedMessageTemplate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The template for the message that has the mentioned users."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/mentionedMessageTemplate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mentionedMessageTemplate"}],"url":"\/documentation\/sendbirdchatsdk\/usermessagecreateparams\/mentionedmessagetemplate"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageCreateParams/init(message:)":{"role":"symbol","title":"init(message:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Default construrctor"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/init(message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMessage:"}],"url":"\/documentation\/sendbirdchatsdk\/usermessagecreateparams\/init(message:)"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessageCreateParams":{"role":"symbol","title":"BaseMessageCreateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessageCreateParams"}],"abstract":[{"type":"text","text":"Represents the base class which has parameters to create a channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageCreateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessageCreateParams"}],"url":"\/documentation\/sendbirdchatsdk\/basemessagecreateparams"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageCreateParams/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Encodes this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/usermessagecreateparams\/encode(to:)"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageCreateParams/message":{"role":"symbol","title":"message","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Message text."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/message","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"message"}],"url":"\/documentation\/sendbirdchatsdk\/usermessagecreateparams\/message"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageCreateParams/translationTargetLanguages":{"role":"symbol","title":"translationTargetLanguages","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"translationTargetLanguages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The target languages that the message will be translated into."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/translationTargetLanguages","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"translationTargetLanguages"}],"url":"\/documentation\/sendbirdchatsdk\/usermessagecreateparams\/translationtargetlanguages"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageCreateParams":{"role":"symbol","title":"UserMessageCreateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMessageCreateParams"}],"abstract":[{"type":"text","text":"An object contains a set of options to create "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserMessageCreateParams"}],"url":"\/documentation\/sendbirdchatsdk\/usermessagecreateparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDUserMessageCreateParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUserMessageCreateParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDUserMessageCreateParams"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/mentionedMessageTemplate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/message","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/pollID","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/translationTargetLanguages"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageCreateParams\/init(message:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDUserMessageCreateParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessageCreateParams","text":"SBDBaseMessageCreateParams"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams~1pollID\/title","value":"pollID"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams~1pollID\/fragments","value":[{"kind":"identifier","text":"pollID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams~1mentionedMessageTemplate\/title","value":"mentionedMessageTemplate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams~1mentionedMessageTemplate\/fragments","value":[{"kind":"identifier","text":"mentionedMessageTemplate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams~1init(message:)\/title","value":"initWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams~1init(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessageCreateParams\/title","value":"SBDBaseMessageCreateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessageCreateParams\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessageCreateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams~1message\/title","value":"message"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams~1message\/fragments","value":[{"kind":"identifier","text":"message"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams~1translationTargetLanguages\/title","value":"translationTargetLanguages"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams~1translationTargetLanguages\/fragments","value":[{"kind":"identifier","text":"translationTargetLanguages"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams\/title","value":"SBDUserMessageCreateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageCreateParams\/fragments","value":[{"kind":"identifier","text":"SBDUserMessageCreateParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}