{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDUserConnectionStatus) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserConnectionStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/userconnectionstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/userconnectionstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"User connection statuses for "},{"type":"codeVoice","code":"User"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserConnectionStatus"}],"title":"UserConnectionStatus","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDUserConnectionStatus","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"UserConnectionStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/nonAvailable","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/offline","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/online"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/Decodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/Encodable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserConnectionStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/userconnectionstatus\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserConnectionStatus/nonAvailable":{"role":"symbol","title":"UserConnectionStatus.nonAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonAvailable"}],"abstract":[{"type":"text","text":"For unavailable user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/nonAvailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUserConnectionStatusNonAvailable"}],"url":"\/documentation\/sendbirdchatsdk\/userconnectionstatus\/nonavailable"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserConnectionStatus":{"role":"symbol","title":"UserConnectionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserConnectionStatus"}],"abstract":[{"type":"text","text":"User connection statuses for "},{"type":"codeVoice","code":"User"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserConnectionStatus"}],"url":"\/documentation\/sendbirdchatsdk\/userconnectionstatus"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserConnectionStatus/offline":{"role":"symbol","title":"UserConnectionStatus.offline","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"offline"}],"abstract":[{"type":"text","text":"For off-line user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/offline","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUserConnectionStatusOffline"}],"url":"\/documentation\/sendbirdchatsdk\/userconnectionstatus\/offline"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserConnectionStatus/Encodable-Implementations":{"role":"collectionGroup","title":"Encodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/Encodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/userconnectionstatus\/encodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserConnectionStatus/Decodable-Implementations":{"role":"collectionGroup","title":"Decodable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/Decodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/userconnectionstatus\/decodable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserConnectionStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/userconnectionstatus\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserConnectionStatus/online":{"role":"symbol","title":"UserConnectionStatus.online","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"online"}],"abstract":[{"type":"text","text":"For on-line user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/online","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUserConnectionStatusOnline"}],"url":"\/documentation\/sendbirdchatsdk\/userconnectionstatus\/online"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDUserConnectionStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUserConnectionStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDUserConnectionStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/nonAvailable","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/offline","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/online"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDUserConnectionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus~1nonAvailable\/title","value":"SBDUserConnectionStatusNonAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus~1nonAvailable\/fragments","value":[{"kind":"identifier","text":"SBDUserConnectionStatusNonAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus\/title","value":"SBDUserConnectionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus\/fragments","value":[{"kind":"identifier","text":"SBDUserConnectionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus~1offline\/title","value":"SBDUserConnectionStatusOffline"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus~1offline\/fragments","value":[{"kind":"identifier","text":"SBDUserConnectionStatusOffline"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus~1online\/title","value":"SBDUserConnectionStatusOnline"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus~1online\/fragments","value":[{"kind":"identifier","text":"SBDUserConnectionStatusOnline"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}