{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDUserListQuery) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserListQuery"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/userlistquery"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/userlistquery"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ApplicationUserListQuery","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BannedUserListQuery","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BlockedUserListQuery","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FriendListQuery","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQuery","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OperatorListQuery","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQuery"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQuery","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQuery\/hasNext","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQuery\/isLoading"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQuery\/loadNextPage(completionHandler:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserListQuery"}],"title":"UserListQuery","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDUserListQuery","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"UserListQuery"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MutedUserListQuery":{"role":"symbol","title":"MutedUserListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MutedUserListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MutedUserListQuery"},{"type":"text","text":" class is a query class for getting the list of muted users in"},{"type":"text","text":" "},{"type":"text","text":"a specific channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MutedUserListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/muteduserlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BlockedUserListQuery":{"role":"symbol","title":"BlockedUserListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockedUserListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BlockedUserListQuery"},{"type":"text","text":" class is a query class for getting the list of blocked users"},{"type":"text","text":" "},{"type":"text","text":"by the current user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BlockedUserListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BlockedUserListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/blockeduserlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ApplicationUserListQuery":{"role":"symbol","title":"ApplicationUserListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplicationUserListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ApplicationUserListQuery"},{"type":"text","text":" class is a query class for getting the list of all"},{"type":"text","text":" "},{"type":"text","text":"users of the current application."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ApplicationUserListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApplicationUserListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/applicationuserlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQuery":{"role":"symbol","title":"UserListQuery","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserListQuery"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/userlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BannedUserListQuery":{"role":"symbol","title":"BannedUserListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannedUserListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BannedUserListQuery"},{"type":"text","text":" class is a query class for getting the list of banned users in"},{"type":"text","text":" "},{"type":"text","text":"a specific channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BannedUserListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BannedUserListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/banneduserlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OperatorListQuery":{"role":"symbol","title":"OperatorListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OperatorListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OperatorListQuery"},{"type":"text","text":" class is a query class for getting the list of operators in channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OperatorListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OperatorListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/operatorlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQuery/isLoading":{"navigatorTitle":[{"kind":"identifier","text":"isLoading"}],"role":"symbol","title":"isLoading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQuery\/isLoading","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/userlistquery\/isloading"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQuery/hasNext":{"navigatorTitle":[{"kind":"identifier","text":"hasNext"}],"role":"symbol","title":"hasNext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasNext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQuery\/hasNext","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/userlistquery\/hasnext"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ParticipantListQuery":{"role":"symbol","title":"ParticipantListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ParticipantListQuery"},{"type":"text","text":" class is a query class for getting the list of participants in"},{"type":"text","text":" "},{"type":"text","text":"an open channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ParticipantListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ParticipantListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/participantlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FriendListQuery":{"role":"symbol","title":"FriendListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FriendListQuery"}],"abstract":[{"type":"text","text":"A object to retrieve friend list"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FriendListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FriendListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/friendlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQuery/loadNextPage(completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"loadNextPageWithCompletionHandler:"}],"role":"symbol","title":"loadNextPage(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadNextPage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserListHandler","preciseIdentifier":"s:15SendbirdChatSDK15UserListHandlera"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQuery\/loadNextPage(completionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/userlistquery\/loadnextpage(completionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBDUserListQuery"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUserListQuery"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDUserListQuery"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQuery\/hasNext","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQuery\/isLoading"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQuery\/loadNextPage(completionHandler:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDUserListQuery"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MutedUserListQuery\/title","value":"SBDMutedUserListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MutedUserListQuery\/fragments","value":[{"kind":"identifier","text":"SBDMutedUserListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BlockedUserListQuery\/title","value":"SBDBlockedUserListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BlockedUserListQuery\/fragments","value":[{"kind":"identifier","text":"SBDBlockedUserListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ApplicationUserListQuery\/title","value":"SBDApplicationUserListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ApplicationUserListQuery\/fragments","value":[{"kind":"identifier","text":"SBDApplicationUserListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQuery\/title","value":"SBDUserListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQuery\/fragments","value":[{"kind":"identifier","text":"SBDUserListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BannedUserListQuery\/title","value":"SBDBannedUserListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BannedUserListQuery\/fragments","value":[{"kind":"identifier","text":"SBDBannedUserListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OperatorListQuery\/title","value":"SBDOperatorListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OperatorListQuery\/fragments","value":[{"kind":"identifier","text":"SBDOperatorListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQuery~1isLoading\/title","value":"isLoading"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQuery~1isLoading\/fragments","value":[{"kind":"identifier","text":"isLoading"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQuery~1hasNext\/title","value":"hasNext"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQuery~1hasNext\/fragments","value":[{"kind":"identifier","text":"hasNext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQuery\/title","value":"SBDParticipantListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ParticipantListQuery\/fragments","value":[{"kind":"identifier","text":"SBDParticipantListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FriendListQuery\/title","value":"SBDFriendListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FriendListQuery\/fragments","value":[{"kind":"identifier","text":"SBDFriendListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQuery~1loadNextPage(completionHandler:)\/title","value":"loadNextPageWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQuery~1loadNextPage(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadNextPageWithCompletionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}