{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDUser) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"User"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/user"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/user"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictedUser","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Sender"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Serializable","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/Se","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/s12IdentifiableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"User"},{"type":"text","text":" class represents a user. The user is identified by the "},{"type":"codeVoice","code":"userID"},{"type":"text","text":", so the "},{"type":"codeVoice","code":"userID"},{"type":"text","text":" has"},{"type":"text","text":" "},{"type":"text","text":"to be unique. The "},{"type":"codeVoice","code":"userID"},{"type":"text","text":", "},{"type":"codeVoice","code":"nickname"},{"type":"text","text":" and "},{"type":"codeVoice","code":"profileURL"},{"type":"text","text":" are valid in every "},{"type":"codeVoice","code":"User"},{"type":"text","text":" "},{"type":"text","text":"instance, however the "},{"type":"codeVoice","code":"connectionStatus"},{"type":"text","text":" and "},{"type":"codeVoice","code":"lastSeenAt"},{"type":"text","text":" is valid in "},{"type":"codeVoice","code":"User"},{"type":"text","text":" instance"},{"type":"text","text":" "},{"type":"text","text":"from "},{"type":"codeVoice","code":"UserListQuery"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"User"}],"title":"User","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDUser","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"User"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/connectionStatus","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/friendDiscoveryKey","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/friendName","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/id-9titu","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/isActive","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/lastSeenAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/metaData","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/nickname","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/originalProfileURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/plainProfileImageURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/preferredLanguages","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/profileURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/userID"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/createMetaData(_:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/deleteAllMetaData(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/deleteMetaData(key:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/encode(to:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/updateMetaData(_:completionHandler:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/Identifiable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/Mappable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/NSCopying-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/Serializable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/connectionStatus":{"role":"symbol","title":"connectionStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserConnectionStatus","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDUserConnectionStatus"}],"abstract":[{"type":"text","text":"User connection status. This is defined in "},{"type":"codeVoice","code":"UserConnectionStatus"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/connectionStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"connectionStatus"}],"url":"\/documentation\/sendbirdchatsdk\/user\/connectionstatus"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/deleteMetaData(key:completionHandler:)":{"role":"symbol","title":"deleteMetaData(key:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteMetaData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Deletes meta data with key for the current user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/deleteMetaData(key:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteMetaDataWithKey:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/user\/deletemetadata(key:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/metaData":{"role":"symbol","title":"metaData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Meta data."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/metaData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metaData"}],"url":"\/documentation\/sendbirdchatsdk\/user\/metadata"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/friendName":{"role":"symbol","title":"friendName","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"User name for friend"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/friendName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"friendName"}],"url":"\/documentation\/sendbirdchatsdk\/user\/friendname"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Sender":{"role":"symbol","title":"Sender","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Sender"}],"abstract":[{"type":"text","text":"Represents a user that typically binds with message"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Sender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Sender"}],"url":"\/documentation\/sendbirdchatsdk\/sender"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Default constructor."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/user\/init(from:)"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/friendDiscoveryKey":{"role":"symbol","title":"friendDiscoveryKey","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendDiscoveryKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Discovery key for friend"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/friendDiscoveryKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"friendDiscoveryKey"}],"url":"\/documentation\/sendbirdchatsdk\/user\/frienddiscoverykey"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Member":{"role":"symbol","title":"Member","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Member"}],"abstract":[{"type":"text","text":"Represents a member in "},{"type":"codeVoice","code":"GroupChannel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Member","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Member"}],"url":"\/documentation\/sendbirdchatsdk\/member"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/Serializable-Implementations":{"role":"collectionGroup","title":"Serializable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/Serializable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/user\/serializable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/userID":{"role":"symbol","title":"userID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"User ID. This has to be unique."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/userID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userID"}],"url":"\/documentation\/sendbirdchatsdk\/user\/userid"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/id-9titu":{"role":"symbol","title":"id","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Identifier for the user conforming to "},{"type":"codeVoice","code":"Identifiable"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/id-9titu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"id"}],"url":"\/documentation\/sendbirdchatsdk\/user\/id-9titu"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Serializable":{"role":"symbol","title":"Serializable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Serializable"}],"abstract":[{"type":"text","text":"Protocol to provide serialization"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Serializable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Serializable"}],"url":"\/documentation\/sendbirdchatsdk\/serializable"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Compares this object with given other object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/sendbirdchatsdk\/user\/isequal(_:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/Identifiable-Implementations":{"role":"collectionGroup","title":"Identifiable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/Identifiable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/user\/identifiable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/createMetaData(_:completionHandler:)":{"role":"symbol","title":"createMetaData(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMetaData"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MetaDataHandler","preciseIdentifier":"s:15SendbirdChatSDK15MetaDataHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Creates the meta data for the current user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/createMetaData(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createMetaData:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/user\/createmetadata(_:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/originalProfileURL":{"role":"symbol","title":"originalProfileURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalProfileURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Original profile image url."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/originalProfileURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"originalProfileURL"}],"url":"\/documentation\/sendbirdchatsdk\/user\/originalprofileurl"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/lastSeenAt":{"role":"symbol","title":"lastSeenAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastSeenAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The lastest time when the user became offline."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/lastSeenAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lastSeenAt"}],"url":"\/documentation\/sendbirdchatsdk\/user\/lastseenat"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Encodes this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/user\/encode(to:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/NSCopying-Implementations":{"role":"collectionGroup","title":"NSCopying Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/NSCopying-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/user\/nscopying-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/profileURL":{"role":"symbol","title":"profileURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"profileURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Profile image url."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/profileURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"profileURL"}],"url":"\/documentation\/sendbirdchatsdk\/user\/profileurl"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/s12IdentifiableP":{"type":"unresolvable","title":"Swift.Identifiable","identifier":"doc:\/\/com.sendbird.chat\/s12IdentifiableP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/isActive":{"role":"symbol","title":"isActive","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Represents the user is activated. This property is changed by the "},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.sendbird.com\/platform#user_3_update_a_user"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/isActive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isActive"}],"url":"\/documentation\/sendbirdchatsdk\/user\/isactive"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/nickname":{"role":"symbol","title":"nickname","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nickname"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"User nickname."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/nickname","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nickname"}],"url":"\/documentation\/sendbirdchatsdk\/user\/nickname"},"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.sendbird.chat\/Se"},"https://docs.sendbird.com/platform#user_3_update_a_user":{"title":"Platform API","titleInlineContent":[{"type":"text","text":"Platform API"}],"type":"link","identifier":"https:\/\/docs.sendbird.com\/platform#user_3_update_a_user","url":"https:\/\/docs.sendbird.com\/platform#user_3_update_a_user"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/preferredLanguages":{"role":"symbol","title":"preferredLanguages","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredLanguages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"User’s preferred language. Used for translating messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/preferredLanguages","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"preferredLanguages"}],"url":"\/documentation\/sendbirdchatsdk\/user\/preferredlanguages"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/deleteAllMetaData(completionHandler:)":{"role":"symbol","title":"deleteAllMetaData(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteAllMetaData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Deletes all meta data for the current user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/deleteAllMetaData(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteAllMetaDataWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/user\/deleteallmetadata(completionhandler:)"},"doc://com.sendbird.chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.sendbird.chat\/objc(cs)NSObject"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/Mappable-Implementations":{"role":"collectionGroup","title":"Mappable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/Mappable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/user\/mappable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Mappable":{"role":"symbol","title":"Mappable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mappable"}],"abstract":[{"type":"text","text":"Mappable protocol to initialize sendbird object from a given dictionary."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Mappable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Mappable"}],"url":"\/documentation\/sendbirdchatsdk\/mappable"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/RestrictedUser":{"role":"symbol","title":"RestrictedUser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictedUser"}],"abstract":[{"type":"text","text":"Represents a user who has been restricted in a channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/RestrictedUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RestrictedUser"}],"url":"\/documentation\/sendbirdchatsdk\/restricteduser"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/plainProfileImageURL":{"role":"symbol","title":"plainProfileImageURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"plainProfileImageURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The profile image URL without the "},{"type":"codeVoice","code":"ekey"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/plainProfileImageURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"plainProfileImageURL"}],"url":"\/documentation\/sendbirdchatsdk\/user\/plainprofileimageurl"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User/updateMetaData(_:completionHandler:)":{"role":"symbol","title":"updateMetaData(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateMetaData"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MetaDataHandler","preciseIdentifier":"s:15SendbirdChatSDK15MetaDataHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Updates the meta data for the current user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/updateMetaData(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateMetaData:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/user\/updatemetadata(_:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/User":{"role":"symbol","title":"User","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"User"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"User"},{"type":"text","text":" class represents a user. The user is identified by the "},{"type":"codeVoice","code":"userID"},{"type":"text","text":", so the "},{"type":"codeVoice","code":"userID"},{"type":"text","text":" has"},{"type":"text","text":" "},{"type":"text","text":"to be unique. The "},{"type":"codeVoice","code":"userID"},{"type":"text","text":", "},{"type":"codeVoice","code":"nickname"},{"type":"text","text":" and "},{"type":"codeVoice","code":"profileURL"},{"type":"text","text":" are valid in every "},{"type":"codeVoice","code":"User"},{"type":"text","text":" "},{"type":"text","text":"instance, however the "},{"type":"codeVoice","code":"connectionStatus"},{"type":"text","text":" and "},{"type":"codeVoice","code":"lastSeenAt"},{"type":"text","text":" is valid in "},{"type":"codeVoice","code":"User"},{"type":"text","text":" instance"},{"type":"text","text":" "},{"type":"text","text":"from "},{"type":"codeVoice","code":"UserListQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"User"}],"url":"\/documentation\/sendbirdchatsdk\/user"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDUser"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUser"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDUser"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/connectionStatus","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/friendDiscoveryKey","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/friendName","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/id-9titu","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/isActive","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/lastSeenAt","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/metaData","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/nickname","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/originalProfileURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/plainProfileImageURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/preferredLanguages","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/profileURL","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/userID"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/createMetaData(_:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/deleteAllMetaData(completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/deleteMetaData(key:completionHandler:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/isEqual(_:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/updateMetaData(_:completionHandler:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/Mappable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/NSCopying-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/User\/Serializable-Implementations"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDUser"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1connectionStatus\/title","value":"connectionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1connectionStatus\/fragments","value":[{"kind":"identifier","text":"connectionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1deleteMetaData(key:completionHandler:)\/title","value":"deleteMetaDataWithKey:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1deleteMetaData(key:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteMetaDataWithKey:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1metaData\/title","value":"metaData"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1metaData\/fragments","value":[{"kind":"identifier","text":"metaData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1friendName\/title","value":"friendName"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1friendName\/fragments","value":[{"kind":"identifier","text":"friendName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Sender\/title","value":"SBDSender"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Sender\/fragments","value":[{"kind":"identifier","text":"SBDSender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1friendDiscoveryKey\/title","value":"friendDiscoveryKey"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1friendDiscoveryKey\/fragments","value":[{"kind":"identifier","text":"friendDiscoveryKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member\/title","value":"SBDMember"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Member\/fragments","value":[{"kind":"identifier","text":"SBDMember"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1userID\/title","value":"userID"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1userID\/fragments","value":[{"kind":"identifier","text":"userID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1id-9titu\/title","value":"id"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1id-9titu\/fragments","value":[{"kind":"identifier","text":"id"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Serializable\/title","value":"Serializable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Serializable\/fragments","value":[{"kind":"identifier","text":"Serializable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1createMetaData(_:completionHandler:)\/title","value":"createMetaData:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1createMetaData(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createMetaData:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1originalProfileURL\/title","value":"originalProfileURL"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1originalProfileURL\/fragments","value":[{"kind":"identifier","text":"originalProfileURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1lastSeenAt\/title","value":"lastSeenAt"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1lastSeenAt\/fragments","value":[{"kind":"identifier","text":"lastSeenAt"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1profileURL\/title","value":"profileURL"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1profileURL\/fragments","value":[{"kind":"identifier","text":"profileURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1isActive\/title","value":"isActive"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1isActive\/fragments","value":[{"kind":"identifier","text":"isActive"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1nickname\/title","value":"nickname"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1nickname\/fragments","value":[{"kind":"identifier","text":"nickname"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1preferredLanguages\/title","value":"preferredLanguages"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1preferredLanguages\/fragments","value":[{"kind":"identifier","text":"preferredLanguages"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1deleteAllMetaData(completionHandler:)\/title","value":"deleteAllMetaDataWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1deleteAllMetaData(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteAllMetaDataWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/title","value":"Mappable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Mappable\/fragments","value":[{"kind":"identifier","text":"Mappable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictedUser\/title","value":"SBDRestrictedUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1RestrictedUser\/fragments","value":[{"kind":"identifier","text":"SBDRestrictedUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1plainProfileImageURL\/title","value":"plainProfileImageURL"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1plainProfileImageURL\/fragments","value":[{"kind":"identifier","text":"plainProfileImageURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1updateMetaData(_:completionHandler:)\/title","value":"updateMetaData:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User~1updateMetaData(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateMetaData:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User\/title","value":"SBDUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1User\/fragments","value":[{"kind":"identifier","text":"SBDUser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}