{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDUserMessageUpdateParams) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMessageUpdateParams"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/usermessageupdateparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/usermessageupdateparams"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageUpdateParams"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.chat\/objc(pl)NSCopying","doc:\/\/com.sendbird.chat\/objc(pl)NSObject","doc:\/\/com.sendbird.chat\/s7CVarArgP","doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.chat\/SE","doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UserMessageUpdateParams"},{"type":"text","text":" class is used to send a user message in "},{"type":"codeVoice","code":"BaseChannel"},{"type":"text","text":". This is a child class of "},{"type":"codeVoice","code":"BaseMessageUpdateParams"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMessageUpdateParams"}],"title":"UserMessageUpdateParams","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessageUpdateParams","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"UserMessageUpdateParams"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/init(message:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/mentionedMessageTemplate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/message","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/pollID"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/encode(to:)"]}],"references":{"doc://com.sendbird.chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s23CustomStringConvertibleP"},"doc://com.sendbird.chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.chat\/s7CVarArgP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageUpdateParams/message":{"role":"symbol","title":"message","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Message text."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/message","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"message"}],"url":"\/documentation\/sendbirdchatsdk\/usermessageupdateparams\/message"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessageUpdateParams":{"role":"symbol","title":"BaseMessageUpdateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessageUpdateParams"}],"abstract":[{"type":"text","text":"Represents the base class which has parameters to update a channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageUpdateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessageUpdateParams"}],"url":"\/documentation\/sendbirdchatsdk\/basemessageupdateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.sendbird.chat\/SE"},"doc://com.sendbird.chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSObject"},"doc://com.sendbird.chat/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.sendbird.chat\/objc(pl)NSCopying"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageUpdateParams/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Copies this object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/sendbirdchatsdk\/usermessageupdateparams\/copy(with:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageUpdateParams/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Encodes this object."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/usermessageupdateparams\/encode(to:)"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageUpdateParams/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Initializes an user message params for update"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirdchatsdk\/usermessageupdateparams\/init()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageUpdateParams/mentionedMessageTemplate":{"role":"symbol","title":"mentionedMessageTemplate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionedMessageTemplate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The template for the message that has the mentioned users."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/mentionedMessageTemplate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mentionedMessageTemplate"}],"url":"\/documentation\/sendbirdchatsdk\/usermessageupdateparams\/mentionedmessagetemplate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageUpdateParams/pollID":{"role":"symbol","title":"pollID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pollID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Links a poll with message, to unlink set it -1"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/pollID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pollID"}],"url":"\/documentation\/sendbirdchatsdk\/usermessageupdateparams\/pollid"},"doc://com.sendbird.chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.chat\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageUpdateParams":{"role":"symbol","title":"UserMessageUpdateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMessageUpdateParams"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UserMessageUpdateParams"},{"type":"text","text":" class is used to send a user message in "},{"type":"codeVoice","code":"BaseChannel"},{"type":"text","text":". This is a child class of "},{"type":"codeVoice","code":"BaseMessageUpdateParams"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserMessageUpdateParams"}],"url":"\/documentation\/sendbirdchatsdk\/usermessageupdateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageUpdateParams/init(message:)":{"role":"symbol","title":"init(message:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initializes an instance of a user message params with message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/init(message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMessage:"}],"url":"\/documentation\/sendbirdchatsdk\/usermessageupdateparams\/init(message:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBDUserMessageUpdateParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUserMessageUpdateParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDUserMessageUpdateParams"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/mentionedMessageTemplate","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/message","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/pollID"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/copy(with:)","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/init()","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageUpdateParams\/init(message:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDUserMessageUpdateParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessageUpdateParams","text":"SBDBaseMessageUpdateParams"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams~1message\/title","value":"message"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams~1message\/fragments","value":[{"kind":"identifier","text":"message"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessageUpdateParams\/title","value":"SBDBaseMessageUpdateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessageUpdateParams\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessageUpdateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams~1mentionedMessageTemplate\/title","value":"mentionedMessageTemplate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams~1mentionedMessageTemplate\/fragments","value":[{"kind":"identifier","text":"mentionedMessageTemplate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams~1pollID\/title","value":"pollID"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams~1pollID\/fragments","value":[{"kind":"identifier","text":"pollID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams\/title","value":"SBDUserMessageUpdateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams\/fragments","value":[{"kind":"identifier","text":"SBDUserMessageUpdateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams~1init(message:)\/title","value":"initWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessageUpdateParams~1init(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMessage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}