{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDUserListQueryType) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserListQueryType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/userlistquerytype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/userlistquerytype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/allUsers","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/blockedUsers","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/filteredUsers","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/openChannelBannedUsers","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/openChannelMutedUsers","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/openChannelParticipants"]},{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserListQueryType"}],"title":"UserListQueryType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDUserListQueryType","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"UserListQueryType"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQueryType/filteredUsers":{"role":"symbol","title":"UserListQueryType.filteredUsers","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"filteredUsers"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/filteredUsers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUserListQueryTypeFilteredUsers"}],"url":"\/documentation\/sendbirdchatsdk\/userlistquerytype\/filteredusers"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQueryType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/userlistquerytype\/equatable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQueryType/blockedUsers":{"role":"symbol","title":"UserListQueryType.blockedUsers","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"blockedUsers"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/blockedUsers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUserListQueryTypeBlockedUsers"}],"url":"\/documentation\/sendbirdchatsdk\/userlistquerytype\/blockedusers"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQueryType/openChannelParticipants":{"role":"symbol","title":"UserListQueryType.openChannelParticipants","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelParticipants"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/openChannelParticipants","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelParticipants"}],"url":"\/documentation\/sendbirdchatsdk\/userlistquerytype\/openchannelparticipants"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQueryType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/userlistquerytype\/rawrepresentable-implementations"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQueryType/openChannelBannedUsers":{"role":"symbol","title":"UserListQueryType.openChannelBannedUsers","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelBannedUsers"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/openChannelBannedUsers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelBannedUsers"}],"url":"\/documentation\/sendbirdchatsdk\/userlistquerytype\/openchannelbannedusers"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQueryType/openChannelMutedUsers":{"role":"symbol","title":"UserListQueryType.openChannelMutedUsers","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelMutedUsers"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/openChannelMutedUsers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelMutedUsers"}],"url":"\/documentation\/sendbirdchatsdk\/userlistquerytype\/openchannelmutedusers"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQueryType":{"role":"symbol","title":"UserListQueryType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserListQueryType"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserListQueryType"}],"url":"\/documentation\/sendbirdchatsdk\/userlistquerytype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQueryType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/userlistquerytype\/init(rawvalue:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserListQueryType/allUsers":{"role":"symbol","title":"UserListQueryType.allUsers","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allUsers"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/allUsers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUserListQueryTypeAllUsers"}],"url":"\/documentation\/sendbirdchatsdk\/userlistquerytype\/allusers"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDUserListQueryType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUserListQueryType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDUserListQueryType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/allUsers","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/blockedUsers","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/filteredUsers","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/openChannelBannedUsers","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/openChannelMutedUsers","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserListQueryType\/openChannelParticipants"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDUserListQueryType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1filteredUsers\/title","value":"SBDUserListQueryTypeFilteredUsers"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1filteredUsers\/fragments","value":[{"kind":"identifier","text":"SBDUserListQueryTypeFilteredUsers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1blockedUsers\/title","value":"SBDUserListQueryTypeBlockedUsers"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1blockedUsers\/fragments","value":[{"kind":"identifier","text":"SBDUserListQueryTypeBlockedUsers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1openChannelParticipants\/title","value":"SBDUserListQueryTypeOpenChannelParticipants"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1openChannelParticipants\/fragments","value":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelParticipants"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1openChannelBannedUsers\/title","value":"SBDUserListQueryTypeOpenChannelBannedUsers"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1openChannelBannedUsers\/fragments","value":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelBannedUsers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1openChannelMutedUsers\/title","value":"SBDUserListQueryTypeOpenChannelMutedUsers"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1openChannelMutedUsers\/fragments","value":[{"kind":"identifier","text":"SBDUserListQueryTypeOpenChannelMutedUsers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType\/title","value":"SBDUserListQueryType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType\/fragments","value":[{"kind":"identifier","text":"SBDUserListQueryType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1allUsers\/title","value":"SBDUserListQueryTypeAllUsers"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserListQueryType~1allUsers\/fragments","value":[{"kind":"identifier","text":"SBDUserListQueryTypeAllUsers"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}