{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBDWebSocketConnectionState) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebSocketConnectionState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/websocketconnectionstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/websocketconnectionstate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.chat\/SQ","doc:\/\/com.sendbird.chat\/SH","doc:\/\/com.sendbird.chat\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Connection state"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebSocketConnectionState"}],"title":"WebSocketConnectionState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdChatSDK@E@SBDWebSocketConnectionState","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"WebSocketConnectionState"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/closed","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/connecting","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/open"]},{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/Equatable-Implementations","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/WebSocketConnectionState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/websocketconnectionstate\/rawrepresentable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/WebSocketConnectionState/closed":{"role":"symbol","title":"WebSocketConnectionState.closed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"}],"abstract":[{"type":"text","text":"Closed"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/closed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDWebSocketConnectionStateClosed"}],"url":"\/documentation\/sendbirdchatsdk\/websocketconnectionstate\/closed"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/WebSocketConnectionState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk\/websocketconnectionstate\/init(rawvalue:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/WebSocketConnectionState":{"role":"symbol","title":"WebSocketConnectionState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebSocketConnectionState"}],"abstract":[{"type":"text","text":"Connection state"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebSocketConnectionState"}],"url":"\/documentation\/sendbirdchatsdk\/websocketconnectionstate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/WebSocketConnectionState/open":{"role":"symbol","title":"WebSocketConnectionState.open","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"open"}],"abstract":[{"type":"text","text":"Open"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/open","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDWebSocketConnectionStateOpen"}],"url":"\/documentation\/sendbirdchatsdk\/websocketconnectionstate\/open"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/WebSocketConnectionState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/websocketconnectionstate\/equatable-implementations"},"doc://com.sendbird.chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.chat\/SH"},"doc://com.sendbird.chat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.chat\/SY"},"doc://com.sendbird.chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.chat\/SQ"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/WebSocketConnectionState/connecting":{"role":"symbol","title":"WebSocketConnectionState.connecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"abstract":[{"type":"text","text":"Connecting"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/connecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDWebSocketConnectionStateConnecting"}],"url":"\/documentation\/sendbirdchatsdk\/websocketconnectionstate\/connecting"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBDWebSocketConnectionState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDWebSocketConnectionState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBDWebSocketConnectionState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/closed","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/connecting","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/WebSocketConnectionState\/open"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBDWebSocketConnectionState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState~1closed\/title","value":"SBDWebSocketConnectionStateClosed"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState~1closed\/fragments","value":[{"kind":"identifier","text":"SBDWebSocketConnectionStateClosed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState\/title","value":"SBDWebSocketConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState\/fragments","value":[{"kind":"identifier","text":"SBDWebSocketConnectionState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState~1open\/title","value":"SBDWebSocketConnectionStateOpen"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState~1open\/fragments","value":[{"kind":"identifier","text":"SBDWebSocketConnectionStateOpen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState~1connecting\/title","value":"SBDWebSocketConnectionStateConnecting"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1WebSocketConnectionState~1connecting\/fragments","value":[{"kind":"identifier","text":"SBDWebSocketConnectionStateConnecting"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}