{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduledStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDScheduledStatus","text":"ScheduledStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/scheduledinfo\/scheduledstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/scheduledinfo\/scheduledstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledInfo\/scheduledStatus","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduledStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledStatus","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDScheduledStatus"}],"title":"scheduledStatus","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledInfo(py)scheduledStatus","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"scheduledStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledInfo"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledStatus":{"role":"symbol","title":"ScheduledStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledStatus"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledStatus"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledstatus"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledInfo":{"role":"symbol","title":"ScheduledInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledInfo"}],"abstract":[{"type":"text","text":"Class holding an information about the scheduled messages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledInfo"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledinfo"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledInfo/scheduledStatus":{"role":"symbol","title":"scheduledStatus","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduledStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledStatus","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDScheduledStatus"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledInfo\/scheduledStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scheduledStatus"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledinfo\/scheduledstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"scheduledStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"scheduledStatus"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledStatus","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDScheduledStatus","text":"SBDScheduledStatus"},{"kind":"identifier","text":"scheduledStatus"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatus\/title","value":"SBDScheduledStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledStatus\/fragments","value":[{"kind":"identifier","text":"SBDScheduledStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledInfo\/title","value":"SBDScheduledInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledInfo\/fragments","value":[{"kind":"identifier","text":"SBDScheduledInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledInfo~1scheduledStatus\/title","value":"scheduledStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledInfo~1scheduledStatus\/fragments","value":[{"kind":"identifier","text":"scheduledStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}