{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelCollection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection","text":"GroupChannelCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDChannelContext","text":"ChannelContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedChannelURLs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"collection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The collection object."}]}]},{"name":"context","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The context that represents the reason why the delegate is invoked."}]}]},{"name":"deletedChannelURLs","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"list of channel url that are deleted."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelcollectiondelegate\/channelcollection(_:context:deletedchannelurls:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannelcollectiondelegate\/channelcollection(_:context:deletedchannelurls:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollectionDelegate\/channelCollection(_:context:deletedChannelURLs:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A callback when the channels are deleted."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"channelCollection:context:deletedChannelURLs:"}],"role":"symbol","title":"channelCollection(_:context:deletedChannelURLs:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannelCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDChannelContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedChannelURLs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(pl)SBDGroupChannelCollectionDelegate(im)channelCollection:context:deletedChannelURLs:","required":true,"modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollectionDelegate"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelContext":{"role":"symbol","title":"ChannelContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelContext"}],"abstract":[{"type":"text","text":"Channel context"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelContext"}],"url":"\/documentation\/sendbirdchatsdk\/channelcontext"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollectionDelegate/channelCollection(_:context:deletedChannelURLs:)":{"navigatorTitle":[{"kind":"identifier","text":"channelCollection:context:deletedChannelURLs:"}],"role":"symbol","title":"channelCollection(_:context:deletedChannelURLs:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannelCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDChannelContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedChannelURLs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"A callback when the channels are deleted."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollectionDelegate\/channelCollection(_:context:deletedChannelURLs:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirdchatsdk\/groupchannelcollectiondelegate\/channelcollection(_:context:deletedchannelurls:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollectionDelegate":{"role":"symbol","title":"GroupChannelCollectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelCollectionDelegate"}],"abstract":[{"type":"text","text":"Methods that are invoked when the event of the channel collection occurs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelCollectionDelegate"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollectiondelegate"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelCollection":{"role":"symbol","title":"GroupChannelCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelCollection"}],"abstract":[{"type":"text","text":"An object that accesses the cache for the group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelCollection"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelcollection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"channelCollection:context:deletedChannelURLs:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelCollection:context:deletedChannelURLs:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"channelCollection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection","text":"SBDGroupChannelCollection"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"collection"},{"kind":"text","text":" "},{"kind":"identifier","text":"context:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDChannelContext","text":"SBDChannelContext"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"context"},{"kind":"text","text":" "},{"kind":"identifier","text":"deletedChannelURLs:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"deletedChannelURLs"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelContext\/title","value":"SBDChannelContext"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelContext\/fragments","value":[{"kind":"identifier","text":"SBDChannelContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollectionDelegate~1channelCollection(_:context:deletedChannelURLs:)\/title","value":"channelCollection:context:deletedChannelURLs:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollectionDelegate~1channelCollection(_:context:deletedChannelURLs:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelCollection:context:deletedChannelURLs:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollectionDelegate\/title","value":"SBDGroupChannelCollectionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollectionDelegate\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelCollectionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection\/title","value":"SBDGroupChannelCollection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelCollection\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelCollection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}