{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPollVoterListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pollID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"optionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollVoterListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollVoterListQuery","text":"PollVoterListQuery"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"poll voter list query object."}]}]},{"kind":"parameters","parameters":[{"name":"pollID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"poll ID."}]}]},{"name":"optionID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"option ID."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.232"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createpollvoterlistquery(pollid:optionid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createpollvoterlistquery(pollid:optionid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createPollVoterListQuery(pollID:optionID:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"PollVoterListQuery"},{"type":"text","text":" instance for getting user list on given poll option"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"createPollVoterListQueryWithPollID:optionID:"}],"role":"symbol","title":"createPollVoterListQuery(pollID:optionID:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPollVoterListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pollID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"optionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PollVoterListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollVoterListQuery"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)createPollVoterListQueryWithPollID:optionID:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollVoterListQuery":{"role":"symbol","title":"PollVoterListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollVoterListQuery"}],"abstract":[{"type":"text","text":"An object to retrieve list of voter"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollVoterListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PollVoterListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/pollvoterlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/createPollVoterListQuery(pollID:optionID:)":{"role":"symbol","title":"createPollVoterListQuery(pollID:optionID:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPollVoterListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pollID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"optionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PollVoterListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollVoterListQuery"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"PollVoterListQuery"},{"type":"text","text":" instance for getting user list on given poll option"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createPollVoterListQuery(pollID:optionID:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createPollVoterListQueryWithPollID:optionID:"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/createpollvoterlistquery(pollid:optionid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createPollVoterListQueryWithPollID:optionID:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createPollVoterListQueryWithPollID:optionID:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollVoterListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollVoterListQuery","text":"SBDPollVoterListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createPollVoterListQueryWithPollID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"pollID"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"optionID"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollVoterListQuery\/title","value":"SBDPollVoterListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollVoterListQuery\/fragments","value":[{"kind":"identifier","text":"SBDPollVoterListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createPollVoterListQuery(pollID:optionID:)\/title","value":"createPollVoterListQueryWithPollID:optionID:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createPollVoterListQuery(pollID:optionID:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createPollVoterListQueryWithPollID:optionID:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}