{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPollVoterListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pollID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"optionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType","text":"ChannelType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollVoterListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollVoterListQuery","text":"PollVoterListQuery"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"poll voter list query object."}]}]},{"kind":"parameters","parameters":[{"name":"pollID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"poll ID."}]}]},{"name":"optionID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"option ID."}]}]},{"name":"channelType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Channel type of the channel URL."}]}]},{"name":"channelURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Channel URL."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createpollvoterlistquery(pollid:optionid:channeltype:channelurl:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createpollvoterlistquery(pollid:optionid:channeltype:channelurl:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createPollVoterListQuery(pollID:optionID:channelType:channelURL:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"PollVoterListQuery"},{"type":"text","text":" instance for getting user list on given poll option"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"createPollVoterListQueryWithPollID:optionID:channelType:channelURL:"}],"role":"symbol","title":"createPollVoterListQuery(pollID:optionID:channelType:channelURL:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPollVoterListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pollID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"optionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PollVoterListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollVoterListQuery"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(cm)createPollVoterListQueryWithPollID:optionID:channelType:channelURL:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PollVoterListQuery":{"role":"symbol","title":"PollVoterListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollVoterListQuery"}],"abstract":[{"type":"text","text":"An object to retrieve list of voter"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollVoterListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PollVoterListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/pollvoterlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/createPollVoterListQuery(pollID:optionID:channelType:channelURL:)":{"role":"symbol","title":"createPollVoterListQuery(pollID:optionID:channelType:channelURL:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPollVoterListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pollID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"optionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PollVoterListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollVoterListQuery"}],"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"PollVoterListQuery"},{"type":"text","text":" instance for getting user list on given poll option"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createPollVoterListQuery(pollID:optionID:channelType:channelURL:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createPollVoterListQueryWithPollID:optionID:channelType:channelURL:"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/createpollvoterlistquery(pollid:optionid:channeltype:channelurl:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelType":{"role":"symbol","title":"ChannelType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelType"}],"abstract":[{"type":"text","text":"Channel types."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelType"}],"url":"\/documentation\/sendbirdchatsdk\/channeltype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createPollVoterListQueryWithPollID:optionID:channelType:channelURL:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createPollVoterListQueryWithPollID:optionID:channelType:channelURL:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PollVoterListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPollVoterListQuery","text":"SBDPollVoterListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createPollVoterListQueryWithPollID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"pollID"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"optionID"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType","text":"SBDChannelType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"channelType"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelURL"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollVoterListQuery\/title","value":"SBDPollVoterListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PollVoterListQuery\/fragments","value":[{"kind":"identifier","text":"SBDPollVoterListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createPollVoterListQuery(pollID:optionID:channelType:channelURL:)\/title","value":"createPollVoterListQueryWithPollID:optionID:channelType:channelURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createPollVoterListQuery(pollID:optionID:channelType:channelURL:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createPollVoterListQueryWithPollID:optionID:channelType:channelURL:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelType\/title","value":"SBDChannelType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelType\/fragments","value":[{"kind":"identifier","text":"SBDChannelType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}