{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPreviousMessageListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType","text":"ChannelType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PreviousMessageListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPreviousMessageListQueryParams","text":"PreviousMessageListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PreviousMessageListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPreviousMessageListQuery","text":"PreviousMessageListQuery"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns the message list of the channel."}]}]},{"kind":"parameters","parameters":[{"name":"channelType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"channel type"}]}]},{"name":"channelURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"channel url"}]}]},{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The params object to change query condition."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createpreviousmessagelistquery(channeltype:channelurl:params:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createpreviousmessagelistquery(channeltype:channelurl:params:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createPreviousMessageListQuery(channelType:channelURL:params:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"PreviousMessageListQuery"},{"type":"text","text":" instance for getting the previous messages list of the channel."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"createPreviousMessageListQueryWithChannelType:channelURL:params:"}],"role":"symbol","title":"createPreviousMessageListQuery(channelType:channelURL:params:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPreviousMessageListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PreviousMessageListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPreviousMessageListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PreviousMessageListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPreviousMessageListQuery"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(cm)createPreviousMessageListQueryWithChannelType:channelURL:params:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PreviousMessageListQueryParams":{"role":"symbol","title":"PreviousMessageListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviousMessageListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PreviousMessageListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreviousMessageListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/previousmessagelistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PreviousMessageListQuery":{"role":"symbol","title":"PreviousMessageListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviousMessageListQuery"}],"abstract":[{"type":"text","text":"An object which retrieves messages from the given channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PreviousMessageListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreviousMessageListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/previousmessagelistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/createPreviousMessageListQuery(channelType:channelURL:params:)":{"role":"symbol","title":"createPreviousMessageListQuery(channelType:channelURL:params:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPreviousMessageListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PreviousMessageListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPreviousMessageListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PreviousMessageListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPreviousMessageListQuery"}],"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"PreviousMessageListQuery"},{"type":"text","text":" instance for getting the previous messages list of the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createPreviousMessageListQuery(channelType:channelURL:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createPreviousMessageListQueryWithChannelType:channelURL:params:"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/createpreviousmessagelistquery(channeltype:channelurl:params:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelType":{"role":"symbol","title":"ChannelType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelType"}],"abstract":[{"type":"text","text":"Channel types."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelType"}],"url":"\/documentation\/sendbirdchatsdk\/channeltype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createPreviousMessageListQueryWithChannelType:channelURL:params:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createPreviousMessageListQueryWithChannelType:channelURL:params:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PreviousMessageListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPreviousMessageListQuery","text":"SBDPreviousMessageListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createPreviousMessageListQueryWithChannelType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType","text":"SBDChannelType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"channelType"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"params:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PreviousMessageListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDPreviousMessageListQueryParams","text":"SBDPreviousMessageListQueryParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PreviousMessageListQueryParams\/title","value":"SBDPreviousMessageListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PreviousMessageListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDPreviousMessageListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PreviousMessageListQuery\/title","value":"SBDPreviousMessageListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PreviousMessageListQuery\/fragments","value":[{"kind":"identifier","text":"SBDPreviousMessageListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createPreviousMessageListQuery(channelType:channelURL:params:)\/title","value":"createPreviousMessageListQueryWithChannelType:channelURL:params:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createPreviousMessageListQuery(channelType:channelURL:params:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createPreviousMessageListQueryWithChannelType:channelURL:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelType\/title","value":"SBDChannelType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelType\/fragments","value":[{"kind":"identifier","text":"SBDChannelType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}