{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBannedUserListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BannedUserListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBannedUserListQueryParams","text":"BannedUserListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BannedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBannedUserListQuery","text":"BannedUserListQuery"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The instance for the banned user list. Query only banned user list."}]}]},{"kind":"parameters","parameters":[{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"BannedUserListQueryParams"},{"type":"text","text":" instance."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.89"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createbanneduserlistquery(params:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createbanneduserlistquery(params:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createBannedUserListQuery(params:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a query instance for banned user list of the channel."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"createBannedUserListQueryWithParams:"}],"role":"symbol","title":"createBannedUserListQuery(params:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBannedUserListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BannedUserListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBannedUserListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"BannedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBannedUserListQuery"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)createBannedUserListQueryWithParams:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/createBannedUserListQuery(params:)":{"role":"symbol","title":"createBannedUserListQuery(params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBannedUserListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BannedUserListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBannedUserListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"BannedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBannedUserListQuery"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Creates a query instance for banned user list of the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createBannedUserListQuery(params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createBannedUserListQueryWithParams:"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/createbanneduserlistquery(params:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BannedUserListQuery":{"role":"symbol","title":"BannedUserListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannedUserListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BannedUserListQuery"},{"type":"text","text":" class is a query class for getting the list of banned users in"},{"type":"text","text":" "},{"type":"text","text":"a specific channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BannedUserListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BannedUserListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/banneduserlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BannedUserListQueryParams":{"role":"symbol","title":"BannedUserListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannedUserListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BannedUserListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BannedUserListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/banneduserlistqueryparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createBannedUserListQueryWithParams:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createBannedUserListQueryWithParams:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BannedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBannedUserListQuery","text":"SBDBannedUserListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createBannedUserListQueryWithParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BannedUserListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBannedUserListQueryParams","text":"SBDBannedUserListQueryParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createBannedUserListQuery(params:)\/title","value":"createBannedUserListQueryWithParams:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createBannedUserListQuery(params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createBannedUserListQueryWithParams:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BannedUserListQuery\/title","value":"SBDBannedUserListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BannedUserListQuery\/fragments","value":[{"kind":"identifier","text":"SBDBannedUserListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BannedUserListQueryParams\/title","value":"SBDBannedUserListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BannedUserListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDBannedUserListQueryParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}