{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMutedUserListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramsBuilder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQueryParams","text":"MutedUserListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQuery","text":"MutedUserListQuery"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"UserListQuery instance for the muted user list."}]}]},{"kind":"parameters","parameters":[{"name":"paramsBuilder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The builder closure for setting "},{"type":"codeVoice","code":"MutedUserListQueryParams"},{"type":"text","text":"."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createmuteduserlistquery(paramsbuilder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createmuteduserlistquery(paramsbuilder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createMutedUserListQuery(paramsBuilder:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a query instance for getting muted user list of the channel instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMutedUserListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramsBuilder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MutedUserListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MutedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQuery"},{"kind":"text","text":"?"}],"title":"createMutedUserListQuery(paramsBuilder:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)createMutedUserListQueryWithParamsBuilder:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"createMutedUserListQueryWithParamsBuilder:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/createMutedUserListQuery(paramsBuilder:)":{"role":"symbol","title":"createMutedUserListQuery(paramsBuilder:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMutedUserListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramsBuilder"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MutedUserListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MutedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQuery"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Creates a query instance for getting muted user list of the channel instance."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createMutedUserListQuery(paramsBuilder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createMutedUserListQueryWithParamsBuilder:"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/createmuteduserlistquery(paramsbuilder:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MutedUserListQueryParams":{"role":"symbol","title":"MutedUserListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MutedUserListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MutedUserListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/muteduserlistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MutedUserListQuery":{"role":"symbol","title":"MutedUserListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MutedUserListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MutedUserListQuery"},{"type":"text","text":" class is a query class for getting the list of muted users in"},{"type":"text","text":" "},{"type":"text","text":"a specific channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MutedUserListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/muteduserlistquery"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createMutedUserListQueryWithParamsBuilder:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createMutedUserListQueryWithParamsBuilder:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQuery","text":"SBDMutedUserListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createMutedUserListQueryWithParamsBuilder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDMutedUserListQueryParams *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQueryParams)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"paramsBuilder"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createMutedUserListQuery(paramsBuilder:)\/title","value":"createMutedUserListQueryWithParamsBuilder:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createMutedUserListQuery(paramsBuilder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createMutedUserListQueryWithParamsBuilder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MutedUserListQueryParams\/title","value":"SBDMutedUserListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MutedUserListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDMutedUserListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MutedUserListQuery\/title","value":"SBDMutedUserListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MutedUserListQuery\/fragments","value":[{"kind":"identifier","text":"SBDMutedUserListQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}