{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOperatorListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OperatorListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOperatorListQueryParams","text":"OperatorListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OperatorListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOperatorListQuery","text":"OperatorListQuery"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The operator list in the channel."}]}]},{"kind":"parameters","parameters":[{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The params object to change query condition."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createoperatorlistquery(params:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createoperatorlistquery(params:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createOperatorListQuery(params:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"OperatorListQuery"},{"type":"text","text":" instance for getting operators in the channel."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"createOperatorListQueryWithParams:"}],"role":"symbol","title":"createOperatorListQuery(params:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOperatorListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OperatorListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOperatorListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"OperatorListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOperatorListQuery"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)createOperatorListQueryWithParams:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OperatorListQuery":{"role":"symbol","title":"OperatorListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OperatorListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OperatorListQuery"},{"type":"text","text":" class is a query class for getting the list of operators in channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OperatorListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OperatorListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/operatorlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/createOperatorListQuery(params:)":{"role":"symbol","title":"createOperatorListQuery(params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOperatorListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OperatorListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOperatorListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"OperatorListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOperatorListQuery"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"OperatorListQuery"},{"type":"text","text":" instance for getting operators in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createOperatorListQuery(params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createOperatorListQueryWithParams:"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/createoperatorlistquery(params:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OperatorListQueryParams":{"role":"symbol","title":"OperatorListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OperatorListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OperatorListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OperatorListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/operatorlistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createOperatorListQueryWithParams:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createOperatorListQueryWithParams:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OperatorListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOperatorListQuery","text":"SBDOperatorListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createOperatorListQueryWithParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OperatorListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOperatorListQueryParams","text":"SBDOperatorListQueryParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OperatorListQuery\/title","value":"SBDOperatorListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OperatorListQuery\/fragments","value":[{"kind":"identifier","text":"SBDOperatorListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createOperatorListQuery(params:)\/title","value":"createOperatorListQueryWithParams:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createOperatorListQuery(params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createOperatorListQueryWithParams:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OperatorListQueryParams\/title","value":"SBDOperatorListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OperatorListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDOperatorListQueryParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}