{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBannedUserListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType","text":"ChannelType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BannedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBannedUserListQuery","text":"BannedUserListQuery"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The instance for the banned user list. Query only banned user list."}]}]},{"kind":"parameters","parameters":[{"name":"channelType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Type of channel, types of open channel or group channel."}]}]},{"name":"channelURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The channel URL."}]}]},{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"BannedUserListQueryParams"},{"type":"text","text":" instance."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createbanneduserlistquery(channeltype:channelurl:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createbanneduserlistquery(channeltype:channelurl:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createBannedUserListQuery(channelType:channelURL:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a query instance for banned user list of the channel."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"createBannedUserListQueryWithChannelType:channelURL:"}],"role":"symbol","title":"createBannedUserListQuery(channelType:channelURL:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBannedUserListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"BannedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBannedUserListQuery"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(cm)createBannedUserListQueryWithChannelType:channelURL:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BannedUserListQuery":{"role":"symbol","title":"BannedUserListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannedUserListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BannedUserListQuery"},{"type":"text","text":" class is a query class for getting the list of banned users in"},{"type":"text","text":" "},{"type":"text","text":"a specific channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BannedUserListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BannedUserListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/banneduserlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/createBannedUserListQuery(channelType:channelURL:)":{"role":"symbol","title":"createBannedUserListQuery(channelType:channelURL:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBannedUserListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"BannedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBannedUserListQuery"}],"abstract":[{"type":"text","text":"Creates a query instance for banned user list of the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createBannedUserListQuery(channelType:channelURL:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createBannedUserListQueryWithChannelType:channelURL:"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/createbanneduserlistquery(channeltype:channelurl:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ChannelType":{"role":"symbol","title":"ChannelType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelType"}],"abstract":[{"type":"text","text":"Channel types."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelType"}],"url":"\/documentation\/sendbirdchatsdk\/channeltype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createBannedUserListQueryWithChannelType:channelURL:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBannedUserListQueryWithChannelType:channelURL:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BannedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBannedUserListQuery","text":"SBDBannedUserListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createBannedUserListQueryWithChannelType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType","text":"SBDChannelType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"channelType"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelURL"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BannedUserListQuery\/title","value":"SBDBannedUserListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BannedUserListQuery\/fragments","value":[{"kind":"identifier","text":"SBDBannedUserListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createBannedUserListQuery(channelType:channelURL:)\/title","value":"createBannedUserListQueryWithChannelType:channelURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createBannedUserListQuery(channelType:channelURL:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBannedUserListQueryWithChannelType:channelURL:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelType\/title","value":"SBDChannelType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ChannelType\/fragments","value":[{"kind":"identifier","text":"SBDChannelType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}