{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMutedUserListQuery"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQuery","text":"MutedUserListQuery"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"UserListQuery instance for the muted user list."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createmuteduserlistquery()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createmuteduserlistquery()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createMutedUserListQuery()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a query instance for getting muted user list of the channel instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMutedUserListQuery"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MutedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQuery"},{"kind":"text","text":"?"}],"title":"createMutedUserListQuery()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)createMutedUserListQuery","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"createMutedUserListQuery"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/createMutedUserListQuery()":{"role":"symbol","title":"createMutedUserListQuery()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMutedUserListQuery"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MutedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQuery"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Creates a query instance for getting muted user list of the channel instance."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createMutedUserListQuery()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createMutedUserListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/createmuteduserlistquery()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MutedUserListQuery":{"role":"symbol","title":"MutedUserListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MutedUserListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MutedUserListQuery"},{"type":"text","text":" class is a query class for getting the list of muted users in"},{"type":"text","text":" "},{"type":"text","text":"a specific channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MutedUserListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/muteduserlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createMutedUserListQuery"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createMutedUserListQuery"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MutedUserListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMutedUserListQuery","text":"SBDMutedUserListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createMutedUserListQuery"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createMutedUserListQuery()\/title","value":"createMutedUserListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createMutedUserListQuery()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createMutedUserListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MutedUserListQuery\/title","value":"SBDMutedUserListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MutedUserListQuery\/fragments","value":[{"kind":"identifier","text":"SBDMutedUserListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}