{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOperatorListQuery"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OperatorListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOperatorListQuery","text":"OperatorListQuery"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The operator list in the channel."}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.94"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createoperatorlistquery()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/createoperatorlistquery()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createOperatorListQuery()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"OperatorListQuery"},{"type":"text","text":" instance for getting operators in the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOperatorListQuery"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"OperatorListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOperatorListQuery"},{"kind":"text","text":"?"}],"title":"createOperatorListQuery()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)createOperatorListQuery","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"createOperatorListQuery"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/createOperatorListQuery()":{"role":"symbol","title":"createOperatorListQuery()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOperatorListQuery"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"OperatorListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOperatorListQuery"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Creates "},{"type":"codeVoice","code":"OperatorListQuery"},{"type":"text","text":" instance for getting operators in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/createOperatorListQuery()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createOperatorListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/createoperatorlistquery()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OperatorListQuery":{"role":"symbol","title":"OperatorListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OperatorListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OperatorListQuery"},{"type":"text","text":" class is a query class for getting the list of operators in channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OperatorListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OperatorListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/operatorlistquery"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createOperatorListQuery"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createOperatorListQuery"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OperatorListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOperatorListQuery","text":"SBDOperatorListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createOperatorListQuery"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createOperatorListQuery()\/title","value":"createOperatorListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1createOperatorListQuery()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createOperatorListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OperatorListQuery\/title","value":"SBDOperatorListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OperatorListQuery\/fragments","value":[{"kind":"identifier","text":"SBDOperatorListQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}