{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMetaCounters"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MetaCountersHandler","preciseIdentifier":"s:15SendbirdChatSDK19MetaCountersHandlera","text":"MetaCountersHandler"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"keys","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The keys to get meta counters."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to execute. "},{"type":"codeVoice","code":"metaCounters"},{"type":"text","text":" is the"},{"type":"text","text":" "},{"type":"text","text":"meta counters which are set on Sendbird server."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/getmetacounters(keys:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/getmetacounters(keys:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/getMetaCounters(keys:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the meta counters with keys for the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMetaCounters"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MetaCountersHandler","preciseIdentifier":"s:15SendbirdChatSDK19MetaCountersHandlera"},{"kind":"text","text":"?)"}],"title":"getMetaCounters(keys:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)getMetaCountersWithKeys:completionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getMetaCountersWithKeys:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/getMetaCounters(keys:completionHandler:)":{"role":"symbol","title":"getMetaCounters(keys:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMetaCounters"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MetaCountersHandler","preciseIdentifier":"s:15SendbirdChatSDK19MetaCountersHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Gets the meta counters with keys for the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/getMetaCounters(keys:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getMetaCountersWithKeys:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/getmetacounters(keys:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MetaCountersHandler":{"role":"symbol","title":"MetaCountersHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetaCountersHandler"}],"abstract":[{"type":"text","text":"Channel meta counter handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MetaCountersHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MetaCountersHandler"}],"url":"\/documentation\/sendbirdchatsdk\/metacountershandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getMetaCountersWithKeys:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMetaCountersWithKeys:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getMetaCountersWithKeys:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"keys"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSDictionary<NSString *,NSNumber *> *, SBError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSDictionary#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1getMetaCounters(keys:completionHandler:)\/title","value":"getMetaCountersWithKeys:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1getMetaCounters(keys:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMetaCountersWithKeys:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}