{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(getMessageChangeLogsSinceTimestamp:params:completionHandler:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessageChangeLogs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams","text":"MessageChangeLogsParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogHandler","preciseIdentifier":"s:15SendbirdChatSDK23MessageChangeLogHandlera","text":"MessageChangeLogHandler"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"timestamp","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Specifies the timestamp to be the reference point for changelogs to retrieve, in Unix milliseconds format."}]}]},{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Contains a set of parameters you can set regarding the messages in the results."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to execute. The "},{"type":"codeVoice","code":"updatedMessages"},{"type":"text","text":" retrieves the"},{"type":"text","text":" "},{"type":"text","text":"updated messages. The "},{"type":"codeVoice","code":"deletedMessageIDs"},{"type":"text","text":" retrieves the unique ID of deleted messages. The"},{"type":"text","text":" "},{"type":"codeVoice","code":"hasMore"},{"type":"text","text":" indicates whether there are more changelogs to be retrieved. The "},{"type":"codeVoice","code":"token"},{"type":"text","text":" retrieves the"},{"type":"text","text":" "},{"type":"text","text":"token of the last changelog in the results. The "},{"type":"codeVoice","code":"error"},{"type":"text","text":" indicates whether there is an error. If there is"},{"type":"text","text":" "},{"type":"text","text":"no error, the value is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.181"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/getmessagechangelogs(timestamp:params:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/getmessagechangelogs(timestamp:params:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/getMessageChangeLogs(timestamp:params:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Retrieves the changelogs since a specified timestamp, in Unix milliseconds format, regarding the updated"},{"type":"text","text":" "},{"type":"text","text":"messages or the unique IDs of deleted messages in the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessageChangeLogs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageChangeLogHandler","preciseIdentifier":"s:15SendbirdChatSDK23MessageChangeLogHandlera"},{"kind":"text","text":"?)"}],"title":"getMessageChangeLogs(timestamp:params:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)getMessageChangeLogsSinceTimestamp:params:completionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getMessageChangeLogsSinceTimestamp:params:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/getMessageChangeLogs(timestamp:params:completionHandler:)":{"role":"symbol","title":"getMessageChangeLogs(timestamp:params:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessageChangeLogs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageChangeLogHandler","preciseIdentifier":"s:15SendbirdChatSDK23MessageChangeLogHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Retrieves the changelogs since a specified timestamp, in Unix milliseconds format, regarding the updated"},{"type":"text","text":" "},{"type":"text","text":"messages or the unique IDs of deleted messages in the channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/getMessageChangeLogs(timestamp:params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getMessageChangeLogsSinceTimestamp:params:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/getmessagechangelogs(timestamp:params:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogsParams":{"role":"symbol","title":"MessageChangeLogsParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageChangeLogsParams"}],"abstract":[{"type":"text","text":"An object contains set of options for message change logs."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageChangeLogsParams"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangelogsparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageChangeLogHandler":{"role":"symbol","title":"MessageChangeLogHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageChangeLogHandler"}],"abstract":[{"type":"text","text":"Message change log handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageChangeLogHandler"}],"url":"\/documentation\/sendbirdchatsdk\/messagechangeloghandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getMessageChangeLogsSinceTimestamp:params:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMessageChangeLogsSinceTimestamp:params:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getMessageChangeLogsSinceTimestamp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"timestamp"},{"kind":"text","text":" "},{"kind":"identifier","text":"params:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageChangeLogsParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageChangeLogsParams","text":"SBDMessageChangeLogsParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<SBDBaseMessage *> *, NSArray<NSNumber *> *, _Bool, NSString *, SBError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*QS4_#b#*$objc(cs)NSString#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1getMessageChangeLogs(timestamp:params:completionHandler:)\/title","value":"getMessageChangeLogsSinceTimestamp:params:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1getMessageChangeLogs(timestamp:params:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMessageChangeLogsSinceTimestamp:params:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams\/title","value":"SBDMessageChangeLogsParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageChangeLogsParams\/fragments","value":[{"kind":"identifier","text":"SBDMessageChangeLogsParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}