{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(removeMessageMetaArrayValuesWithMessage:metaArrays:completionHandler:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeMessageMetaArrayValues"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage","text":"BaseMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metaArrays"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageMetaArray","text":"MessageMetaArray"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18BaseMessageHandlera","text":"BaseMessageHandler"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The message instance. The metaArrays will removed from the message."}]}]},{"name":"metaArrays","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of message meta array will be removed from the message. the string of"},{"type":"text","text":" "},{"type":"text","text":"the value in the metaArray MUST exist with same key."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to execute after removing message meta arrays."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"message"},{"type":"text","text":" of the handler is removed message. If failed to remove message meta arrays,"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"codeVoice","code":"error"},{"type":"text","text":" of the handler is not nil(null)."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"metaArrays"},{"type":"text","text":" are removed from the message. If a key in the metaArrays has an emtpy"},{"type":"text","text":" "},{"type":"text","text":"array of the value, the key will be removed. If not, the value of the messageMetaArray will be removed from the message."}]}]},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The order of the meta array is guaranteed."}]}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.148"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/removemessagemetaarrayvalues(message:metaarrays:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/removemessagemetaarrayvalues(message:metaarrays:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/removeMessageMetaArrayValues(message:metaArrays:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Removes the array of meta array from the message."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"removeMessageMetaArrayValuesWithMessage:metaArrays:completionHandler:"}],"role":"symbol","title":"removeMessageMetaArrayValues(message:metaArrays:completionHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeMessageMetaArrayValues"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metaArrays"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MessageMetaArray","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageMetaArray"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18BaseMessageHandlera"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)removeMessageMetaArrayValuesWithMessage:metaArrays:completionHandler:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageMetaArray":{"role":"symbol","title":"MessageMetaArray","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageMetaArray"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MessageMetaArray"},{"type":"text","text":" instance has a string type of key and an array type of value."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageMetaArray","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageMetaArray"}],"url":"\/documentation\/sendbirdchatsdk\/messagemetaarray"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessageHandler":{"role":"symbol","title":"BaseMessageHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessageHandler"}],"abstract":[{"type":"text","text":"Message handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessageHandler"}],"url":"\/documentation\/sendbirdchatsdk\/basemessagehandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/removeMessageMetaArrayValues(message:metaArrays:completionHandler:)":{"role":"symbol","title":"removeMessageMetaArrayValues(message:metaArrays:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeMessageMetaArrayValues"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metaArrays"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MessageMetaArray","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageMetaArray"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18BaseMessageHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Removes the array of meta array from the message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/removeMessageMetaArrayValues(message:metaArrays:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeMessageMetaArrayValuesWithMessage:metaArrays:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/removemessagemetaarrayvalues(message:metaarrays:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseMessage":{"role":"symbol","title":"BaseMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseMessage"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":" class represents the base message which is generated by a user or an admin."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"UserMessage"},{"type":"text","text":", the "},{"type":"codeVoice","code":"FileMessage"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"AdminMessage"},{"type":"text","text":" are derived from this class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseMessage"}],"url":"\/documentation\/sendbirdchatsdk\/basemessage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeMessageMetaArrayValuesWithMessage:metaArrays:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeMessageMetaArrayValuesWithMessage:metaArrays:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeMessageMetaArrayValuesWithMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage","text":"SBDBaseMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"message"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaArrays:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBDMessageMetaArray *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"metaArrays"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDBaseMessage *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDBaseMessage#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray\/title","value":"SBDMessageMetaArray"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageMetaArray\/fragments","value":[{"kind":"identifier","text":"SBDMessageMetaArray"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1removeMessageMetaArrayValues(message:metaArrays:completionHandler:)\/title","value":"removeMessageMetaArrayValuesWithMessage:metaArrays:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1removeMessageMetaArrayValues(message:metaArrays:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeMessageMetaArrayValuesWithMessage:metaArrays:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/title","value":"SBDBaseMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseMessage\/fragments","value":[{"kind":"identifier","text":"SBDBaseMessage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}