{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(resendFileMessageWithMessage:binaryData:progressHandler:completionHandler:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resendFileMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage","text":"FileMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"binaryData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"progressHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MultiProgressHandler","preciseIdentifier":"s:15SendbirdChatSDK20MultiProgressHandlera","text":"MultiProgressHandler"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18FileMessageHandlera","text":"FileMessageHandler"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage","text":"FileMessage"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns a temporary file message being sent to the Sendbird server."}]}]},{"kind":"parameters","parameters":[{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A message to send. A failed message is passed to the callback when fails to send a message"}]}]},{"name":"binaryData","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Data to resend. If the failed message has a file URL, the method will not send binary data."},{"type":"text","text":" "},{"type":"text","text":"If the failed message does not have a file URL, the method will send binary data first and send a file message"},{"type":"text","text":" "},{"type":"text","text":"command with file url."}]}]},{"name":"progressHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to be used to monitor progression. "},{"type":"codeVoice","code":"requestID"},{"type":"text","text":" is a unique identifier"},{"type":"text","text":" "},{"type":"text","text":"for the message send request. "},{"type":"codeVoice","code":"bytesSent"},{"type":"text","text":" is the number of bytes sent since this method was called."},{"type":"text","text":" "},{"type":"codeVoice","code":"totalBytesSent"},{"type":"text","text":" is the total number of bytes sent so far. "},{"type":"codeVoice","code":"totalBytesExpectedToSend"},{"type":"text","text":" is the expected"},{"type":"text","text":" "},{"type":"text","text":"length of the body data. These parameters are the same to the declaration of "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsessiontaskdelegate\/1408299-urlsession"},{"type":"text","text":"."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to be executed after the message is sent. This block has no return"},{"type":"text","text":" "},{"type":"text","text":"value and takes two arguments. One is a file message. If the message is successfully sent, the complete message"},{"type":"text","text":" "},{"type":"text","text":"instance is delivered. If the message fails to be sent, a failed message based on the pending message is delivered"},{"type":"text","text":" "},{"type":"text","text":"except invalid parameter error. If failed because of invalid parameter, message is nil. Another factor is errors. If the"},{"type":"text","text":" "},{"type":"text","text":"message fails to be sent, a message error is dispatched."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Only failed message MUST be passed, not a succeeded message or a pending message. If the failed"},{"type":"text","text":" "},{"type":"text","text":"message has a file URL, it means the failed message was created after failure of sending a file message"},{"type":"text","text":" "},{"type":"text","text":"command. So the method retries to send a file message command. If the failed message does not have"},{"type":"text","text":" "},{"type":"text","text":"a file URL, it means the failed message was created from failure of uploading a binary data. So the method"},{"type":"text","text":" "},{"type":"text","text":"retries to upload a binary data frist."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.147"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/resendfilemessage(_:binarydata:progresshandler:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/resendfilemessage(_:binarydata:progresshandler:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/resendFileMessage(_:binaryData:progressHandler:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Attempts to resend a failed file message received by the failure callback."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resendFileMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"binaryData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"progressHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MultiProgressHandler","preciseIdentifier":"s:15SendbirdChatSDK20MultiProgressHandlera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18FileMessageHandlera"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage"},{"kind":"text","text":"?"}],"title":"resendFileMessage(_:binaryData:progressHandler:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)resendFileMessageWithMessage:binaryData:progressHandler:completionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"resendFileMessageWithMessage:binaryData:progressHandler:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessageHandler":{"role":"symbol","title":"FileMessageHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessageHandler"}],"abstract":[{"type":"text","text":"File Message handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessageHandler"}],"url":"\/documentation\/sendbirdchatsdk\/filemessagehandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage":{"role":"symbol","title":"FileMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessage"}],"abstract":[{"type":"text","text":"Represents a mesage object that contains a file. Derived from "},{"type":"codeVoice","code":"BaseMessage"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessage"}],"url":"\/documentation\/sendbirdchatsdk\/filemessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MultiProgressHandler":{"role":"symbol","title":"MultiProgressHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiProgressHandler"}],"abstract":[{"type":"text","text":"multi file progress handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MultiProgressHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MultiProgressHandler"}],"url":"\/documentation\/sendbirdchatsdk\/multiprogresshandler"},"https://developer.apple.com/documentation/foundation/urlsessiontaskdelegate/1408299-urlsession":{"title":"urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)","titleInlineContent":[{"type":"codeVoice","code":"urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsessiontaskdelegate\/1408299-urlsession","url":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsessiontaskdelegate\/1408299-urlsession"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/resendFileMessage(_:binaryData:progressHandler:completionHandler:)":{"role":"symbol","title":"resendFileMessage(_:binaryData:progressHandler:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resendFileMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"binaryData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"progressHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MultiProgressHandler","preciseIdentifier":"s:15SendbirdChatSDK20MultiProgressHandlera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18FileMessageHandlera"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Attempts to resend a failed file message received by the failure callback."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/resendFileMessage(_:binaryData:progressHandler:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resendFileMessageWithMessage:binaryData:progressHandler:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/resendfilemessage(_:binarydata:progresshandler:completionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"resendFileMessageWithMessage:binaryData:progressHandler:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resendFileMessageWithMessage:binaryData:progressHandler:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage","text":"SBDFileMessage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"resendFileMessageWithMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage","text":"SBDFileMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"message"},{"kind":"text","text":" "},{"kind":"identifier","text":"binaryData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"binaryData"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSString *, long long, long long, long long)","preciseIdentifier":"c:BFv(#*$objc(cs)NSString#K#K#K)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"progressHandler"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDFileMessage *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDFileMessage#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage\/title","value":"SBDFileMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage\/fragments","value":[{"kind":"identifier","text":"SBDFileMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1resendFileMessage(_:binaryData:progressHandler:completionHandler:)\/title","value":"resendFileMessageWithMessage:binaryData:progressHandler:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1resendFileMessage(_:binaryData:progressHandler:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resendFileMessageWithMessage:binaryData:progressHandler:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}