{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(resendUserMessageWithMessage:completionHandler:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resendUserMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage","text":"UserMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18UserMessageHandlera","text":"UserMessageHandler"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage","text":"UserMessage"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns a temporary user message being sent to the Sendbird server."}]}]},{"kind":"parameters","parameters":[{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A message to send. A failed message is passed to the callback when fails to send a message"}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to be executed after the message is sent."},{"type":"text","text":" "},{"type":"text","text":"This block has no return value and takes two arguments. One is a user message. If the message is"},{"type":"text","text":" "},{"type":"text","text":"successfully sent, the complete message instance is delivered. If the message fails to be sent, a failed"},{"type":"text","text":" "},{"type":"text","text":"message based on the pending message is delivered. Another factor is errors. If the message fails"},{"type":"text","text":" "},{"type":"text","text":"to be sent, a message error is dispatched."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Only failed message MUST be passed, not a succeeded message or a pending message."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.141"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/resendusermessage(_:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/resendusermessage(_:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/resendUserMessage(_:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Attempts to resend a failed user message received by the failure callback."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resendUserMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18UserMessageHandlera"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage"}],"title":"resendUserMessage(_:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)resendUserMessageWithMessage:completionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"resendUserMessageWithMessage:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/resendUserMessage(_:completionHandler:)":{"role":"symbol","title":"resendUserMessage(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resendUserMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18UserMessageHandlera"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage"}],"abstract":[{"type":"text","text":"Attempts to resend a failed user message received by the failure callback."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/resendUserMessage(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resendUserMessageWithMessage:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/resendusermessage(_:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageHandler":{"role":"symbol","title":"UserMessageHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMessageHandler"}],"abstract":[{"type":"text","text":"User Message handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserMessageHandler"}],"url":"\/documentation\/sendbirdchatsdk\/usermessagehandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessage":{"role":"symbol","title":"UserMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMessage"}],"abstract":[{"type":"text","text":"Represents a mesage object that contains a text message. Derived from "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserMessage"}],"url":"\/documentation\/sendbirdchatsdk\/usermessage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"resendUserMessageWithMessage:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resendUserMessageWithMessage:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage","text":"SBDUserMessage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"resendUserMessageWithMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage","text":"SBDUserMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"message"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDUserMessage *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDUserMessage#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1resendUserMessage(_:completionHandler:)\/title","value":"resendUserMessageWithMessage:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1resendUserMessage(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resendUserMessageWithMessage:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessage\/title","value":"SBDUserMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessage\/fragments","value":[{"kind":"identifier","text":"SBDUserMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}