{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendFileMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessageCreateParams","text":"FileMessageCreateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18FileMessageHandlera","text":"FileMessageHandler"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage","text":"FileMessage"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns a temporary file message being sent to the Sendbird server. The message has a request ID instead of a message ID."},{"type":"text","text":" "},{"type":"text","text":"The request status of the message is pending. If you try to send a message with an invalid parameter, the returned message is a user"},{"type":"text","text":" "},{"type":"text","text":"message with no properties. You can perform a validation of pending message by checking for the existence of the request ID."}]}]},{"kind":"parameters","parameters":[{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Instance of "},{"type":"codeVoice","code":"FileMessageCreateParams"},{"type":"text","text":" that can has parameters related with file."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"handler block to be executed after the message was sent. This block has no return value"},{"type":"text","text":" "},{"type":"text","text":"and takes two argument, one is a file message was sent and other is an error made when there is something wrong to message."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the params has a binary file, it will upload data to Sendbird storage. If not, the params has a file url, it will send a message with file url."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/sendfilemessage(params:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/sendfilemessage(params:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/sendFileMessage(params:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sends a file message with file or file URL of params without progress."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendFileMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessageCreateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18FileMessageHandlera"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage"},{"kind":"text","text":"?"}],"title":"sendFileMessage(params:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)sendFileMessageWithParams:completionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"sendFileMessageWithParams:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessageCreateParams":{"role":"symbol","title":"FileMessageCreateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessageCreateParams"}],"abstract":[{"type":"text","text":"An object contains set of options to create "},{"type":"codeVoice","code":"FileMessage"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageCreateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessageCreateParams"}],"url":"\/documentation\/sendbirdchatsdk\/filemessagecreateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessageHandler":{"role":"symbol","title":"FileMessageHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessageHandler"}],"abstract":[{"type":"text","text":"File Message handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessageHandler"}],"url":"\/documentation\/sendbirdchatsdk\/filemessagehandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/sendFileMessage(params:completionHandler:)":{"role":"symbol","title":"sendFileMessage(params:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendFileMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessageCreateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18FileMessageHandlera"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sends a file message with file or file URL of params without progress."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/sendFileMessage(params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendFileMessageWithParams:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/sendfilemessage(params:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessage":{"role":"symbol","title":"FileMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessage"}],"abstract":[{"type":"text","text":"Represents a mesage object that contains a file. Derived from "},{"type":"codeVoice","code":"BaseMessage"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessage"}],"url":"\/documentation\/sendbirdchatsdk\/filemessage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sendFileMessageWithParams:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendFileMessageWithParams:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage","text":"SBDFileMessage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"sendFileMessageWithParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessageCreateParams","text":"SBDFileMessageCreateParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDFileMessage *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDFileMessage#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessageCreateParams\/title","value":"SBDFileMessageCreateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessageCreateParams\/fragments","value":[{"kind":"identifier","text":"SBDFileMessageCreateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1sendFileMessage(params:completionHandler:)\/title","value":"sendFileMessageWithParams:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1sendFileMessage(params:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendFileMessageWithParams:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage\/title","value":"SBDFileMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessage\/fragments","value":[{"kind":"identifier","text":"SBDFileMessage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}