{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"serialize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"optioanal "},{"type":"codeVoice","code":"Data"},{"type":"text","text":" instance"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/serialize()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/serialize()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/serialize()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Serializes this object into data"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"serialize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"title":"serialize()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)serialize","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"serialize"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/Serializable-Implementations"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/serialize()":{"role":"symbol","title":"serialize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"serialize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Serializes this object into data"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/serialize()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serialize"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/serialize()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/Serializable-Implementations":{"role":"collectionGroup","title":"Serializable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/Serializable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirdchatsdk\/basechannel\/serializable-implementations"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"serialize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"serialize"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"serialize"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1serialize()\/title","value":"serialize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1serialize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"serialize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}