{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"translateUserMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage","text":"UserMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetLanguages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18UserMessageHandlera","text":"UserMessageHandler"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The string type of the message of the user message instance will be translated."}]}]},{"name":"targetLanguages","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The target languages that the message will be translated into. e.g. “en”, “es”, “ch”"}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to be executed after translation. This block has no"},{"type":"text","text":" "},{"type":"text","text":"return value and takes two arguments. One is a user message. If succeeded to translate text of"},{"type":"text","text":" "},{"type":"text","text":"the message, the message instance with translations is delivered. If failed to translate, nil is delivered."},{"type":"text","text":" "},{"type":"text","text":"Another factor is an error. If failed to request, an error is dispatched."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can get a user message with the "},{"type":"codeVoice","code":"translations"},{"type":"text","text":" property after the request, but the request does"},{"type":"text","text":" "},{"type":"text","text":"not trigger an update event on the message and does not get the message by"},{"type":"text","text":" "},{"type":"codeVoice","code":"getMessageChangeLogs(token:params:completionHandler:)"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A translation request can affect not only your message, but also other people’s messages."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.148"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/translateusermessage(_:targetlanguages:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/translateusermessage(_:targetlanguages:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/translateUserMessage(_:targetLanguages:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Requests to translate the text message into the target languages."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"translateUserMessage:targetLanguages:completionHandler:"}],"role":"symbol","title":"translateUserMessage(_:targetLanguages:completionHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"translateUserMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetLanguages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18UserMessageHandlera"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)translateUserMessage:targetLanguages:completionHandler:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/translateUserMessage(_:targetLanguages:completionHandler:)":{"role":"symbol","title":"translateUserMessage(_:targetLanguages:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"translateUserMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetLanguages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18UserMessageHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Requests to translate the text message into the target languages."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/translateUserMessage(_:targetLanguages:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"translateUserMessage:targetLanguages:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/translateusermessage(_:targetlanguages:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessageHandler":{"role":"symbol","title":"UserMessageHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMessageHandler"}],"abstract":[{"type":"text","text":"User Message handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserMessageHandler"}],"url":"\/documentation\/sendbirdchatsdk\/usermessagehandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserMessage":{"role":"symbol","title":"UserMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserMessage"}],"abstract":[{"type":"text","text":"Represents a mesage object that contains a text message. Derived from "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserMessage"}],"url":"\/documentation\/sendbirdchatsdk\/usermessage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"translateUserMessage:targetLanguages:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"translateUserMessage:targetLanguages:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"translateUserMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage","text":"SBDUserMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"message"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetLanguages:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"targetLanguages"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDUserMessage *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDUserMessage#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1translateUserMessage(_:targetLanguages:completionHandler:)\/title","value":"translateUserMessage:targetLanguages:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1translateUserMessage(_:targetLanguages:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"translateUserMessage:targetLanguages:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessage\/title","value":"SBDUserMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserMessage\/fragments","value":[{"kind":"identifier","text":"SBDUserMessage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}