{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateFileMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messageID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessageUpdateParams","text":"FileMessageUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18FileMessageHandlera","text":"FileMessageHandler"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"messageID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The message ID of the message to be updated."}]}]},{"name":"FileMessageCreateParams","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The file message params that has updating fields."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to be executed after update."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.110"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/updatefilemessage(messageid:params:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/basechannel\/updatefilemessage(messageid:params:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/updateFileMessage(messageID:params:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Updates a file message. The data, custom type from file message params can be updated."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"updateFileMessageWithMessageID:params:completionHandler:"}],"role":"symbol","title":"updateFileMessage(messageID:params:completionHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateFileMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messageID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessageUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessageUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18FileMessageHandlera"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDBaseChannel(im)updateFileMessageWithMessageID:params:completionHandler:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessageUpdateParams":{"role":"symbol","title":"FileMessageUpdateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessageUpdateParams"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"FileMessageCreateParams"},{"type":"text","text":" class is used to send a file message in "},{"type":"codeVoice","code":"BaseChannel"},{"type":"text","text":". This is a child class of "},{"type":"codeVoice","code":"BaseMessageCreateParams"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageUpdateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessageUpdateParams"}],"url":"\/documentation\/sendbirdchatsdk\/filemessageupdateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel/updateFileMessage(messageID:params:completionHandler:)":{"role":"symbol","title":"updateFileMessage(messageID:params:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateFileMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messageID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessageUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessageUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18FileMessageHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Updates a file message. The data, custom type from file message params can be updated."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel\/updateFileMessage(messageID:params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateFileMessageWithMessageID:params:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel\/updatefilemessage(messageid:params:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessageHandler":{"role":"symbol","title":"FileMessageHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessageHandler"}],"abstract":[{"type":"text","text":"File Message handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessageHandler"}],"url":"\/documentation\/sendbirdchatsdk\/filemessagehandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/BaseChannel":{"role":"symbol","title":"BaseChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseChannel"}],"abstract":[{"type":"text","text":"An object represents base class for channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/BaseChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseChannel"}],"url":"\/documentation\/sendbirdchatsdk\/basechannel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateFileMessageWithMessageID:params:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateFileMessageWithMessageID:params:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateFileMessageWithMessageID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"messageID"},{"kind":"text","text":" "},{"kind":"identifier","text":"params:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessageUpdateParams","text":"SBDFileMessageUpdateParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDFileMessage *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDFileMessage#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessageUpdateParams\/title","value":"SBDFileMessageUpdateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1FileMessageUpdateParams\/fragments","value":[{"kind":"identifier","text":"SBDFileMessageUpdateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1updateFileMessage(messageID:params:completionHandler:)\/title","value":"updateFileMessageWithMessageID:params:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel~1updateFileMessage(messageID:params:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateFileMessageWithMessageID:params:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/title","value":"SBDBaseChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1BaseChannel\/fragments","value":[{"kind":"identifier","text":"SBDBaseChannel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}