{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"operation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEventAction","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReactionEventAction","text":"ReactionEventAction"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/reactionevent\/operation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/reactionevent\/operation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/operation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The operation that the user did. It will be adding a reaction or deleting a reaction."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"operation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReactionEventAction","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReactionEventAction"}],"title":"operation","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDReactionEvent(py)operation","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"operation"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReactionEvent/operation":{"role":"symbol","title":"operation","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"operation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReactionEventAction","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReactionEventAction"}],"abstract":[{"type":"text","text":"The operation that the user did. It will be adding a reaction or deleting a reaction."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent\/operation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"operation"}],"url":"\/documentation\/sendbirdchatsdk\/reactionevent\/operation"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReactionEvent":{"role":"symbol","title":"ReactionEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReactionEvent"}],"abstract":[{"type":"text","text":"An object represents reaction event info."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReactionEvent"}],"url":"\/documentation\/sendbirdchatsdk\/reactionevent"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ReactionEventAction":{"role":"symbol","title":"ReactionEventAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReactionEventAction"}],"abstract":[{"type":"text","text":"The ReactionEvent action state."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEventAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReactionEventAction"}],"url":"\/documentation\/sendbirdchatsdk\/reactioneventaction"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"operation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"operation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ReactionEventAction","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDReactionEventAction","text":"SBDReactionEventAction"},{"kind":"identifier","text":"operation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent~1operation\/title","value":"operation"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent~1operation\/fragments","value":[{"kind":"identifier","text":"operation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent\/title","value":"SBDReactionEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEvent\/fragments","value":[{"kind":"identifier","text":"SBDReactionEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEventAction\/title","value":"SBDReactionEventAction"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ReactionEventAction\/fragments","value":[{"kind":"identifier","text":"SBDReactionEventAction"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}