{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mutedMemberFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelMutedMemberFilter","text":"GroupChannelMutedMemberFilter"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.89"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/memberlistquery\/mutedmemberfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/memberlistquery\/mutedmemberfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/mutedMemberFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets a filter to query muted member list."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"mutedMemberFilter"}],"role":"symbol","title":"mutedMemberFilter","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mutedMemberFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelMutedMemberFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelMutedMemberFilter"}],"symbolKind":"property","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDMemberListQuery(py)mutedMemberFilter","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery":{"role":"symbol","title":"MemberListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MemberListQuery"},{"type":"text","text":" class is a query class for getting the list member in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelMutedMemberFilter":{"role":"symbol","title":"GroupChannelMutedMemberFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelMutedMemberFilter"}],"abstract":[{"type":"text","text":"Filter operators in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelMutedMemberFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelmutedmemberfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery/mutedMemberFilter":{"role":"symbol","title":"mutedMemberFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mutedMemberFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelMutedMemberFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelMutedMemberFilter"}],"abstract":[{"type":"text","text":"Sets a filter to query muted member list."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/mutedMemberFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mutedMemberFilter"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery\/mutedmemberfilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mutedMemberFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mutedMemberFilter"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelMutedMemberFilter","text":"SBDGroupChannelMutedMemberFilter"},{"kind":"identifier","text":"mutedMemberFilter"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery\/title","value":"SBDMemberListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery\/fragments","value":[{"kind":"identifier","text":"SBDMemberListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter\/title","value":"SBDGroupChannelMutedMemberFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1mutedMemberFilter\/title","value":"mutedMemberFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1mutedMemberFilter\/fragments","value":[{"kind":"identifier","text":"mutedMemberFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}