{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberListOrder","text":"MemberListOrder"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the "},{"type":"codeVoice","code":"order"},{"type":"text","text":" is "},{"type":"codeVoice","code":".nicknameAlphabetical"},{"type":"text","text":", the result will be ordered by the nickname in"},{"type":"text","text":" "},{"type":"text","text":"alphabetical order. If the "},{"type":"codeVoice","code":"order"},{"type":"text","text":" is "},{"type":"codeVoice","code":".operatorThenMemberNicknameAlphabetical"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"then the result will contain the operators first, and then the members. The two groups (operators"},{"type":"text","text":" "},{"type":"text","text":"and members) will be ordered by the nickname in alphabetical order. The default value is "},{"type":"codeVoice","code":".nicknameAlphabetical"},{"type":"text","text":"."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.198"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/memberlistquery\/order"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/memberlistquery\/order"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/order","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets how the query result should be ordered."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MemberListOrder","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberListOrder"}],"title":"order","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDMemberListQuery(py)order","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"order"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListOrder":{"role":"symbol","title":"MemberListOrder","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListOrder"}],"abstract":[{"type":"text","text":"The order type for member list query."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListOrder"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistorder"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery":{"role":"symbol","title":"MemberListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MemberListQuery"},{"type":"text","text":" class is a query class for getting the list member in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery/order":{"role":"symbol","title":"order","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MemberListOrder","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberListOrder"}],"abstract":[{"type":"text","text":"Sets how the query result should be ordered."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery\/order","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"order"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery\/order"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"order"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"order"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListOrder","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberListOrder","text":"SBDMemberListOrder"},{"kind":"identifier","text":"order"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder\/title","value":"SBDMemberListOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListOrder\/fragments","value":[{"kind":"identifier","text":"SBDMemberListOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery\/title","value":"SBDMemberListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery\/fragments","value":[{"kind":"identifier","text":"SBDMemberListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1order\/title","value":"order"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery~1order\/fragments","value":[{"kind":"identifier","text":"order"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}