{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memberStateFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberStateFilter","text":"MemberStateFilter"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/memberlistqueryparams\/memberstatefilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/memberlistqueryparams\/memberstatefilter"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams\/memberStateFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets a filter to query member list with member state."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memberStateFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MemberStateFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberStateFilter"}],"title":"memberStateFilter","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQueryParams(py)memberStateFilter","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"memberStateFilter"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberStateFilter":{"role":"symbol","title":"MemberStateFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberStateFilter"}],"abstract":[{"type":"text","text":"Member state filter for group channel list query and group channel count"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberStateFilter"}],"url":"\/documentation\/sendbirdchatsdk\/memberstatefilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQueryParams":{"role":"symbol","title":"MemberListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQueryParams/memberStateFilter":{"role":"symbol","title":"memberStateFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memberStateFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MemberStateFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberStateFilter"}],"abstract":[{"type":"text","text":"Sets a filter to query member list with member state."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams\/memberStateFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"memberStateFilter"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistqueryparams\/memberstatefilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"memberStateFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"memberStateFilter"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberStateFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDMemberStateFilter","text":"SBDMemberStateFilter"},{"kind":"identifier","text":"memberStateFilter"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter\/title","value":"SBDMemberStateFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberStateFilter\/fragments","value":[{"kind":"identifier","text":"SBDMemberStateFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams\/title","value":"SBDMemberListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDMemberListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams~1memberStateFilter\/title","value":"memberStateFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams~1memberStateFilter\/fragments","value":[{"kind":"identifier","text":"memberStateFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}