{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mutedMemberFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelMutedMemberFilter","text":"GroupChannelMutedMemberFilter"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.89"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/memberlistqueryparams\/mutedmemberfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/memberlistqueryparams\/mutedmemberfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams\/mutedMemberFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets a filter to query muted member list."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mutedMemberFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelMutedMemberFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelMutedMemberFilter"}],"title":"mutedMemberFilter","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQueryParams(py)mutedMemberFilter","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"mutedMemberFilter"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQueryParams":{"role":"symbol","title":"MemberListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQueryParams/mutedMemberFilter":{"role":"symbol","title":"mutedMemberFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mutedMemberFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelMutedMemberFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelMutedMemberFilter"}],"abstract":[{"type":"text","text":"Sets a filter to query muted member list."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams\/mutedMemberFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mutedMemberFilter"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistqueryparams\/mutedmemberfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelMutedMemberFilter":{"role":"symbol","title":"GroupChannelMutedMemberFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelMutedMemberFilter"}],"abstract":[{"type":"text","text":"Filter operators in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelMutedMemberFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelmutedmemberfilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mutedMemberFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mutedMemberFilter"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelMutedMemberFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelMutedMemberFilter","text":"SBDGroupChannelMutedMemberFilter"},{"kind":"identifier","text":"mutedMemberFilter"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams\/title","value":"SBDMemberListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDMemberListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams~1mutedMemberFilter\/title","value":"mutedMemberFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams~1mutedMemberFilter\/fragments","value":[{"kind":"identifier","text":"mutedMemberFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter\/title","value":"SBDGroupChannelMutedMemberFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelMutedMemberFilter\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelMutedMemberFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}