{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatorFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelOperatorFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelOperatorFilter","text":"GroupChannelOperatorFilter"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.89"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/memberlistqueryparams\/operatorfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/memberlistqueryparams\/operatorfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams\/operatorFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets a filter to query operators."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatorFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelOperatorFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelOperatorFilter"}],"title":"operatorFilter","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQueryParams(py)operatorFilter","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"operatorFilter"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQueryParams":{"role":"symbol","title":"MemberListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelOperatorFilter":{"role":"symbol","title":"GroupChannelOperatorFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelOperatorFilter"}],"abstract":[{"type":"text","text":"Filter operators in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelOperatorFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelOperatorFilter"}],"url":"\/documentation\/sendbirdchatsdk\/groupchanneloperatorfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQueryParams/operatorFilter":{"role":"symbol","title":"operatorFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatorFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelOperatorFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelOperatorFilter"}],"abstract":[{"type":"text","text":"Sets a filter to query operators."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams\/operatorFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"operatorFilter"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistqueryparams\/operatorfilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"operatorFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"operatorFilter"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelOperatorFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelOperatorFilter","text":"SBDGroupChannelOperatorFilter"},{"kind":"identifier","text":"operatorFilter"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams\/title","value":"SBDMemberListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDMemberListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelOperatorFilter\/title","value":"SBDGroupChannelOperatorFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelOperatorFilter\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelOperatorFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams~1operatorFilter\/title","value":"operatorFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams~1operatorFilter\/fragments","value":[{"kind":"identifier","text":"operatorFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}