{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageSearchQueryParams","text":"MessageSearchQueryParams"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagesearchquery\/params"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagesearchquery\/params"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQuery\/params","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageSearchQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageSearchQueryParams"}],"title":"params","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageSearchQuery(py)params","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"params"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQuery"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQuery/params":{"role":"symbol","title":"params","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageSearchQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageSearchQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQuery\/params","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"params"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchquery\/params"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQuery":{"role":"symbol","title":"MessageSearchQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSearchQuery"}],"abstract":[{"type":"text","text":"A class representing query to retrieve list of "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":"s that matches a given"},{"type":"text","text":" "},{"type":"text","text":"query with given filters. "},{"type":"codeVoice","code":"MessageSearchQuery"},{"type":"text","text":" can be generated by using"},{"type":"text","text":" "},{"type":"codeVoice","code":"MessageSearchQueryBuilder"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageSearchQuery"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQueryParams":{"role":"symbol","title":"MessageSearchQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSearchQueryParams"}],"abstract":[{"type":"text","text":"Message search query builder"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageSearchQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"params"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"params"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageSearchQueryParams","text":"SBDMessageSearchQueryParams"},{"kind":"text","text":" *"},{"kind":"identifier","text":"params"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQuery~1params\/title","value":"params"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQuery~1params\/fragments","value":[{"kind":"identifier","text":"params"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQuery\/title","value":"SBDMessageSearchQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQuery\/fragments","value":[{"kind":"identifier","text":"SBDMessageSearchQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryParams\/title","value":"SBDMessageSearchQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDMessageSearchQueryParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}