{"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/messagesearchquery\/serializable-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/messagesearchquery\/serializable-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQuery\/Serializable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQuery\/serialize()"],"generated":true},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQuery\/build(fromSerializedData:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"SendbirdChatSDK"}],"role":"collectionGroup","title":"Serializable Implementations"},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQuery"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQuery":{"role":"symbol","title":"MessageSearchQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSearchQuery"}],"abstract":[{"type":"text","text":"A class representing query to retrieve list of "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":"s that matches a given"},{"type":"text","text":" "},{"type":"text","text":"query with given filters. "},{"type":"codeVoice","code":"MessageSearchQuery"},{"type":"text","text":" can be generated by using"},{"type":"text","text":" "},{"type":"codeVoice","code":"MessageSearchQueryBuilder"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageSearchQuery"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQuery/build(fromSerializedData:)":{"role":"symbol","title":"build(fromSerializedData:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromSerializedData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?) -> `Self`"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Deserializes and reconstructs the object"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQuery\/build(fromSerializedData:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildFromSerializedData:"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchquery\/build(fromserializeddata:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MessageSearchQuery/serialize()":{"role":"symbol","title":"serialize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"serialize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Serializes this object into data"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQuery\/serialize()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serialize"}],"url":"\/documentation\/sendbirdchatsdk\/messagesearchquery\/serialize()"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQuery\/serialize()"],"generated":true},{"title":"Type Methods","identifiers":["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MessageSearchQuery\/build(fromSerializedData:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQuery\/title","value":"SBDMessageSearchQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQuery\/fragments","value":[{"kind":"identifier","text":"SBDMessageSearchQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQuery~1build(fromSerializedData:)\/title","value":"buildFromSerializedData:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQuery~1build(fromSerializedData:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildFromSerializedData:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQuery~1serialize()\/title","value":"serialize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MessageSearchQuery~1serialize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"serialize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}