{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(makeWithThumbnail:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"make"},{"kind":"text","text":"("},{"kind":"externalParam","text":"thumbnail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Thumbnail","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnail","text":"Thumbnail"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize","text":"ThumbnailSize"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" object."}]}]},{"kind":"parameters","parameters":[{"name":"thumbnail","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Thumbnail"},{"type":"text","text":" object"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/thumbnailsize\/make(thumbnail:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/thumbnailsize\/make(thumbnail:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/make(thumbnail:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Makes "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" object with thumbnail"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"make"},{"kind":"text","text":"("},{"kind":"externalParam","text":"thumbnail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Thumbnail","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnail"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize"}],"title":"make(thumbnail:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize(cm)makeWithThumbnail:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"makeWithThumbnail:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Thumbnail":{"role":"symbol","title":"Thumbnail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Thumbnail"}],"abstract":[{"type":"text","text":"Represents a thumbnail information"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Thumbnail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Thumbnail"}],"url":"\/documentation\/sendbirdchatsdk\/thumbnail"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThumbnailSize":{"role":"symbol","title":"ThumbnailSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailSize"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" class represents the thumbnail size of thumbnail."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThumbnailSize"}],"url":"\/documentation\/sendbirdchatsdk\/thumbnailsize"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThumbnailSize/make(thumbnail:)":{"role":"symbol","title":"make(thumbnail:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"make"},{"kind":"text","text":"("},{"kind":"externalParam","text":"thumbnail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Thumbnail","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnail"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize"}],"abstract":[{"type":"text","text":"Makes "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" object with thumbnail"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/make(thumbnail:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"makeWithThumbnail:"}],"url":"\/documentation\/sendbirdchatsdk\/thumbnailsize\/make(thumbnail:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"makeWithThumbnail:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"makeWithThumbnail:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize","text":"SBDThumbnailSize"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"makeWithThumbnail:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Thumbnail","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnail","text":"SBDThumbnail"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"thumbnail"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Thumbnail\/title","value":"SBDThumbnail"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Thumbnail\/fragments","value":[{"kind":"identifier","text":"SBDThumbnail"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize\/title","value":"SBDThumbnailSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize\/fragments","value":[{"kind":"identifier","text":"SBDThumbnailSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize~1make(thumbnail:)\/title","value":"makeWithThumbnail:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize~1make(thumbnail:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"makeWithThumbnail:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}