{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(makeWithMaxWidth:maxHeight:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"make"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize","text":"ThumbnailSize"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" object."}]}]},{"kind":"parameters","parameters":[{"name":"maxWidth","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The max width of the thumbnail."}]}]},{"name":"maxHeight","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The max height of the thumbnail."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/thumbnailsize\/make(maxwidth:maxheight:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/thumbnailsize\/make(maxwidth:maxheight:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/make(maxWidth:maxHeight:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Makes "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" object with width and height."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"make"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize"}],"title":"make(maxWidth:maxHeight:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize(cm)makeWithMaxWidth:maxHeight:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"makeWithMaxWidth:maxHeight:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThumbnailSize/make(maxWidth:maxHeight:)":{"role":"symbol","title":"make(maxWidth:maxHeight:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"make"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize"}],"abstract":[{"type":"text","text":"Makes "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" object with width and height."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize\/make(maxWidth:maxHeight:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"makeWithMaxWidth:maxHeight:"}],"url":"\/documentation\/sendbirdchatsdk\/thumbnailsize\/make(maxwidth:maxheight:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ThumbnailSize":{"role":"symbol","title":"ThumbnailSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailSize"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ThumbnailSize"},{"type":"text","text":" class represents the thumbnail size of thumbnail."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThumbnailSize"}],"url":"\/documentation\/sendbirdchatsdk\/thumbnailsize"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"makeWithMaxWidth:maxHeight:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"makeWithMaxWidth:maxHeight:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ThumbnailSize","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDThumbnailSize","text":"SBDThumbnailSize"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"makeWithMaxWidth:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":")"},{"kind":"internalParam","text":"maxWidth"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxHeight:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":")"},{"kind":"internalParam","text":"maxHeight"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize~1make(maxWidth:maxHeight:)\/title","value":"makeWithMaxWidth:maxHeight:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize~1make(maxWidth:maxHeight:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"makeWithMaxWidth:maxHeight:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize\/title","value":"SBDThumbnailSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ThumbnailSize\/fragments","value":[{"kind":"identifier","text":"SBDThumbnailSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}