{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEmojiUpdateNeeded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"prevEmojiHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"prevEmojiHash","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Emoji hash value in use"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Since 3.0.180"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/appinfo\/isemojiupdateneeded(prevemojihash:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/appinfo\/isemojiupdateneeded(prevemojihash:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/isEmojiUpdateNeeded(prevEmojiHash:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function can check if Emoji information needs to be updated to date."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEmojiUpdateNeeded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"prevEmojiHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isEmojiUpdateNeeded(prevEmojiHash:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDAppInfo(im)isEmojiUpdateNeededWithPrevEmojiHash:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"isEmojiUpdateNeededWithPrevEmojiHash:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppInfo":{"role":"symbol","title":"AppInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppInfo"}],"abstract":[{"type":"text","text":"An object contains application information"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppInfo"}],"url":"\/documentation\/sendbirdchatsdk\/appinfo"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/AppInfo/isEmojiUpdateNeeded(prevEmojiHash:)":{"role":"symbol","title":"isEmojiUpdateNeeded(prevEmojiHash:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEmojiUpdateNeeded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"prevEmojiHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"This function can check if Emoji information needs to be updated to date."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/AppInfo\/isEmojiUpdateNeeded(prevEmojiHash:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEmojiUpdateNeededWithPrevEmojiHash:"}],"url":"\/documentation\/sendbirdchatsdk\/appinfo\/isemojiupdateneeded(prevemojihash:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"isEmojiUpdateNeededWithPrevEmojiHash:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEmojiUpdateNeededWithPrevEmojiHash:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEmojiUpdateNeededWithPrevEmojiHash:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"prevEmojiHash"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo\/title","value":"SBDAppInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo\/fragments","value":[{"kind":"identifier","text":"SBDAppInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1isEmojiUpdateNeeded(prevEmojiHash:)\/title","value":"isEmojiUpdateNeededWithPrevEmojiHash:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1AppInfo~1isEmojiUpdateNeeded(prevEmojiHash:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEmojiUpdateNeededWithPrevEmojiHash:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}