{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeEmptyChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/includeemptychannel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/includeemptychannel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/includeEmptyChannel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Determines channel list includes empty channel. Deafult is "},{"type":"codeVoice","code":"true"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeEmptyChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"includeEmptyChannel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDPublicGroupChannelListQueryParams(py)includeEmptyChannel","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"includeEmptyChannel"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/includeEmptyChannel":{"role":"symbol","title":"includeEmptyChannel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeEmptyChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines channel list includes empty channel. Deafult is "},{"type":"codeVoice","code":"true"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/includeEmptyChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeEmptyChannel"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/includeemptychannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams":{"role":"symbol","title":"PublicGroupChannelListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicGroupChannelListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PublicGroupChannelListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"includeEmptyChannel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"includeEmptyChannel"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"identifier","text":"includeEmptyChannel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1includeEmptyChannel\/title","value":"includeEmptyChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1includeEmptyChannel\/fragments","value":[{"kind":"identifier","text":"includeEmptyChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams\/title","value":"SBDPublicGroupChannelListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelListQueryParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}