{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicMembershipFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelMembershipFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDPublicGroupChannelMembershipFilter","text":"PublicGroupChannelMembershipFilter"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" list containing only and exactly the passed "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" URLs will be returned."}]},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This does not cooperate with other filters."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/publicmembershipfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/publicmembershipfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/publicMembershipFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" URLs filter."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicMembershipFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PublicGroupChannelMembershipFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDPublicGroupChannelMembershipFilter"}],"title":"publicMembershipFilter","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDPublicGroupChannelListQueryParams(py)publicMembershipFilter","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"publicMembershipFilter"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelMembershipFilter":{"role":"symbol","title":"PublicGroupChannelMembershipFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicGroupChannelMembershipFilter"}],"abstract":[{"type":"text","text":"Filter my channels or all ones in public group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelMembershipFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PublicGroupChannelMembershipFilter"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannelmembershipfilter"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams":{"role":"symbol","title":"PublicGroupChannelListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicGroupChannelListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PublicGroupChannelListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PublicGroupChannelListQueryParams/publicMembershipFilter":{"role":"symbol","title":"publicMembershipFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicMembershipFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PublicGroupChannelMembershipFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDPublicGroupChannelMembershipFilter"}],"abstract":[{"type":"text","text":"Sets "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" URLs filter."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelListQueryParams\/publicMembershipFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publicMembershipFilter"}],"url":"\/documentation\/sendbirdchatsdk\/publicgroupchannellistqueryparams\/publicmembershipfilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"publicMembershipFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"publicMembershipFilter"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PublicGroupChannelMembershipFilter","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDPublicGroupChannelMembershipFilter","text":"SBDPublicGroupChannelMembershipFilter"},{"kind":"identifier","text":"publicMembershipFilter"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelMembershipFilter\/title","value":"SBDPublicGroupChannelMembershipFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelMembershipFilter\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelMembershipFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams\/title","value":"SBDPublicGroupChannelListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDPublicGroupChannelListQueryParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1publicMembershipFilter\/title","value":"publicMembershipFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PublicGroupChannelListQueryParams~1publicMembershipFilter\/fragments","value":[{"kind":"identifier","text":"publicMembershipFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}