{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scheduledAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fileURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An initialized file message params."}]}]},{"kind":"parameters","parameters":[{"name":"fileURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The file URL to be sent."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/scheduledfilemessagecreateparams\/init(scheduledat:fileurl:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/scheduledfilemessagecreateparams\/init(scheduledat:fileurl:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledFileMessageCreateParams\/init(scheduledAt:fileURL:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes and returns a params object for creating a scheduled file message with the given file URL."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scheduledAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fileURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"init(scheduledAt:fileURL:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledFileMessageCreateParams(im)initWithScheduledAt:fileURL:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithScheduledAt:fileURL:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledFileMessageCreateParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledFileMessageCreateParams":{"role":"symbol","title":"ScheduledFileMessageCreateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledFileMessageCreateParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledFileMessageCreateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledFileMessageCreateParams"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledfilemessagecreateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledFileMessageCreateParams/init(scheduledAt:fileURL:)":{"role":"symbol","title":"init(scheduledAt:fileURL:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scheduledAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fileURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes and returns a params object for creating a scheduled file message with the given file URL."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledFileMessageCreateParams\/init(scheduledAt:fileURL:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithScheduledAt:fileURL:"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledfilemessagecreateparams\/init(scheduledat:fileurl:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithScheduledAt:fileURL:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithScheduledAt:fileURL:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithScheduledAt:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"scheduledAt"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"fileURL"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledFileMessageCreateParams\/title","value":"SBDScheduledFileMessageCreateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledFileMessageCreateParams\/fragments","value":[{"kind":"identifier","text":"SBDScheduledFileMessageCreateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledFileMessageCreateParams~1init(scheduledAt:fileURL:)\/title","value":"initWithScheduledAt:fileURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledFileMessageCreateParams~1init(scheduledAt:fileURL:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithScheduledAt:fileURL:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}