{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGImage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOGImage","text":"OGImage"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/ogmetadata\/defaultimage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/ogmetadata\/defaultimage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/defaultImage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An image object which should represent the object within the graph"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OGImage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOGImage"},{"kind":"text","text":"?"}],"title":"defaultImage","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDOGMetaData(py)defaultImage","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"defaultImage"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OGMetaData/defaultImage":{"role":"symbol","title":"defaultImage","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OGImage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOGImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"An image object which should represent the object within the graph"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData\/defaultImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultImage"}],"url":"\/documentation\/sendbirdchatsdk\/ogmetadata\/defaultimage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OGImage":{"role":"symbol","title":"OGImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OGImage"}],"abstract":[{"type":"text","text":"Represents OpenGraph Image information"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OGImage"}],"url":"\/documentation\/sendbirdchatsdk\/ogimage"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/OGMetaData":{"role":"symbol","title":"OGMetaData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OGMetaData"}],"abstract":[{"type":"text","text":"Represents OpenGraph information"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGMetaData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OGMetaData"}],"url":"\/documentation\/sendbirdchatsdk\/ogmetadata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"defaultImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultImage"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/OGImage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOGImage","text":"SBDOGImage"},{"kind":"text","text":" *"},{"kind":"identifier","text":"defaultImage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGMetaData~1defaultImage\/title","value":"defaultImage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGMetaData~1defaultImage\/fragments","value":[{"kind":"identifier","text":"defaultImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGImage\/title","value":"SBDOGImage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGImage\/fragments","value":[{"kind":"identifier","text":"SBDOGImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGMetaData\/title","value":"SBDOGMetaData"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1OGMetaData\/fragments","value":[{"kind":"identifier","text":"SBDOGMetaData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}