{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/scheduledbasemessagecreateparams\/customtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/scheduledbasemessagecreateparams\/customtype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageCreateParams\/customType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The custom type of the message. The default value is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"customType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledBaseMessageCreateParams(py)customType","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"customType"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageCreateParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledBaseMessageCreateParams/customType":{"role":"symbol","title":"customType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The custom type of the message. The default value is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageCreateParams\/customType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customType"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledbasemessagecreateparams\/customtype"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledBaseMessageCreateParams":{"role":"symbol","title":"ScheduledBaseMessageCreateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledBaseMessageCreateParams"}],"abstract":[{"type":"text","text":"A base class to create a scheduled message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageCreateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledBaseMessageCreateParams"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledbasemessagecreateparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"customType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"customType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *"},{"kind":"identifier","text":"customType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageCreateParams~1customType\/title","value":"customType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageCreateParams~1customType\/fragments","value":[{"kind":"identifier","text":"customType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageCreateParams\/title","value":"SBDScheduledBaseMessageCreateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageCreateParams\/fragments","value":[{"kind":"identifier","text":"SBDScheduledBaseMessageCreateParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}