{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushNotificationDeliveryOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDPushNotificationDeliveryOption","text":"PushNotificationDeliveryOption"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/scheduledbasemessagecreateparams\/pushnotificationdeliveryoption"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/scheduledbasemessagecreateparams\/pushnotificationdeliveryoption"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageCreateParams\/pushNotificationDeliveryOption","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The push notification delivery option that determines how to deliver the push notification when sending"},{"type":"text","text":" "},{"type":"text","text":"a user or a file message. The default value is "},{"type":"codeVoice","code":".default"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushNotificationDeliveryOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushNotificationDeliveryOption","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDPushNotificationDeliveryOption"}],"title":"pushNotificationDeliveryOption","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledBaseMessageCreateParams(py)pushNotificationDeliveryOption","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"pushNotificationDeliveryOption"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageCreateParams"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledBaseMessageCreateParams/pushNotificationDeliveryOption":{"role":"symbol","title":"pushNotificationDeliveryOption","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushNotificationDeliveryOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushNotificationDeliveryOption","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDPushNotificationDeliveryOption"}],"abstract":[{"type":"text","text":"The push notification delivery option that determines how to deliver the push notification when sending"},{"type":"text","text":" "},{"type":"text","text":"a user or a file message. The default value is "},{"type":"codeVoice","code":".default"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageCreateParams\/pushNotificationDeliveryOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pushNotificationDeliveryOption"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledbasemessagecreateparams\/pushnotificationdeliveryoption"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledBaseMessageCreateParams":{"role":"symbol","title":"ScheduledBaseMessageCreateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledBaseMessageCreateParams"}],"abstract":[{"type":"text","text":"A base class to create a scheduled message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledBaseMessageCreateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledBaseMessageCreateParams"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledbasemessagecreateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/PushNotificationDeliveryOption":{"role":"symbol","title":"PushNotificationDeliveryOption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationDeliveryOption"}],"abstract":[{"type":"text","text":"The push option that determines how to deliver the push notification when sending a user or a file message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationDeliveryOption"}],"url":"\/documentation\/sendbirdchatsdk\/pushnotificationdeliveryoption"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"pushNotificationDeliveryOption"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"pushNotificationDeliveryOption"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/PushNotificationDeliveryOption","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDPushNotificationDeliveryOption","text":"SBDPushNotificationDeliveryOption"},{"kind":"identifier","text":"pushNotificationDeliveryOption"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageCreateParams~1pushNotificationDeliveryOption\/title","value":"pushNotificationDeliveryOption"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageCreateParams~1pushNotificationDeliveryOption\/fragments","value":[{"kind":"identifier","text":"pushNotificationDeliveryOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageCreateParams\/title","value":"SBDScheduledBaseMessageCreateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledBaseMessageCreateParams\/fragments","value":[{"kind":"identifier","text":"SBDScheduledBaseMessageCreateParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption\/title","value":"SBDPushNotificationDeliveryOption"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1PushNotificationDeliveryOption\/fragments","value":[{"kind":"identifier","text":"SBDPushNotificationDeliveryOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}