{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonAvailable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/userconnectionstatus\/nonavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/userconnectionstatus\/nonavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/nonAvailable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"For unavailable user."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonAvailable"}],"title":"UserConnectionStatus.nonAvailable","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDUserConnectionStatus@SBDUserConnectionStatusNonAvailable","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDUserConnectionStatusNonAvailable"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserConnectionStatus":{"role":"symbol","title":"UserConnectionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserConnectionStatus"}],"abstract":[{"type":"text","text":"User connection statuses for "},{"type":"codeVoice","code":"User"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserConnectionStatus"}],"url":"\/documentation\/sendbirdchatsdk\/userconnectionstatus"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserConnectionStatus/nonAvailable":{"role":"symbol","title":"UserConnectionStatus.nonAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonAvailable"}],"abstract":[{"type":"text","text":"For unavailable user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/nonAvailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUserConnectionStatusNonAvailable"}],"url":"\/documentation\/sendbirdchatsdk\/userconnectionstatus\/nonavailable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDUserConnectionStatusNonAvailable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUserConnectionStatusNonAvailable"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDUserConnectionStatusNonAvailable"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus\/title","value":"SBDUserConnectionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus\/fragments","value":[{"kind":"identifier","text":"SBDUserConnectionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus~1nonAvailable\/title","value":"SBDUserConnectionStatusNonAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus~1nonAvailable\/fragments","value":[{"kind":"identifier","text":"SBDUserConnectionStatusNonAvailable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}