{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"offline"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/userconnectionstatus\/offline"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/userconnectionstatus\/offline"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/offline","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"For off-line user."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"offline"}],"title":"UserConnectionStatus.offline","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDUserConnectionStatus@SBDUserConnectionStatusOffline","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDUserConnectionStatusOffline"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserConnectionStatus":{"role":"symbol","title":"UserConnectionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserConnectionStatus"}],"abstract":[{"type":"text","text":"User connection statuses for "},{"type":"codeVoice","code":"User"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserConnectionStatus"}],"url":"\/documentation\/sendbirdchatsdk\/userconnectionstatus"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserConnectionStatus/offline":{"role":"symbol","title":"UserConnectionStatus.offline","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"offline"}],"abstract":[{"type":"text","text":"For off-line user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/offline","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUserConnectionStatusOffline"}],"url":"\/documentation\/sendbirdchatsdk\/userconnectionstatus\/offline"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDUserConnectionStatusOffline"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUserConnectionStatusOffline"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDUserConnectionStatusOffline"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus\/title","value":"SBDUserConnectionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus\/fragments","value":[{"kind":"identifier","text":"SBDUserConnectionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus~1offline\/title","value":"SBDUserConnectionStatusOffline"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus~1offline\/fragments","value":[{"kind":"identifier","text":"SBDUserConnectionStatusOffline"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}