{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"online"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/userconnectionstatus\/online"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/userconnectionstatus\/online"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/online","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"For on-line user."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"online"}],"title":"UserConnectionStatus.online","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdChatSDK@E@SBDUserConnectionStatus@SBDUserConnectionStatusOnline","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBDUserConnectionStatusOnline"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserConnectionStatus/online":{"role":"symbol","title":"UserConnectionStatus.online","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"online"}],"abstract":[{"type":"text","text":"For on-line user."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus\/online","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBDUserConnectionStatusOnline"}],"url":"\/documentation\/sendbirdchatsdk\/userconnectionstatus\/online"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UserConnectionStatus":{"role":"symbol","title":"UserConnectionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserConnectionStatus"}],"abstract":[{"type":"text","text":"User connection statuses for "},{"type":"codeVoice","code":"User"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UserConnectionStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserConnectionStatus"}],"url":"\/documentation\/sendbirdchatsdk\/userconnectionstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBDUserConnectionStatusOnline"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBDUserConnectionStatusOnline"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBDUserConnectionStatusOnline"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus~1online\/title","value":"SBDUserConnectionStatusOnline"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus~1online\/fragments","value":[{"kind":"identifier","text":"SBDUserConnectionStatusOnline"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus\/title","value":"SBDUserConnectionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UserConnectionStatus\/fragments","value":[{"kind":"identifier","text":"SBDUserConnectionStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}