{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emojis"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Emoji","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDEmoji","text":"Emoji"},{"kind":"text","text":"] { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/emojicategory\/emojis"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/emojicategory\/emojis"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiCategory\/emojis","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Emoji list"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emojis"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Emoji","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDEmoji"},{"kind":"text","text":"]"}],"title":"emojis","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDEmojiCategory(py)emojis","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"emojis"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiCategory"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/EmojiCategory/emojis":{"role":"symbol","title":"emojis","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emojis"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Emoji","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDEmoji"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Emoji list"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiCategory\/emojis","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"emojis"}],"url":"\/documentation\/sendbirdchatsdk\/emojicategory\/emojis"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/EmojiCategory":{"role":"symbol","title":"EmojiCategory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmojiCategory"}],"abstract":[{"type":"text","text":"Class to represent emoji cateogry"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/EmojiCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmojiCategory"}],"url":"\/documentation\/sendbirdchatsdk\/emojicategory"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/Emoji":{"role":"symbol","title":"Emoji","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Emoji"}],"abstract":[{"type":"text","text":"Class to represent emoji"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/Emoji","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Emoji"}],"url":"\/documentation\/sendbirdchatsdk\/emoji"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"emojis"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"emojis"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBDEmoji *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *"},{"kind":"identifier","text":"emojis"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiCategory~1emojis\/title","value":"emojis"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiCategory~1emojis\/fragments","value":[{"kind":"identifier","text":"emojis"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiCategory\/title","value":"SBDEmojiCategory"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1EmojiCategory\/fragments","value":[{"kind":"identifier","text":"SBDEmojiCategory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Emoji\/title","value":"SBDEmoji"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1Emoji\/fragments","value":[{"kind":"identifier","text":"SBDEmoji"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}