{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"compare"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelA"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel","text":"GroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelB"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel","text":"GroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListOrder","text":"GroupChannelListOrder"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"channelA","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"First channel object."}]}]},{"name":"channelB","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Second channel obejct."}]}]},{"name":"order","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Order."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.227"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/compare(channela:channelb:order:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/compare(channela:channelb:order:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/compare(channelA:channelB:order:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Compares two channel objects with the channel list order."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"compare"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelA"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelB"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListOrder","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListOrder"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"compare(channelA:channelB:order:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel(cm)compareWithChannelA:channelB:order:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"compareWithChannelA:channelB:order:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel":{"role":"symbol","title":"GroupChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" class represents a group channel which is a private chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelListOrder":{"role":"symbol","title":"GroupChannelListOrder","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelListOrder"}],"abstract":[{"type":"text","text":"The order type for "},{"type":"codeVoice","code":"GroupChannelListQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelListOrder"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannellistorder"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel/compare(channelA:channelB:order:)":{"role":"symbol","title":"compare(channelA:channelB:order:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"compare"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelA"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelB"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListOrder","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListOrder"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Compares two channel objects with the channel list order."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/compare(channelA:channelB:order:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"compareWithChannelA:channelB:order:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel\/compare(channela:channelb:order:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"compareWithChannelA:channelB:order:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"compareWithChannelA:channelB:order:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"compareWithChannelA:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel","text":"SBDGroupChannel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelA"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelB:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel","text":"SBDGroupChannel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelB"},{"kind":"text","text":" "},{"kind":"identifier","text":"order:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelListOrder","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelListOrder","text":"SBDGroupChannelListOrder"},{"kind":"text","text":")"},{"kind":"internalParam","text":"order"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/title","value":"SBDGroupChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder\/title","value":"SBDGroupChannelListOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelListOrder\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelListOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1compare(channelA:channelB:order:)\/title","value":"compareWithChannelA:channelB:order:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1compare(channelA:channelB:order:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"compareWithChannelA:channelB:order:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}