{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMemberListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQueryParams","text":"MemberListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQuery","text":"MemberListQuery"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The instance to query the members in group channel."}]}]},{"kind":"parameters","parameters":[{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The params object to change query condition."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/creatememberlistquery(params:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/creatememberlistquery(params:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/createMemberListQuery(params:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a query for members in group channel."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"createMemberListQueryWithParams:"}],"role":"symbol","title":"createMemberListQuery(params:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMemberListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MemberListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MemberListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQuery"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDGroupChannel(im)createMemberListQueryWithParams:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel":{"role":"symbol","title":"GroupChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" class represents a group channel which is a private chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery":{"role":"symbol","title":"MemberListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MemberListQuery"},{"type":"text","text":" class is a query class for getting the list member in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel/createMemberListQuery(params:)":{"role":"symbol","title":"createMemberListQuery(params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMemberListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MemberListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQueryParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MemberListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQuery"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Creates a query for members in group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/createMemberListQuery(params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createMemberListQueryWithParams:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel\/creatememberlistquery(params:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQueryParams":{"role":"symbol","title":"MemberListQueryParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListQueryParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListQueryParams"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistqueryparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createMemberListQueryWithParams:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createMemberListQueryWithParams:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQuery","text":"SBDMemberListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createMemberListQueryWithParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQueryParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQueryParams","text":"SBDMemberListQueryParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/title","value":"SBDGroupChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery\/title","value":"SBDMemberListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery\/fragments","value":[{"kind":"identifier","text":"SBDMemberListQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1createMemberListQuery(params:)\/title","value":"createMemberListQueryWithParams:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1createMemberListQuery(params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createMemberListQueryWithParams:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams\/title","value":"SBDMemberListQueryParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQueryParams\/fragments","value":[{"kind":"identifier","text":"SBDMemberListQueryParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}