{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMemberListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQuery","text":"MemberListQuery"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The instance to query the members in group channel."}]}]},{"kind":"parameters","parameters":[{"name":"channelURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"channel url"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/creatememberlistquery(channelurl:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/creatememberlistquery(channelurl:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/createMemberListQuery(channelURL:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a query for members in group channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMemberListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MemberListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQuery"}],"title":"createMemberListQuery(channelURL:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDGroupChannel(cm)createMemberListQueryWithChannelURL:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"createMemberListQueryWithChannelURL:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel":{"role":"symbol","title":"GroupChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" class represents a group channel which is a private chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel/createMemberListQuery(channelURL:)":{"role":"symbol","title":"createMemberListQuery(channelURL:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMemberListQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MemberListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQuery"}],"abstract":[{"type":"text","text":"Creates a query for members in group channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/createMemberListQuery(channelURL:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createMemberListQueryWithChannelURL:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel\/creatememberlistquery(channelurl:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/MemberListQuery":{"role":"symbol","title":"MemberListQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListQuery"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MemberListQuery"},{"type":"text","text":" class is a query class for getting the list member in group channels."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListQuery"}],"url":"\/documentation\/sendbirdchatsdk\/memberlistquery"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createMemberListQueryWithChannelURL:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createMemberListQueryWithChannelURL:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/MemberListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMemberListQuery","text":"SBDMemberListQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createMemberListQueryWithChannelURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelURL"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/title","value":"SBDGroupChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1createMemberListQuery(channelURL:)\/title","value":"createMemberListQueryWithChannelURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1createMemberListQuery(channelURL:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createMemberListQueryWithChannelURL:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery\/title","value":"SBDMemberListQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1MemberListQuery\/fragments","value":[{"kind":"identifier","text":"SBDMemberListQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}