{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(getChannelWithURL:completionHandler:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK19GroupChannelHandlera","text":"GroupChannelHandler"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"url","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The channel URL."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to execute. "},{"type":"codeVoice","code":"channel"},{"type":"text","text":" is the group channel"},{"type":"text","text":" "},{"type":"text","text":"instance which has the "},{"type":"codeVoice","code":"channelURL"},{"type":"text","text":"."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/getchannel(url:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/getchannel(url:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/getChannel(url:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets a group channel instance from channel URL asynchronously."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK19GroupChannelHandlera"},{"kind":"text","text":"?)"}],"title":"getChannel(url:completionHandler:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDGroupChannel(cm)getChannelWithURL:completionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getChannelWithURL:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel":{"role":"symbol","title":"GroupChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" class represents a group channel which is a private chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHandler":{"role":"symbol","title":"GroupChannelHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelHandler"}],"abstract":[{"type":"text","text":"Group channel handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelHandler"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelhandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel/getChannel(url:completionHandler:)":{"role":"symbol","title":"getChannel(url:completionHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK19GroupChannelHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Gets a group channel instance from channel URL asynchronously."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/getChannel(url:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getChannelWithURL:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel\/getchannel(url:completionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getChannelWithURL:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getChannelWithURL:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getChannelWithURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"url"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDGroupChannel *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDGroupChannel#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/title","value":"SBDGroupChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1getChannel(url:completionHandler:)\/title","value":"getChannelWithURL:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1getChannel(url:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getChannelWithURL:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}