{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(getReadStatusIncludingAllMembers:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getReadStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"includeAllMembers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]]"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The read status. If there’s no data, it will be an empty dictionary."}]}]},{"kind":"parameters","parameters":[{"name":"includeAllMembers","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If true, the return value includes the current user and the sender of the message."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.115"}]}],"type":"aside","name":"Since"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"USER_ID"},{"type":"text","text":" is the user ID as a key. Each "},{"type":"codeVoice","code":"USER_ID"},{"type":"text","text":" has a "},{"type":"codeVoice","code":"Dictionary"},{"type":"text","text":" which includes"},{"type":"text","text":" "},{"type":"codeVoice","code":"User"},{"type":"text","text":" object and "},{"type":"codeVoice","code":"Int64"},{"type":"text","text":". The “user” is a key of "},{"type":"codeVoice","code":"User"},{"type":"text","text":" object and the"},{"type":"text","text":" "},{"type":"text","text":"“last_seen_at” is a key of "},{"type":"codeVoice","code":"Int64"},{"type":"text","text":" object."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/getreadstatus(includeallmembers:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/getreadstatus(includeallmembers:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/getReadStatus(includeAllMembers:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the read status."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getReadStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"includeAllMembers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]]"}],"title":"getReadStatus(includeAllMembers:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDGroupChannel(im)getReadStatusIncludingAllMembers:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getReadStatusIncludingAllMembers:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel/getReadStatus(includeAllMembers:)":{"role":"symbol","title":"getReadStatus(includeAllMembers:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getReadStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"includeAllMembers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]]"}],"abstract":[{"type":"text","text":"Returns the read status."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/getReadStatus(includeAllMembers:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getReadStatusIncludingAllMembers:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel\/getreadstatus(includeallmembers:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel":{"role":"symbol","title":"GroupChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" class represents a group channel which is a private chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getReadStatusIncludingAllMembers:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getReadStatusIncludingAllMembers:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSDictionary<NSString *,id> *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getReadStatusIncludingAllMembers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"includeAllMembers"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1getReadStatus(includeAllMembers:)\/title","value":"getReadStatusIncludingAllMembers:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1getReadStatus(includeAllMembers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getReadStatusIncludingAllMembers:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/title","value":"SBDGroupChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}