{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(hideChannelWithHidePreviousMessages:allowAutoUnhide:completionHandler:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hide"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hidePreviousMessages"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowAutoUnhide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera","text":"SBErrorHandler"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"hidePreviousMessages","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The option to hide the previous message of this channel when the channel will be appeared again."}]}]},{"name":"allowAutoUnhide","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The auto unhide option."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"THe handle block to be executed."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.122"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/hide(hidepreviousmessages:allowautounhide:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/hide(hidepreviousmessages:allowautounhide:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/hide(hidePreviousMessages:allowAutoUnhide:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Hides the group channel with the auto unhide option. The channel will be hid from the channel list."},{"type":"text","text":" "},{"type":"text","text":"If the "},{"type":"codeVoice","code":"allowAutoUnhide"},{"type":"text","text":" is "},{"type":"codeVoice","code":"true"},{"type":"text","text":", the channel will be appeared again when the other user send a"},{"type":"text","text":" "},{"type":"text","text":"message in the channel. However, if the "},{"type":"codeVoice","code":"allowAutoUnhide"},{"type":"text","text":" is "},{"type":"codeVoice","code":"false"},{"type":"text","text":", the channel will be appeared"},{"type":"text","text":" "},{"type":"text","text":"by "},{"type":"codeVoice","code":"unhideChannel(completionHandler:)"},{"type":"text","text":" method."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"hideChannelWithHidePreviousMessages:allowAutoUnhide:completionHandler:"}],"role":"symbol","title":"hide(hidePreviousMessages:allowAutoUnhide:completionHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hide"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hidePreviousMessages"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowAutoUnhide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDGroupChannel(im)hideChannelWithHidePreviousMessages:allowAutoUnhide:completionHandler:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel":{"role":"symbol","title":"GroupChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" class represents a group channel which is a private chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBErrorHandler":{"role":"symbol","title":"SBErrorHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBErrorHandler"}],"abstract":[{"type":"text","text":"Error handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBErrorHandler"}],"url":"\/documentation\/sendbirdchatsdk\/sberrorhandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel/hide(hidePreviousMessages:allowAutoUnhide:completionHandler:)":{"role":"symbol","title":"hide(hidePreviousMessages:allowAutoUnhide:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hide"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hidePreviousMessages"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowAutoUnhide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Hides the group channel with the auto unhide option. The channel will be hid from the channel list."},{"type":"text","text":" "},{"type":"text","text":"If the "},{"type":"codeVoice","code":"allowAutoUnhide"},{"type":"text","text":" is "},{"type":"codeVoice","code":"true"},{"type":"text","text":", the channel will be appeared again when the other user send a"},{"type":"text","text":" "},{"type":"text","text":"message in the channel. However, if the "},{"type":"codeVoice","code":"allowAutoUnhide"},{"type":"text","text":" is "},{"type":"codeVoice","code":"false"},{"type":"text","text":", the channel will be appeared"},{"type":"text","text":" "},{"type":"text","text":"by "},{"type":"codeVoice","code":"unhideChannel(completionHandler:)"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/hide(hidePreviousMessages:allowAutoUnhide:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hideChannelWithHidePreviousMessages:allowAutoUnhide:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel\/hide(hidepreviousmessages:allowautounhide:completionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"hideChannelWithHidePreviousMessages:allowAutoUnhide:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hideChannelWithHidePreviousMessages:allowAutoUnhide:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"hideChannelWithHidePreviousMessages:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"hidePreviousMessages"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowAutoUnhide:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"allowAutoUnhide"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/title","value":"SBDGroupChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1hide(hidePreviousMessages:allowAutoUnhide:completionHandler:)\/title","value":"hideChannelWithHidePreviousMessages:allowAutoUnhide:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1hide(hidePreviousMessages:allowAutoUnhide:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hideChannelWithHidePreviousMessages:allowAutoUnhide:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}