{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetMyHistory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera","text":"SBErrorHandler"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to execute."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/resetmyhistory(completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/resetmyhistory(completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/resetMyHistory(completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Resets the history in this channel."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"resetMyHistoryWithCompletionHandler:"}],"role":"symbol","title":"resetMyHistory(completionHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetMyHistory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDGroupChannel(im)resetMyHistoryWithCompletionHandler:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel":{"role":"symbol","title":"GroupChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" class represents a group channel which is a private chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel/resetMyHistory(completionHandler:)":{"role":"symbol","title":"resetMyHistory(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetMyHistory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBErrorHandler","preciseIdentifier":"s:15SendbirdChatSDK14SBErrorHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Resets the history in this channel."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/resetMyHistory(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resetMyHistoryWithCompletionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel\/resetmyhistory(completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/SBErrorHandler":{"role":"symbol","title":"SBErrorHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBErrorHandler"}],"abstract":[{"type":"text","text":"Error handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/SBErrorHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBErrorHandler"}],"url":"\/documentation\/sendbirdchatsdk\/sberrorhandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"resetMyHistoryWithCompletionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetMyHistoryWithCompletionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"resetMyHistoryWithCompletionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/title","value":"SBDGroupChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1resetMyHistory(completionHandler:)\/title","value":"resetMyHistoryWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1resetMyHistory(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetMyHistoryWithCompletionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}