{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(updateScheduledFileMessageWithScheduledMessageID:params:completionHandler:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateScheduledFileMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scheduledMessageID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledFileMessageUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledFileMessageUpdateParams","text":"ScheduledFileMessageUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18FileMessageHandlera","text":"FileMessageHandler"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"scheduledMessageID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The scheduled message ID."}]}]},{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The instance of "},{"type":"codeVoice","code":"ScheduledFileMessageUpdateParams"},{"type":"text","text":" that can has parameters"},{"type":"text","text":" "},{"type":"text","text":"related with file message."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to be executed after the message is registered in the schedule."},{"type":"text","text":" "},{"type":"text","text":"This block has no return value and takes two argument, one is a user message is registered in the schedule and other is an"},{"type":"text","text":" "},{"type":"text","text":"error made when there is something wrong to message."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If a user leaves before sending scheduled messages, the scheduled messages will be removed."}]}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/updatescheduledfilemessage(scheduledmessageid:params:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/updatescheduledfilemessage(scheduledmessageid:params:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/updateScheduledFileMessage(scheduledMessageID:params:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Updates a scheduled file message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateScheduledFileMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scheduledMessageID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledFileMessageUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledFileMessageUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18FileMessageHandlera"},{"kind":"text","text":"?)"}],"title":"updateScheduledFileMessage(scheduledMessageID:params:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDGroupChannel(im)updateScheduledFileMessageWithScheduledMessageID:params:completionHandler:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"updateScheduledFileMessageWithScheduledMessageID:params:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel/updateScheduledFileMessage(scheduledMessageID:params:completionHandler:)":{"role":"symbol","title":"updateScheduledFileMessage(scheduledMessageID:params:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateScheduledFileMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scheduledMessageID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScheduledFileMessageUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledFileMessageUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessageHandler","preciseIdentifier":"s:15SendbirdChatSDK18FileMessageHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Updates a scheduled file message."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/updateScheduledFileMessage(scheduledMessageID:params:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateScheduledFileMessageWithScheduledMessageID:params:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel\/updatescheduledfilemessage(scheduledmessageid:params:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/FileMessageHandler":{"role":"symbol","title":"FileMessageHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessageHandler"}],"abstract":[{"type":"text","text":"File Message handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/FileMessageHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileMessageHandler"}],"url":"\/documentation\/sendbirdchatsdk\/filemessagehandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel":{"role":"symbol","title":"GroupChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" class represents a group channel which is a private chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ScheduledFileMessageUpdateParams":{"role":"symbol","title":"ScheduledFileMessageUpdateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduledFileMessageUpdateParams"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledFileMessageUpdateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScheduledFileMessageUpdateParams"}],"url":"\/documentation\/sendbirdchatsdk\/scheduledfilemessageupdateparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateScheduledFileMessageWithScheduledMessageID:params:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateScheduledFileMessageWithScheduledMessageID:params:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateScheduledFileMessageWithScheduledMessageID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"scheduledMessageID"},{"kind":"text","text":" "},{"kind":"identifier","text":"params:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ScheduledFileMessageUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDScheduledFileMessageUpdateParams","text":"SBDScheduledFileMessageUpdateParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDFileMessage *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDFileMessage#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1updateScheduledFileMessage(scheduledMessageID:params:completionHandler:)\/title","value":"updateScheduledFileMessageWithScheduledMessageID:params:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1updateScheduledFileMessage(scheduledMessageID:params:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateScheduledFileMessageWithScheduledMessageID:params:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/title","value":"SBDGroupChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledFileMessageUpdateParams\/title","value":"SBDScheduledFileMessageUpdateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1ScheduledFileMessageUpdateParams\/fragments","value":[{"kind":"identifier","text":"SBDScheduledFileMessageUpdateParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}