{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(updateChannelWithParams:progressHandler:completionHandler:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelUpdateParams","text":"GroupChannelUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progressHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ProgressHandler","preciseIdentifier":"s:15SendbirdChatSDK15ProgressHandlera","text":"ProgressHandler"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK19GroupChannelHandlera","text":"GroupChannelHandler"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"instance of "},{"type":"codeVoice","code":"GroupChannelUpdateParams"},{"type":"text","text":" contains what to update for group channel."}]}]},{"name":"progressHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to monitor progression. "},{"type":"codeVoice","code":"bytesSent"},{"type":"text","text":" is the number of bytes"},{"type":"text","text":" "},{"type":"text","text":"sent since the last time this method was called. "},{"type":"codeVoice","code":"totalBytesSent"},{"type":"text","text":" is the total number of bytes sent so far."},{"type":"text","text":" "},{"type":"codeVoice","code":"totalBytesExpectedToSend"},{"type":"text","text":" is the expected length of the body "},{"type":"strong","inlineContent":[{"type":"text","text":"data"}]},{"type":"text","text":". These parameters are"},{"type":"text","text":" "},{"type":"text","text":"the same to the declaration of "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsessiontaskdelegate\/1408299-urlsession"},{"type":"text","text":"."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler block to execute. "},{"type":"codeVoice","code":"channel"},{"type":"text","text":" is the group channel instance which"},{"type":"text","text":" "},{"type":"text","text":"has the "},{"type":"codeVoice","code":"userIDs"},{"type":"text","text":" as "},{"type":"strong","inlineContent":[{"type":"text","text":"members"}]},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"anchor":"parameter-d","level":2,"type":"heading","text":"parameter d"}]}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.215"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/update(params:progresshandler:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/groupchannel\/update(params:progresshandler:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/update(params:progressHandler:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Update a group channel with "},{"type":"codeVoice","code":"GroupChannelUpdateParams"},{"type":"text","text":" class."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"updateChannelWithParams:progressHandler:completionHandler:"}],"role":"symbol","title":"update(params:progressHandler:completionHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progressHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProgressHandler","preciseIdentifier":"s:15SendbirdChatSDK15ProgressHandlera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK19GroupChannelHandlera"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@SendbirdChatSDK@objc(cs)SBDGroupChannel(im)updateChannelWithParams:progressHandler:completionHandler:","extendedModule":"SendbirdChatSDK","modules":[{"name":"SendbirdChatSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel":{"role":"symbol","title":"GroupChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannel"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" class represents a group channel which is a private chat."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannel"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel"},"https://developer.apple.com/documentation/foundation/urlsessiontaskdelegate/1408299-urlsession":{"title":"urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)","titleInlineContent":[{"type":"codeVoice","code":"urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsessiontaskdelegate\/1408299-urlsession","url":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsessiontaskdelegate\/1408299-urlsession"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelHandler":{"role":"symbol","title":"GroupChannelHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelHandler"}],"abstract":[{"type":"text","text":"Group channel handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelHandler"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelhandler"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannel/update(params:progressHandler:completionHandler:)":{"role":"symbol","title":"update(params:progressHandler:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progressHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProgressHandler","preciseIdentifier":"s:15SendbirdChatSDK15ProgressHandlera"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelHandler","preciseIdentifier":"s:15SendbirdChatSDK19GroupChannelHandlera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Update a group channel with "},{"type":"codeVoice","code":"GroupChannelUpdateParams"},{"type":"text","text":" class."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannel\/update(params:progressHandler:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateChannelWithParams:progressHandler:completionHandler:"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannel\/update(params:progresshandler:completionhandler:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/GroupChannelUpdateParams":{"role":"symbol","title":"GroupChannelUpdateParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChannelUpdateParams"}],"abstract":[{"type":"text","text":"An object contains a set of options to update a group channel"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChannelUpdateParams"}],"url":"\/documentation\/sendbirdchatsdk\/groupchannelupdateparams"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/ProgressHandler":{"role":"symbol","title":"ProgressHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressHandler"}],"abstract":[{"type":"text","text":"Binary progress handler"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/ProgressHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProgressHandler"}],"url":"\/documentation\/sendbirdchatsdk\/progresshandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateChannelWithParams:progressHandler:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateChannelWithParams:progressHandler:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateChannelWithParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/GroupChannelUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelUpdateParams","text":"SBDGroupChannelUpdateParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"params"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(long long, long long, long long)","preciseIdentifier":"c:BFv(#K#K#K)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"progressHandler"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(SBDGroupChannel *, SBError *)","preciseIdentifier":"c:BFv(#*$@M@SendbirdChatSDK@objc(cs)SBDGroupChannel#*$@M@SendbirdChatSDK@objc(cs)SBError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/title","value":"SBDGroupChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1update(params:progressHandler:completionHandler:)\/title","value":"updateChannelWithParams:progressHandler:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannel~1update(params:progressHandler:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateChannelWithParams:progressHandler:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams\/title","value":"SBDGroupChannelUpdateParams"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1GroupChannelUpdateParams\/fragments","value":[{"kind":"identifier","text":"SBDGroupChannelUpdateParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}