{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelUnreadMentionCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey","text":"UnreadItemKey"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemkey\/groupchannelunreadmentioncount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemkey\/groupchannelunreadmentioncount"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/groupChannelUnreadMentionCount","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The bitmask key for unread mention count of group channel(super and non-super)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelUnreadMentionCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"}],"title":"groupChannelUnreadMentionCount","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey(cpy)groupChannelUnreadMentionCount","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"groupChannelUnreadMentionCount"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/groupChannelUnreadMentionCount":{"role":"symbol","title":"groupChannelUnreadMentionCount","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelUnreadMentionCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"}],"abstract":[{"type":"text","text":"The bitmask key for unread mention count of group channel(super and non-super)."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/groupChannelUnreadMentionCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelUnreadMentionCount"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/groupchannelunreadmentioncount"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey":{"role":"symbol","title":"UnreadItemKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadItemKey"}],"abstract":[{"type":"text","text":"The bitmask keys of count about unread messages or invitation."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnreadItemKey"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"groupChannelUnreadMentionCount"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"groupChannelUnreadMentionCount"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey","text":"SBDUnreadItemKey"},{"kind":"text","text":" *"},{"kind":"identifier","text":"groupChannelUnreadMentionCount"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1groupChannelUnreadMentionCount\/title","value":"groupChannelUnreadMentionCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1groupChannelUnreadMentionCount\/fragments","value":[{"kind":"identifier","text":"groupChannelUnreadMentionCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey\/title","value":"SBDUnreadItemKey"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey\/fragments","value":[{"kind":"identifier","text":"SBDUnreadItemKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}