{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey","text":"UnreadItemKey"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"keys","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"array of "},{"type":"codeVoice","code":"UnreadItemKey"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemkey\/init(keys:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirdchatsdk\/unreaditemkey\/init(keys:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/init(keys:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Parameter constructor"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"},{"kind":"text","text":"])"}],"title":"init(keys:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey(im)initWithKeys:","modules":[{"name":"SendbirdChatSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithKeys:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey"]]},"references":{"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey/init(keys:)":{"role":"symbol","title":"init(keys:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UnreadItemKey","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUnreadItemKey"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Parameter constructor"}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey\/init(keys:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithKeys:"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey\/init(keys:)"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK":{"role":"collection","title":"SendbirdChatSDK","abstract":[],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK","kind":"symbol","type":"topic","url":"\/documentation\/sendbirdchatsdk"},"doc://com.sendbird.chat/documentation/SendbirdChatSDK/UnreadItemKey":{"role":"symbol","title":"UnreadItemKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnreadItemKey"}],"abstract":[{"type":"text","text":"The bitmask keys of count about unread messages or invitation."}],"identifier":"doc:\/\/com.sendbird.chat\/documentation\/SendbirdChatSDK\/UnreadItemKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnreadItemKey"}],"url":"\/documentation\/sendbirdchatsdk\/unreaditemkey"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithKeys:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKeys:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithKeys:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBDUnreadItemKey *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"keys"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1init(keys:)\/title","value":"initWithKeys:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey~1init(keys:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKeys:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey\/title","value":"SBDUnreadItemKey"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.chat~1documentation~1SendbirdChatSDK~1UnreadItemKey\/fragments","value":[{"kind":"identifier","text":"SBDUnreadItemKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}